// VI / EM companion to One Filter, Many Derivations. No build dependencies.
const C={paper:'#F7F5EF',panel:'#FFFEFB',ink:'#203129',muted:'#66756E',rule:'#D8DED7',green:'#2F6B4F',soft:'#E7F0EA',rust:'#A94F2A',warm:'#F5E8DF',blue:'#496E87',cool:'#E7EEF3'};
const serif="Georgia, 'Times New Roman', serif",sans="Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",mono="'SFMono-Regular', Consolas, monospace";
const M=(s)=>`<span class="math-tex math-display">\\[${s}\\]</span>`;
const I=(s)=>`<span class="math-tex math-inline">\\(${s}\\)</span>`;
const R=String.raw;
function text(id,x,y,w,h,html,o={}){return {id,type:'text',x,y,w,h,rotation:0,opacity:1,html,fontSize:18,fontFamily:sans,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.4,...o};}
function box(id,x,y,w,h,fill=C.panel,stroke=C.rule){return {id,type:'shape',shape:'rect',x,y,w,h,fill,stroke,strokeWidth:1,radius:14,rotation:0,opacity:1};}
function panel(id,x,y,w,h,label,html,o={}){return [box(id+'-bg',x,y,w,h,o.fill||C.panel,o.stroke||C.rule),text(id+'-label',x+22,y+17,w-44,23,label,{fontFamily:mono,fontSize:11,fontWeight:800,color:o.accent||C.green,letterSpacing:.8}),text(id+'-body',x+22,y+57,w-44,h-73,html,{fontSize:o.size||19,lineHeight:1.45,...(o.body||{})})];}
function chrome(id,source){return [box('chrome-rule',72,669,1136,1,C.rule,C.rule),text('chrome-home',72,685,260,18,'BAI LIPING · INFERENCE NOTES',{fontFamily:mono,fontSize:10,color:C.muted,link:'https://bailiping.com/'}),text('chrome-source',350,684,550,22,source||'VI / EM · ONE BOUND, TWO ALGORITHMS',{fontFamily:mono,fontSize:10,color:C.muted,align:'center'}),text('chrome-index',1030,684,178,20,'CONTENTS ↗',{fontSize:10,fontFamily:mono,color:C.green,align:'right',link:'overview'})];}
function slide(id,section,title,sub,elements,notes,source='[1] Blei et al. · [3] Neal & Hinton',transition='none') {return {id,background:C.paper,transition,notes,elements:[text('eyebrow',72,35,1110,23,section.toUpperCase(),{fontFamily:mono,fontSize:11,fontWeight:800,color:C.rust,letterSpacing:1.3}),text('heading',72,70,1136,58,title,{fontFamily:serif,fontSize:38,fontWeight:700,lineHeight:1.05}),text('subtitle',72,129,1136,44,sub,{fontSize:16,color:C.muted,lineHeight:1.35}),...elements,...chrome(id,source)]};}
function two(id,section,title,sub,leftLabel,left,rightLabel,right,notes,source,extra={}) {return slide(id,section,title,sub,[...panel(id+'-idea',72,188,426,422,leftLabel,left,{fill:C.soft,size:19}),...panel(id+'-math',522,188,686,422,rightLabel,right,{size:extra.size||24,body:{valign:'middle',align:'center'}})],notes,source,extra.transition||'none');}
function sheet(id,title,sub,items,notes,source){return slide(id,'Equation sheet',title,sub,items.flatMap(([label,body],i)=>panel(id+'-'+i,72+(i%2)*578,184+Math.floor(i/2)*231,558,211,label,body,{size:21,body:{valign:'middle',align:'center'}})),notes,source);}
function table(headers,rows){return `<table style="border-collapse:collapse;width:100%;font-size:18px;line-height:1.35"><thead><tr>${headers.map(h=>`<th style="text-align:left;border-bottom:2px solid ${C.green};padding:13px 12px;color:${C.green}">${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr style="background:${i%2?C.soft:C.panel}">${r.map(c=>`<td style="vertical-align:top;padding:16px 12px;border-bottom:1px solid ${C.rule}">${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
const slides=[];
slides.push(slide('overview','Variational inference & expectation–maximization','One bound. Two algorithms.','A common language for posterior approximation and latent-variable learning.',[
 text('cover-title',77,195,700,112,'Infer hidden variables.<br><span style="color:#2F6B4F">Then learn the model.</span>',{fontFamily:serif,fontSize:46,fontWeight:700,lineHeight:1.08,fx:{enter:'fade-up',order:0}}),
 ...[['01','The ELBO','bound → KL → Jensen','elbo'],['02','Variational inference','restriction → coordinate ascent','vi'],['03','EM algorithm','exact E → parameter M','em'],['04','Beyond exact EM','variational EM → Bayesian VI','vem']].flatMap(([n,t,d,link],j)=>[box('cover-card-'+j,72+(j%2)*354,356+Math.floor(j/2)*105,336,89,j<2?C.soft:C.warm),text('cover-link-'+j,91+(j%2)*354,369+Math.floor(j/2)*105,298,28,n+' · '+t,{fontSize:20,fontFamily:serif,fontWeight:700,link}),text('cover-desc-'+j,91+(j%2)*354,407+Math.floor(j/2)*105,298,21,d,{fontSize:12,fontFamily:mono,color:C.muted,link})]),
 ...panel('cover-bound',808,195,400,371,'THE SHARED IDENTITY',M(R`\begin{gathered}\log p_\theta(x)\\=\mathcal L(q,\theta)\\+\mathrm{KL}\!\left(q\Vert p_\theta(z\mid x)\right)\end{gathered}`),{size:26,body:{valign:'middle',align:'center'}}),
 text('cover-labs',75,590,1125,40,'TWO LIVE LABS   ·   Mean-field geometry ↗',{fontFamily:mono,fontSize:13,color:C.green,link:'mean-field-live'}),
 text('cover-em-link',674,591,420,35,'Gaussian-mixture EM ↗',{fontFamily:mono,fontSize:13,color:C.rust,link:'em-live'})
],'Use the cover cards to jump between sections. The two examples are a correlated Gaussian posterior and a Gaussian mixture. They illustrate different tasks: approximation of a fixed posterior versus parameter learning.'));
slides.push(two('setup','Shared setup','What is inferred, and what is learned?','Keep the data, latent variables, model parameters, and variational parameters distinct.',
 'FOUR SYMBOLS',`${I('x')}: observed data, held fixed.<br><br>${I('z')}: unobserved variables.<br><br>${I(R`\theta`)}: model parameters.<br><br>${I(R`q_\lambda(z)`)}: trial distribution, indexed by variational parameters ${I(R`\lambda`)}.`,
 'TWO DIFFERENT OPTIMIZATIONS',M(R`\begin{aligned}p_\theta(x)&=\int p_\theta(x,z)\,dz\\[8pt]\text{Inference: }&p_\theta(z\mid x)\quad(\theta\text{ fixed})\\[8pt]\text{Learning: }&\max_\theta\log p_\theta(x)\end{aligned}`),
 'Integrals also denote sums for discrete variables. Assume finite positive evidence, normalized trial distributions, and the support/integrability conditions needed for finite KL and expectations. The model parameters are not variational parameters.'));
slides.push(two('elbo','01 · The common objective','The ELBO is an identity before it is a bound','Expand the reverse KL divergence; isolate the observed-data log-likelihood.',
 'KEY IDEA',`The evidence lower bound (ELBO) combines expected log joint density with entropy.<br><br>Its gap to log evidence is a nonnegative KL divergence.<br><br>For fixed ${I(R`\theta`)}, maximizing the ELBO is exactly the same optimization as minimizing that KL.`,
 'DERIVATION',M(R`\begin{aligned}\mathrm{KL}(q\Vert p_\theta(z\mid x))&=\mathbb E_q\log\frac{q(z)}{p_\theta(x,z)}+\log p_\theta(x)\\[9pt]\mathcal L(q,\theta)&=\mathbb E_q\log p_\theta(x,z)+H(q)\\[9pt]\log p_\theta(x)&=\mathcal L(q,\theta)+\mathrm{KL}(q\Vert p_\theta(z\mid x))\end{aligned}`),
 'H(q)=-E_q log q. Require q to be absolutely continuous with respect to the posterior for finite KL; expressions involving infinity require care. Equality of ELBO and evidence holds precisely when q equals the posterior almost everywhere.',undefined,{size:21}));
slides.push(two('jensen','01 · A second derivation','Jensen reaches the same lower bound','Move a concave logarithm outside an expectation, in the correct direction.',
 'WHY INTRODUCE q?',`Write the latent-variable integral as an expectation under a distribution we can handle.<br><br>Concavity of log gives a lower bound.<br><br>The bound is tight at the exact posterior—not at a point estimate of ${I('z')}.`,
 'JENSEN FORM',M(R`\begin{aligned}\log p_\theta(x)&\geq\log\mathbb E_q\!\left[\frac{p_\theta(x,z)}{q(z)}\right]\\&\geq\mathbb E_q\!\left[\log\frac{p_\theta(x,z)}{q(z)}\right]\\&=\mathcal L(q,\theta)\\[9pt]q(z)=p_\theta(z\mid x)&\Longrightarrow\mathcal L=\log p_\theta(x)\end{aligned}`),
 'The first inequality becomes equality if q covers the support of the joint density in z. Without that support coverage, the expectation integrates only over q-positive regions and is at most the evidence. The KL derivation is usually the cleanest general presentation.'));
slides.push(sheet('elbo-sheet','ELBO · the equations to keep','One identity; three equivalent readings.',[
 ['EXPECTED LOG JOINT + ENTROPY',M(R`\mathcal L(q,\theta)=\mathbb E_q\log p_\theta(x,z)-\mathbb E_q\log q(z)`)],
 ['EXPECTED FIT − PRIOR KL',M(R`\mathcal L=\mathbb E_q\log p_\theta(x\mid z)-\mathrm{KL}(q\Vert p_\theta(z))`)],
 ['THE EXACT GAP',M(R`\log p_\theta(x)-\mathcal L=\mathrm{KL}(q\Vert p_\theta(z\mid x))\geq0`)],
 ['TIGHTNESS',M(R`\mathcal L=\log p_\theta(x)\iff q=p_\theta(z\mid x)\ \text{a.e.}`)]
],'The expected fit minus prior KL form assumes the factorization p_theta(x,z)=p_theta(x|z)p_theta(z). Entropy may be differential entropy for continuous variables; it need not be positive.'));
slides.push(two('vi','02 · Variational inference','Replace an intractable posterior by an optimization','The approximation is the family restriction—not the ELBO identity.',
 'WHAT CHANGES?',`Hold ${I(R`\theta`)} fixed. Search only within a tractable family ${I(R`\mathcal Q`)}.<br><br>A richer family can represent more dependence, but is often harder to optimize.<br><br>Reverse KL penalizes placing mass where the target density is small. “Mode-seeking” is a tendency, not a universal theorem.`,
 'THE VARIATIONAL PROBLEM',M(R`\begin{aligned}q^*&=\arg\min_{q\in\mathcal Q}\mathrm{KL}(q\Vert p_\theta(z\mid x))\\&=\arg\max_{q\in\mathcal Q}\mathcal L(q,\theta)\\[12pt]\mathcal Q_{\rm MF}&=\left\{q(z)=\prod_{j=1}^{m}q_j(z_j)\right\}\end{aligned}`),
 'Mean-field independence is an assumption about the approximating distribution, not a statement that latent variables are independent in the model or posterior. A globally optimized ELBO in a restricted family can still give a poor approximation.'));
slides.push(two('cavi','02 · Coordinate ascent','Optimize one variational factor at a time','Hold all other factors fixed; collect terms that depend on the current factor.',
 'FUNCTIONAL DERIVATION',`Let ${I(R`q_{-j}=\prod_{k\ne j}q_k`)}.<br><br>Define an expected log joint ${I(R`f_j(z_j)`)}.<br><br>The factor-specific ELBO becomes a constant minus KL to a normalized exponential of ${I(R`f_j`)}.<br><br>That KL is minimized by matching the normalized density.`,
 'THE COORDINATE UPDATE',M(R`\begin{aligned}f_j(z_j)&=\mathbb E_{q_{-j}}\log p_\theta(x,z)\\ \widetilde p_j(z_j)&=\frac{\exp f_j(z_j)}{\int\exp f_j(u)\,du}\\ \mathcal L&=-\mathrm{KL}(q_j\Vert\widetilde p_j)+\mathrm{const}\\ \log q_j^*(z_j)&=\mathbb E_{q_{-j}}\log p_\theta(x,z)+\mathrm{const}\end{aligned}`),
 'This unrestricted factor update requires a finite normalizer. If the factor itself is restricted to a smaller parameterized family, an additional optimization/projection is needed. Sequential exact coordinate updates increase or preserve the same ELBO.',undefined,{size:22}));
slides.push(sheet('cavi-sheet','Mean-field VI · equation sheet','Coordinate ascent variational inference (CAVI).',[
 ['FAMILY',M(R`q(z)=\prod_jq_j(z_j),\qquad H(q)=\sum_j H(q_j)`)],
 ['ONE FACTOR',M(R`q_j^{\rm new}(z_j)\propto\exp\!\left\{\mathbb E_{q_{-j}}\log p_\theta(x,z)\right\}`)],
 ['SEQUENTIAL ASCENT',M(R`\mathcal L(q_1^{\rm new},q_2,\ldots)\geq\mathcal L(q_1,q_2,\ldots)`)],
 ['WHAT TO MONITOR',M(R`\Delta\mathcal L\geq0,\qquad\int q_j=1,\qquad q_j\geq0`)]
],'Use the newest factors within each sweep. Simultaneously updating all factors from stale values is not covered by the sequential coordinate-ascent guarantee. A bounded monotone sequence of ELBO values converges; this alone does not establish global optimality or convergence of every parameter.'));
slides.push(two('gaussian','02 · Worked example','Mean-field loses correlation—and can lose variance','A correlated Gaussian makes the restriction exactly calculable.',
 'A FIXED POSTERIOR',`Take a zero-mean, unit-marginal-variance Gaussian with correlation ${I(R`\rho`)}.<br><br>Approximate it by a product of two Gaussians.<br><br>The optimal mean is correct, but each variational variance is ${I(R`1-\rho^2`)} rather than 1.<br><br>This is an exact result for this example, not a universal VI variance guarantee.`,
 'CLOSED-FORM OPTIMUM',M(R`\begin{gathered}p(z\mid x)=\mathcal N\!\left(0,\begin{bmatrix}1&\rho\\\rho&1\end{bmatrix}\right),\quad |\rho|<1\\[9pt]\Lambda=\Sigma^{-1},\quad q^*=\mathcal N\!\left(0,\operatorname{diag}(\Lambda_{11}^{-1},\Lambda_{22}^{-1})\right)\\[9pt]v_1^*=v_2^*=1-\rho^2,\qquad\mathrm{KL}_{\min}=-\tfrac12\log(1-\rho^2)\end{gathered}`),
 'For p=N(mu,Sigma) and diagonal Gaussian q=N(m,D), reverse KL is one half of tr(Lambda D)+(m-mu)^T Lambda (m-mu)-d+log(det Sigma/det D). Differentiating gives m=mu and D_jj=1/Lambda_jj. For this 2D example, CAVI means are m1=rho m2, then m2=rho m1, with both variances 1-rho squared.',undefined,{size:21}));
slides.push(slide('mean-field-live','Interactive lab 01','Watch the independence assumption reshape uncertainty','Move correlation; compare exact contours, mean-field VI, and the product of exact marginals.',[],
 'The lab runs sequential CAVI on a normalized two-dimensional Gaussian target. It displays exact Gaussian KL, not a sampled estimate. The objective is -KL because the target density is normalized; no arbitrary log evidence is invented. Dashed contours are the product of marginals, not the reverse-KL optimum.','Own analytical Gaussian example · [1]'));
slides.push(two('em','03 · Expectation–maximization','EM learns parameters through a posterior over hidden data','The E-step is a distributional expectation—not filling in a single best latent value.',
 'THE COMPLETE-DATA IDEA',`The observed log-likelihood contains a log of a sum or integral.<br><br>The complete-data log joint can be easier to optimize.<br><br>EM averages that simpler log joint under the current posterior, then updates ${I(R`\theta`)}.`,
 'THE Q-FUNCTION',M(R`\begin{aligned}\ell(\theta)&=\log\int p_\theta(x,z)\,dz\\[9pt]q^{(t)}(z)&=p_{\theta^{(t)}}(z\mid x)\\[9pt]Q(\theta\mid\theta^{(t)})&=\mathbb E_{q^{(t)}}[\log p_\theta(x,z)]\\[9pt]\mathcal L(q^{(t)},\theta)&=Q(\theta\mid\theta^{(t)})+H(q^{(t)})\end{aligned}`),
 'The capital Q function is not the variational family calligraphic Q. In the M-step, q at the old theta is held fixed. E[f(z)] is generally not f(E[z]). The E-step need only compute the expectations required for Q.','[2] Dempster et al. · [3] Neal & Hinton',{size:22}));
slides.push(two('em-steps','03 · Alternating optimization','E tightens the bound. M raises it.','Two coordinate optimizations of the same ELBO.',
 'E → M → REPEAT',`<b>E-step:</b> hold parameters fixed; select the exact posterior. The KL gap closes.<br><br><b>M-step:</b> hold that distribution fixed; maximize the expected complete-data log joint.<br><br>The old entropy is constant in the M-step.`,
 'EXACT EM',M(R`\begin{aligned}\text{E: }q^{(t)}&=\arg\max_q\mathcal L(q,\theta^{(t)})\\&=p_{\theta^{(t)}}(z\mid x)\\[12pt]\text{M: }\theta^{(t+1)}&\in\arg\max_\theta\mathcal L(q^{(t)},\theta)\\&=\arg\max_\theta Q(\theta\mid\theta^{(t)})\end{aligned}`),
 'The E-step optimizes over all admissible distributions; a tractable exact posterior is needed for ordinary EM. Generalized EM can use an M-step that only increases Q. It still needs an exact E-step for the standard likelihood guarantee.','[2] · [3]',{transition:'morph'}));
slides.push(two('monotonicity','03 · The central proof','Why exact EM cannot lower the likelihood','The bound touches at the old parameters and lies below at the new parameters.',
 'READ THE CHAIN',`<b>First inequality:</b> an ELBO never exceeds the log evidence.<br><br><b>Second inequality:</b> the M-step does not lower the bound.<br><br><b>Equality:</b> the exact E-step made the old bound tight.<br><br>Monotonicity does not guarantee the global maximum.`,
 'THREE LINES',M(R`\begin{aligned}\ell(\theta^{(t+1)})&\geq\mathcal L(q^{(t)},\theta^{(t+1)})\\[10pt]&\geq\mathcal L(q^{(t)},\theta^{(t)})\\[10pt]&=\ell(\theta^{(t)})\end{aligned}`),
 'Regularity conditions are needed for stationary-point convergence claims. A nondecreasing likelihood may be unbounded, as in an unconstrained Gaussian mixture with a collapsing covariance. Increasing Q suffices for generalized EM, but replacing the posterior by an arbitrary approximate q removes the final equality.','[2] Dempster et al. · [3] Neal & Hinton'));
slides.push(sheet('em-sheet','EM · equation sheet','Learning a point estimate of the model parameters.',[
 ['E-STEP',M(R`q^{(t)}(z)=p_{\theta^{(t)}}(z\mid x)`)],
 ['M-STEP',M(R`\theta^{(t+1)}\in\arg\max_\theta\mathbb E_{q^{(t)}}\log p_\theta(x,z)`)],
 ['GENERALIZED EM',M(R`Q(\theta^{(t+1)}\mid\theta^{(t)})\geq Q(\theta^{(t)}\mid\theta^{(t)})`)],
 ['MAP-EM EXTENSION',M(R`\theta^{(t+1)}\in\arg\max_\theta\{Q(\theta\mid\theta^{(t)})+\log p(\theta)\}`)]
],'Maximum a posteriori EM adds a log parameter prior to the M-step objective. Its monotonic objective is the log parameter posterior up to an additive constant, not necessarily the data likelihood. MAP-EM still returns a point parameter estimate.','[2] · [3]'));
slides.push(two('gmm','03 · A concrete latent-variable model','Gaussian mixtures: assignments are the missing data','Each observation belongs to a component, but its component label is hidden.',
 'THE GENERATIVE MODEL',`${I(R`z_i\sim\operatorname{Categorical}(\pi)`)}, with ${I(R`\sum_k\pi_k=1`)}.<br><br>${I(R`x_i\mid z_i=k\sim\mathcal N(\mu_k,\Sigma_k)`)}.<br><br>Observations are independent given the parameters.<br><br>The latent assignment converts log-sum into a sum of selected log densities.`,
 'OBSERVED VS. COMPLETE',M(R`\begin{aligned}\ell(\theta)&=\sum_i\log\sum_k\pi_k\mathcal N(x_i\mid\mu_k,\Sigma_k)\\[12pt]\log p_\theta(x,z)&=\sum_{i,k}\mathbf1[z_i=k]\\&\quad\cdot\big[\log\pi_k+\log\mathcal N(x_i\mid\mu_k,\Sigma_k)\big]\end{aligned}`),
 'For fixed parameters, the posterior assignments factorize across observations in an ordinary independent-observation mixture. Thus a product over assignments is exact here; calling this factorization alone an approximate E-step would be misleading.','[1] · [2]',{size:22}));
slides.push(two('responsibilities','03 · GMM E-step','Responsibilities are soft assignments','Use Bayes’ rule, then evaluate the expected complete-data log-likelihood.',
 'E-STEP OUTPUT',`${I(R`r_{ik}`)} is the posterior probability that point ${I('i')} belongs to component ${I('k')}.<br><br>Every row sums to one.<br><br>Compute scores in log space and normalize with log-sum-exp.<br><br>Do not replace responsibilities by hard nearest-centre labels.`,
 'BAYES → EXPECTATION',M(R`\begin{aligned}r_{ik}^{(t)}&=\frac{\pi_k^{(t)}\mathcal N(x_i\mid\mu_k^{(t)},\Sigma_k^{(t)})}{\sum_j\pi_j^{(t)}\mathcal N(x_i\mid\mu_j^{(t)},\Sigma_j^{(t)})}\\[14pt]Q(\theta\mid\theta^{(t)})&=\sum_{i,k}r_{ik}^{(t)}\big[\log\pi_k+\log\mathcal N(x_i\mid\mu_k,\Sigma_k)\big]\end{aligned}`),
 'The formula is valid for positive denominators. In code use a_ik=log pi_k+log normal and r_ik=exp(a_ik-logsumexp_j a_ij). Zero weights give negative-infinite scores and zero responsibilities.','[1] · [2]',{size:21}));
slides.push(sheet('gmm-sheet','Gaussian-mixture EM · equation sheet','All quantities on the right use the same frozen responsibilities.',[
 ['E-STEP + EFFECTIVE COUNT',M(R`r_{ik}\propto\pi_k\mathcal N(x_i\mid\mu_k,\Sigma_k),\quad N_k=\sum_i r_{ik}`)],
 ['WEIGHTS + MEANS',M(R`\pi_k^{\rm new}=\frac{N_k}{N},\qquad\mu_k^{\rm new}=\frac{\sum_i r_{ik}x_i}{N_k}`)],
 ['COVARIANCES',M(R`\Sigma_k^{\rm new}=\frac{\sum_i r_{ik}(x_i-\mu_k^{\rm new})(x_i-\mu_k^{\rm new})^\mathsf T}{N_k}`)],
 ['ELBO FOR ASSIGNMENTS',M(R`\mathcal L=\sum_{i,k}r_{ik}\log\frac{\pi_k\mathcal N(x_i\mid\mu_k,\Sigma_k)}{r_{ik}}`)]
],'The weight update follows from a Lagrange multiplier enforcing sum pi=1. Differentiating the weighted Gaussian Q gives the mean and covariance updates; use the new mean and denominator Nk, not Nk-1. Components with Nk=0 require special handling. The demo is one-dimensional with optional learned variances constrained to at least 0.09, so its variance M-step is max(weighted residual variance,0.09).','[1] · [2]'));
slides.push(slide('em-live','Interactive lab 02','Step through a Gaussian mixture, one half-step at a time','E changes responsibilities. M changes the model. Watch the ELBO gap close and reopen.',[],
 'Begin with uniform responsibilities and deliberately imperfect parameters. E makes ELBO equal log likelihood. M keeps responsibilities fixed and raises the ELBO; the exact log likelihood remains above it. Try identical initial means to see a symmetric fixed point. Data are seeded synthetic samples, not empirical evidence. A variance lower bound prevents singular likelihoods when variance learning is enabled.','Own seeded numerical experiment · [2] · [3]'));
slides.push(slide('comparison','Synthesis','Same bound does not mean the same task','Distinguish exact EM, variational EM, and fully Bayesian variational inference.',[
 text('comparison-table',72,184,1136,408,table(['Method','What is optimized?','What does it return?'],[
 ['VI, fixed model',`${I(R`q\in\mathcal Q`)}; ${I(R`\theta`)} fixed`,'Approximate latent posterior'],
 ['Exact EM',`Unrestricted ${I('q')}; point ${I(R`\theta`)}`,'Exact E-step posterior; parameter point estimate'],
 ['Variational EM',`Restricted ${I('q')}; point ${I(R`\theta`)}`,'Approximate E-step; parameter point estimate'],
 ['Bayesian VI',`${I(R`q(z,\theta)`)} under a parameter prior`,'Approximate joint posterior, including parameter uncertainty']
 ]),{fontSize:18}),text('comparison-note',82,610,1116,34,'Mean-field is a family choice. CAVI is an optimizer. EM is a latent-variable learning algorithm.',{fontSize:17,fontWeight:700,color:C.green})
],'The common variational objective clarifies the relationship without equating the methods. Bayesian VI treats theta as random; the distinction between parameters and latent variables shifts into the model definition.'));
slides.push(two('vem','04 · Variational EM','When the E-step is approximate, the guarantee changes','Coordinate ascent still raises the ELBO; it need not raise the exact likelihood.',
 'A RESTRICTED E-STEP',`Optimize ${I(R`q\in\mathcal Q`)} instead of using the exact posterior.<br><br>The E-step no longer necessarily closes the gap.<br><br>If each block update improves its objective, the same ELBO is nondecreasing.<br><br>The true likelihood can fall if the KL gap shrinks by more than the ELBO rises.`,
 'BOUND ASCENT ≠ LIKELIHOOD ASCENT',M(R`\begin{aligned}q^{(t+1)}&\in\arg\max_{q\in\mathcal Q}\mathcal L(q,\theta^{(t)})\\\theta^{(t+1)}&\in\arg\max_\theta\mathcal L(q^{(t+1)},\theta)\\[12pt]\Delta\ell&=\Delta\mathcal L+\Delta\mathrm{KL}\end{aligned}`),
 'The delta identity compares any two complete (q,theta) states, with each KL measured to its own parameter-dependent posterior. Approximate inference and stochastic optimization require their own guarantees; do not carry over exact EM monotonicity.'));
slides.push(two('bayesian','04 · Bayesian VI','Put a posterior over parameters, not just a point estimate','The joint model now includes a parameter prior.',
 'MODEL UNCERTAINTY',`Introduce ${I(R`p(\theta)`)} and approximate ${I(R`p(z,\theta\mid x)`)}.<br><br>One possible restriction is ${I(R`q(z,\theta)=q(z)q(\theta)`)}.<br><br>Both updates optimize distributions.<br><br>This is not ordinary EM with a different name, nor a literal finite-entropy Dirac approximation.`,
 'TWO VARIATIONAL BLOCKS',M(R`\begin{aligned}p(x,z,\theta)&=p_\theta(x,z)p(\theta)\\[10pt]\log q^*(z)&=\mathbb E_{q(\theta)}\log p(x,z,\theta)+c_z\\[10pt]\log q^*(\theta)&=\mathbb E_{q(z)}\log p(x,z,\theta)+c_\theta\end{aligned}`),
 'Continuous point masses generally have infinite KL against a continuous posterior, so an exact finite-entropy identification of EM with Bayesian mean-field VI at a Dirac distribution is invalid. MAP-EM and Bayesian VI optimize different objects.',undefined,{size:22}));
slides.push(sheet('bayesian-sheet','Bayesian mixture · one concrete CAVI update','Known component weights and observation variance; uncertain component means.',[
 ['MODEL + FAMILY',M(R`\mu_k\sim\mathcal N(m_0,\tau_0^2),\quad x_i\mid z_i=k,\mu_k\sim\mathcal N(\mu_k,\sigma^2)\\q=\prod_i\operatorname{Cat}(r_i)\prod_k\mathcal N(\mu_k\mid m_k,v_k)`)],
 ['ASSIGNMENT UPDATE',M(R`r_{ik}\propto\pi_k\exp\!\left[-\frac{(x_i-m_k)^2+v_k}{2\sigma^2}\right]`)],
 ['MEAN-POSTERIOR UPDATE',M(R`v_k=\left(\tau_0^{-2}+\frac{N_k}{\sigma^2}\right)^{-1},\quad m_k=v_k\left(\frac{m_0}{\tau_0^2}+\frac{\sum_i r_{ik}x_i}{\sigma^2}\right)`)],
 ['THE EXTRA UNCERTAINTY TERM',M(R`\mathbb E_q[(x_i-\mu_k)^2]=(x_i-m_k)^2+v_k`)]
],'Here pi and sigma squared are fixed and known; this is not the full unknown-weight/unknown-covariance Bayesian mixture. All updates use the most recently available opposite block. The variance term in the responsibility update is exactly what a plug-in-mean update misses. This is a direct conjugate-Gaussian calculation.','Own conjugate derivation · [1]'));
slides.push(two('gradients','04 · Beyond conjugacy','No closed-form update? Optimize the same ELBO.','A parameterized variational family permits gradient-based inference.',
 'REPARAMETERIZE',`For continuous latent variables, write a sample as a differentiable transform of parameter-free noise.<br><br>Differentiate the Monte Carlo objective through the transform.<br><br>Use positive scale parameterizations.<br><br>A noisy gradient step does not guarantee an ELBO increase on every iteration.`,
 'PATHWISE GRADIENT',M(R`\begin{aligned}z&=g_\lambda(\varepsilon),\quad\varepsilon\sim s(\varepsilon)\\\mathcal L(\lambda,\theta)&=\mathbb E_{s(\varepsilon)}\left[\log p_\theta(x,g_\lambda(\varepsilon))-\log q_\lambda(g_\lambda(\varepsilon))\right]\\\nabla_\lambda\mathcal L&=\mathbb E_s\nabla_\lambda\left[\log p_\theta(x,g_\lambda(\varepsilon))-\log q_\lambda(g_\lambda(\varepsilon))\right]\end{aligned}`),
 'Interchange of differentiation and expectation requires regularity conditions. This pathwise estimator is directly applicable to differentiably reparameterizable continuous distributions. Discrete variables require other estimators, enumeration, or approximations. Amortized inference predicts variational parameters from data, while the ELBO remains the objective.','[4] Kingma & Welling',{size:19}));
slides.push(slide('pitfalls','Implementation & interpretation','Five mistakes worth preventing','A higher objective is useful only when the objective and the model are correctly identified.',[
 ...panel('pitfalls-a',72,184,550,420,'STATISTICAL DISTINCTIONS',`<b>Expectation ≠ substitution.</b><br>${I(R`\mathbb E[f(z)]\ne f(\mathbb E[z])`)} in general.<br><br><b>Soft EM ≠ k-means.</b><br>Hard assignments change the algorithm.<br><br><b>Convergence ≠ global optimality.</b><br>Try multiple starts; inspect responsibilities and effective counts.`,{size:19}),
 ...panel('pitfalls-b',646,184,562,420,'NUMERICAL & MODEL CHECKS',`<b>Prevent covariance collapse.</b><br>Unconstrained Gaussian-mixture likelihood can be unbounded. Use an explicit constraint or prior.<br><br><b>Monitor the right quantity.</b><br>Exact EM: likelihood. Restricted VI: ELBO. MAP-EM: posterior objective.<br><br>Use log-sum-exp and verify normalization.`,{fill:C.warm,accent:C.rust,size:19})
],'The example variance floor is an explicit model constraint, not an unexplained numerical patch. Objective comparisons require the same data, model, and normalization conventions. Label swapping produces equivalent mixture fits.','[1] · [2] · [3]'));
slides.push(slide('summary','One-page synthesis','Choose the unknown you want to optimize','The ELBO unifies the calculations without erasing their differences.',[
 ...panel('summary-id',72,181,1136,123,'THE IDENTITY',M(R`\log p_\theta(x)=\underbrace{\mathbb E_q\log p_\theta(x,z)+H(q)}_{\mathcal L(q,\theta)}+\mathrm{KL}(q\Vert p_\theta(z\mid x))`),{size:24,body:{align:'center',valign:'middle'}}),
 text('summary-table',72,325,1136,278,table(['Question','Method','Key operation'],[
 ['Approximate a fixed posterior?','VI / CAVI',`${I(R`q_j\propto\exp\{\mathbb E_{-j}\log p\}`)}`],
 ['Learn parameters with an exact E-step?','EM',`${I(R`q=p_\theta(z\mid x)`)}; maximize expected log joint`],
 ['Exact E-step is unavailable?','Variational EM','Restrict q; alternate bound improvements'],
 ['Need parameter uncertainty?','Bayesian VI',`Approximate ${I(R`p(z,\theta\mid x)`)}`]
 ]),{fontSize:17})
],'Return to the two labs: the Gaussian example isolates approximation error, while the mixture example isolates alternating latent-variable learning. Neither should be confused with a global-optimum guarantee.'));
slides.push(slide('references','Sources','Foundations and further reading','Primary sources, plus explicitly labeled analytical and synthetic examples.',[
 ...[
 ['[1] Blei, Kucukelbir & McAuliffe (2017)','Variational Inference: A Review for Statisticians. JASA 112(518), 859–877. ELBO, mean-field VI, CAVI, and Gaussian mixtures.','https://arxiv.org/abs/1601.00670'],
 ['[2] Dempster, Laird & Rubin (1977)','Maximum Likelihood from Incomplete Data via the EM Algorithm. JRSS B 39(1), 1–22. EM and likelihood monotonicity.','https://doi.org/10.1111/j.2517-6161.1977.tb01600.x'],
 ['[3] Neal & Hinton (1998)','A View of the EM Algorithm that Justifies Incremental, Sparse, and Other Variants. Learning in Graphical Models, 355–368.','https://www.cs.toronto.edu/~hinton/absps/em.htm'],
 ['[4] Kingma & Welling (2014)','Auto-Encoding Variational Bayes. ICLR. Reparameterization and stochastic variational optimization.','https://arxiv.org/abs/1312.6114']
 ].flatMap(([author,desc,link],i)=>[box('ref-'+i,72,181+i*106,1136,91,i%2?C.soft:C.panel),text('ref-title-'+i,92,194+i*106,1096,26,author,{fontSize:20,fontFamily:serif,fontWeight:700,link}),text('ref-desc-'+i,92,228+i*106,1096,37,desc,{fontSize:14,color:C.muted,link})]),
 text('refs-note',82,618,1116,32,'Labs: seeded synthetic data and exact Gaussian identities. No external data, API keys, or training service.',{fontSize:14,color:C.green})
],'All references are clickable. The mean-field Gaussian and fixed-variance Bayesian mixture formulas are worked derivations included in these notes. The interactive experiments are teaching examples, not empirical research claims.','PRIMARY REFERENCES') );
export const deck={format:'bento/slides',version:1,docId:'variational-inference-em-bento',title:'One Bound, Two Algorithms: Variational Inference & EM',readonly:true,meta:{author:'Bai Liping',subject:'Variational inference, ELBO, CAVI, expectation–maximization, and Bayesian VI',company:'bailiping.com'},size:{width:1280,height:720},theme:{background:C.paper,color:C.ink,accent:C.green,fontFamily:sans},slides};
export const inlineLiveMap=[['mean-field-live','meanfield','gaussian','Mean-field Gaussian geometry'],['em-live','em','gmm-sheet','Gaussian-mixture EM']].map(([id,demo,intro,title])=>({introSlide:intro,slide:id,slideIndex:slides.findIndex(s=>s.id===id),inline:true,layout:'region',bounds:{x:72,y:180,width:1136,height:475},src:'./live/?demo='+demo+'&embed=region',source:'./live/?demo='+demo,title,sandbox:'allow-scripts',hideSource:true,readyMessage:true,unloadWhenHidden:false}));
