import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
import {deck,inlineLiveMap} from './bento-deck.mjs';
const here=dirname(fileURLToPath(import.meta.url));
const template=await readFile(resolve(here,'../kalman-filter-derivations/index.html'),'utf8');
const safe=value=>JSON.stringify(value,null,1).replaceAll('<','\\u003c');
// Editorial fit adjustments are kept here so the original content remains easy to edit.
const summary=deck.slides.find(s=>s.id==='summary').elements.find(e=>e.id==='summary-table');
summary.h=320;summary.html=summary.html.replaceAll('font-size:18px','font-size:16px').replaceAll('padding:16px 12px','padding:11px 10px');
const conjugate=deck.slides.find(s=>s.id==='bayesian-sheet').elements.find(e=>e.id==='bayesian-sheet-0-body');
conjugate.html=conjugate.html.replace('\\[','\\[\\begin{gathered}').replace('\\]','\\end{gathered}\\]');
// Keep one line of ambient motion on the cover, as in the existing deck.
deck.slides[0].elements.push({id:'cover-accent-line',type:'shape',shape:'line',x:77,y:324,w:685,h:1,fill:'none',stroke:'#A94F2A',strokeWidth:2,rotation:0,opacity:.6,fx:{loop:{type:'dash-march'}}});
for(const [i,s] of deck.slides.entries()){
  if(!s.notes)throw new Error('Missing notes: '+s.id);
  const ids=new Set();
  for(const e of s.elements){if(ids.has(e.id))throw new Error('Duplicate element '+e.id);ids.add(e.id);if(e.x<0||e.y<0||e.x+e.w>1281||e.y+e.h>721)throw new Error('Out of slide: '+s.id+'/'+e.id);}
  s.elements.push({id:'slide-number',type:'text',x:937,y:684,w:80,h:20,html:`${String(i+1).padStart(2,'0')} / ${deck.slides.length}`,fontSize:10,fontFamily:'monospace',color:'#66756E',align:'center'});
}
const pattern=/(<script type="application\/bento\+json" id="bento-doc">\s*)[\s\S]*?(\s*<\/script>)/;
if(!pattern.test(template))throw new Error('Bento template document not found');
let html=template.replace(pattern,(_,a,b)=>a+safe(deck)+b);
const mapPattern=/<script type="application\/json" id="bento-inline-live-map">[\s\S]*?<\/script>/;
if(!mapPattern.test(html))throw new Error('Bento inline-live map not found');
html=html.replace(mapPattern,()=>'<script type="application/json" id="bento-inline-live-map">\n'+safe(inlineLiveMap)+'\n</script>');
const routes=Object.fromEntries(deck.slides.map((s,i)=>[s.id,i]));
const routeScript=`<script>(()=>{const routes=${JSON.stringify(routes)};function routeToSlide(){let r;try{r=decodeURIComponent(location.hash.replace(/^#\\/?/,''));}catch{return;}if(r&&!/^\\d+$/.test(r)&&Number.isInteger(routes[r]))history.replaceState(null,'',location.pathname+location.search+'#/'+routes[r]);}addEventListener('hashchange',routeToSlide);routeToSlide();})();</script>`;
let replaced=false;
html=html.replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/g,(full,attrs,body)=>{if(!attrs.trim()&&body.includes('const routes =')&&body.includes('routeToSlide')){replaced=true;return routeScript;}return full;});
if(!replaced)throw new Error('Template route mapper not found');
html=html.replace(/<title>[\s\S]*?<\/title>/,'<title>One Bound, Two Algorithms: Variational Inference &amp; EM | Bai Liping</title>');
html=html.replace(/<meta name="description"[^>]*>/,'<meta name="description" content="26 interactive Bento slides on the ELBO, mean-field variational inference, CAVI, exact EM, variational EM, and Bayesian VI, with two live numerical laboratories." />');
html=html.replace(/<link rel="canonical"[^>]*>/,'<link rel="canonical" href="https://bailiping.com/variational-inference-em/" />');
html=html.replace(/<!-- Generated by kalman-filter-derivations[^>]*-->/,'<!-- Generated by variational-inference-em/build.mjs. Edit bento-deck.mjs, then rebuild. -->');
if(!html.includes('tex-svg-full.js')||!html.includes('mathjax-dynamic.js')||!html.includes('bento-inline-live.js'))throw new Error('Required shared runtime missing');
await writeFile(resolve(here,'index.html'),html);
console.log(`Built ${deck.slides.length} VI/EM slides and ${inlineLiveMap.length} live experiments (${html.length} characters).`);
console.log('Slide routes: '+deck.slides.map(s=>s.id).join(', '));
