import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
import {deck,inlineLiveMap} from './bento-deck.mjs';
const here=dirname(fileURLToPath(import.meta.url));
const template=await readFile(resolve(here,'../kalman-filter-derivations/index.html'),'utf8');
const safe=value=>JSON.stringify(value,null,1).replaceAll('<','\\u003c');
// Text boxes sanitize table tags; compile editorial grids to native Bento tables.
for(const s of deck.slides){
  s.elements=s.elements.map(e=>{
    if(e.type!=='text'||!e.html?.startsWith('<table'))return e;
    const rows=[...e.html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/g)].map(row=>({cells:[...row[1].matchAll(/<t[hd]\b[^>]*>([\s\S]*?)<\/t[hd]>/g)].map(cell=>({html:cell[1]}))}));
    if(rows.length!==5||rows.some(r=>r.cells.length!==3))throw new Error('Invalid comparison grid: '+e.id);
    const compact=s.id==='summary';
    return {id:e.id,type:'table',x:e.x,y:e.y,w:e.w,h:compact?320:e.h,rotation:0,opacity:1,header:true,
      columns:(compact?[1.45,.95,1.9]:[1.15,1.35,1.5]).map(w=>({w})),rows,
      style:{headerBg:'#2F6B4F',headerColor:'#FFFFFF',zebra:'#E7F0EA',borderColor:'#D8DED7',borderWidth:1,cellPadX:16,cellPadY:11,fontSize:compact?17:18,color:'#203129',fontFamily:deck.theme.fontFamily,radius:12}};
  });
}
const conjugate=deck.slides.find(s=>s.id==='bayesian-sheet').elements.find(e=>e.id==='bayesian-sheet-0-body');
conjugate.html=conjugate.html.replace('\\[','\\[\\begin{gathered}').replace('\\]','\\end{gathered}\\]');
deck.slides[0].elements.push({id:'cover-accent-line',type:'shape',shape:'line',x:77,y:324,w:685,h:1,fill:'none',stroke:'#A94F2A',strokeWidth:2,rotation:0,opacity:.6,fx:{loop:{type:'dash-march'}}});
for(const [i,s] of deck.slides.entries()){
  if(!s.notes)throw new Error('Missing notes: '+s.id);
  const ids=new Set();
  for(const e of s.elements){if(ids.has(e.id))throw new Error('Duplicate element '+e.id);ids.add(e.id);if(e.x<0||e.y<0||e.x+e.w>1281||e.y+e.h>721)throw new Error('Out of slide: '+s.id+'/'+e.id);}
  s.elements.push({id:'slide-number',type:'text',x:937,y:684,w:80,h:20,html:`${String(i+1).padStart(2,'0')} / ${deck.slides.length}`,fontSize:10,fontFamily:'monospace',color:'#66756E',align:'center'});
}
const pattern=/(<script type="application\/bento\+json" id="bento-doc">\s*)[\s\S]*?(\s*<\/script>)/;
if(!pattern.test(template))throw new Error('Bento template document not found');
let html=template.replace(pattern,(_,a,b)=>a+safe(deck)+b);
const mapPattern=/<script type="application\/json" id="bento-inline-live-map">[\s\S]*?<\/script>/;
if(!mapPattern.test(html))throw new Error('Bento inline-live map not found');
html=html.replace(mapPattern,()=>'<script type="application/json" id="bento-inline-live-map">\n'+safe(inlineLiveMap)+'\n</script>');
const routes=Object.fromEntries(deck.slides.map((s,i)=>[s.id,i]));
const routeScript=`<script>(()=>{const routes=${JSON.stringify(routes)};function routeToSlide(){let r;try{r=decodeURIComponent(location.hash.replace(/^#\\/?/,''));}catch{return;}if(r&&!/^\\d+$/.test(r)&&Number.isInteger(routes[r]))history.replaceState(null,'',location.pathname+location.search+'#/'+routes[r]);}addEventListener('hashchange',routeToSlide);routeToSlide();})();</script>`;
let replaced=false;
html=html.replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/g,(full,attrs,body)=>{if(!attrs.trim()&&body.includes('const routes =')&&body.includes('routeToSlide')){replaced=true;return routeScript;}return full;});
if(!replaced)throw new Error('Template route mapper not found');
html=html.replace(/<title>[\s\S]*?<\/title>/,'<title>One Bound, Two Algorithms: Variational Inference &amp; EM | Bai Liping</title>');
html=html.replace(/<meta name="description"[^>]*>/,'<meta name="description" content="26 interactive Bento slides on the ELBO, mean-field variational inference, CAVI, exact EM, variational EM, and Bayesian VI, with two live numerical laboratories." />');
html=html.replace(/<link rel="canonical"[^>]*>/,'<link rel="canonical" href="https://bailiping.com/variational-inference-em/" />');
html=html.replace(/<!-- Generated by kalman-filter-derivations[^>]*-->/,'<!-- Generated by variational-inference-em/build.mjs. Edit bento-deck.mjs, then rebuild. -->');
// Bento strips span classes. The shared restorer handles text panels only;
// this local bridge extends restoration to table cells and reuses its queue.
const tableMathBridge=String.raw`<script>
(()=>{
  function restoreTableMath(){
    let changed=false;
    document.querySelectorAll('.bento-cell-inner span:not(.math-tex)').forEach(node=>{
      const source=node.textContent.trim();
      const inline=source.startsWith('\\(')&&source.endsWith('\\)');
      const display=source.startsWith('\\[')&&source.endsWith('\\]');
      if(inline||display){node.classList.add('math-tex',inline?'math-inline':'math-display');changed=true;}
    });
    if(changed)window.typesetDynamicMath?.();
  }
  new MutationObserver(restoreTableMath).observe(document.documentElement,{childList:true,subtree:true});
  document.addEventListener('DOMContentLoaded',restoreTableMath,{once:true});
  restoreTableMath();
})();
</script>`;
html=html.replace('</body>',tableMathBridge+'\n</body>');
if(!html.includes('tex-svg-full.js')||!html.includes('mathjax-dynamic.js')||!html.includes('bento-inline-live.js'))throw new Error('Required shared runtime missing');
await writeFile(resolve(here,'index.html'),html);
console.log(`Built ${deck.slides.length} VI/EM slides and ${inlineLiveMap.length} live experiments (${html.length} characters).`);
console.log('Slide routes: '+deck.slides.map(s=>s.id).join(', '));
