import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { deck, inlineLiveMap } from './deck.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const templatePath = resolve(here, '../frame-registration-slides/index.html');
// Preserve the scrollable reference at index.html; this builds the legacy deck only.
const outputPath = resolve(here, 'slides.html');

const template = await readFile(templatePath, 'utf8');
const docPattern = /(<script type="application\/bento\+json" id="bento-doc">\s*)[\s\S]*?(\s*<\/script>)/;

if (!docPattern.test(template)) {
  throw new Error(`Bento document block not found in ${templatePath}`);
}

const safeJson = value => JSON.stringify(value, null, 1).replaceAll('<', '\\u003c');

let html = template.replace(docPattern, `$1${safeJson(deck)}$2`);
const pageTitle = '<title>One Filter, Sixteen Derivations | Bai Liping</title>';
const pageDescription = '<meta name="description" content="Sixteen derivations of the linear–Gaussian Kalman measurement update, presented as a Bento slide atlas with three inline experiments." />';
const liveStylesheet = '<link rel="stylesheet" href="../assets/bento-inline-live.css" />';

html = html.replace(/<title>[\s\S]*?<\/title>/, pageTitle);
if (/<meta name="description"\b[^>]*>/.test(html)) {
  html = html.replace(/<meta name="description"\b[^>]*>/, pageDescription);
} else {
  html = html.replace(pageTitle, `${pageTitle}\n    ${pageDescription}`);
}
if (!html.includes(liveStylesheet)) {
  html = html.replace(pageDescription, `${pageDescription}\n    ${liveStylesheet}`);
}

const liveIntegration = `
    <script type="application/json" id="bento-inline-live-map">
${safeJson(inlineLiveMap)}
    </script>
    <script src="../assets/bento-inline-live.js"></script>
`;
const existingLiveIntegration = /\s*<script type="application\/json" id="bento-inline-live-map">[\s\S]*?<\/script>\s*<script src="\.\.\/assets\/bento-inline-live\.js"><\/script>/;

if (!html.includes('</body>')) {
  throw new Error('Bento template has no closing body tag');
}

if (existingLiveIntegration.test(html)) {
  html = html.replace(existingLiveIntegration, liveIntegration.trimEnd());
} else {
  html = html.replace('</body>', `${liveIntegration}  </body>`);
}
html = html.replace(
  '<!DOCTYPE html>',
  '<!DOCTYPE html>\n<!-- Generated by kalman-filter-derivations/build.mjs. Edit deck.mjs or routes.mjs, then rebuild. -->'
);
html = html.replace(/[ \t]+$/gm, '').replace(/\n*$/, '\n');

await writeFile(outputPath, html);
console.log(`Built ${outputPath}`);
console.log(`${deck.slides.length} regular slides; ${inlineLiveMap.length} inline live regions`);
