import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { deck, inlineLiveMap } from './bento-deck.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const templatePath = resolve(here, '../frame-registration-slides/index.html');
const preview = process.argv.includes('--preview');
const outputPath = resolve(here, preview ? 'bento-preview.html' : 'index.html');
const template = await readFile(templatePath, 'utf8');
const safeJson = value => JSON.stringify(value, null, 1).replaceAll('<', '\\u003c');

const legacyAliases = {
  main: 'overview',
  routes: 'overview',
  result: 'model',
  conditioning: 'bayes',
  information: 'bayes',
  'bayes-closure': 'bayes',
  projection: 'mse',
  covariance: 'mse',
  blue: 'least-squares',
  'square-root': 'least-squares',
  'graphs-equations': 'graphs',
  connections: 'implementations'
};
const slideIndexes = Object.fromEntries(deck.slides.map((slide, index) => [slide.id, index]));
const routeIndexes = Object.fromEntries(
  Object.entries({ ...slideIndexes, ...legacyAliases }).map(([route, target]) => [
    route,
    Number.isInteger(target) ? target : slideIndexes[target]
  ])
);
const routeScript = `    <script>
      (() => {
        const routes = ${JSON.stringify(routeIndexes)};
        const routeToSlide = () => {
          const route = decodeURIComponent(location.hash.replace(/^#\\/?/, ''));
          if (route && !/^\\d+$/.test(route) && Number.isInteger(routes[route])) {
            history.replaceState(null, '', location.pathname + location.search + '#/' + routes[route]);
          }
        };
        addEventListener('hashchange', routeToSlide);
        routeToSlide();
      })();
    </script>`;

const docPattern = /(<script type="application\/bento\+json" id="bento-doc">\s*)[\s\S]*?(\s*<\/script>)/;
if (!docPattern.test(template)) throw new Error(`Bento document block not found in ${templatePath}`);

let html = template.replace(docPattern, `$1${safeJson(deck)}$2`);
const pageTitle = '<title>One Filter, Four Derivation Families | Bai Liping</title>';
const pageDescription = '<meta name="description" content="An interactive Bento deck presenting four Kalman filter derivation families with equation sheets and deterministic experiments." />';
const canonical = '<link rel="canonical" href="https://bailiping.com/kalman-filter-derivations/" />';
const liveStylesheet = '<link rel="stylesheet" href="../assets/bento-inline-live.css" />';

html = html.replace(/<title>[\s\S]*?<\/title>/, pageTitle);
if (/<meta name="description"\b[^>]*>/.test(html)) {
  html = html.replace(/<meta name="description"\b[^>]*>/, pageDescription);
} else {
  html = html.replace(pageTitle, `${pageTitle}\n    ${pageDescription}`);
}
if (!html.includes(canonical)) html = html.replace(pageDescription, `${pageDescription}\n    ${canonical}`);
if (!html.includes(liveStylesheet)) html = html.replace(canonical, `${canonical}\n    ${liveStylesheet}`);
if (!html.includes('const routes =')) html = html.replace('</head>', `${routeScript}\n  </head>`);

const liveMap = `    <script type="application/json" id="bento-inline-live-map">\n${safeJson(inlineLiveMap)}\n    </script>`;
const mapPattern = /\s*<script type="application\/json" id="(?:bento-live-config|bento-inline-live-map)">[\s\S]*?<\/script>/;
if (mapPattern.test(html)) {
  html = html.replace(mapPattern, `\n${liveMap}`);
} else {
  html = html.replace('</body>', `${liveMap}\n  </body>`);
}

const liveScript = '<script src="../assets/bento-inline-live.js"></script>';
if (!html.includes(liveScript)) html = html.replace('</body>', `    ${liveScript}\n  </body>`);
html = html.replaceAll('../assets/bento-live.css', '../assets/bento-inline-live.css');
html = html.replaceAll('../assets/bento-live.js', '../assets/bento-inline-live.js');
html = html.replace(
  '<!DOCTYPE html>',
  '<!DOCTYPE html>\n<!-- Generated by kalman-filter-derivations/build-bento.mjs. Edit bento-deck.mjs, then rebuild. -->'
);
html = html.replace(/[ \t]+$/gm, '').replace(/\n*$/, '\n');

if (!html.includes('"docId": "kalman-filter-four-families-bento"')) throw new Error('Bento document replacement failed');
if (!html.includes('id="bento-inline-live-map"') || html.includes('id="bento-live-config"')) throw new Error('Inline live map replacement failed');

await writeFile(outputPath, html);
console.log(`Built ${outputPath}`);
console.log(`${deck.slides.length} regular Bento slides; ${inlineLiveMap.length} inline live regions`);

if (!preview) {
  const redirect = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="refresh" content="0; url=./">
    <title>One Filter, Four Derivation Families</title>
    <script>location.replace('./' + location.search + location.hash);</script>
  </head>
  <body><p><a href="./">Open the interactive Bento deck</a>.</p></body>
</html>
`;
  await Promise.all([
    writeFile(resolve(here, 'consolidated-slides.html'), redirect),
    writeFile(resolve(here, 'slides.html'), redirect)
  ]);
  console.log('Updated compatibility redirects.');
}
