/** Principal-route catalogue and distinctive experiments, 2026-09-05.
 * Runs after math-review.mjs. Four principles + two computational viewpoints:
 * neither the six groups nor the individual rows are independent estimators.
 */
const R=String.raw, M=s=>`<span class="math-tex math-display">\\[${s}\\]</span>`;
const C={paper:'#F7F5EF',panel:'#FFFEFB',ink:'#203129',muted:'#66756E',rule:'#D8DED7'};
const sans="Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",mono="'SFMono-Regular', Consolas, monospace",serif="Georgia, 'Times New Roman', serif";
export const groups=[
{id:'bayes',n:'01',name:'Probability & conditioning',short:'Bayes',color:'#2F6B4F',soft:'#E7F0EA',kind:'DERIVATION PRINCIPLE',question:'Which distribution remains after an observation?',eq:R`p^+(x)=p(z\mid x)p^-(x)/p(z)`,output:'Full posterior; closure gives Gaussian moments.',reference:['Särkkä · Bayesian Filtering and Smoothing','https://users.aalto.fi/~ssarkka/pub/cup_book_online_20131111.pdf'],rows:[
['Gaussian product / completing the square',R`\log p^+(x)=-\tfrac12x^{\mathsf T}Jx+h^{\mathsf T}x+C`,'Read off both mean and covariance.'],
['Joint Gaussian conditioning',R`m^+=m^-+C_{xz}S^{-1}\nu`,'Condition the state–measurement covariance blocks.'],
['Conjugacy / information form',R`J=P^{-1}+H^{\mathsf T}R^{-1}H`,'Gaussian factors add precision coefficients.'],
['Bayesian / HMM recursion',R`p_k^-=\int p(x_k\mid x_{k-1})p_{k-1}^+\,dx_{k-1}`,'Predict by integration, then condition.'],
['Gaussian-process conditioning',R`P^+=P-C_{xz}S^{-1}C_{xz}^{\mathsf T}`,'Same identity; finite Markov realization is extra.']],
boundary:'Exact Bayes is not restricted to Gaussian laws; the closed Kalman recursion is. Here Cxz = PHᵀ. Information form, conjugacy, and conditioning are related representations of the same posterior.',demo:'Switch a Gaussian prior to a two-component mixture with the same mean and variance. Compare exact Bayes with the moment-matched Kalman Gaussian.',contrast:'A density calculation retains shape that a mean-and-covariance update can miss.',labTitle:'A posterior is more than its mean.',fallback:R`p^+(x)=\sum_i\widetilde w_i\,\mathcal N(x;m_i^+,P_i^+)`,fallbackText:'Update each component, then reweight it by its predictive evidence. At z = 0, a symmetric mixture may keep two modes even though its mean is zero. Away from symmetry, the exact and affine means can differ.'},
{id:'mse',n:'02',name:'Second moments & projection',short:'Minimum MSE',color:'#496E87',soft:'#E7EEF3',kind:'DERIVATION PRINCIPLE',question:'Which affine estimator has the smallest error?',eq:R`\mathbb E[(e^- -K\nu)\nu^{\mathsf T}]=0`,output:'Optimal affine gain and error covariance.',reference:['Kalman (1960) · linear estimation','https://doi.org/10.1115/1.3662552'],rows:[
['Orthogonality / Hilbert-space projection',R`KS=\operatorname{Cov}(x,z)=PH^{\mathsf T}`,'The remaining error is orthogonal to the innovation.'],
['Differentiate mean-square error',R`\nabla_K\operatorname{tr}P_e(K)=2(KS-PH^{\mathsf T})`,'Choose a gain using only second moments.'],
['Complete the covariance square',R`P_e(K)=P^++(K-K_*)S(K-K_*)^{\mathsf T}`,'A PSD difference proves global affine optimality.'],
['Wiener–Hopf / linear regression',R`\widehat x=m_x+C_{xz}C_{zz}^{-1}(z-m_z)`,'The batch linear projection gives the same gain.'],
['Innovations / Gram–Schmidt',R`\widehat x=\sum_i\operatorname{Cov}(x,\nu_i)S_i^{-1}\nu_i`,'Centered variables; project onto uncorrelated innovations.']],
boundary:'Finite second moments suffice under the stated cross-covariances. Without joint Gaussianity, LMMSE need not equal the conditional mean, and its error covariance is not a realized posterior covariance.',demo:'Move a candidate gain. Find both minimum expected error and zero error–innovation covariance. Change the distribution without changing its variance.',contrast:'The same affine gain survives distribution changes that alter the Bayesian posterior.',labTitle:'Choose the gain. Remove the correlation.',fallback:R`\mathcal R(K)=4(1-K)^2+K^2,\quad K_*=0.8`,fallbackText:'For independent prior error and noise with variances 4 and 1, the minimum risk is 0.8 and E[eν] = 4 − 5K. Gaussian and symmetric two-point variables produce the same risk curve.'},
{id:'wls',n:'03',name:'Quadratic objectives',short:'Least squares',color:'#A94F2A',soft:'#F5E8DF',kind:'DERIVATION PRINCIPLE',question:'Which state minimizes weighted discrepancy?',eq:R`\nabla_x\!\left[\tfrac12\|x-m^-\|_{P^{-1}}^2+\tfrac12\|z-Hx\|_{R^{-1}}^2\right]=0`,output:'Point estimate; covariance needs a model.',reference:['Aitken (1936) · generalized least squares','https://doi.org/10.1017/S0370164600014346'],rows:[
['Gaussian MAP / negative log density',R`x^*=\arg\min_x[-\log p^-(x)-\log p(z\mid x)]`,'A Gaussian posterior has the same mean and mode.'],
['Weighted / generalized least squares',R`(A^{\mathsf T}A)x^*=A^{\mathsf T}b`,'Stack and whiten the prior and measurement residuals.'],
['Gauss–Markov / BLUE',R`\widehat x=(G^{\mathsf T}W^{-1}G)^{-1}G^{\mathsf T}W^{-1}d`,'Unbiased noisy observations of a fixed state.'],
['Tikhonov / regularized least squares',R`\min_x\|z-Hx\|_{R^{-1}}^2+\|L(x-m^-)\|^2`,'Choose LᵀL = P⁻¹ for the Kalman prior weighting.'],
['Recursive least squares / Woodbury',R`J_k=J_{k-1}+H_k^{\mathsf T}R_k^{-1}H_k`,'Static state: update sufficient normal statistics.']],
boundary:'A,b are whitened stacks. BLUE: d = [a;z], G = [I;H], W = diag(P,R), where a is unbiased for a fixed x and its error is uncorrelated with measurement noise. Forgetting-factor RLS changes the model.',demo:'Inspect prior and data penalties, their sum, its gradient, and curvature. One Newton step reaches the scalar quadratic optimum.',contrast:'This optimizes a point; the KL group must optimize both location and spread.',labTitle:'The update is the bottom of a quadratic.',fallback:R`J=\alpha/P+1/R,\quad x^*=J^{-1}(\alpha m^-/P+z/R)`,fallbackText:'At α = 1 the objective is the shared Kalman model. A different prior multiplier changes the effective prior variance to P/α. Changing statistical weights is not merely a numerical implementation change.'},
{id:'kl',n:'04',name:'Variational & information views',short:'Variational / KL',color:'#71638B',soft:'#ECE9F2',kind:'DERIVATION PRINCIPLE',question:'Which updated distribution balances fit and belief change?',eq:R`q_* =\arg\min_q D_{\rm KL}(q\Vert p^-)-\mathbb E_q\log p(z\mid x)`,output:'Bayes posterior as distributional optimization.',reference:['Bissiri, Holmes & Walker (2016)','https://arxiv.org/abs/1306.6430'],rows:[
['Gibbs / minimum relative-entropy update',R`q_*(x)\propto p^-(x)e^{-\ell_z(x)}`,'Negative log-likelihood loss recovers Bayes.'],
['ELBO / variational free energy',R`F(q)+\log p(z)=D_{\rm KL}(q\Vert p^+)`,'Minimize free energy or maximize the ELBO.'],
['Gaussian variational calculus',R`\nabla_\mu F=J\mu-h,\quad\nabla_\Sigma F=\tfrac12(J-\Sigma^{-1})`,'Optimize mean AND covariance; retain entropy.'],
['Exponential-family natural parameters',R`h^+=h^-+H^{\mathsf T}R^{-1}z,\quad J^+=J^-+H^{\mathsf T}R^{-1}H`,'Likelihood tilting adds Gaussian parameters.'],
['Maximum relative entropy with data',R`p^+(x)=p^-(x)p(z\mid x)/p(z)`,'A conditioning argument; observation constraints matter.']],
boundary:'These are reformulations, not independent probability laws. Gaussian-restricted VI is exact here because the posterior is Gaussian. Entropy reduction or surprise alone cannot determine the observed mean update.',demo:'Move candidate mean and standard deviation separately. Plot the exact free-energy gap; matching only the mean leaves a positive gap.',contrast:'Unlike MAP, a correct mean is insufficient: the candidate distribution must also have the correct spread.',labTitle:'A correct mean can still be a wrong belief.',fallback:R`D_{\rm KL}(q\Vert p^+)=\tfrac12\!\left[\frac{\sigma_q^2+(\mu_q-m^+)^2}{P^+}-1+\log\frac{P^+}{\sigma_q^2}\right]`,fallbackText:'The gap is zero only when both moments match. Collapsing the candidate variance to zero makes this KL diverge for a nonsingular Gaussian posterior. Likelihood normalization is retained for the evidence.'},
{id:'graphs',n:'05',name:'Recursive elimination & messages',short:'Recursive inference',color:'#287A78',soft:'#E4F1EF',kind:'COMPUTATIONAL VIEWPOINT',question:'How can a trajectory be reduced to a small message?',eq:R`J_b^{\rm marg}=J_{bb}-J_{ba}J_{aa}^{-1}J_{ab}`,output:'Filtering by elimination; smoothing with future data.',reference:['Loeliger et al. (2007) · Gaussian messages','https://www.isiweb.ee.ethz.ch/papers/arch/aloe-jdau-juhu-skor-2007-1.pdf'],rows:[
['Sum-product / HMM forward messages',R`\mu_{k-1\to k}(x_k)=\int f_k(x_{k-1},x_k)b_{k-1}(x_{k-1})\,dx_{k-1}`,'Integrate the old state out of the chain.'],
['Gaussian / Schur-complement elimination',R`h_b^{\rm marg}=h_b-J_{ba}J_{aa}^{-1}h_a`,'Eliminate a block in canonical coordinates.'],
['Dynamic programming / min-sum',R`V_k(x_k)=\ell_k(x_k)+\min_{x_{k-1}}[V_{k-1}(x_{k-1})+d_k]`,'Gaussian quadratics give the same Schur coefficients.'],
['Innovation / predictive factorization',R`p(z_{1:k})=\prod_{i=1}^k p(z_i\mid z_{1:i-1})`,'Sequential prediction also gives the evidence.'],
['Backward messages / RTS smoothing',R`m_{k\mid T}=m_k^++G_k(m_{k+1\mid T}-m_{k+1}^-)`,'Extension: future observations refine earlier states.']],
boundary:'a,b are eliminated/retained blocks; ℓk and dk are observation and transition costs. Gk = Pk⁺Fk₊₁ᵀ(Pk₊₁⁻)⁻¹. Min-sum and integration share Gaussian quadratic coefficients, not normalization constants.',demo:'Eliminate a four-state chain step by step. Move its final observation: the final filter and batch marginal agree, but earlier smoothed estimates move.',contrast:'Filtering and smoothing use different information sets, not different answers to the same question.',labTitle:'Eliminate the past; retain a message.',fallback:R`d_i=J_{ii}-J_{i,i-1}^2/d_{i-1},\qquad g_i=h_i-J_{i,i-1}g_{i-1}/d_{i-1}`,fallbackText:'Forward elimination leaves the last marginal precision and information coefficient. Back substitution recovers the batch trajectory mean. Earlier filtered estimates do not use the last observation.'},
{id:'numerical',n:'06',name:'Numerical forms & algebraic bridges',short:'Numerical forms',color:'#92702E',soft:'#F4EEDC',kind:'COMPUTATIONAL VIEWPOINT',question:'Which algebra computes the estimator reliably?',eq:R`A=UT,\quad Tm^+=U^{\mathsf T}b,\quad P^+=T^{-1}T^{-\mathsf T}`,output:'Same target; different factors and rounding.',reference:['Kaminski, Bryson & Schmidt (1971)','https://doi.org/10.1109/TAC.1971.1099816'],rows:[
['Covariance update / Joseph form',R`P_e(K)=(I-KH)P(I-KH)^{\mathsf T}+KRK^{\mathsf T}`,'Any fixed gain; equals P⁺ at the optimal gain.'],
['Information filter / Woodbury',R`J^+=J^-+H^{\mathsf T}R^{-1}H`,'Store precision; prediction requires elimination.'],
['Square-root covariance / information',R`P=LL^{\mathsf T}\quad\text{or}\quad J=T^{\mathsf T}T`,'Propagate factors using orthogonal transformations.'],
['UD / LDLᵀ factorization',R`P=UDU^{\mathsf T}`,'Unit triangular U and diagonal D.'],
['Riccati / LQR duality',R`\Pi'=F\Pi F^{\mathsf T}+Q-F\Pi H^{\mathsf T}(H\Pi H^{\mathsf T}+R)^{-1}H\Pi F^{\mathsf T}`,'An algebraic bridge; constant gain needs convergence.']],
boundary:'U in thin QR is orthonormal; U in UD is unit triangular. The LQR dual uses Ac = Fᵀ, Bc = Hᵀ, Qc = Q, Rc = R and reverses finite-horizon time. These are not additional statistical optimality principles.',demo:'Use the precision lab after the QR/Riccati equation slide: increase conditioning and reduce simulated significant digits. Compare four arithmetic paths.',contrast:'Changing arithmetic should not change the exact estimator; changing the assumed uncertainty does.'}
];
function text(id,x,y,w,h,html,o={}){return {id,type:'text',x,y,w,h,rotation:0,opacity:1,html,fontFamily:sans,fontSize:16,fontWeight:400,color:C.ink,lineHeight:1.25,align:'left',valign:'top',...o};}
function box(id,x,y,w,h,fill=C.panel,stroke=C.rule){return {id,type:'shape',shape:'rect',x,y,w,h,fill,stroke,strokeWidth:1,radius:12,rotation:0,opacity:1};}
function slide(id,title,subtitle,els,g,notes){const ref=(g||groups[0]).reference;return {id,background:C.paper,transition:'none',notes:notes||`${title}. ${subtitle}`,elements:[text('guide-eyebrow',72,37,1136,22,g?`${g.kind} · GROUP ${g.n}`:'ONE FILTER · MANY ROUTES',{fontFamily:mono,fontSize:11,fontWeight:800,color:g?.color||groups[0].color}),text('guide-title',72,69,1136,51,title,{fontFamily:serif,fontSize:35,fontWeight:700,lineHeight:1.08}),text('guide-subtitle',72,124,1136,43,subtitle,{fontSize:15,color:C.muted}),...els,box('guide-rule',72,674,1136,1,C.rule,C.rule),text('guide-home',72,687,300,18,'BAI LIPING · ESTIMATION NOTES',{fontSize:10,fontFamily:mono,color:C.muted,link:'overview'}),text('guide-source',365,687,543,18,ref[0],{fontSize:10,color:C.muted,align:'center',link:ref[1]})]};}
function overview(){const els=[];groups.forEach((g,i)=>{const x=72+i%3*384,y=182+Math.floor(i/3)*184;els.push(box('tile-'+g.id,x,y,368,168,g.soft,g.color),text('kind-'+g.id,x+18,y+15,332,18,`${g.n} · ${g.kind}`,{fontSize:10,fontFamily:mono,color:g.color,fontWeight:800}),text('name-'+g.id,x+18,y+44,332,29,g.short,{fontSize:23,fontFamily:serif,fontWeight:700,link:'group-'+g.id}),text('question-'+g.id,x+18,y+82,332,43,g.question,{fontSize:14}),text('link-'+g.id,x+18,y+138,332,18,'5 routes · distinctive demo · equations ↗',{fontSize:11,color:g.color,link:'group-'+g.id}));});els.push(text('guide-scope',76,570,1128,76,'Four derivation principles + two computational viewpoints. The groups overlap: Bayes and unrestricted KL updating are equivalent; information form appears in both derivation and implementation. This is a map of principal routes, not an exhaustive count of all possible proofs.',{fontSize:16,lineHeight:1.4}));return slide('overview','One filter. Six useful viewpoints.','Start with the governing question. Compare what is optimized, what is assumed, and what each route reveals.',els,null,'The old four-family grouping was editorial, not exhaustive. Four principles are retained, and two computational viewpoints are made explicit. Each group catalogues principal derivations, aliases and extensions without calling them independent filters.');}
function comparison(){const els=[text('notation',78,173,1124,41,M(R`P=P^-,\quad\nu=z-Hm^-,\quad S=HPH^{\mathsf T}+R,\quad J=P^{-1}+H^{\mathsf T}R^{-1}H`),{fontSize:16,align:'center'})];groups.forEach((g,i)=>{const y=224+i*62;els.push(box('cmp-'+g.id,72,y,1136,57,i%2?g.soft:C.panel),text('cmp-name-'+g.id,86,y+11,191,39,`${g.n} · ${g.short}`,{fontSize:15,fontWeight:750,color:g.color,link:'group-'+g.id}),text('cmp-eq-'+g.id,281,y+8,632,41,M(g.eq),{fontSize:g.id==='wls'?13:15,align:'center',valign:'middle'}),text('cmp-out-'+g.id,933,y+9,259,40,g.output,{fontSize:12.6,lineHeight:1.25}));});els.push(text('comparison-foot',78,609,1124,48,'Inverse-based equations require positive-definite covariances. Linear–Gaussian case: posterior mean = MAP = LMMSE. QR factors a whitened residual system; Schur elimination marginalizes a precision block. The common model and detailed definitions follow.',{fontSize:13.5,color:C.muted,lineHeight:1.3}));return slide('family-comparison','Different governing equations. The same Gaussian answer.','Each route solves for a density, a gain, a state, a message, or a matrix factor—not the same kind of unknown.',els,null,'Equation comparison for all six viewpoints. See the shared model next for prediction, conditional notation and positive-definiteness requirements. Sources [1–8] on the references slide.');}
function catalogue(g){const els=[];g.rows.forEach(([name,eq,why],i)=>{const y=180+i*70;els.push(box('route-'+i,72,y,1136,65,i%2?g.soft:C.panel),text('name-'+i,87,y+10,248,48,name,{fontSize:15,fontWeight:700,color:g.color}),text('eq-'+i,345,y+10,577,44,M(eq),{fontSize:eq.length>120?12.5:15,align:'center',valign:'middle'}),text('why-'+i,942,y+10,250,48,why,{fontSize:12.5,lineHeight:1.25}));});els.push(box('demo-card',72,543,1136,116,g.soft,g.color),text('demo-label',90,558,205,21,'DISTINCTIVE EXPERIMENT',{fontSize:10,fontFamily:mono,color:g.color,fontWeight:850}),text('demo-copy',304,554,881,43,g.demo,{fontSize:14,lineHeight:1.3}),text('boundary',90,609,1094,42,g.boundary,{fontSize:12.4,lineHeight:1.25}));return slide('group-'+g.id,`${g.n} · ${g.name}`,`${g.question} Principal routes, their governing equations, and their limits.`,els,g,`${g.boundary}\n${g.contrast}\nSource: ${g.reference.join(' — ')}. Additional references: innovations [3], GP state-space models [9], maximum-relative-entropy conditioning [7]. See the retained equation sheets for defined notation and derivations. The innovations expansion is for centered variables and the linear span of orthogonal innovations; RTS is a smoothing extension rather than another filter.`);}
export const bounds={x:74,y:164,width:1132,height:492};
function lab(g){return slide(g.id+'-lab',g.labTitle,g.contrast,[box('fallback',74,164,1132,492,g.soft,g.color),text('fallback-type',101,190,1078,22,'STATIC / PRINT FALLBACK · LIVE CONTROLS LOAD ON THIS SLIDE',{fontFamily:mono,fontSize:11,color:g.color,fontWeight:800}),text('fallback-eq',112,249,1056,107,M(g.fallback),{fontSize:23,align:'center',valign:'middle'}),text('fallback-copy',126,389,1028,99,g.fallbackText,{fontSize:21,fontFamily:serif,lineHeight:1.35}),text('fallback-try',126,523,1028,85,'Try: '+g.demo,{fontSize:17,lineHeight:1.4}),{id:'live-demo-mount',type:'shape',shape:'rect',x:bounds.x,y:bounds.y,w:bounds.width,h:bounds.height,fill:'rgba(0,0,0,0)',stroke:'none',strokeWidth:0,opacity:0,rotation:0}],g,`${g.demo}\n${g.contrast}\n${g.fallbackText}\nAll plotted values and statistics come from the deterministic functions in live/families.js, also used by the regression tests. PageUp/PageDown navigate; Escape returns focus to the deck. No animation timer.`);}
export function applyFamilyGuide(slides){
 if(slides.some(s=>s.id==='family-comparison'))throw new Error('Guide applied twice');
 const old=new Map(slides.map(s=>[s.id,s]));const newer=[overview(),comparison(),...groups.map(catalogue),...groups.filter(g=>g.id!=='numerical').map(lab)];const map=new Map([...old,...newer.map(s=>[s.id,s])]);
 const order=['overview','family-comparison','model','model-live','assumptions-prediction','group-bayes','bayes-lab','bayes','bayes-equations','conditioning-bridge','group-mse','mse-lab','mse','mse-live','mse-equations','covariance-identities','group-wls','wls-lab','least-squares','least-squares-equations','group-kl','kl-lab','kl','kl-equations','group-graphs','graphs-lab','graphs','group-numerical','implementations','implementations-live','boundaries','equivalence','references'];
 for(const id of order)if(!map.has(id))throw new Error('Missing slide: '+id);
 for(const id of old.keys())if(!order.includes(id))throw new Error('Unplaced existing slide: '+id);
 slides.splice(0,slides.length,...order.map(id=>map.get(id)));
 for(const [i,s] of slides.entries()){
  s.notes=(s.notes||'').replaceAll('not a fifth derivation family','a computational viewpoint, not a new optimality principle');
  for(const e of s.elements)if(typeof e.html==='string')e.html=e.html.replaceAll('four-family consolidation','principal derivation routes');
  s.elements.push(text('guide-progress',920,685,112,18,`${String(i+1).padStart(2,'0')} / ${slides.length}`,{fontSize:10,fontFamily:mono,color:C.muted,align:'right'}),text('guide-toc',1060,685,148,20,'GROUP MAP ↗',{fontSize:10,fontFamily:mono,color:groups[0].color,align:'right',link:'overview'}));
 }
}
export function familyLiveEntries(slides){return groups.filter(g=>g.id!=='numerical').map(g=>({introSlide:'group-'+g.id,slide:g.id+'-lab',slideIndex:slides.findIndex(s=>s.id===g.id+'-lab'),inline:true,layout:'region',bounds,src:`./live/families.html?demo=${g.id}&embed=region`,source:`./live/families.html?demo=${g.id}`,title:g.labTitle,sandbox:'allow-scripts',hideSource:true,readyMessage:true,unloadWhenHidden:true}));}
