'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),M=require('../bp-vs-pmbm/association-model.js');
function close(a,b,tol=1e-9){assert.ok(Math.abs(a-b)<=tol,`${a} != ${b} (tol ${tol})`);}
function matrixClose(a,b,tol=1e-9){assert.equal(a.length,b.length);a.forEach((r,i)=>r.forEach((v,j)=>close(v,b[i][j],tol)));}
function probabilityRows(a){for(const row of a){close(row.reduce((s,x)=>s+x,0),1);for(const x of row)assert.ok(Number.isFinite(x)&&x>=0&&x<=1+1e-12);}}
// Independent Cartesian-product oracle: no use of the production recursion or marginal routine.
function oracle(L){const n=L.length,m=L[0].length-1,events=[];for(let code=0;code<(m+1)**n;code++){let c=code,w=1,a=[];for(let i=0;i<n;i++){const q=c%(m+1);c=Math.floor(c/(m+1));a.push(q-1);w*=L[i][q];}const assigned=a.filter(x=>x>=0);if(new Set(assigned).size===assigned.length&&w>0)events.push({a,w});}const z=events.reduce((s,e)=>s+e.w,0),A=Array.from({length:n},()=>Array(m+1).fill(0));for(const e of events)for(let i=0;i<n;i++)A[i][e.a[i]+1]+=e.w/z;return {A,count:events.length};}
let seed=217;function random(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;}
test('default benchmark: independent oracle, exact values, legal support',()=>{const {L}=M.buildWeights(M.DEFAULT),events=M.enumerate(L),exact=M.eventMarginals(events,3,4);assert.equal(events.length,22);matrixClose(exact.marginals,oracle(L).A);close(exact.marginals[0][1],0.6304694627813121);for(const e of events){const a=e.a.filter(j=>j>=0);assert.equal(new Set(a).size,a.length);}probabilityRows(exact.marginals);probabilityRows(exact.measurementMarginals);close(M.eventMarginals(events,3,4,5).mass,0.8583644020135235);});
test('five sweeps must not be labeled converged; default fixed point and dual consistency',()=>{const {L}=M.buildWeights(M.DEFAULT),short=M.bp(L,{maxIterations:5}),full=M.bp(L),exact=M.eventMarginals(M.enumerate(L),3,4).marginals;assert.equal(short.converged,false);assert.equal(full.converged,true);assert.equal(full.iterations,30);close(100*M.maxDifference(full.marginals,exact),6.926238446320272,1e-8);close(100*M.maxDifference(short.marginals,full.marginals),0.4276701178047799,1e-7);probabilityRows(full.marginals);probabilityRows(full.measurementMarginals);for(let i=0;i<3;i++)for(let j=0;j<4;j++)close(full.marginals[i][j+1],full.measurementMarginals[j][i+1],1e-10);});
test('half-step history changes the correct orientation',()=>{const {L}=M.buildWeights(M.DEFAULT),h=M.bp(L).history;assert.equal(h[0].bmarg,null);for(let t=1;t<h.length;t+=2){assert.equal(h[t].kind,'mu');matrixClose(h[t].marg,h[t-1].marg,0);matrixClose(h[t].nu,h[t-1].nu,0);assert.equal(h[t+1].kind,'nu');matrixClose(h[t+1].mu,h[t].mu,0);}});
test('BP exact on positive-weight forests, including all misses and zero measurements',()=>{const forests=[[[.2,3,0],[.1,2,4]],[[.1,2,3,5]],[[.2,0,0],[.4,0,0]],[[.2],[.8]],[[.3,2,0,0],[.1,0,3,0],[.4,0,0,5]]];for(const L of forests){assert.equal(M.topology(L).acyclic,true);const b=M.bp(L);assert.equal(b.converged,true);matrixClose(b.marginals,oracle(L).A,1e-9);}});
test('symmetry is respected on a cyclic graph without claiming exactness',()=>{const L=[[.1,2,2],[.1,2,2]],b=M.bp(L);assert.equal(M.topology(L).acyclic,false);assert.equal(b.converged,true);matrixClose([b.marginals[0]],[b.marginals[1]]);close(b.marginals[0][1],b.marginals[0][2]);assert.ok(M.maxDifference(b.marginals,oracle(L).A)>1e-3);});
test('100 randomized small problems: oracle, probability bounds, gates, BP stopping',()=>{for(let trial=0;trial<100;trial++){const n=1+trial%4,m=trial%5,L=Array.from({length:n},()=>[.05+random(),...Array.from({length:m},()=>random()<.25?0:10**(3*random()-1))]);const e=M.enumerate(L),o=oracle(L),x=M.eventMarginals(e,n,m),b=M.bp(L,{history:false});assert.equal(e.length,o.count);matrixClose(x.marginals,o.A);assert.equal(b.converged,true);probabilityRows(b.marginals);probabilityRows(b.measurementMarginals);for(let i=0;i<n;i++)for(let j=0;j<m;j++)if(L[i][j+1]===0){assert.equal(b.marginals[i][j+1],0);assert.equal(x.marginals[i][j+1],0);}if(M.topology(L).acyclic)matrixClose(b.marginals,o.A,1e-8);}});
test('row rescaling and log-domain enumeration preserve the distribution',()=>{const L=[[.1,3,2],[.3,4,1],[.2,1,2]],scaled=L.map((r,i)=>r.map(x=>x*[1e100,1e-100,1e100][i]));matrixClose(M.bp(L).marginals,M.bp(scaled).marginals);matrixClose(M.eventMarginals(M.enumerate(L),3,2).marginals,M.eventMarginals(M.enumerate(scaled),3,2).marginals);const b=M.bp([[1e-30,1,0],[.1,0,1]]);assert.equal(b.converged,true);probabilityRows(b.marginals);});
test('top-k renormalization: endpoints, retained mass and total-variation bound',()=>{const {L}=M.buildWeights(M.DEFAULT),e=M.enumerate(L),exact=M.eventMarginals(e,3,4);let previous=0;for(let k=1;k<=e.length;k++){const q=M.eventMarginals(e,3,4,k);assert.ok(q.mass>=previous);previous=q.mass;probabilityRows(q.marginals);assert.ok(M.maxDifference(q.marginals,exact.marginals)<=q.discardedMass+1e-12);const tv=.5*e.reduce((s,x,i)=>s+Math.abs(x.p-(i<k?x.p/q.mass:0)),0);close(tv,q.discardedMass);}matrixClose(M.eventMarginals(e,3,4,e.length).marginals,exact.marginals,0);});
test('graph topology is measured, not inferred from approximation error',()=>{const {L}=M.buildWeights(M.DEFAULT);assert.deepEqual(M.topology(L),{edges:7,cycles:2,acyclic:false,components:2});const L2=[[1e9,1,1],[1e9,1,1]];assert.equal(M.topology(L2).acyclic,false);assert.ok(M.maxDifference(M.bp(L2).marginals,oracle(L2).A)<1e-8);});
test('complete partial-assignment counts include misses',()=>{for(const [n,m,count]of [[1,1,2],[3,3,34],[3,4,73],[7,7,130922]]){const L=Array.from({length:n},()=>Array(m+1).fill(1));assert.equal(M.enumerate(L).length,count);}});
test('PMBM likelihood normalization: existing existence and PPP evidence',()=>{const r=[.8,.6],pd=[.7,.9],eta=[[.3,.8],[.5,.2]],c=[.2,.4],e=[.1,.6],q=M.pmbmWeights(r,pd,eta,c,e);close(q.L[0][0],.44);close(q.newExistence[0],1/3);close(q.missedExistence[0],.24/.44);const ev=M.enumerate(q.L);const direct=ev.map(h=>{let w=1;for(let i=0;i<r.length;i++)w*=h.a[i]<0?1-r[i]*pd[i]:r[i]*eta[i][h.a[i]];for(let j=0;j<c.length;j++)if(!h.a.includes(j))w*=c[j]+e[j];return w;});const z=direct.reduce((a,b)=>a+b,0);ev.forEach((h,i)=>close(h.p,direct[i]/z));const x=M.eventMarginals(ev,2,2);assert.ok(x.measurementMarginals[0][0]*q.newExistence[0]<q.newExistence[0]);});
test('zero PPP and certain targets reduce to the teaching weights',()=>{const {L}=M.buildWeights(M.DEFAULT,false),eta=L.map(row=>row.slice(1).map(v=>v*M.DEFAULT.c));matrixClose(M.pmbmWeights([1,1,1],[.9,.9,.9],eta,Array(4).fill(M.DEFAULT.c),Array(4).fill(0)).L,L);});
test('gate quantile and parameter extremes are finite and accurately labeled',()=>{close(1-Math.exp(-M.GATE/2),.99);for(const PD of [.5,.9,.99])for(const c of [1e-6,5e-5,1e-3])for(const gated of [true,false]){const s=M.clone(M.DEFAULT);s.PD=PD;s.c=c;const b=M.bp(M.buildWeights(s,gated).L,{history:false});assert.equal(b.converged,true);probabilityRows(b.marginals);}});
test('invalid inputs fail explicitly instead of yielding false probabilities',()=>{for(const L of [[],[[0,1]],[[1,-1]],[[1,Infinity]],[[1,2],[1]]])assert.throws(()=>M.bp(L));assert.throws(()=>M.bp([[1,2]],{maxIterations:0}));assert.throws(()=>M.buildWeights({...M.DEFAULT,PD:1}));assert.throws(()=>M.buildWeights({...M.DEFAULT,c:0}));assert.throws(()=>M.enumerate([[1,1]],{maxEvents:1}));assert.throws(()=>M.gaussian2(0,0,[[1,2],[2,1]]));});
test('article, generated deck, and live demos use one actual solver',()=>{const article=fs.readFileSync('bp-vs-pmbm/index.html','utf8'),build=fs.readFileSync('bp-vs-pmbm-slides/build-deck.mjs','utf8'),live=fs.readFileSync('bp-vs-pmbm-slides/live/app.js','utf8'),html=fs.readFileSync('bp-vs-pmbm-slides/index.html','utf8');assert.match(article,/association-model\.js/);assert.match(build,/association-model\.js/);assert.match(live,/window.AssociationModel/);assert.doesNotMatch(live,/RadioSlamS1|PMBM_PARTICLES/);assert.doesNotMatch(article,/maxIter=5\b|Exact \/ PMBM marginals|BP sweeps to converge:/);const doc=JSON.parse(html.match(/id="bento-doc">\s*([\s\S]*?)<\/script>/)[1]);assert.equal(doc.slides.length,19);assert.equal(doc.slides.find(s=>s.id==='s-bp-marginals').elements.find(e=>e.id==='bp-error-number').html,'6.93 pp');assert.ok(doc.slides.some(s=>s.id==='s-pmbm-weights'));assert.ok(doc.slides.some(s=>s.id==='s-dependence'));for(const match of article.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);});
