import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {deck,inlineLiveMap} from './deck.mjs';
const require=createRequire(import.meta.url),BP=require('./model.js'),G=require('./graph.js');
const here=fileURLToPath(new URL('.',import.meta.url));
let html=readFileSync(new URL('../variational-inference-em/index.html',import.meta.url),'utf8');
const safe=o=>JSON.stringify(o,null,1).replaceAll('<','\\u003c');
const documentPattern=/(<script type="application\/bento\+json" id="bento-doc">\s*)[\s\S]*?(\s*<\/script>)/;
if(!documentPattern.test(html))throw new Error('Missing Bento payload');
html=html.replace(documentPattern,(_,a,b)=>a+safe(deck)+b);
html=html.replace(/<script type="application\/json" id="bento-inline-live-map">[\s\S]*?<\/script>/,()=>`<script type="application/json" id="bento-inline-live-map">${safe(inlineLiveMap)}</script>`);
const routes=Object.fromEntries(deck.slides.map((s,i)=>[s.id,i]));
const routeScript=`<script>(()=>{const routes=${JSON.stringify(routes)};function routeToSlide(){let r;try{r=decodeURIComponent(location.hash.replace(/^#\\/?/,''));}catch{return;}if(r&&!/^\\d+$/.test(r)&&Number.isInteger(routes[r]))history.replaceState(null,'',location.pathname+location.search+'#/'+routes[r]);}addEventListener('hashchange',routeToSlide);routeToSlide();})();</script>`;
let routeFound=false;
html=html.replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/g,(all,attrs,body)=>{if(!attrs.trim()&&body.includes('function routeToSlide')){routeFound=true;return routeScript;}return all;});
if(!routeFound)throw new Error('Missing route mapper');
html=html.replace(/<title>[\s\S]*?<\/title>/,'<title>Message Passing for Multitarget Tracking | Bai Liping</title>');
html=html.replace(/<meta name="description"[^>]*>/,'<meta name="description" content="Interactive walkthrough of Figure 4 in Meyer et al. (2018): prediction, association messages, new targets, and existence beliefs." />');
html=html.replace(/<link rel="canonical"[^>]*>/,'<link rel="canonical" href="https://bailiping.com/message-passing-tracking/" />');
html=html.replace(/<!-- Generated by [^>]*-->/,'<!-- Generated by message-passing-tracking/build.mjs. Edit deck.mjs and rebuild. -->');
html=html.replace('<body>','<body>\n<noscript><p style="padding:32px">This presentation requires JavaScript. <a href="./study.html">Read the static version of the slides.</a></p></noscript>');
html=html.replace('</body>','<script src="./navigation.js"></script>\n</body>');
// Supply Bento's native print root for the read-only shell. It otherwise only
// creates this root through editor-only print commands. No live iframe is copied.
const styleAttr=o=>Object.entries(o).map(([k,v])=>`${k}:${v}`).join(';');
const printPages=deck.slides.map((s,i)=>`<div class="bp-page"><div class="bp-static-slide" style="position:relative;width:1280px;height:720px;background:${s.background};transform:scale(1.25);transform-origin:0 0">${s.elements.filter(e=>e.opacity!==0).map(e=>{
  const base={position:'absolute',left:e.x+'px',top:e.y+'px',width:e.w+'px',height:e.h+'px',opacity:e.opacity??1,transform:`rotate(${e.rotation||0}deg)`};
  if(e.type==='shape')return `<div style="${styleAttr({...base,background:e.fill,'border-radius':e.shape==='ellipse'?'50%':(e.radius||0)+'px',border:e.stroke&&e.stroke!=='none'?`${e.strokeWidth}px solid ${e.stroke}`:'none','box-sizing':'border-box'})}"></div>`;
  if(e.type!=='text')return '';
  const html=e.html.replaceAll('{{page}}',String(i+1)).replaceAll('{{pages}}',String(deck.slides.length));
  return `<div class="bento-el-text" style="${styleAttr({...base,display:'flex','flex-direction':'column','justify-content':e.valign==='middle'?'center':'flex-start'})}"><div class="bento-text-inner" style="font-size:${e.fontSize}px;font-family:${e.fontFamily.replaceAll('"','&quot;')};font-weight:${e.fontWeight};color:${e.color};text-align:${e.align};line-height:${e.lineHeight};letter-spacing:${e.letterSpacing||0}px;width:100%">${html}</div></div>`;
 }).join('')}</div></div>`).join('');
html=html.replace('</head>','<style>#bento-print{display:none}@media print{#bento-print{display:block!important}#bento-print .bp-page{position:relative;width:1600px;height:900px;break-after:page;overflow:hidden}#bento-print .bp-static-slide{display:block}#bento-print .bento-text-inner{margin:0}@page{size:1600px 900px;margin:0}}</style></head>');
html=html.replace('</body>',`<div id="bento-print">${printPages}</div>\n</body>`);
// Keep every compressed Bento runtime byte from the existing deck.
const template=readFileSync(new URL('../variational-inference-em/index.html',import.meta.url),'utf8');
for(const id of ['bento-rt','bento-rt-css']){const re=new RegExp(`<script[^>]*id="${id}"[^>]*>([\\s\\S]*?)<\\/script>`);if(html.match(re)?.[1]!==template.match(re)?.[1])throw new Error('Runtime changed: '+id);}
writeFileSync(here+'index.html',html);
// A normal-flow reading/print page retains complete static content if a lab fails.

const escape=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const exclude=new Set(['section','title','subtitle','home','source','pages','cover-nav','read-static']);
const sections=deck.slides.map((slide,i)=>{
  const texts=slide.elements.filter(e=>e.type==='text'&&!exclude.has(e.id)&&!e.id.startsWith('label-')&&!e.id.startsWith('belief-')&&e.id!=='table-header');
  const diagram=slide.elements.some(e=>e.id==='node-a0')?`<div class="diagram">${G.svg({step:{id:slide.id==='schedule-live'?'prior':'none'},interactive:false})}</div>`:'';
  const table=slide.id==='beliefs'?`<table><thead><tr><th>Candidate</th><th>BP existence</th><th>Exact existence</th></tr></thead><tbody>${[...BP.run().legacy.map((v,j)=>['Legacy '+(j+1),v,BP.run().exact.legacy[j]]),...BP.run().newTargets.map((v,m)=>['New '+(m+1),v,BP.run().exact.newTargets[m]])].map(([name,v,e])=>`<tr><td>${name}</td><td>${(100*(1-v[0])).toFixed(2)}%</td><td>${(100*(1-e[0])).toFixed(2)}%</td></tr>`).join('')}</tbody></table>`:'';
  return `<article id="${slide.id}"><span class="number">${String(i+1).padStart(2,'0')} / ${deck.slides.length}</span><h2>${slide.elements.find(e=>e.id==='title').html}</h2><p class="subtitle">${slide.elements.find(e=>e.id==='subtitle').html}</p>${diagram}${texts.map(e=>`<div class="block">${e.link?`<a href="${escape(routes[e.link]!==undefined?'#'+e.link:e.link)}">${e.html}</a>`:e.html}</div>`).join('')}${table}<p class="source">${slide.elements.find(e=>e.id==='source').html}</p></article>`;
}).join('\n');
writeFileSync(here+'study.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Multitarget Tracking · Reading & print view | Bai Liping</title><link rel="stylesheet" href="./reading.css"><style>body{background:#f4f7fa;padding:24px}header,article{max-width:960px;margin:0 auto 26px}header{display:flex;gap:22px}article{background:white;border:1px solid #d8e1e8;padding:42px;break-inside:avoid}h2{font:32px/1.2 Georgia,serif;margin:10px 0 16px}.number,.source{font-size:12px;color:#617181}.subtitle{font-size:19px;color:#617181}.block{font-size:20px;line-height:1.6;margin:23px 0}.math-display{margin:24px 0;overflow-x:auto}.diagram{max-width:720px;margin:24px auto}.diagram>svg{width:100%}table{border-collapse:collapse;font-size:19px;width:100%;max-width:500px}td,th{text-align:left;padding:9px;border-bottom:1px solid #d8e1e8}@media(max-width:700px){body{padding:12px}article{padding:20px}.block{font-size:17px}h2{font-size:27px}}@media print{body{padding:0;background:white}header{display:none}article{border:0;break-after:page;margin:0;max-width:none;padding:20px}a{color:inherit;text-decoration:none}.message-edge{pointer-events:none}}</style><script>window.MathJax={tex:{inlineMath:[['\\\\(','\\\\)']],displayMath:[['\\\\[','\\\\]']]},svg:{fontCache:'local'},startup:{typeset:false}};</script><script defer src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-svg-full.js"></script><script defer src="../assets/mathjax-dynamic.js"></script></head><body><header><a href="./">← Interactive slides</a><a href="/">All topics</a></header>${sections}</body></html>`);
console.log(`Built ${deck.slides.length} slides, ${inlineLiveMap.length} adjacent live pairs, and the static reading page.`);
