(function(){
const slider=(id,label,min,max,step,value,unit='')=>`<label class="slider" for="${id}"><span>${label}<output id="${id}-out">${value}${unit}</output></span><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-unit="${unit}"></label>`;
const check=(id,label,on=true)=>`<label class="check"><input id="${id}" type="checkbox" ${on?'checked':''}>${label}</label>`;
const btn=(id,text,primary=false)=>`<button id="${id}" class="${primary?'primary':''}" type="button">${text}</button>`;
const stats=id=>`<div id="${id}" class="metrics" aria-live="polite" aria-atomic="true"></div>`;
const presets=(items)=>`<div class="presets" aria-label="Experiment presets">${items.map(([id,label])=>`<button type="button" data-preset="${id}">${label}</button>`).join('')}</div>`;
const history=id=>`<div class="history"><span>Progress · lower is better</span><svg id="${id}" viewBox="0 0 600 40" role="img" aria-label="Error over solver updates"></svg></div>`;
window.RadarLabs={
'whole-run':{title:'Watch the map grow',canvas:'mission-canvas',caption:'Blue: detections · green: estimate / retained map · dashed gray: truth',presets:presets([['start','Start'],['half','Halfway'],['loop','Revisit']]),controls:`${slider('mission-frame','Scan',0,48,1,24,' / 48')}<div class="buttons">${btn('mission-play','Play',true)}${btn('mission-step','Step')}${btn('mission-reset','Restart')}</div>${check('mission-bias','Add 0.35° heading bias / frame')}${check('mission-map','Show accumulated map')}${check('mission-truth','Show simulator reference')}${stats('mission-stats')}`,insight:'Each point keeps its local coordinates. The composed pose determines where it enters the map.'},
range:{title:'Resolve two reflectors',canvas:'range-canvas',caption:'Green: DFT · dashed orange: true reflector ranges · I / Q above',presets:presets([['merged','Merged'],['resolved','Separated'],['default','Reset']]),controls:`${slider('range-band','Bandwidth',.15,1.2,.05,.45,' GHz')}${slider('range-sep','Reflector separation',.05,1.5,.05,.45,' m')}${check('range-hann','Hann window')}${stats('range-stats')}`,insight:'Compare peak structure as bandwidth changes. The nominal resolution does not include window broadening.'},
cfar:{title:'Inspect a CFAR decision',canvas:'cfar-canvas',caption:'Blue: power · green: threshold · orange circles: detections',presets:presets([['uniform','Uniform'],['edge','Clutter edge'],['default','Reset']]),controls:`${slider('cfar-pfa','Design Pfa exponent',1,6,1,3)}${slider('cfar-cell','Inspect range bin',10,117,1,62)}${check('cfar-edge','Nonuniform clutter edge',false)}<div class="buttons">${btn('cfar-new','New noise')}${btn('cfar-reset','Reset noise')}</div>${stats('cfar-stats')}`,insight:'Green bands: 16 training cells. Beige bands: 4 guard cells. Orange line: the cell under test.'},
frames:{title:'Transform a radar return',canvas:'frames-canvas',caption:'Blue: same point · green: sensor pose · orange: measurement uncertainty',presets:presets([['identity','Identity'],['quarter','Quarter turn'],['default','Reset']]),controls:`${slider('frames-x','World x',-5,5,.1,1.5,' m')}${slider('frames-y','World y',-5,5,.1,-1,' m')}${slider('frames-yaw','Heading',-180,180,1,35,'°')}${stats('frames-stats')}`,insight:'The return remains at 6 m and 30° in the radar frame. Only its assumed world placement changes.'},
velocity:{title:'Separate ego motion from moving returns',canvas:'velocity-canvas',caption:'Green: selected fit · orange dashed: ordinary fit · gray dashed: truth',presets:presets([['clean','Static scene'],['moving','Moving returns'],['narrow','Narrow view']]),controls:`${slider('velocity-x','Forward velocity',0,8,.1,4,' m/s')}${slider('velocity-movers','Moving-return fraction',0,45,5,25,'%')}${slider('velocity-span','Bearing span',4,170,2,130,'°')}${check('velocity-robust','Use RANSAC + least squares')}${stats('velocity-stats')}`,insight:'Both curves use exactly the same observations. The estimator never receives moving/static labels.'},
icp:{title:'Inspect each ICP stage',canvas:'icp-canvas',caption:'Hollow gray: reference · green: current scan · lines: tentative matches',history:history('icp-history'),presets:presets([['near','Near start'],['poor','Poor start'],['tight','Tight gate']]),controls:`${slider('icp-start','Initial heading',-45,45,1,0,'°')}${slider('icp-gate','Match gate',.3,4,.1,2,' m')}${check('icp-robust','Robust pair weights')}<div class="buttons">${btn('icp-step','1 · Find matches',true)}${btn('icp-run','Animate')}${btn('icp-reset','Reset')}</div>${stats('icp-stats')}`,insight:'Find tentative matches first. The next stage fits their weighted rigid transform.'},
optimize:{title:'Correct a trajectory with a loop',canvas:'graph-canvas',caption:'Gray: truth · orange: odometry · green: optimized · purple: loop',history:history('graph-history'),presets:presets([['valid','Valid loop'],['false','False loop'],['robust','Robust loss']]),controls:`${slider('graph-sigma','Loop translation noise',.05,2,.05,.15,' m')}${check('graph-false','Inject a false loop',false)}${check('graph-robust','Huber loss on loop',false)}${check('graph-map','Re-place the scan map',false)}<div class="buttons">${btn('graph-step','Step',true)}${btn('graph-solve','Optimize')}${btn('graph-reset','Reset')}</div>${stats('graph-stats')}<div class="buttons export">${btn('graph-export','Export run JSON')}</div>`,insight:'A lower objective means a better fit to the supplied measurements; it does not certify that the loop is correct.'}
};
const requested=new URLSearchParams(location.search).get('demo');window.activeDemo=Object.hasOwn(window.RadarLabs,requested)?requested:'whole-run';
const d=window.RadarLabs[window.activeDemo];document.documentElement.classList.toggle('embedded',new URLSearchParams(location.search).get('embed')==='region');
document.getElementById('lab-title').textContent=d.title;document.title=d.title+' | Radar SLAM';
document.getElementById('lab').innerHTML=`<section class="experiment"><div class="visual ${d.history?'has-history':''} ${['whole-run','frames','optimize'].includes(window.activeDemo)?'paired':''}"><div class="plot"><canvas id="${d.canvas}" role="img" aria-label="${d.title}. ${d.caption}. Numerical values appear in the controls."></canvas></div>${d.history||''}<p class="legend">${d.caption}</p></div><aside class="controls" aria-label="Experiment controls">${d.presets}${d.controls}</aside><p class="insight" id="insight" role="status">${d.insight}</p></section>`;
})();
