// Canonical teaching content. The generated page uses the site's native Bento runtime.
const C={bg:'#F5F3ED',paper:'#FFFDFA',ink:'#182D33',muted:'#60747A',line:'#D6DEDC',teal:'#16736E',soft:'#E4F0ED',rust:'#B44F37',warm:'#F7E8E1',blue:'#276991'};
const sans='Arial, Helvetica, sans-serif',serif="Georgia, 'Times New Roman', serif",mono='Consolas, monospace';
const R=String.raw;
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const M=s=>`<span class="math-tex math-display">\\[${esc(s)}\\]</span>`;
const I=s=>`<span class="math-tex math-inline">\\(${esc(s)}\\)</span>`;
const P=s=>`<p>${s}</p>`;
export const PAPER='https://arxiv.org/html/2605.16644v1';
const cite=(label,anchor='')=>({label,url:PAPER+(anchor?'#'+anchor:'')});
const link=(label,url)=>({label,url});
const slides=[],labs=[];
function text(id,x,y,w,h,html,o={}){return{id,type:'text',x,y,w,h,rotation:0,opacity:1,html,fontFamily:sans,fontSize:22,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.32,...o};}
function box(id,x,y,w,h,fill=C.paper){return{id,type:'shape',shape:'rect',x,y,w,h,fill,stroke:C.line,strokeWidth:1,radius:10,rotation:0,opacity:1};}
function panel(id,x,y,w,h,label,html,{fill=C.soft,size=22}={}){return[box(id+'-box',x,y,w,h,fill),text(id+'-label',x+22,y+18,w-44,24,label,{fontFamily:mono,fontSize:13,fontWeight:700,color:C.teal}),text(id+'-body',x+22,y+57,w-44,h-73,html,{fontSize:size})];}
function add(id,section,title,subtitle,elements,notes,sources=[cite('Paper')]){
 slides.push({id,background:C.bg,transition:'none',lessonTitle:title,lessonSubtitle:subtitle,notes:notes+'\n\nSources:\n'+sources.map(s=>s.label+' — '+s.url).join('\n'),elements:[
 text('section',72,29,880,25,section.toUpperCase(),{fontSize:13,fontFamily:mono,color:C.rust,fontWeight:700}),
 text('home',971,29,237,25,'RANDOM THOUGHTS',{fontSize:12,fontFamily:mono,align:'right',color:C.muted,link:'https://bailiping.com/'}),
 box('rule',72,66,1136,1,C.line),text('heading',72,84,1136,54,title,{fontFamily:serif,fontSize:38,fontWeight:700,lineHeight:1.12}),
 text('subtitle',72,143,1136,34,subtitle,{fontSize:18,color:C.muted}),...elements,
 text('sources',72,676,850,29,sources[0].label,{fontSize:12,color:C.muted,link:sources[0].url}),
 text('read',931,679,155,20,'READ NOTES',{fontSize:12,fontFamily:mono,color:C.teal,link:'https://bailiping.com/score-kalman-filter/study.html#'+id,align:'right'}),
 text('contents',1090,679,118,20,'CONTENTS',{fontSize:12,fontFamily:mono,color:C.teal,link:'overview',align:'right'})]});
}
function pair(id,section,title,subtitle,l,L,r,U,notes,sources,size=[22,22]){add(id,section,title,subtitle,[...panel('left',72,193,550,448,l,L,{size:size[0]}),...panel('right',646,193,562,448,r,U,{fill:C.paper,size:size[1]})],notes,sources);}
function live(id,intro,lab,title,subtitle,summary,notes,sources){add(id,'Interactive laboratory',title,subtitle,[...panel('fallback',72,180,1136,475,'LIVE EQUATIONS',summary,{size:25}),{...box('live-demo-mount',72,180,1136,475,'transparent'),opacity:0}],notes,sources);labs.push({slide:id,introSlide:intro,inline:true,layout:'region',bounds:{x:72,y:180,width:1136,height:475},src:`./live/?lab=${lab}&embed=1`,source:`./live/?lab=${lab}`,title,sandbox:'allow-scripts allow-same-origin allow-top-navigation-by-user-activation',hideSource:true,readyMessage:true,unloadWhenHidden:true});}
const table=(heads,rows)=>`<table class="lesson-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;

add('overview','Paper walkthrough · arXiv:2605.16644v1','The Score Kalman Filter','Kaito Iwasaki, Anthony Bloch, Taeyoung Lee and Maani Ghaffari · 15 May 2026',[
 text('hero',72,203,1136,114,'A non-Gaussian belief,<br><span style="color:#16736E">fitted through its score.</span>',{fontFamily:serif,fontSize:47,fontWeight:700,lineHeight:1.12}),
 ...panel('idea',72,341,1136,125,'THE CENTRAL COMPUTATION','Moments determine a linear system. Its solution determines the score.',{size:26,fill:C.paper}),
 ...[['01','Fit the score','score-system'],['02','Close the moments','stein-identity'],['03','Update the belief','bayes-score']].flatMap(([n,t,target],i)=>[box('nav-box-'+i,72+384*i,492,368,145,i===1?C.paper:C.soft),text('nav-'+i,95+384*i,513,320,104,n+'<br><b>'+t+'</b>',{fontSize:26,link:target})])
],'This lesson follows version 1 of The Score Kalman Filter. The paper combines score matching for polynomial exponential families with Stein moment identities. A density fit is a linear solve, while nonlinear prediction still involves moment ODE integration and finite closure. The three browser laboratories are independent scalar teaching examples. They expose the matrix fit, higher-moment closure and one measurement update. Their reference curves and input moments use quadrature, explicitly separated from the algebra being illustrated. They do not reproduce the authors’ full filter or benchmarks.',[cite('Iwasaki et al. · 2026'),link('PDF','https://arxiv.org/pdf/2605.16644v1')]);

pair('relation-mem','01 · motivation','The connection to the MaxEnt filter','The belief family stays flexible. The method for fitting it changes.',
 'MAXIMUM-ENTROPY MOMENT FIT',M(R`p_\lambda(x)=Z(\lambda)^{-1}e^{-\lambda^\top\phi(x)}`)+P('Fit coefficients so the represented density matches a set of moments.')+P('Evaluating the partition function and its derivatives can require expensive integration.'),
 'SCORE MATCHING FIT',M(R`s_\lambda(x)=\nabla_x\log p_\lambda(x)`)+P('Fit the spatial derivative of the log density.')+P('For polynomial features, its objective becomes quadratic in the coefficients. Moments provide every matrix entry.'),
 'This is the direct conceptual continuation of the existing MEM-KF lesson. Maximum entropy and score matching use different objectives. They recover the same member when the supplied moments come from a density inside the assumed exponential family and the theorem’s regularity conditions hold. For a density outside that family, or approximate moments, the fitted parameters generally differ. Avoid describing SKF as a faster exact implementation of every MaxEnt fit.',[cite('Sections 2–3','S2'),link('Existing MEM-KF deck','https://bailiping.com/mem-kf/')]);

pair('state-and-input','01 · problem statement','What the filter receives and carries','Initial uncertainty is an input to the algorithm.',
 'KNOWN MODEL AND INITIAL BELIEF',M(R`dx=X(x)\,dt+h(x)\,dW`)+M(R`z_k=g(x_k)+v_k,\quad v_k\sim\mathcal N(0,R)`)+P('Provide initial moments, polynomial drift and diffusion, the observation model, and its covariance.'),
 'TWO INTERNAL REPRESENTATIONS',M(R`m_\alpha=\mathbb E[x^\alpha],\qquad m_{\mathbf0}=1`)+P('<b>Moments m:</b> convenient for prediction.')+P('<b>Coefficients λ:</b> convenient for the score and likelihood update.')+P('The reported point estimate is the posterior mean from first moments.'),
 'The state has dimension n. X is the drift vector field and h is the diffusion matrix, not the measurement function. g is the observation function in this lesson, with additive Gaussian observation noise for the conjugate update. The paper starts with given initial moments. It does not solve a general unknown-initial-pose problem. The estimator receives measurements, model parameters and an initial belief, rather than the subsequent true state. Algorithm 1 carries both m and λ.',[cite('Eq. (1)','S2.E1'),cite('Algorithm 1','S6')]);

pair('polynomial-belief','02 · belief representation','A polynomial energy can have several wells','The constant coefficient carries no score information.',
 'NORMALIZED DENSITY · EQ. (6)',M(R`p_\lambda(x)=\frac{1}{Z(\lambda)}\exp[-V_\lambda(x)]`)+M(R`V_\lambda(x)=\sum_{1\le|\alpha|\le r}\lambda_\alpha x^\alpha`)+P('Fix '+I(R`\lambda_{\mathbf0}=0`)+'. The normalizer absorbs constants.'),
 'A PROPER SCALAR QUARTIC',M(R`V(x)=a x^4+b x^2-cx,\quad a>0`)+P('Positive a gives integrable tails.')+P('When c = 0 and b < 0, two density modes occur at '+I(R`x=\pm\sqrt{-b/(2a)}`)+'.')+P('The mean can lie between the modes.'),
 'A multi-index α=(α1,…,αn) represents the monomial product x1^α1 ⋯ xn^αn, and |α| is the total degree. The paper counts M=binomial(n+r,n) including the constant. The actual score fit omits the zero row and column, leaving M−1 parameters. A polynomial energy only defines a probability density if Z is finite. The scalar quartic example is globally normalizable on the real line because its leading coefficient is positive.',[cite('Eq. (6) and Section 3','S2.E6')]);

pair('score','02 · the score','Differentiation removes the normalizer','The gradient is with respect to the state x.',
 'THE SPATIAL SCORE',M(R`\log p_\lambda(x)=-V_\lambda(x)-\log Z(\lambda)`)+M(R`s_\lambda(x)=-\nabla_xV_\lambda(x)`)+M(R`=-J_\phi(x)\lambda`),
 'THE QUARTIC EXAMPLE',M(R`s(x)=c-2bx-4ax^3`)+P('A positive score means the density increases as x increases locally.')+P('No value of Z is needed to evaluate this field.')+P('The score does not give a normalized density height by itself.'),
 'The score here is ∇x log p(x), not the gradient of a parameter log-likelihood with respect to λ. Z depends on λ but is constant in x, so its spatial derivative is zero. In the paper’s convention Jφ has one row per state coordinate and one column per feature. Thus Jφ is n by (M−1) after dropping the constant feature. The resulting score has n components. No neural network training or diffusion-model sampler is required for this polynomial score fit.',[cite('Section 2.3','S2.SS3')]);

pair('moment-prediction','03 · prediction','The generator propagates expectations','Polynomial dynamics turn derivatives into moment lookups.',
 'GENERATOR · EQ. (2)',M(R`H(x)=\tfrac12 h(x)h(x)^\top`)+M(R`\mathcal A f=\nabla f\cdot X+\operatorname{Tr}(H\nabla^2f)`)+P('Drift moves the state. Diffusion spreads its uncertainty.'),
 'DYNKIN’S FORMULA · EQS. (3)–(4)',M(R`\frac{d}{dt}\mathbb E[f(x_t)]=\mathbb E[\mathcal A f(x_t)]`)+M(R`\dot m_\alpha=\mathbb E[\mathcal A x^\alpha]`)+P('Apply the generator to each monomial, then replace monomials by their expectations.'),
 'The exact generator identity is a continuous-time result under the required smoothness and integrability conditions. A finite implementation additionally chooses a moment budget, a closure for omitted moments and an ODE time integrator. Linear algebra in the density fit does not remove numerical ODE integration. For polynomial drift and diffusion, the right-hand side is a linear combination of moments, although it can involve moments of higher degree than those being propagated.',[cite('Eqs. (1)–(4)','S2.E2')]);

pair('moment-budget','03 · degree accounting','Density order and moment budget differ','A quartic density fit needs moments through degree six.',
 'SCORE FIT BUDGET',M(R`K=2r-2`)+table(['Energy order r','Tracked degree K'],[['2','2'],['3','4'],['4','6'],['6','10']])+P('This budget comes from products of feature gradients in A.'),
 'EXTRA DEGREES FOR PREDICTION',M(R`\bar d=\max(d_X-1,\,2d_h-2)`)+M(R`\dot m^{(\le K)}\ \text{uses}\ m^{(\le K+\bar d)}`)+P('If the hierarchy increases degree, its missing moments require closure.')+P('The budget alone does not guarantee stable closure.'),
 'Eq. (5) gives the excess degree. dX is the maximum drift degree and dh is the maximum degree of entries of h. The diffusion tensor hhᵀ/2 can have degree 2dh. K=2r−2 is sufficient to assemble A, while b uses degree at most r−2. Degree r may identify a member of the family abstractly, but this particular quadratic fitting method requires more moments. The table is degree accounting only. In particular, an unrestricted nonzero cubic energy is not globally normalizable on Rn, as discussed later.',[cite('Eq. (5)','S2.E5'),cite('Proposition 1 and Remark 3','S3')]);

pair('score-objective','04 · fitting the score','The fitting objective is quadratic','Integration by parts removes the unknown data score.',
 'HYVÄRINEN OBJECTIVE · EQ. (7)',M(R`J_{\rm SM}=\mathbb E[\nabla\cdot s_\lambda+\tfrac12\|s_\lambda\|^2]+C`)+P('The expectation is under the distribution whose moments are supplied.')+P('Boundary terms must vanish for the identity to hold.'),
 'SUBSTITUTE THE POLYNOMIAL SCORE',M(R`J_{\rm SM}(\lambda)=\tfrac12\lambda^\top A\lambda-b^\top\lambda+C`)+M(R`A=\mathbb E[J_\phi^\top J_\phi],\qquad b=\mathbb E[\Delta\phi]`)+M(R`\nabla_\lambda J_{\rm SM}=A\lambda-b`),
 'The Fisher-divergence formulation contains the unknown true score. Integration by parts rewrites it as an expectation of the model-score divergence and squared norm plus a parameter-independent constant. Since s=−Jφλ, the squared term produces λᵀAλ/2 and the divergence produces −bᵀλ. For polynomial features, every expectation is a moment lookup. The fit has a unique unconstrained minimizer if A is positive definite on the nonconstant features.',[cite('Eq. (7)','S2.E7'),cite('Section 3','S3')],[21,21]);

pair('score-system','04 · the central linear solve','Assemble A and b directly from moments','No partition function appears in Eqs. (8)–(9).',
 'MATRIX AND RIGHT-HAND SIDE · EQ. (8)',M(R`A_{\alpha\beta}=\sum_i\alpha_i\beta_i\,m_{\alpha+\beta-2e_i}`)+M(R`b_\alpha=\sum_i\alpha_i(\alpha_i-1)m_{\alpha-2e_i}`)+P('Omit the constant feature. Terms with zero derivative factors contribute zero.'),
 'SOLVE · EQ. (9)',M(R`\boxed{A(m)\lambda=b(m)}`)+P('<b>1.</b> Index the nonconstant monomials.<br><br><b>2.</b> Fill A and b by moment lookup.<br><br><b>3.</b> Solve and inspect conditioning.')+P('Use a numerical factorization rather than explicitly forming an inverse.'),
 'e_i is the multi-index with one in coordinate i and zeros elsewhere. The paper writes λ=A−1b to express the mathematical solution. A numerical implementation should use a stable factorization and explicitly diagnose rank and conditioning. The covariance-like Gram matrix need not be well-conditioned merely because it is positive definite in exact arithmetic. Approximate input moments can perturb it. Solving this system fits the score parameters, not the unknown physical state directly.',[cite('Eqs. (8)–(9)','S3.E8')],[21,22]);

add('quartic-matrix','04 · laboratory 1 setup','The entire scalar quartic matrix','With φ = [x, x², x³, x⁴], only m₀ through m₆ are needed.',[
 ...panel('matrix',72,193,710,448,'EQ. (8), WRITTEN OUT',M(R`A=\begin{bmatrix}1&2m_1&3m_2&4m_3\\2m_1&4m_2&6m_3&8m_4\\3m_2&6m_3&9m_4&12m_5\\4m_3&8m_4&12m_5&16m_6\end{bmatrix}`)+M(R`b=\begin{bmatrix}0&2&6m_1&12m_2\end{bmatrix}^{\!\top}`),{size:25}),
 ...panel('try',806,193,402,448,'WHAT TO INSPECT',P('The next lab computes each entry from the current input moments.')+P('Change the well depth and asymmetry. The fitted coefficients should recover')+M(R`\lambda=[-c,b,0,a]^\top`)+P('Inspect '+I(R`\|A\lambda-b\|`)+ ' and the score curve.'),{size:23,fill:C.paper})
],'This is a direct specialization of Eq. (8) to n=1 and r=4. The b used as the quadratic energy coefficient in the teaching family is a scalar, whereas the bold or vector b in Aλ=b is the score-fit right-hand side. The lab labels the energy coefficient separately to avoid ambiguity. It generates a proper quartic density, computes its reference moments numerically, and solves the matrix system. Quadrature supplies the teaching input and plots. The matrix fit itself uses only those moments.',[cite('Eqs. (8)–(9)','S3.E8')]);

live('score-live','quartic-matrix','score','Fit the score from seven moments','Change the belief shape and inspect the fitted coefficients.',P('The 4 × 4 system recovers the quartic score from m₀,…,m₆.')+P('Vary the double-well shape and asymmetry. Compare the target coefficients, fitted coefficients and residual.')+P('Synthetic reference moments and density plots use quadrature.'),'This laboratory implements the scalar score-matching system. Its numerical reference distribution is a globally proper quartic family. It demonstrates on-model recovery rather than claiming that score matching reproduces arbitrary moment targets exactly. The displayed residual checks the matrix equation. It does not certify a full nonlinear filtering algorithm.',[cite('Proposition 1 and Theorem 1','S3')]);

pair('recovery-theorem','04 · what the theorem guarantees','Exact recovery has an on-model condition','Theorem 1 does not make every approximate moment vector valid.',
 'CORRECT RECOVERY · EQ. (11)',P('Suppose the input moments come from a density '+I(R`p_{\lambda_{\rm true}}`)+ ' inside the chosen family, with the required regularity.')+M(R`A(m)\lambda=b(m)\quad\Longrightarrow\quad\lambda=\lambda_{\rm true}`)+P('The associated MaxEnt solution is then the same density.'),
 'WHEN THE CONDITION FAILS',P('Moment propagation and closure introduce approximation.')+P('A distribution outside the family can produce a different score-matching and MaxEnt fit.')+M(R`\frac{\|\delta\lambda\|}{\|\lambda\|}=O\!\left(\kappa(A)\frac{\|\delta m\|}{\|m\|}\right)`)+P('Eq. (10) makes conditioning part of the error story.'),
 'Theorem 1 assumes a true member of the polynomial exponential family in the interior of the natural parameter domain. Under the zero-constant convention and positive definiteness of A, the solution recovers its nonconstant coefficients. The perturbation expression is a local sensitivity statement, not an unconditional stability bound for a recursive filter. Inaccurate moments can yield a fitted score whose energy is not integrable. Appendix B.2 Remark 5 explicitly separates existence of an unconstrained score fit from existence of its normalized density.',[cite('Eqs. (10)–(11), Theorem 1','S3.SS1')],[21,21]);

pair('closure-problem','05 · moment closure','Nonlinear prediction requests more moments','A finite list of moment ODEs generally does not close itself.',
 'A SCALAR DOUBLE-WELL SDE',M(R`dx=(x-x^3)dt+\sigma\,dW`)+M(R`\dot m_k=k m_k-k m_{k+2}`)+M(R`\hspace{9mm}+\tfrac12 k(k-1)\sigma^2m_{k-2}`),
 'IF THE TRACKED BUDGET IS K = 6',P('The fifth-moment derivative requires m₇.')+P('The sixth-moment derivative requires m₈.')+P('Those moments cannot be determined by a finite lower-order list for every possible distribution.')+P('SKF supplies them through its fitted score model.'),
 'This is an original one-dimensional worked application of Eqs. (2)–(5), not a claim about the precise oscillator drift in the paper’s scaling experiment. Differentiate x^k twice and substitute X=x−x³ and h=σ. The result involves m_(k+2), giving excess degree two. For k=0 or k=1, derivative prefactors make the negative-degree term zero. This example connects the two higher moments in the next laboratory to a concrete prediction need.',[cite('Eqs. (2)–(5)','S2.E2'),cite('Section 4.1','S4.SS1')]);

pair('stein-identity','05 · the closure identity','Stein’s identity links score and moments','It follows from integrating a total derivative.',
 'VANISHING BOUNDARY TERM',M(R`\int\partial_i[f(x)p(x)]\,dx=0`)+M(R`\mathbb E[\partial_i f+f s_i]=0`)+P('Choose '+I(R`f(x)=x^\beta`)+ ' and substitute the polynomial score.'),
 'MOMENT RELATION · EQ. (12)',M(R`\sum_\alpha\lambda_\alpha\alpha_i\,m_{\alpha+\beta-e_i}=\beta_i m_{\beta-e_i}`)+P('With λ fixed, this is linear in the moments.')+P('With moments fixed, it is linear in λ.')+P('Support, finite moments and boundary conditions matter.'),
 'The identity is exact for a valid density with the stated score when the integrations and boundary cancellation are justified. On a bounded domain, ordinary monomial Stein tests can leave nonzero boundary terms unless the density or test function satisfies suitable conditions. On a manifold, the appropriate derivatives and measure must respect its geometry. SKF uses a finite selection of these relations as a model-based closure and for posterior recovery. This finite use inherits additional approximation choices.',[cite('Eq. (12), Proposition 2','S4.E12')],[22,21]);

pair('quartic-closure','05 · laboratory 2 setup','Two missing moments from two equations','For the proper quartic family, λ₄ = a is positive.',
 'β = 4 GIVES THE SEVENTH MOMENT',M(R`\lambda_1m_4+2\lambda_2m_5+3\lambda_3m_6+4\lambda_4m_7=4m_3`)+M(R`m_7=\frac{4m_3-\lambda_1m_4-2\lambda_2m_5-3\lambda_3m_6}{4\lambda_4}`),
 'β = 5 THEN GIVES THE EIGHTH',M(R`m_8=\frac{5m_4-\lambda_1m_5-2\lambda_2m_6-3\lambda_3m_7}{4\lambda_4}`)+P('In our family λ₃ = 0. A general quartic also uses the recovered m₇ here.')+P('The next lab compares both results with reference moments from numerical integration.'),
 'In one dimension Eq. (12) becomes Σ_j j λ_j m_(j+β−1)=β m_(β−1). Setting β=4 and β=5 gives the displayed recurrence. The first step only uses m0 through m6 and λ. The second step uses the just-computed m7. For this on-model quartic example, the recurrence agrees with the reference up to numerical integration and solve errors. In a filter, a fitted quartic is an approximation and closure error can accumulate. Dividing by a small λ4 also makes the recurrence sensitive.',[cite('Scalar specialization of Eq. (12)','S4.E12')],[20,21]);

live('closure-live','quartic-closure','closure','Recover the missing moments','The score parameters provide the closure coefficients.',P('Recover m₇ and m₈ from known m₀,…,m₆ and the fitted quartic score.')+P('Compare the two algebraic results with numerical reference values, including the Stein residuals.')+P('This is an on-model closure example, not a universal rule for arbitrary distributions.'),'The algebraic recurrence is exact for the proper quartic reference distribution. Numerical quadrature is used only to create input/reference moments and plotted curves. It is not called by the recurrence itself. The lab deliberately avoids a truncated posterior-recovery claim. It illustrates higher-layer closure with already-known lower moments, which is a different problem.',[cite('Eq. (12)','S4.E12')]);

pair('multivariate-closure','05 · closure in several dimensions','A layer of moments becomes a linear system','The needed degrees and the matrix rank determine the work.',
 'COLLECT THE UNKNOWN MOMENTS',M(R`\Lambda_1(\lambda)\,m^{(K+1)}=c_1(\lambda,m^{(\le K)})`)+P('For larger excess degree, solve successive layers.')+P('Overdetermined systems can require least squares. Rank and consistency are separate checks.'),
 'REUSE AND ACTIVE CLOSURE',P('Hold λ fixed across a prediction window and reuse the factorization.')+P('Update the right-hand side at ODE substeps.')+P('For structured dynamics, close only higher moments actually requested by the generator.')+P('The n = 12–20 experiment uses this active closure.'),
 'The paper’s general counting analysis does not guarantee a universally unique closure. A full-basis degree-three construction becomes underdetermined at n=16, while the degree-four crossover occurs between n=35 and n=36. Structured active closure is a distinct construction that avoids requesting every possible high-degree moment. Its least-squares residual may be nonzero. Factorization caching saves repeated decomposition because Λ depends on fixed λ during a window, while c changes with m.',[cite('Section 4.2 and Remark 2','S4.SS2'),cite('Appendix B.5','A2.SS5')],[21,22]);

pair('bayes-score','06 · measurement update','Bayes’ rule adds the likelihood score','The evidence disappears when differentiating with respect to x.',
 'EXACT SCORE IDENTITY · EQ. (13)',M(R`\log p(x\mid z)=\log p^-(x)+\log p(z\mid x)-\log p(z)`)+M(R`s^+(x)=s^-(x)+\nabla_x\log p(z\mid x)`),
 'POLYNOMIAL GAUSSIAN OBSERVATION',M(R`\nabla_x\log p(z\mid x)=J_g^\top R^{-1}(z-g(x))`)+P('If g has degree d<sub>g</sub>, its likelihood energy has degree at most 2d<sub>g</sub>.')+M(R`2d_g\le r\ \Longrightarrow\ \lambda^+=\lambda^-+\lambda_{\rm lik}`),
 'Eq. (13) is a general differentiable Bayes identity. Eq. (14) is exact within the retained coefficient basis only if the likelihood score fits that basis. For additive Gaussian noise with state-independent covariance, −log p(z|x) is half the squared Mahalanobis residual plus an x-independent constant. A polynomial g of degree dg gives polynomial energy degree at most 2dg and score degree at most 2dg−1. Nonpolynomial observation functions or higher-degree likelihoods require an enlarged basis or an explicitly approximate projection.',[cite('Eqs. (13)–(14)','S5.E13')],[21,21]);

pair('scalar-update','06 · laboratory 3 setup','One measurement updates two coefficients','For z = x + v, the likelihood energy is quadratic.',
 'EXPAND THE LIKELIHOOD',M(R`v\sim\mathcal N(0,R)`)+M(R`-\log p(z\mid x)=\frac{(z-x)^2}{2R}+C`)+M(R`=\frac{x^2}{2R}-\frac{z}{R}x+C'`),
 'ADD ITS COEFFICIENTS ONCE',M(R`\lambda_1^+=\lambda_1^--\frac{z}{R}`)+M(R`\lambda_2^+=\lambda_2^-+\frac{1}{2R}`)+M(R`\lambda_3^+=\lambda_3^-,\quad\lambda_4^+=\lambda_4^-`)+P('The score changes by '+I(R`(z-x)/R`)+'.'),
 'R is the scalar measurement variance. If a control specifies a standard deviation σz, square it before using this formula. A quartic prior times this Gaussian likelihood remains a proper quartic density because its positive quartic leading coefficient is unchanged. The next lab lets the same fixed prior be updated with one chosen observation. Moving a slider recomputes that one update from the prior and does not accumulate repeated copies of the observation.',[cite('Worked expansion of Eq. (14)','S5.E14')]);

live('update-live','scalar-update','update','Watch a measurement reshape the belief','Change the observation and its uncertainty. Compare prior and posterior scores.',P('The quartic prior can retain two modes or favor one after a measurement.')+P('Only λ₁ and λ₂ change for the linear Gaussian sensor. The likelihood is included once.')+P('Posterior density curves and their displayed reference moments use numerical quadrature.'),'This laboratory implements exact coefficient addition for a scalar quartic prior and a linear Gaussian likelihood. It does not implement the paper’s finite truncated Stein recovery for all posterior moments. Any posterior means or variances shown with the plots are numerical reference integrals. That separation prevents a visually accurate density update from being mistaken for validation of the full SKF recurrence.',[cite('Eqs. (13)–(14)','S5.E13')]);

pair('posterior-recovery','07 · the difficult return to moments','Posterior coefficients do not give moments for free','This step uses a finite approximation in the general nonlinear case.',
 'REUSE STEIN AT λ⁺ · EQ. (15)',M(R`\sum_\alpha\lambda_\alpha^+\alpha_i m^+_{\alpha+\beta-e_i}=\beta_i m^+_{\beta-e_i}`)+M(R`m^+_{\mathbf0}=1`)+P('Here λ⁺ is known and the posterior moments are unknown.'),
 'WHY TRUNCATION ENTERS',P('Within K = 2r − 2, the exact directional rows can be underdetermined.')+P('For n = 2, r = 4: <b>12 rows, 27 unknown moments</b>.')+P('The paper adds higher test rows, drops terms above K and solves least squares.')+P('<b>This is approximate moment recovery.</b>'),
 'The moment map of a valid exponential family identifies the moments mathematically, but evaluating that map usually requires integration. A finite set of Stein equations need not determine the same map. Section 5.2 explicitly states the underdetermination and introduces higher-degree directional rows with omitted terms above K. Its small-error discussion assumes small neglected centered moments near a Gaussian regime. Centering helps conditioning and truncation error, but does not supply a general guarantee for broad or strongly multimodal beliefs.',[cite('Section 5.2 · Eq. (15)','S5.SS2')],[21,21]);

pair('gaussian-case','08 · recover the familiar Kalman update','A quadratic energy is the information form','The exact reduction assumes a linear Gaussian filtering problem.',
 'GAUSSIAN NATURAL PARAMETERS',M(R`V(x)=\tfrac12x^\top Jx-h^\top x`)+M(R`J=P^{-1},\qquad h=P^{-1}\mu`)+M(R`s(x)=h-Jx`)+P('Here h is the information vector. The paper uses the same letter elsewhere for diffusion.'),
 'LINEAR MEASUREMENT z = Hx + v',M(R`J^+=J^-+H^\top R^{-1}H`)+M(R`h^+=h^-+H^\top R^{-1}z`)+M(R`P^+=(J^+)^{-1},\qquad\mu^+=P^+h^+`),
 'Appendix D maps the quadratic polynomial coefficients to the information matrix and vector. The coordinate-free quadratic expression avoids off-diagonal monomial factor-of-two mistakes. Under linear dynamics, Gaussian initialization and Gaussian process and measurement noise, the moment hierarchy closes at order two and the prediction covariance satisfies the usual Riccati equation. Merely choosing r=2 in a nonlinear or non-Gaussian problem does not make a Gaussian approximation exact.',[cite('Appendix D · linear Gaussian specialization','A4')]);

pair('gaussian-numbers','08 · a complete numerical update','A scalar calculation you can check by hand','Prior mean 0.5, prior variance 2.0, observation 1.2, measurement variance 0.5.',
 'INFORMATION PARAMETERS',M(R`J^-=1/2=0.5,\qquad h^-=0.5/2=0.25`)+M(R`J^+=0.5+2=2.5`)+M(R`h^+=0.25+1.2/0.5=2.65`),
 'POSTERIOR MOMENTS',M(R`P^+=1/2.5=0.4`)+M(R`\mu^+=2.65/2.5=1.06`)+M(R`m_2^+=P^++(\mu^+)^2=1.5236`)+P('Equivalently: '+I(R`\lambda_1^+=-2.65`)+', '+I(R`\lambda_2^+=1.25`)+'.'),
 'This original numerical example applies Appendix D and the scalar coefficient rule. It checks both the sign of the linear energy term and the one-half factor of the quadratic term. The classical Kalman gain is 2/(2+0.5)=0.8, giving μ+=0.5+0.8(1.2−0.5)=1.06 and P+=(1−0.8)2=0.4. The raw second moment is variance plus mean squared, not just the variance.',[cite('Appendix D','A4')]);

add('algorithm','09 · complete recursion','One prediction and one measurement update','Algorithm 1 alternates moments and score coefficients.',[
 ...[['1 · INITIALIZE','Choose r and K = 2r − 2.<br>Fit λ from given initial moments.'],['2 · PREDICT MOMENTS','Integrate the moment ODE.<br>Use Stein closure if needed.'],['3 · FIT THE PREDICTION','Assemble A(m⁻) and b(m⁻).<br>Solve for λ⁻.'],['4 · APPLY THE MEASUREMENT','Form its polynomial energy.<br>Add λlik to λ⁻ once.'],['5 · RECOVER MOMENTS','Solve the finite Stein system.<br>Record truncation and residuals.'],['6 · PREPARE THE NEXT STEP','Refit λ from recovered m⁺.<br>Report first moments as the mean.']].flatMap(([title,body],i)=>panel('step-'+i,72+(i%3)*384,193+Math.floor(i/3)*232,368,216,title,body,{size:23,fill:i%2?C.paper:C.soft}))
],'Algorithm 1 performs initial score matching, prediction through the moment ODE with the previous score as a closure model, a fit to the predicted moments, one conjugate measurement update, posterior Stein recovery, and a refit from the recovered posterior moments. A refit is not new evidence. Section 5.2 and Appendix E separately propose iterative consistency refinement. That optional map needs its own audit because its written recipe re-adds the same likelihood after refitting posterior moments. The main recursion shown here follows one measurement assimilation per cycle.',[cite('Algorithm 1','S6')]);

add('curved-density','10 · a reported density reconstruction','A curved position belief needs more shape','Figure 1 compares a Monte Carlo marginal with several score-matching orders.',[
 box('figure-bg',72,193,1136,292,C.paper),
 {id:'paper-figure',type:'image',x:89,y:210,w:1102,h:253,src:'./figures/se2-density-paper.png',fit:'contain',rotation:0,opacity:1,alt:'Paper Figure 1. Monte Carlo curved position marginal and reconstructions at polynomial orders two, four, six and eight.'},
 ...panel('figure-note',72,508,1136,133,'HOW TO READ THE PANELS','The quadratic fit is Gaussian. Higher orders capture the curved position marginal. This is a reconstruction from predicted moments, not a full SE(3) filtering result.',{size:22})
],'Reproduced without modification from Figure 1 of Iwasaki, Bloch, Lee and Ghaffari, The Score Kalman Filter, arXiv:2605.16644v1, under CC BY 4.0. The source image compares a Monte Carlo 2D position marginal to score-matching reconstructions for r=2,4,6,8. The displayed parameter counts include the constant feature. The visual demonstrates richer representational shape at higher polynomial order. It does not establish posterior filtering accuracy in a growing mapping state.',[cite('Figure 1 · Section 7.1','S7.F1'),link('CC BY 4.0','https://creativecommons.org/licenses/by/4.0/')]);

pair('prediction-evidence','10 · evidence','Prediction and filtering are separate tests','The paper reports several types of numerical experiment.',
 'PREDICTION AND RECONSTRUCTION',P('<b>SE(2):</b> a geometry-adapted moment basis closes for the chosen dynamics. Quartic and higher fits represent a curved position marginal.')+P('<b>Lotka–Volterra:</b> Stein closure approximates a nonlinear moment hierarchy.')+P('These tests assess moments and density reconstruction.'),
 'FULL FILTERING EXPERIMENT',P('<b>Coupled oscillators:</b> repeated prediction and measurement updates through 25 steps.')+P('The reported estimate is the posterior mean.')+P('Comparisons use 10 random seeds.')+P('The n = 12–20 sweep changes to active Stein closure.'),
 'Section 7.1 reports SE(2) moment prediction using a Fourier × position basis and a score reconstruction of its 2D position marginal. That is different from solving a full pose filtering problem at the same polynomial order. Section 7.2 compares nonlinear prediction moments against Monte Carlo for an additive-noise Lotka–Volterra model. Section 7.3 is the full coupled-oscillator filtering comparison. Appendix J’s SE(3) density illustration uses Monte Carlo moments, so it should not be presented as a complete SE(3) SKF demonstration.',[cite('Sections 7.1–7.3','S7'),cite('Appendix J','A10')],[22,22]);

add('reported-rmse','10 · reported filtering results','Lower RMSE on the tested oscillator systems','Table A1 values. SKF entries are mean ± standard deviation over 10 seeds.',[
 ...panel('results',72,193,1136,304,'RMSE OVER 25 STEPS',table(['State n','SKF','EKF','UKF','EnKF','PF (500k)'],[['4','0.0103 ± 0.0040','0.0676','0.0725','0.0762','0.0727'],['8','0.0181 ± 0.0112','0.0713','0.0775','0.0806','0.0747'],['12','0.0029 ± 0.0017','0.0708','0.0731','0.0768','0.0741'],['20','0.0039 ± 0.0050','0.0734','0.0752','0.0806','0.0761']]),{size:24,fill:C.paper}),
 ...panel('interpret',72,510,1136,131,'INTERPRETATION','The error drop at n = 12 coincides with a change of closure. It is not evidence that adding state dimensions makes filtering easier.',{size:22})
],'These are values reported by the authors, not measurements from the browser demonstrations. The table reproduces selected coupled-oscillator rows from Table A1. The baselines’ standard deviations are omitted in this compact comparison, as in A1, and are supplied in Table A2. The paper uses r=3 in these sweeps, centered coordinates and a change to active closure at n=12. Results establish performance on this specific synthetic benchmark and implementation. They do not establish a general accuracy ranking over all nonlinear filters or robotics tasks.',[cite('Table A1','A10.T1'),cite('Table A2','A10.T2')]);

add('reported-time','10 · reported computational cost','Accuracy comes with substantial runtime','Seconds for the full 25-step filter on one CPU, as reported in Table A1.',[
 ...panel('times',72,193,1136,304,'FILTER RUNTIME · SECONDS',table(['State n','SKF','EKF','UKF','EnKF','PF (500k)'],[['4','1','< 0.1','< 0.1','1.2','110'],['8','14','< 0.1','0.1','2.9','291'],['12','195','0.02','0.21','4.0','385'],['20','2079','0.03','0.57','6.5','646']]),{size:24,fill:C.paper}),
 ...panel('time-meaning',72,510,1136,131,'SCOPE OF THE SPEED CLAIM','Removing high-dimensional quadrature helps the architecture scale. It does not make SKF uniformly faster than the Gaussian or particle baselines.',{size:22})
],'Timings are the paper’s full-run values for 25 steps on an Intel i9-11900H CPU using NumPy/SciPy. In particular, 2079 seconds at n=20 means roughly 83 seconds per filter step if divided evenly. The table does not report real-time performance for that setting. SKF is faster than the reported 500,000-particle filter at n=10, but slower at n=20. MEM-KF is not run as a comparable nonlinear closed-hierarchy baseline in these oscillator rows, so no direct measured speedup against MEM-KF should be inferred from them.',[cite('Table A1 and its footnotes','A10.T1')]);

pair('complexity','11 · scaling','Linear algebra still has a combinatorial budget','Fixing polynomial order avoids grid quadrature, but dimensions remain expensive.',
 'DENSE FULL-BASIS COUNTS',M(R`M=\binom{n+r}{n},\qquad N_m=\binom{n+K}{n}`)+table(['n = 20','Parameters M − 1','Moments incl. m₀'],[['r = 3, K = 4','1770','10626'],['r = 4, K = 6','10625','230230']]),
 'COSTS TO ACCOUNT FOR',P('A dense score fit costs approximately '+I(R`O(M^3)`)+'.')+P('Stein closure and posterior recovery add their own systems.')+P('Centering, scaling, sparsity and caching can matter as much as the formula.')+P('A larger r expands both representations.'),
 'The counts are calculated from the full total-degree monomial basis. N_m includes the normalization moment m0 and counts all monomials through K. The paper’s M includes the constant term even though the fit removes it. These counts are not claims about exactly how many unknowns the active-closure benchmark solves in every stage. The dense O(M³) estimate is polynomial in n for fixed r, but r and the exponent strongly influence feasibility. Eliminating O(G^n) tensor-product quadrature does not eliminate every dimensional scaling problem.',[cite('Section 6 · complexity','S6'),cite('Appendix F · moment budget','A6')],[21,22]);

pair('numerical-limits','11 · validity and stability','A solved system can still be a poor belief','Density validity and recursion stability require separate attention.',
 'DENSITY AND MOMENT VALIDITY',P('Check that the fitted energy is integrable on the stated support.')+P('Check symmetry and nonnegative covariance from recovered moments.')+P('Inspect A and closure-system conditioning.')+P('An unconstrained score solution can fall outside the normalizable family.'),
 'FINITE CLOSURE IS A MODEL CHOICE',P('Centering improves numerical behavior but does not make truncation exact.')+P('The optional high-order equations can be inconsistent.')+P('Appendix L gives a closure blow-up counterexample.')+P('Successful benchmark runs are not a global stability theorem.'),
 'These checks are mathematical limitations of the presented filtering construction. Appendix B.2 Remark 5 explicitly notes that unconstrained score fitting does not enforce the natural parameter domain. Appendix L discusses missing convergence and stability guarantees and provides a finite-time closure blow-up counterexample. Positive semidefiniteness of a covariance is necessary but is not sufficient to establish validity of an entire truncated moment sequence. A robust implementation should report failures and sensitivity, rather than silently interpreting every linear-solve output as a density.',[cite('Appendix B.2 · Remark 5','A2.SS2'),cite('Appendix L','A12')],[22,22]);

pair('reading-checks','11 · two implementation questions','Two points need care when reproducing the paper','The following are independent algebraic checks of the written method.',
 'ODD-DEGREE ENERGY ON ℝⁿ',P('The scaling sweep reports r = 3.')+P('A nonzero leading cubic term changes sign under x ↦ −x. Along some tail the energy decreases without bound.')+P('A globally normalized density then needs a different support or a coercive even-degree term.'),
 'REUSING ONE MEASUREMENT',P('Section 5.2 describes refitting posterior moments and then adding the same likelihood again.')+P('If refitting were exact, this would multiply by the likelihood again.')+M(R`J^-+J_{\rm lik}\ \mapsto\ J^-+2J_{\rm lik}`)+P('Clarify the intended refinement target before copying that loop.'),
 'These are teaching-note deductions, not claims of author-acknowledged corrections. For a nonzero homogeneous cubic top-degree polynomial, there is an open set of directions on which it is negative, so exp(−V) is not integrable over all Rn. On a bounded support integrability is possible, but ordinary Stein boundary cancellation must then be checked. Thus the r=3 benchmark scores need a clarified domain or stabilization interpretation before treating them as globally normalizable beliefs. Separately, Eq. (14) already assimilates the likelihood. Refitting the exact posterior would return its same natural parameters, so the Section 5.2/Appendix E recipe of adding λlik again reuses the evidence. This follows immediately in the exact Gaussian special case. The educational demo applies each likelihood once. These checks warrant clarification and limit how literally one should read the broad density and consistency claims.',[cite('Section 5.2 refinement','S5.SS2'),cite('Section 7.3 · r = 3','S7.SS3'),cite('Appendix E','A5')],[21,21]);

pair('radio-slam','12 · connection to radio SLAM','A possible belief model for radio localization','This connection is an interpretation, not an experiment in the paper.',
 'WHERE THE IDEA MAY HELP',P('A position or clock belief can be skewed or multimodal.')+P('Moment prediction could preserve richer uncertainty than a single Gaussian in a small state.')+P('Polynomial approximations could make selected prediction or likelihood blocks compatible.'),
 'WHAT NEEDS ADDITIONAL WORK',P('Ranges, angles and rotations are not generic Euclidean polynomials.')+P('Unknown path associations introduce mixtures and changing map structure.')+P('A growing pose-and-map state makes moment counts expensive.')+P('The paper does not provide a radio-SLAM backend or unknown-pose initializer.'),
 'For radio SLAM, the interesting connection is representation of uncertainty, not a direct replacement of sparse nonlinear graph optimization. Geometric range and angle models typically contain norms, inverse trigonometric operations and periodic variables. A polynomial surrogate changes the likelihood and must be assessed. Lie-group coordinates or embedded constraints need their correct derivatives and base measure, as the paper’s geometry-specific experiments illustrate. Association uncertainty and a changing map require additional machinery. A bounded local state-estimation block is a more defensible initial experiment than assuming a complete high-dimensional SLAM deployment from the oscillator results.',[cite('Problem formulation and experiments','S2'),link('Radio measurement model deck','https://bailiping.com/mpc-detection-to-bounce-count-slides/')],[22,22]);

add('equation-map','13 · reference map','The equations behind each operation','Use this slide to move between the method and the original paper.',[
 ...panel('map',72,193,1136,448,'PAPER EQUATION NUMBERS',table(['Operation','Paper reference','What is solved or computed'],[['Predict moments','(1)–(5)','Generator and moment ODE, with extra degrees'],['Represent the density','(6)','Polynomial energy and its normalizer'],['Fit its score','(7)–(9)','A(m)λ = b(m)'],['Understand fit guarantees','(10)–(11)','Conditioning and recovery inside the model family'],['Close higher moments','(12)','A system linear in unknown moments'],['Assimilate one measurement','(13)–(14)','Add the likelihood score or coefficients'],['Recover posterior moments','(15)','A finite, generally truncated Stein system'],['Recover the Kalman filter','Appendix D','Quadratic information parameters']]),{size:22,fill:C.paper})
],'The key distinction is between three uses of linear algebra: score fitting from given moments, supplying missing higher moments from lower moments and a fixed score, and recovering a new posterior moment vector from updated coefficients. The first has an explicit quadratic objective. The second is a model-based closure. The third is underdetermined if restricted to exact low-degree rows and is approximated in the paper. Their mathematical and numerical guarantees are therefore different.',[cite('Sections 2–6','S2'),cite('Appendix D','A4')]);

add('references','13 · continue reading','Paper, related lessons and live equations','All equation numbers in this deck refer to arXiv:2605.16644v1.',[
 ...panel('paper-ref',72,193,1136,183,'PRIMARY SOURCE',P('<b>K. Iwasaki, A. Bloch, T. Lee and M. Ghaffari</b><br>The Score Kalman Filter. arXiv:2605.16644v1, 15 May 2026.'),{size:23,fill:C.paper}),
 text('paper-html',94,329,380,34,'Read the full HTML paper',{fontSize:23,color:C.teal,link:PAPER}),
 text('paper-pdf',500,329,300,34,'Open the PDF',{fontSize:23,color:C.teal,link:'https://arxiv.org/pdf/2605.16644v1'}),
 ...panel('related',72,398,550,243,'RELATED RANDOM THOUGHTS','',{size:23}),
 text('related-mem',94,455,506,38,'Max Entropy Moment Kalman Filter',{fontSize:23,color:C.teal,link:'https://bailiping.com/mem-kf/'}),
 text('related-kf',94,509,506,38,'One Filter, Many Derivations',{fontSize:23,color:C.teal,link:'https://bailiping.com/kalman-filter-derivations/'}),
 text('related-notes',94,563,506,38,'Read this lesson with expanded notes',{fontSize:23,color:C.teal,link:'https://bailiping.com/score-kalman-filter/study.html'}),
 ...panel('labs',646,398,562,243,'INTERACTIVE EQUATIONS','',{size:23,fill:C.paper}),
 ...[['score','Score matching matrix'],['closure','Stein moment closure'],['update','One measurement update']].map(([lab,title],i)=>text('lab-link-'+lab,668,455+i*54,518,38,title,{fontSize:23,color:C.teal,link:'https://bailiping.com/score-kalman-filter/live/?lab='+lab}))
],'This is an independent educational reading of the cited paper. The paper is available under CC BY 4.0. Slide explanations and scalar examples are original teaching material. Reported benchmark numbers are attributed to the paper’s Table A1. The linked labs use quadrature for synthetic input/reference data and plotted densities, and use algebra for the score fit, selected closure equations and coefficient update. The full benchmark implementation and the paper’s truncated posterior-recovery and optional refinement loops are outside the laboratory scope.',[cite('Primary paper'),link('CC BY 4.0','https://creativecommons.org/licenses/by/4.0/')]);

slides.forEach((s,i)=>s.elements.push(text('number',998,650,210,21,`${String(i+1).padStart(2,'0')} / ${slides.length}`,{fontSize:12,fontFamily:mono,color:C.muted,align:'right'})));
for(const l of labs){l.slideIndex=slides.findIndex(s=>s.id===l.slide);slides[l.slideIndex].elements.push(text('open-lab',750,653,220,18,'OPEN FULL LAB',{fontSize:12,color:C.teal,align:'right',link:'https://bailiping.com/score-kalman-filter/'+l.source.replace(/^\.\//,'')}));}
export const deck={format:'bento/slides',version:1,docId:'score-kalman-filter',title:'The Score Kalman Filter',readonly:true,meta:{author:'Bai Liping',subject:'Polynomial score matching, Stein moment closure and nonlinear Bayesian filtering',company:'bailiping.com',source:'https://bailiping.com/score-kalman-filter/'},size:{width:1280,height:720},theme:{background:C.bg,color:C.ink,accent:C.teal,fontFamily:serif},slides};
export const inlineLiveMap=labs;
