// Rebuild the selected public slides while preserving the bundled Bento runtime.
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import incidenceModel from './live/geometry/incidence-single-model.js';
import incidenceDrawing from './live/geometry/incidence-single-render.js';

const here = dirname(fileURLToPath(import.meta.url));
const read = name => readFileSync(join(here, name), 'utf8');
const doc = JSON.parse(read('deck.json'));
const demos = JSON.parse(read('live-demos.json'));
const ids = doc.slides.map(slide => slide.id);
assert.equal(new Set(ids).size, ids.length, 'Slide IDs must be unique');
for (const slide of doc.slides) {
  for (const element of slide.elements) {
    if (element.link && !element.link.includes(':')) {
      assert.ok(ids.includes(element.link), `Missing slide target: ${element.link}`);
    }
  }
}
for (const entry of demos) {
  assert.ok(ids.includes(entry.slide), `Missing demo slide: ${entry.slide}`);
  assert.ok(ids.includes(entry.introSlide), `Missing demo introduction: ${entry.introSlide}`);
  entry.slideIndex = ids.indexOf(entry.slide);
  for (const key of ['src', 'source']) {
    const path = entry[key].split(/[?#]/)[0];
    assert.ok(existsSync(join(here, path, 'index.html')), `Missing demo: ${entry[key]}`);
  }
}

const geometry = join(here, 'live', 'geometry');
const families = ['single', 'corner', 'paths'];
writeFileSync(join(geometry, 'incidence-points.js'), '// Generated by mpc-detection-to-bounce-count-slides/build.mjs.\n' +
  families.flatMap(name => ['-model', '-render', ''].map(part => `incidence-${name}${part}.js`))
    .map(file => `\n/* ${file} */\n${readFileSync(join(geometry, file), 'utf8')}`).join('\n;\n'));
writeFileSync(join(geometry, 'incidence-points.css'), '/* Generated by mpc-detection-to-bounce-count-slides/build.mjs. */\n' +
  families.map(name => `\n/* incidence-${name}.css */\n${readFileSync(join(geometry, `incidence-${name}.css`), 'utf8')}`).join('\n'));
const scene = incidenceModel.scene;
const measurement = incidenceModel.referenceMeasurements(scene.bs, scene.ue, scene.wallPoint, scene.wallTangent);
const result = incidenceModel.construction(scene.bs, scene.ue, measurement.aod, measurement.aoa, measurement.length);
writeFileSync(join(here, 'assets', 'incidence-single-static.svg'), incidenceDrawing.render({ bs: scene.bs, ue: scene.ue, result }).svg);

const serialize = value => JSON.stringify(value, null, 1).replaceAll('<', '\\u003c');
let html = read('index.html');
for (const [type, id, data] of [
  ['application/bento\\+json', 'bento-doc', doc],
  ['application/json', 'bento-inline-live-map', demos]
]) {
  const pattern = new RegExp(`(<script type="${type}" id="${id}">\\s*)[\\s\\S]*?(\\s*<\\/script>)`);
  assert.ok(pattern.test(html), `Missing ${id} in the runtime shell`);
  html = html.replace(pattern, (_, open, close) => open + serialize(data) + close);
}
writeFileSync(join(here, 'index.html'), html);
console.log(`Radio Measurements → Radio Map: ${doc.slides.length} slides, ${demos.length} live demos`);
