// Original vector illustrations, generated from the same geometry as the labs.
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import * as M from './model.mjs';
import * as A from './association.mjs';
const C={ink:'#213D36',teal:'#137B69',gold:'#BC702D',purple:'#8063AB',line:'#D4DDD5',muted:'#64746D'};
const dir=fileURLToPath(new URL('./figures/',import.meta.url));
const svg=(s,title)=>`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="420" viewBox="0 0 600 420" role="img"><title>${title}</title><rect width="600" height="420" rx="20" fill="#FFFDf8"/>${s}</svg>`;
const text=(x,y,t,col=C.ink,size=16)=>`<text x="${x}" y="${y}" fill="${col}" font-family="Arial, sans-serif" font-size="${size}">${t}</text>`;
const line=(a,b,col=C.line,width=1,dash='')=>`<path d="M${a}L${b}" fill="none" stroke="${col}" stroke-width="${width}" ${dash?'stroke-dasharray="'+dash+'"':''}/>`;
const path=(points,col=C.line,width=1,fill='none')=>`<path d="M${points.map(p=>p.join(',')).join('L')}${fill!=='none'?'Z':''}" stroke="${col}" stroke-width="${width}" fill="${fill}"/>`;
const project=([x,y,z],s=115,cx=300,cy=210)=>[cx+s*(.85*x-.53*y),cy+s*(.28*x+.45*y-.85*z)];
const circ=(x,y,r,col)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${col}"/>`;
function plane(Q,s=115,center=[0,0,0],col=C.teal){const p=(a,b)=>project(Q.map((r,i)=>r[0]*a+r[1]*b+center[i]),s);let z=path([p(-1.3,-1.3),p(1.3,-1.3),p(1.3,1.3),p(-1.3,1.3)],col,1.5,col+'18');for(let a=-1;a<=1;a+=.5)z+=line(p(a,-1.3),p(a,1.3),col+'35')+line(p(-1.3,a),p(1.3,a),col+'35');return z;}
const Q=M.planeBasis(.45),Y=M.mul(Q,M.rotation(.8));let hero='';
[[1.7,0,0],[0,1.7,0],[0,0,1.7]].forEach((p,i)=>{hero+=line(project(p.map(x=>-x)),project(p));const a=project(p);hero+=text(a[0]+8,a[1],['x','y','z'][i],C.muted,13);});hero+=plane(Q);
[[Q,C.gold,'q'],[Y,C.teal,'y']].forEach(([B,c,n])=>M.transpose(B).forEach((v,i)=>{const p=project(v);hero+=line(project([0,0,0]),p,c,4)+circ(...p,4,c)+text(p[0]+8,p[1]-9,n+(i+1),c,21);}));hero+=circ(...project([0,0,0]),5,C.ink)+text(35,46,'ONE SUBSPACE',C.teal,13)+text(35,379,'span(Q) = span(QO)',C.ink,23);
let angles='';[Math.PI/6,Math.PI/3].forEach((a,i)=>{const x=155+i*290,y=195,r=95;angles+=`<circle cx="${x}" cy="${y}" r="${r}" fill="none" stroke="${C.line}"/>`+line([x-r-15,y],[x+r+15,y])+line([x,y-r-15],[x,y+r+15])+line([x,y],[x+r,y],C.gold,4)+line([x,y],[x+r*Math.cos(a),y-r*Math.sin(a)],C.teal,4)+text(x-25,y+145,i?'60°':'30°',C.teal,29)+text(x-85,45,i?'(e₂, e₄) slice':'(e₁, e₃) slice',C.muted,16);});angles+=text(145,398,'Two independent rotations in R⁴',C.muted,16);
let sphere='';for(const z of [-.5,0,.5]){const r=Math.sqrt(1-z*z);sphere+=path(Array.from({length:81},(_,i)=>project([r*Math.cos(i*Math.PI/40),r*Math.sin(i*Math.PI/40),z],150)));}for(let a=0;a<Math.PI;a+=Math.PI/4)sphere+=path(Array.from({length:81},(_,i)=>project([Math.cos(a)*Math.cos(i*Math.PI/40),Math.sin(a)*Math.cos(i*Math.PI/40),Math.sin(i*Math.PI/40)],150)));
const u=[1,0,0],v=[.5,.8*Math.sqrt(.75),.6*Math.sqrt(.75)];sphere+=path(Array.from({length:70},(_,i)=>project(M.lineGeodesic(u,v,i/69).point,150)),C.teal,5);[u,v,M.lineGeodesic(u,v,.5).point].forEach((p,i)=>{const pt=project(p,150);sphere+=line(project([0,0,0]),pt,[C.gold,C.purple,C.teal][i],3)+text(pt[0]+8,pt[1]-8,['[u]','[v]','[q(½)]'][i],[C.gold,C.purple,C.teal][i],19);});sphere+=text(90,393,'q and −q represent the same line',C.muted,18);
const data=M.pcaData();let cloud=plane(data.target,34);for(const p of data.points){const a=project(p,34);cloud+=circ(...a,3,C.purple+'A0');}cloud+=text(28,42,'CAPTURE THE SHARED VARIATION',C.teal,13)+text(54,384,'λ = (9, 4, 1)  →  captured variance = 13',C.ink,20);
let affine=plane(Q,85,[0,0,.85],C.teal)+plane(Q,85,[0,0,0],C.gold);affine+=line(project([0,0,0],85),project([0,0,.85],85),C.purple,3)+circ(...project([0,0,0],85),5,C.ink)+text(329,140,'b + span(A)',C.teal,20)+text(329,310,'span(A)',C.gold,20)+text(30,45,'DIRECTION + ORTHOGONAL DISPLACEMENT',C.muted,12)+text(35,392,'Affine objects need not contain the origin.',C.ink,20);
const scene=A.makeScene(),res=A.associate(scene);let graph='';const size=270,cell=size/res.weights.length;res.weights.forEach((row,i)=>row.forEach((v,j)=>{graph+=`<rect x="${40+j*cell}" y="${65+i*cell}" width="${cell-1}" height="${cell-1}" fill="${v>.5?C.teal:v>0?'#9BBDB0':'#E8EBE4'}"/>`;}));res.selected.forEach(i=>{graph+=`<rect x="39" y="${64+i*cell}" width="272" height="${cell+1}" fill="none" stroke="${C.gold}" stroke-width="1.5"/>`;});graph+=text(40,37,'24 × 24 CONSISTENCY MATRIX',C.muted,13)+text(351,109,'24',C.ink,54)+text(351,137,'candidate matches',C.muted,14)+text(351,219,'6',C.teal,54)+text(351,247,'selected matches',C.muted,14)+text(40,385,'Gold rows = one jointly consistent set',C.ink,20);
let tangent=plane(Q);const d=[-Math.sin(.45)*1.2,0,Math.cos(.45)*1.2];tangent+=line(project([0,0,0]),project(d),C.purple,4)+text(...project(d).map((x,i)=>x+(i?-10:7)),'Δ',C.purple,27)+text(37,43,'LEAVE THE SUBSPACE',C.purple,13)+text(120,389,'QᵀΔ = 0',C.ink,26);
await mkdir(dir,{recursive:true});
for(const [name,s,title]of [['hero',hero,'One plane with two different bases'],['angles',angles,'Principal angles of 30 and 60 degrees'],['geodesic',sphere,'A shortest path of unoriented lines'],['pca',cloud,'A principal plane and its centered data cloud'],['affine',affine,'A linear plane and an offset affine plane'],['graph',graph,'Twenty-four candidates with six selected consistent matches'],['tangent',tangent,'A horizontal tangent moves out of the subspace']])await writeFile(dir+name+'.svg',svg(s,title));
console.log('Built seven original geometric SVG illustrations.');
