import {results,metrics,sources,figureUrl,noteUrl} from './data.mjs';
const C={paper:'#ffffff',ink:'#1d2520',muted:'#56665d',rule:'#dbe4dc',wash:'#edf4ef',accent:'#215c43',orange:'#984d22',blue:'#315aa5'};
const FONT='Arial, Helvetica, sans-serif';
const T=(id,x,y,w,h,html,size=24,color=C.ink,weight=400)=>({id,type:'text',x,y,w,h,html,fontSize:size,fontFamily:FONT,fontWeight:weight,color,align:'left',valign:'top',lineHeight:1.3,rotation:0,opacity:1});
const R=(id,x,y,w,h,fill=C.wash)=>({id,type:'shape',shape:'rect',x,y,w,h,fill,stroke:'none',strokeWidth:0,rotation:0,opacity:1});
const I=(id,n,x,y,w,h,alt)=>({id,type:'image',src:figureUrl(n),x,y,w,h,alt,fit:'contain',rotation:0,opacity:1});
const link=(href,label)=>`<a href="${href}">${label}</a>`;
function S(id,section,title,elements,notes){return {id,transition:'none',background:C.paper,notes,elements:[T('eyebrow',72,34,1136,24,section.toUpperCase(),14,C.accent,700),T('title',72,78,1136,91,title,38,C.ink,700),R('rule',72,173,1136,1,C.rule),...elements,T('footer',72,679,1020,22,`${link('./','Multitarget tracking · nuScenes')} · Bai Liping`,14,C.muted),T('page',1110,679,98,22,'{{page:2}} / {{pages:2}}',14,C.muted)]}}
const P=(id,x,y,w,title,copy)=>[T(id+'-title',x,y,w,60,title,27,C.accent,650),T(id+'-copy',x,y+72,w,205,copy,24)];
const B=(id,x,y,w,title,copy)=>[R(id+'-bg',x,y,w,235),T(id+'-title',x+22,y+22,w-44,68,title,26,C.accent,650),T(id+'-copy',x+22,y+106,w-44,112,copy,22,C.muted)];
function caseSlide(id,kicker,title,num,observation,interpretation){return S(id,kicker,title,[I('figure',num,565,200,643,416,'Original nuScenes experiment visualization'),T('observation-label',72,210,450,25,'RECORDED OBSERVATION',14,C.accent,700),T('observation',72,252,440,155,observation,27),T('interpretation-label',72,440,440,25,'WHAT IT SUGGESTS',14,C.orange,700),T('interpretation',72,480,440,146,interpretation,23,C.muted),T('source',565,631,643,25,link(noteUrl(num),'Original figure and caption'),15,C.muted)],`${observation} Interpretation: ${interpretation} Source: ${noteUrl(num)}. Keep observation and hypothesis distinct.`)}
export function buildSlides(){const s=[];
s.push({id:'cover',background:C.paper,transition:'none',notes:'Introduce this as an organized retrospective of RFS_Filters and the Visualization Analysis notebook. The 0.761 number is AMOTA from a saved validation log, not a new run or test-set leaderboard claim. The cover is an original experiment GIF, displayed at twice the source playback speed and looping continuously.',elements:[T('eyebrow',72,35,1120,26,'BAI LIPING / RESEARCH ARCHIVE',14,C.accent,700),T('title',72,128,605,175,'Multitarget tracking<br>on nuScenes',54,C.ink,700),T('subtitle',72,338,545,102,'Random finite sets, real driving scenes,<br>and the problem of keeping identity.',27,C.muted),R('line',72,475,520,2,C.rule),T('metric',72,509,210,77,metrics.AMOTA.toFixed(3),57,C.accent,700),T('metric-label',277,524,290,85,'AMOTA<br><span style="font-size:18px">Archived validation result</span>',24,C.muted),I('cover-figure',21,689,111,519,498,'Original nuScenes classification sequence at 2× speed, looping continuously'),T('cover-animation-caption',689,615,519,24,'Original sequence · 2× speed · continuous loop',16,C.muted),T('cover-links',72,646,1136,28,`${link('./','Project page & figure archive')} &nbsp; · &nbsp; ${link(sources.repo,'RFS_Filters')} &nbsp; · &nbsp; ${link(sources.notion,'Original notes')}`,17,C.accent)]});
s.push(S('question','01 / Scope','A box in each frame is only the beginning.',[
T('premise',72,211,1095,92,'Which object generated each detection—and when should an identity begin or end?',37,C.ink,650),
...B('a',72,358,350,'Unknown count','Objects enter, leave, and sometimes go undetected.'),...B('b',465,358,350,'Uncertain association','Nearby detections can support several plausible histories.'),...B('c',858,358,350,'Unstable input','Detection labels and velocity estimates can change.')
],'Frame the task as state estimation, cardinality estimation, and identity management. This repository is a research collection and application study. It does not claim to originate the standard RFS filter families.'));
s.push(S('rfs','02 / Probabilistic model','PMBM separates two kinds of uncertainty.',[
...P('poisson',72,222,330,'Not yet detected','A Poisson component represents objects that may exist but have not yet been observed.'),...P('bernoulli',467,222,330,'Detected tracks','Bernoulli components represent candidate objects, each with an existence probability and state distribution.'),...P('mixture',862,222,346,'Association histories','A mixture of multi-Bernoulli hypotheses represents competing explanations of the measurements.'),
R('band',72,554,1136,79),T('band-copy',96,571,1088,54,'PMBMGNN in this repository propagates the highest-weight global hypothesis.',23,C.accent,650)
],`Conceptual summary of PMBM. Do not equate Poisson intensity with a per-track probability. The PMBMGNN behavior follows the repository’s documented procedure: ${sources.repo}/blob/master/nuScenes/trackers/PMBMGNN/README.md`));
s.push(S('filters','02 / Code map','A collection of filters and approximations.',[
...P('classical',72,220,330,'Classical association','GNN, PDA, and JPDA provide different ways of assigning or weighting detections.'),...P('rfs',467,220,330,'RFS filter families','GM-PHD, GM-CPHD, PMB, PMBM, and PMBMGNN appear in the repository.'),...P('message',862,220,346,'Message passing','SPA and supporting implementations explore association through message passing.'),
T('boundary',72,556,1136,62,'Repository coverage is broader than the validation run. These are not all results from one controlled benchmark.',24,C.orange),T('source',72,632,1136,22,`${link(sources.repo+'/tree/master/simulation','Simulation code')} · ${link(sources.repo+'/tree/master/nuScenes/trackers','nuScenes trackers')}`,15,C.muted)
],'Use this slide as a map of the code collection, not a ranking or assertion that every implementation was compared with identical detector inputs. The README credits previous implementations.'));
s.push(S('pipeline','03 / nuScenes application','From detection files to persistent tracks.',[
...B('load',72,222,260,'1. Load','Read boxes, classes, scores, and frame times.'),...B('predict',364,222,260,'2. Predict','Propagate motion, survival, and possible births.'),...B('update',656,222,260,'3. Update','Gate, associate, and update object states.'),...B('evaluate',948,222,260,'4. Evaluate','Export tracks; inspect metrics and trajectories.'),
T('classes',72,508,1136,76,'Seven tracking classes: bicycle, bus, car, motorcycle, pedestrian, trailer, and truck.',27,C.ink,650),T('runner',72,622,1136,28,link(sources.repo+'/blob/master/nuScenes/run_pmbmgnn_tracker.py','Implementation: class-specific nuScenes runner'),17,C.muted)
],'Explain the interface between a detector and a tracker. The repository uses precomputed detections; detector names in scripts should not be taken as proof of the checkpoint used for the featured log. Official tracking task: '+sources.evaluation));
s.push(S('validation','04 / Recorded result','The saved validation run reports 0.761 AMOTA.',[
T('score',72,216,450,115,metrics.AMOTA.toFixed(3),88,C.accent,700),T('score-label',80,338,450,48,'AMOTA · higher is better',25,C.muted),T('amotp',80,413,450,52,metrics.AMOTP.toFixed(3)+' m AMOTP',33,C.ink,650),T('amotp-label',80,472,450,38,'Position error · lower is better',22,C.muted),
T('scope',625,229,535,250,'<b>Dataset:</b> v1.0-trainval<br><br><b>Split:</b> val<br><br><b>Samples:</b> 6,019<br><br><b>Recorded:</b> October 12, 2022',25),
T('boundary',72,568,1136,62,'Archived log, not a new reproduction. Exact detector and tracker settings are not established by the attachment.',23,C.orange),T('source',72,633,1136,24,link('./assets/validation-results.txt','Source: evaluation summary extracted from 0.761.log'),15,C.muted)
],`Numbers are transcribed from the 0.761.log attachment on the user-supplied Notion page. The log explicitly states val and 6019 samples. Its run path dates it to 2022-10-12. Do not call this a test-set or leaderboard result. Source ${sources.notion}`));
const chart=[];results.forEach((r,i)=>{const y=218+i*53;chart.push(T('class-'+i,72,y,180,36,r.name,23),R('track-'+i,273,y+8,570,22,'#edf1ee'),R('bar-'+i,273,y+8,570*r.amota,22,C.accent),T('value-'+i,870,y,95,40,r.amota.toFixed(3),24,C.accent,650))});
s.push(S('per-class','04 / Class-level results','The average hides substantial differences.',[
...chart,T('axis-zero',265,599,60,26,'0.0',15,C.muted),T('axis-half',549,599,60,26,'0.5',15,C.muted),T('axis-one',833,599,60,26,'1.0',15,C.muted),T('insight',1000,247,204,272,'Bus<br><b>0.873</b><br><br>Trailer<br><b>0.529</b>',26),T('source',72,636,1136,25,`${link('./#results','Per-class table and metric definitions')} · Values are rounded as recorded in the saved log.`,15,C.muted)
],'Read per-class AMOTA on a common zero-to-one scale. Class differences may reflect several interacting causes; the log alone does not isolate detector versus tracker contributions.'));
s.push(S('identity','04 / Why inspect trajectories?','Accuracy does not tell the whole identity story.',[
T('ids',72,225,515,108,String(metrics.IDS),80,C.accent,700),T('ids-label',72,343,515,50,'Identity switches',30,C.ink,650),T('frag',671,225,515,108,String(metrics.FRAG),80,C.accent,700),T('frag-label',671,343,515,50,'Track fragmentations',30,C.ink,650),
T('question',72,460,1136,90,'Where do identities change? Which gaps are recoverable? When does continuity preserve the wrong object?',31),T('scope',72,594,1136,48,'These are the log’s reported operating-point counts, not averages over recall thresholds.',21,C.muted)
],'AMOTA is a threshold-averaged metric. ID switches and fragmentations shown here are the counts reported by the evaluator, and should not be described as averaged counts. These motivate the scene-level diagnosis.'));
s.push(S('sequences','05 / Read the original evidence','Follow an identity through the difficult interval.',[
I('occlusion',2,72,206,620,415,'Original annotation: 13 frames of missed pedestrian detection'),T('watch-title',752,214,440,60,'What to watch',29,C.accent,650),T('watch',752,294,430,226,'1. A gap in detections.<br><br>2. A crossing or class change.<br><br>3. Termination, restart, or an implausible link.',26),T('next',752,562,430,73,'Next: inspect four original sequences in the slide.',22,C.muted)
],'Introduce the viewer before advancing. Start from the original occlusion example, then optionally show crossings or class instability. No tracker is running in the browser. The animations are original experiment outputs.'));
const live=S('sequences-live','05 / Original sequence viewer','Inspect the recorded sequence.',[
I('fallback',2,72,208,660,397,'Original occlusion figure used as static fallback'),T('fallback-title',775,228,403,50,'Occlusion',29,C.accent,650),T('fallback-copy',775,300,403,209,'The original note marks 13 frames of missed pedestrian detection.<br><br>Watch the gap and the continuity of the track.',25),T('fallback-source',775,556,403,72,'Original experiment output. The printed slide retains this still.',20,C.muted),{...R('live-demo-mount',48,194,1184,454,'transparent'),opacity:0}
],'The sequence viewer automatically mounts. Selecting a sequence starts its GIF automatically at 2× speed in a continuous loop. Stop returns to a still. Page Up and Page Down navigate the deck; Escape returns keyboard focus to the presentation. The initial case is always occlusion.');
live.__demo={introSlide:'sequences',slide:'sequences-live',slideIndex:s.length,inline:true,layout:'region',bounds:{x:48,y:194,width:1184,height:454},src:'./live/?embed=region',source:'./live/',title:'Original nuScenes tracking sequences',sandbox:'allow-scripts',hideSource:true,readyMessage:true,unloadWhenHidden:true};s.push(live);
s.push(S('birth','06 / Birth versus continuation','Lower birth rate repairs some premature restarts.',[
T('before',72,205,543,33,'Original setting',23,C.muted,650),T('after',665,205,543,33,'Birth rate reduced to 0.001',23,C.accent,650),I('before-image',11,72,250,543,312,'Original premature termination'),I('after-image',12,665,250,543,312,'The paired result after birth-rate reduction'),T('caption',72,586,1136,57,'The source labels this example as resolved. A selected visual repair is not sufficient to choose the setting.',24),T('source',72,641,1136,24,link(noteUrl(12),'Original before / after evidence'),15,C.muted)
],'Compare the paired source figures. The caption identifies a birth-rate setting of 0.001. Do not infer that this value is optimal across classes or scenes. The following slide presents the contrary aggregate observation.'));
s.push(S('tradeoff','06 / Tuning trade-off','Fixing selected tracks can reduce the overall score.',[
T('before-score',72,229,442,99,'0.707',75,C.accent,700),T('before-label',72,347,442,60,'Earlier reported score',25,C.muted),T('arrow',555,250,120,70,'→',54,C.muted),T('after-score',736,229,442,99,'0.690',75,C.orange,700),T('after-label',736,347,442,60,'After reducing birth rate',25,C.muted),T('reason',72,444,1136,81,'The notes report fewer restarts in some examples, but more incorrect associations overall.',31,C.ink,650),T('proposal',72,552,1136,72,'Proposed in the notes: adapt birth intensity to local crowding. This is a hypothesis to evaluate.',24,C.muted),T('source',72,635,1136,26,link(sources.notion+'#2270d664735d818da7eed961c6b91367','Earlier tuning observation; separate from the 0.761 run'),15,C.muted)
],'The two scores are reproduced from the narrative notes. Complete corresponding configurations are not provided, so label them reported scores and keep them separate from the featured validation log. The adaptation idea is proposed, not proved.'));
s.push(caseSlide('classification','07 / Failure analysis','Changing class labels can break a persistent object.',22,'The notes record alternating classification and premature track termination.','Accumulate class evidence over time; test identity continuity as well as class accuracy.'));
s.push(caseSlide('turning','07 / Failure analysis','Turning exposes a second source of mismatch.',29,'The source records termination while turning, even after adding radar velocity.','Separate motion-model mismatch from birth-rate tuning. A turn-aware model is a testable direction.'));
s.push(caseSlide('crossings','07 / Failure analysis','Crossings make several associations plausible.',3,'Two bus tracks intersect, then terminate and restart in the recorded example.','Inspect the competing associations around the intersection, including temporarily missed tracks.'));
s.push(S('mht-pmb','08 / Compare behavior','MHT and TO-PMB: inspect the same source track.',[
T('left-label',72,205,538,40,'MHT · source label',25,C.muted,650),T('right-label',670,205,538,40,'TO-PMB · source label',25,C.accent,650),I('left',43,72,257,538,295,'MHT output: source describes termination'),I('right',44,670,257,538,295,'TO-PMB output for the same source track'),T('caption',72,575,1136,62,'The source identifies termination in the MHT result. This pair illustrates behavior; it does not establish an overall method ranking.',24),T('source',72,642,1136,22,link('./#comparison','Comparison context and original captions'),15,C.muted)
],'TO-PMB means track-oriented Poisson multi-Bernoulli. MHT and TO-PMB labels are retained from the original notes. The exact configurations are not established for every image, so use this as a qualitative comparison rather than a benchmark.'));
s.push(S('coalescence','08 / Compare behavior','Continuity also needs the right association.',[
I('coalescence-figure',66,72,234,650,344,'Original figure from the Track Coalescing section'),T('coalescence-title',777,229,422,60,'Coalescence',28,C.accent,650),T('coalescence-copy',777,305,422,123,'The notes collect cases where tracks become difficult to keep distinct.',25),T('long-title',777,457,422,49,'Long associations',28,C.accent,650),T('long-copy',777,521,422,94,'Other captions flag connections made from too far away.',25),T('source',72,632,1136,25,link('./#archive-coalescence','Original coalescence and long-association figures'),15,C.muted)
],'The image is taken from the Track Coalescing section. Separate these symptoms from premature termination: a longer track is not automatically a more correct track. The archive preserves all original figures, including those with limited captions.'));
s.push(S('next','09 / Next experiments','Four questions the archive makes concrete.',[
...P('birth-test',72,220,525,'01 · Adaptive birth','Does scene-dependent birth behavior reduce restarts without increasing wrong associations?'),...P('class-test',682,220,526,'02 · Class evidence','Can temporal class information preserve identity through unstable detector labels?'),T('motion-title',72,478,525,47,'03 · Motion and occlusion',27,C.accent,650),T('motion-copy',72,542,525,100,'Which failures need better dynamics, and which need better survival through gaps?',23),T('provenance-title',682,478,526,47,'04 · Reproducible comparisons',27,C.accent,650),T('provenance-copy',682,542,526,100,'Keep detections, settings, code revision, and evaluation protocol fixed and recorded.',23)
],'These are future experiment questions, not demonstrated gains. The adaptive-birth idea is explicitly proposed in the original notes; other directions are interpretations of the recorded failure patterns.'));
s.push(S('reproduce','10 / Code and provenance','The repository is a starting point for reproduction.',[
T('code-map',72,220,600,344,`${link(sources.repo+'/tree/master/simulation','simulation/')}<br><span style="font-size:21px;color:${C.muted}">Synthetic experiments and filter implementations</span><br><br>${link(sources.repo+'/tree/master/nuScenes/trackers','nuScenes/trackers/')}<br><span style="font-size:21px;color:${C.muted}">Filter families and experimental variants</span><br><br>${link(sources.repo+'/tree/master/nuScenes/evaluate','nuScenes/evaluate/')}<br><span style="font-size:21px;color:${C.muted}">Evaluation code and historical results</span>`,28,C.accent,650),T('context',739,219,465,332,'The README reports known implementation errors.<br><br>Runners reference local dataset paths and configuration files.<br><br>Mini-split and full validation metrics belong to separate experiments.',25),T('credit',72,597,1136,54,'The README credits prior MATLAB implementations; preserve the original code and method attributions.',22,C.muted)
],'Do not present the repository as a turnkey reproduction of the 0.761 run. The attachment does not fully identify its detector checkpoint and tracker settings. No new tracking experiments were run to build this presentation.'));
s.push(S('takeaways','11 / Takeaways','The useful result is both a score and a diagnosis.',[
T('one',72,227,1136,75,'01   RFS provides a framework for object count and existence uncertainty.',30,C.ink,650),T('two',72,332,1136,100,'02   Track identity depends on detections, association, motion, and birth decisions together.',30,C.ink,650),T('three',72,460,1136,77,'03   Keep quantitative evidence and visual failure analysis side by side.',30,C.accent,650),T('sources',72,589,1136,63,`${link('./','Read the project page')} &nbsp; · &nbsp; ${link('./#archive','Browse 73 original figures')}<br>${link(sources.repo,'RFS_Filters')} &nbsp; · &nbsp; ${link(sources.notion,'Source notes')} &nbsp; · &nbsp; ${link(sources.evaluation,'nuScenes evaluation')}`,20,C.muted)
],'Close by returning to the scope: organizing existing code, results, and visual observations into a research narrative. The page links to the original notes and retains the full figure archive.'));
return s;}
export const theme={background:C.paper,color:C.ink,accent:C.accent,fontFamily:FONT};
