// Active analog-acquisition revision. The original source retains the explicitly labeled reference derivations.
import {deck as original,inlineLiveMap as originalLive,references as legacyReferences} from './bento-deck.mjs';
export const references={...legacyReferences,Analog:{short:'Sohrabi & Yu (2017)',title:'Hybrid Analog and Digital Beamforming for mmWave OFDM Large-Scale Antenna Arrays',url:'https://arxiv.org/abs/1711.08408'}};
const C={bg:'#F4F6F8',ink:'#16222E',muted:'#51606E',line:'#D7DEE5',blue:'#1874B8',teal:'#0A6B5E',orange:'#D76809',paper:'#FFFFFF',cool:'#E8F2FA',mint:'#E3F2EF'};
const sans='Arial, Helvetica, sans-serif',serif="Georgia, 'Times New Roman', serif",mono='Menlo, Consolas, monospace';
const R=String.raw,M=s=>`<span class="math-tex math-display">\\[${s}\\]</span>`;
function text(id,x,y,w,h,html,size=21,more={}){return {id,type:'text',x,y,w,h,html,rotation:0,opacity:1,fontFamily:sans,fontSize:size,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.32,...more};}
function box(id,x,y,w,h,fill=C.paper){return {id,type:'shape',shape:'rect',x,y,w,h,fill,stroke:C.line,strokeWidth:1,radius:10,rotation:0,opacity:1};}
function panel(id,x,y,w,h,label,body,fill=C.paper,size=21){return [box(id+'-box',x,y,w,h,fill),text(id+'-label',x+22,y+18,w-44,28,label,12,{fontFamily:mono,fontWeight:700,color:C.blue}),text(id+'-body',x+22,y+61,w-44,h-79,body,size)];}
function slide(id,title,subtitle,body,notes,keys=['Li','Shah'],section='ANALOG BS + UE · CURRENT ACQUISITION'){
 return {id,background:C.bg,transition:'none',notes:notes+'\n\nSources:\n'+keys.map(k=>references[k].title+' — '+references[k].url).join('\n'),elements:[text('section',96,28,820,22,section,12,{fontFamily:mono,color:C.orange,fontWeight:700}),text('home',930,28,254,22,'RADIO SLAM · ESTIMATION',11,{fontFamily:mono,align:'right',color:C.muted,link:'https://bailiping.com/'}),box('rule',96,66,1088,1,C.line),text('heading',96,86,1088,52,title,36,{fontFamily:serif,fontWeight:700,lineHeight:1.1}),text('subtitle',96,142,1088,35,subtitle,17,{color:C.muted}),...body,text('sources',96,676,920,22,keys.map(k=>`<a href="${references[k].url}" target="_blank" rel="noopener">${references[k].short}</a>`).join(' · '),11,{color:C.muted}),text('contents',1034,677,150,20,'CONTENTS ↗',11,{fontFamily:mono,color:C.blue,align:'right',link:'overview'})]};
}
function two(id,title,subtitle,lLabel,lBody,rLabel,rBody,notes,keys=['Li','Shah'],sizes=[21,21]){return slide(id,title,subtitle,[...panel('left',96,195,532,443,lLabel,lBody,C.cool,sizes[0]),...panel('right',652,195,532,443,rLabel,rBody,C.paper,sizes[1])],notes,keys);}
export const deck=structuredClone(original);
export const inlineLiveMap=structuredClone(originalLive);
const replace=s=>{const i=deck.slides.findIndex(x=>x.id===s.id);if(i<0)throw new Error('Missing original slide '+s.id);deck.slides[i]=s;};
const after=(id,s)=>{const i=deck.slides.findIndex(x=>x.id===id);if(i<0)throw new Error('Missing insertion anchor '+id);deck.slides.splice(i+1,0,s);};
replace(slide('overview','Cramér–Rao bounds for radio measurements','Analog beam sweeping at the BS and UE · revised 29 September 2026',[
 text('hero',96,207,1088,120,'100 BS beams. 32 UE beams.<br><span style="color:#0A6B5E">One pilot symbol per beam pair.</span>',43,{fontFamily:serif,fontWeight:700,lineHeight:1.12}),
 text('intro',96,350,1088,65,'Known beam weights and pilots. Unknown delay, AoA, AoD, path gain and receiver clock. Retain the complex I/Q after analog combining.',23,{color:C.muted}),
 ...[['01','Analog sweep','project-setup',C.cool],['02','Live calculator','project-live',C.mint],['03','Unknown clock','unknown-clock',C.cool],['04','Paper links','references',C.mint]].flatMap(([n,t,link,fill],i)=>[box('tile-'+i,96+278*i,455,254,119,fill),text('nav-'+i,116+278*i,477,214,74,n+'<br><b>'+t+'</b>',20,{link})]),
 text('scope',96,604,1088,38,'One symbol means one OFDM symbol at each tested pair—not one symbol for the full sweep.',18,{color:C.teal})
],'User configuration: analog BS and UE; BS beam grid 10 by 10; UE beam grid 8 by 4; one pilot symbol. This revision interprets the pilot as one OFDM symbol per tested beam pair and assumes one active transmit/receive RF stream. Exhaustive Cartesian pairing is an explicit schedule assumption. Physical antenna dimensions are retained, not inferred from beam counts.',['Li','Shah','Analog']));
replace(two('setup','Beam counts are not antenna counts','Keep hardware, codebook size and training duration separate.',
 'CONFIGURED BEAM SWEEP','<b>BS beam grid:</b> 10 × 10 = 100 beams.<br><br><b>UE beam grid:</b> 8 × 4 = 32 beams.<br><br><b>Pilot:</b> one OFDM symbol per pair.<br><br>One complex receiver output per tone after analog combining.',
 'RETAINED ARRAY AND OFDM ASSUMPTIONS','<b>BS array:</b> 24 × 16 = 384 elements.<br><b>UE array:</b> 8 × 4 = 32 elements.<br><br>27.2 GHz carrier; λ/2 spacing.<br>3300 pilot tones over 400 MHz.<br><br>Array sizes are inherited from the earlier deck. Beam grid sizes do not specify physical antenna counts.',
 'Only the analog architecture, beam-grid sizes and one-symbol pilot are newly supplied. Array dimensions, carrier and tone configuration are retained assumptions. The calculator uses ideal phase shifters and a single stream at each end. The UE codebook has 32 beams, coincidentally the same count as the retained receive elements; these are different concepts.',['Analog','Shah'],[23,21]));
replace(two('project-setup','The analog beam-pair observation','The receiver does not observe the individual antenna-port signals.',
 'ONE SCALAR PER PAIR AND TONE',M(R`y_{mnk}=s_k\mathbf w_n^H\widetilde{\mathbf H}_k\mathbf v_m+z_{mnk}`)+M(R`\widetilde{\mathbf H}_k=e^{-j2\pi f_kb}\mathbf H_k^{\rm g}`)+'m = 1, …, 100 BS beams.<br>n = 1, …, 32 UE combiners.<br>k indexes pilot tones.<br><br>The one-symbol index is suppressed.',
 'ONE ISOLATED PATH',M(R`\mu_{mnk}=s_k\alpha e^{-j2\pi f_k\tau^{\rm a}}r_n t_m`)+M(R`r_n=\mathbf w_n^H\mathbf a_r,\quad t_m=\mathbf a_t^H\mathbf v_m`)+M(R`\tau^{\rm a}=\tau^{\rm g}+b`)+ 'Angles enter the known beam responses. The channel and complex gain remain unknown.',
 'The mean is a specialization of the path-based OFDM model to a single analog transmit vector and receive vector per acquisition. Conventional phase-shifter weights are frequency-independent within each symbol. The array model here uses narrowband steering at the carrier; beam squint is excluded and requires frequency-dependent array responses. All complex I/Q values are retained, not only beam powers.',['Analog','Li','Shah'],[22,22]));
after('project-setup',two('sweep-time','One symbol per pair is 3,200 symbols per sweep','This count assumes every BS beam is tested against every UE beam.',
 'EXHAUSTIVE CARTESIAN SCHEDULE',M(R`M=10\times10=100,\quad N=8\times4=32`)+M(R`Q=MN=3200`)+M(R`N_{\rm samples}=QK=10{,}560{,}000`)+ 'Each sample is a complex scalar. Sequential beam settings are not simultaneous RF outputs.',
 'USEFUL DURATION, NOT WALL-CLOCK TIME',M(R`\Delta f=B/K=121.212\ {\rm kHz}`)+M(R`T_u=1/\Delta f=8.25\ \mu{\rm s}`)+M(R`T_{\rm sweep}=Q/\Delta f=26.4\ {\rm ms}`)+ 'Add CP, beam switching and scheduling gaps. A reduced schedule uses its actual pair count.',
 'Derived counts assume one useful OFDM symbol at every pair, 3300 contiguous active bins and B=K delta f=400 MHz. Useful time is 26.4 ms; it is not an assertion about hardware latency or channel coherence. The 10 by 10 and 8 by 4 dimensions describe azimuth/elevation codebook grids under the interpretation used here.',['Li','Analog'],[22,22]));
replace(two('project-fim','Differentiate the swept mean, not the old pilots','The actual beam responses and acquisition schedule determine the Fisher matrix.',
 'INFORMATION FROM COMPLEX I/Q',M(R`J_{ij}=2\operatorname{Re}\sum_{(m,n)\in\mathcal S}\sum_k\frac{(\partial_i\mu_{mnk})^*(\partial_j\mu_{mnk})}{\sigma_{mnk}^2}`)+M(R`\boldsymbol\eta=[\tau^{\rm a},\varphi_r,\epsilon_r,\varphi_t,\epsilon_t,\ell,\phi]^T`)+ 'Unknown attenuation and phase are included, not held fixed.',
 'BEAM-WEIGHTED DERIVATIVES',M(R`\partial_{q_r}\mu=s_k\alpha e^{-j2\pi f_k\tau^{\rm a}}(\partial_{q_r}r_n)t_m`)+M(R`\partial_{q_t}\mu=s_k\alpha e^{-j2\pi f_k\tau^{\rm a}}r_n(\partial_{q_t}t_m)`)+M(R`\partial_{\tau^{\rm a}}\mu=-j2\pi f_k\mu`)+ 'Invert the identifiable joint information—not only its diagonal entries.',
 'The noise is proper circular complex Gaussian with known parameter-independent variance. Stack derivatives over the scheduled scalar observations; J=2 Re(D^H C^-1 D). The browser accumulates exact tone moments and spatial derivatives, algebraically equivalent to summing every raw sample. Parameter units are ns, degrees, degrees, degrees, degrees, dB, radians. Full joint marginal bounds include gain/phase nuisance coupling.',['Li','Shah','LeMagoarou'],[21,21]));
after('project-fim',two('beam-identifiability','A short pilot can still provide spatial diversity','One symbol at many pairs is different from repeating one fixed pair.',
 'ONE FIXED BEAM PAIR',M(R`\alpha_{\rm eff}=\alpha\,r_n(\mathbf q_r)\,t_m(\mathbf q_t)`)+ 'Under narrowband steering, all four angles enter one unknown complex scalar.<br><br>A free gain can absorb their effect.<br><br>Frequency diversity can retain delay information, but does not supply the missing spatial diversity.',
 'SWEEP BOTH ENDS','Different known beam responses reveal angle-dependent changes across the schedule.<br><br>'+M(R`\operatorname{rank}\begin{bmatrix}\operatorname{Re}\mathbf D\\\operatorname{Im}\mathbf D\end{bmatrix}`)+'determines local identifiability.<br><br><b>No requirement of 384 symbols per pair.</b> Check the structured Jacobian, not the old time-code rank condition.',
 'A single fixed beam pair generally cannot identify AoA/AoD jointly with a free complex gain in the stated frequency-flat array-response model. Across a coherent sweep the gain is shared but the known responses vary; full rank is possible, not guaranteed. Beam coverage, calibration, physical aperture and chosen operating point matter. Beam squint can alter the single-pair conclusion and is not modeled here.',['Li','LeMagoarou'],[21,22]));
after('beam-identifiability',two('sweep-coherence','Coherence is an acquisition assumption','A 26.4 ms useful sweep must not silently become one simultaneous snapshot.',
 'WHAT THE CURRENT CALCULATOR ASSUMES','One static isolated far-field path.<br><br>A common complex gain and stable or compensated phase across beam pairs.<br><br>Known, calibrated beam weights.<br><br>Retained complex I/Q, not just received power or the index of the strongest beam.',
 'WHEN THESE ASSUMPTIONS FAIL',M(R`\mu_{mnk}\ \mapsto\ \mu_{mnk}e^{j2\pi\nu t_{mn}}`)+ 'Retain timestamps and Doppler for motion.<br><br>Model switching offsets, phase noise and calibration uncertainty as appropriate nuisance parameters.<br><br>Power-only data need a different likelihood.',
 'Useful sweep duration is not a coherence guarantee. For a moving channel, angles, delay and gain can vary as well as Doppler phase. One symbol per pair does not remove the time spread of the whole schedule. Unknown pairwise phases change the nuisance structure; independent arbitrary complex pair gains can remove spatial identifiability. The CRB shown is conditional on the static coherent likelihood.',['Li','Analog'],[22,21]));
replace(two('project-codes','An analog beam-sweep bounds calculator','The codebook directions are illustrative; the measured beam weights have not been supplied.',
 'POWER AND COMBINED NOISE',M(R`\|\mathbf v_m\|=\|\mathbf w_n\|=1,\quad |s_k|^2=P/K`)+M(R`\sigma^2=N_0\Delta f,\quad N_0=10^{(-174+{\rm NF}-30)/10}`)+ 'At NF = 9 dB: σ² = 3.8331 × 10⁻¹⁵ W.<br><br>Do not divide noise by 32 beams or by 3,200 pairs.',
 'EXPERIMENTS TO TRY','Compare the full sweep with one fixed pair, a BS-only sweep, and a UE-only sweep.<br><br>Vary physical aperture independently of beam-grid density.<br><br>Change beam coverage and true path direction.<br><br>Inspect the full Fisher matrix and its rank.',
 'Unit-modulus array steering and unit-norm RF weights keep transmit power and receive noise consistent. Pre-combining noise is spatially white with independent realizations at sequential pairs. An aligned beam can gain Nt or Nr in signal power, already captured in the responses; never multiply those gains in again. Noise figure includes whatever effective RF loss is assumed. Default ideal beams form uniform azimuth/elevation grids covering -60 to 60 and -30 to 30 degrees at both ends. These coverage choices, power=30 dBm and loss=120 dB are teaching inputs, not user-supplied measured hardware settings.',['Analog','Li','Noise'],[21,21]));
replace(slide('project-live','Analog sweeping and measurement bounds','100 BS beams × 32 UE beams · one OFDM pilot symbol per tested pair',[
 ...panel('print-fallback',72,180,1136,475,'INTERACTIVE ANALOG LAB','Vary arrays, beam grids, coverage, bandwidth, power, noise and path direction.<br><br>Compare a full sweep with a single fixed pair and one-sided sweeps. Check local rank and all seven marginal bounds.<br><br>The ideal codebook and isolated path are illustrative, not a saved measured acquisition.',C.cool,23),
 {...box('live-demo-mount',72,180,1136,475,'transparent'),stroke:'transparent',opacity:0}
],'The interactive calculator reports square roots of the full joint marginal CRB. Unobservable coordinates are shown as unidentifiable, not pseudoinverse zeros. One OFDM symbol per pair is fixed. Partial one-sided/fixed-pair examples freeze their strongest beam at the evaluation point and do not model adaptive selection or charge a search overhead.',['Li','Shah','Analog']));
const currentLab=inlineLiveMap.find(x=>x.slide==='project-live');
currentLab.src='./analog/?embed=1';currentLab.source='./analog/';currentLab.title='Analog beam-sweep CRB calculator';
replace(two('unknown-channel','Known training does not mean a known channel','The receiver knows the experiment. It must estimate the propagation parameters.',
 'KNOWN BY DESIGN','Pilot values and subcarrier frequencies.<br><br>BS beam weights and UE combiner weights.<br><br>Beam-pair schedule and timestamps.<br><br>Array calibration and the assumed noise covariance.',
 'UNKNOWN TO THE ESTIMATOR','Each path’s apparent delay, two arrival angles, two departure angles, attenuation and phase.<br><br>The receiver clock and the number of paths are unknown.<br><br>The true channel is used only to evaluate the CRB—not as an estimator input.',
 'The deterministic CRB is conditional on the true parameter point and a chosen number of paths. Path detection and model order are outside the isolated-path bound. The analog lab uses one illustrative isolated path; a full multipath bound must stack all path derivatives and retain cross-path coupling.',['Li','Shah','LeMagoarou'],[23,22]));
replace(two('unknown-clock','Beam sweeping does not resolve the clock gauge','Every path still contains the same receiver timing bias.',
 'UNKNOWN MULTIPATH MEAN',M(R`\mu_{mnk}=s_k\sum_p\alpha_p e^{-j2\pi f_k(\tau_p^{\rm g}+b)}r_{np}t_{mp}`)+M(R`\partial_b\mu_{mnk}=\sum_p\partial_{\tau_p^{\rm g}}\mu_{mnk}`)+ 'Adding δ to b and subtracting δ from every geometric delay leaves all samples unchanged.',
 'ESTIMATE APPARENT DELAYS',M(R`\tau_p^{\rm a}=\tau_p^{\rm g}+b`)+ 'Channel-level CRBs refer to apparent delay.<br><br>Delay differences cancel the common clock.<br><br>A clock reference, prior or geometric constraints are additional information, not a benefit of extra beam pairs alone.',
 'With free geometric delays and common clock, the Fisher matrix has the gauge direction (-delta,...,-delta,+delta). Common carrier phase is absorbed into the free path gains. Multiplication by analog weights does not change this invariance. The geometry section remains applicable after using the correct beam-sweep channel information.',['Li','Shah'],[21,22]));
// Preserve the original educational derivations, but never present their special closed forms as the current acquisition.
const referenceIds=['signal','pilots','snr','noise-budget','calculator','calculator-live','derivatives','fisher-live','bandwidth','bandwidth-live','geometry','geometry-live','angle-example','gain','scaling'];
for(const s of deck.slides)if(referenceIds.includes(s.id)){
 s.elements.find(e=>e.id==='section').html='ORTHOGONAL REFERENCE · NOT THE ANALOG ACQUISITION';
 s.notes='REFERENCE ONLY: balanced orthogonal transmit training and per-antenna reception. These closed forms/labs do not model the current analog beam sweep. Use project-live for that acquisition.\n\n'+s.notes;
}
for(const [id,title] of [['calculator-live','Orthogonal reference calculator'],['fisher-live','Reference Fisher information matrix'],['geometry-live','Reference array-geometry bounds'],['bandwidth-live','Reference bandwidth and time']])deck.slides.find(s=>s.id===id).elements.find(e=>e.id==='heading').html=title;
replace(two('extensions','Extensions must enter the same likelihood','Analog precoding and combining are already part of the current model.',
 'MOTION AND SWITCHING',M(R`\mu_{mnk}\propto e^{-j2\pi f_k\tau}e^{j2\pi\nu t_{mn}}`)+M(R`\partial_\nu\mu=j2\pi t_{mn}\mu`)+ 'Use actual pair timestamps.<br><br>Account for beam-dependent RF calibration, switching transients and phase offsets before trusting a coherent bound.',
 'WIDEBAND, GEOMETRY AND NOISE','<b>Beam squint:</b> steering at f<sub>c</sub> + fₖ with fixed phase-shifter weights.<br><br><b>Near field:</b> spherical path lengths.<br><br><b>Multiple RF chains:</b> vector observations with combined noise covariance.<br><br><b>Colored noise:</b> whiten with the actual covariance.',
 'The generic proper-complex Gaussian formula is J=2 Re(D^H C^-1 D) for parameter-independent covariance. If covariance depends on unknown parameters, include the covariance-derivative contribution. For motion, Doppler alone can be inadequate if angles, delays or path gains evolve appreciably during the sweep.',['Li','Analog'],[22,21]));
replace(two('formula-sheet','The analog-sweep equations in one place','Use the full joint matrix for the configured beamformed observations.',
 'MEAN, NOISE AND INFORMATION',M(R`\mu_{mnk}=s_k\alpha e^{-j2\pi f_k\tau^{\rm a}}r_nt_m`)+M(R`\sigma^2=N_0\Delta f`)+M(R`\mathbf J=2\operatorname{Re}(\mathbf D^H\mathbf C^{-1}\mathbf D)`)+M(R`\sigma_{i,\rm LB}=\sqrt{[\mathbf J^{-1}]_{ii}}`),
 'ACQUISITION AND ENERGY',M(R`Q=100\times32=3200,\quad T_u^{\rm sweep}=Q/\Delta f`)+M(R`\Gamma=\sum_{m,n,k}\frac{|\mu_{mnk}|^2}{\sigma^2}`)+ 'Beam gain is already in rₙtₘ.<br><br>No automatic NᵣKLρ replacement.<br>No 384-symbol requirement per pair.<br>No finite CRB for unobservable coordinates.',
 'The derivative matrix stacks the actual schedule. Delay has the familiar 1/(2 pi beta sqrt(2 Gamma)) form for this isolated path when tone and spatial signatures are separable and complex gain is unknown. Angular and gain/phase bounds generally require the joint matrix; orthogonal array-covariance formulas cannot be transplanted into an arbitrary swept codebook.',['Li','Shah','LeMagoarou'],[22,22]));
replace(slide('references','Reference papers — direct links','The analog specialization is derived here; these papers provide the underlying models and FIM framework.',[
 ...[['Analog','F. Sohrabi and W. Yu · analog/hybrid OFDM architecture; not a CRB paper.'],['Li','X. Li et al. · MIMO–OFDM waveform-dependent Fisher information.'],['Shah','A. Shahmansoori et al. · joint channel parameters and position/orientation bounds.'],['LeMagoarou','L. Le Magoarou and S. Paquelet · structured channel estimation and pilot design.']].flatMap(([k,note],i)=>[
 box('ref-'+i,96,188+113*i,1088,103,i%2?C.paper:C.cool),
 text('ref-title-'+i,113,199+113*i,1054,40,`<a href="${references[k].url}" target="_blank" rel="noopener"><b>${references[k].title}</b></a>`,18),
 text('ref-url-'+i,113,239+113*i,1054,22,`<a href="${references[k].url}" target="_blank" rel="noopener">${references[k].url}</a>`,15,{color:C.blue}),
 text('ref-note-'+i,113,266+113*i,1054,19,note,13,{color:C.muted})])
],'All paper titles, visible URLs and slide footers are clickable. Sohrabi and Yu assume known CSI for their beamforming optimization; this deck uses their architecture, not that known-channel premise. The other papers provide related Fisher-information and structured-estimation frameworks. The specific 100-by-32 schedule is user configuration, not claimed to come from these papers. Thermal-noise technical note (not a research paper): https://www.ti.com/lit/pdf/slaa652 .',['Analog','Li','Shah','LeMagoarou'],'REFERENCES · LINKS TO EVERY PAPER'));
// Bento sanitizes inline HTML anchors. Use native element links for every paper URL and footer reference.
for(const [i,k] of ['Analog','Li','Shah','LeMagoarou'].entries())for(const prefix of ['ref-title-','ref-url-'])deck.slides.find(s=>s.id==='references').elements.find(e=>e.id===prefix+i).link=references[k].url;
for(const s of deck.slides){
 const source=s.elements.find(e=>e.id==='sources');if(!source)continue;
 const matches=[...source.html.matchAll(/<a href="([^"]+)"[^>]*>(.*?)<\/a>/g)];
 if(!matches.length)continue;
 s.elements=s.elements.filter(e=>e.id!=='sources');let x=96;
 for(const [i,m] of matches.entries()){const label=m[2].replace(/<[^>]+>/g,'')+' ↗',w=Math.max(88,label.length*5.8+12);s.elements.push(text('source-link-'+i,x,676,w,22,label,11,{color:C.muted,link:m[1]}));x+=w+9;}
}
// Rebuild numbering and live-lab links after insertions; keep project-setup/project-live/unknown-channel bookmarks stable.
for(const s of deck.slides)s.elements=s.elements.filter(e=>!['slide-number','open-lab'].includes(e.id));
for(const e of inlineLiveMap){e.slideIndex=deck.slides.findIndex(s=>s.id===e.slide);deck.slides[e.slideIndex].elements.push(text('open-lab',760,657,240,18,'OPEN FULL-SIZE LAB ↗',11,{fontFamily:mono,color:C.blue,link:'https://bailiping.com/radio-cramer-rao-slides/'+e.source.replace(/^\.\//,'')}));}
for(let i=0;i<deck.slides.length;i++)deck.slides[i].elements.push(text('slide-number',970,656,214,16,`${String(i+1).padStart(2,'0')} / ${deck.slides.length}`,11,{fontFamily:mono,color:C.muted,align:'right'}));
deck.meta.subject='Analog BS/UE beam-sweeping Fisher information: 100 by 32 beams, one OFDM pilot symbol per pair';
deck.meta.revision='2026-09-29-analog-beam-sweep';
