// Canonical Bento source for Advanced State Variable Representations.
// The supplied SLAM Handbook chapter is summarized; its PDF is not republished.
const C={paper:'#F5F3ED',panel:'#FFFDFA',ink:'#182D33',muted:'#60747A',rule:'#D6DEDC',teal:'#16736E',soft:'#E4F0ED',coral:'#C2573F',warm:'#F7E8E1',blue:'#3F6F91',cool:'#E5EDF4',amber:'#A87820',sun:'#F2DCA7'};
const serif="Georgia, 'Times New Roman', serif",sans="Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",mono="'SFMono-Regular', Consolas, monospace";
const SOURCE_URL='https://github.com/SLAM-Handbook-contributors/slam-handbook-public-release';
const R=String.raw;
const M=s=>`<span class="math-tex math-display">\\[${s}\\]</span>`;
const I=s=>`<span class="math-tex math-inline">\\(${s}\\)</span>`;
function text(id,x,y,w,h,html,o={}){return {id,type:'text',x,y,w,h,rotation:0,opacity:1,html,fontSize:18,fontFamily:sans,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.4,...o};}
function box(id,x,y,w,h,fill=C.panel,stroke=C.rule,o={}){return {id,type:'shape',shape:'rect',x,y,w,h,fill,stroke,strokeWidth:1,radius:14,rotation:0,opacity:1,...o};}
function line(id,x,y,dx,dy,color=C.rule,width=2,o={}){const length=Math.hypot(dx,dy);return {id,type:'shape',shape:'line',x:x+dx/2-length/2,y:y+dy/2-width/2,w:length,h:width,fill:color,stroke:'none',strokeWidth:0,radius:0,rotation:Math.atan2(dy,dx)*180/Math.PI,opacity:1,...o};}
function circle(id,x,y,size,fill=C.panel,stroke=C.teal,o={}){return {id,type:'shape',shape:'ellipse',x,y,w:size,h:size,fill,stroke,strokeWidth:2,rotation:0,opacity:1,...o};}
function panel(id,x,y,w,h,label,html,o={}){return [box(id+'-bg',x,y,w,h,o.fill||C.panel,o.stroke||C.rule),text(id+'-label',x+22,y+17,w-44,22,label,{fontFamily:mono,fontSize:11,fontWeight:800,color:o.accent||C.teal,letterSpacing:.8}),text(id+'-body',x+22,y+55,w-44,h-72,html,{fontSize:o.size||18,lineHeight:o.lineHeight||1.42,...(o.body||{})})];}
function chrome(source='SH2 · ADVANCED STATE VARIABLE REPRESENTATIONS'){return [box('chrome-rule',72,669,1136,1,C.rule,C.rule,{radius:0}),text('chrome-home',72,684,310,20,'BAI LIPING · RANDOM THOUGHTS',{fontFamily:mono,fontSize:10,color:C.muted,link:'https://bailiping.com/'}),text('chrome-source',370,684,540,20,source,{fontFamily:mono,fontSize:10,color:C.muted,align:'center',link:SOURCE_URL}),text('chrome-index',1032,684,176,20,'CONTENTS ↗',{fontFamily:mono,fontSize:10,color:C.teal,align:'right',link:'overview'})];}
function slide(id,section,title,sub,elements,notes,source,transition='none'){return {id,background:C.paper,transition,notes,elements:[text('eyebrow',72,35,1110,22,section.toUpperCase(),{fontFamily:mono,fontSize:11,fontWeight:800,color:C.coral,letterSpacing:1.25}),text('heading',72,69,1136,55,title,{fontFamily:serif,fontSize:37,fontWeight:700,lineHeight:1.05}),text('subtitle',72,128,1136,42,sub,{fontSize:15.5,color:C.muted,lineHeight:1.35}),...elements,...chrome(source)]};}
function two(id,section,title,sub,leftLabel,left,rightLabel,right,notes,source,o={}){return slide(id,section,title,sub,[...panel(id+'-left',72,188,548,422,leftLabel,left,{fill:o.leftFill||C.soft,accent:o.leftAccent||C.teal,size:o.leftSize||18,lineHeight:o.leftLineHeight||1.42,body:o.leftBody}),...panel(id+'-right',644,188,564,422,rightLabel,right,{fill:o.rightFill||C.panel,accent:o.rightAccent||C.coral,size:o.rightSize||18,lineHeight:o.rightLineHeight||1.42,body:o.rightBody})],notes,source,o.transition||'none');}
function three(id,section,title,sub,cards,notes,source){return slide(id,section,title,sub,cards.flatMap(([label,body,fill,accent],i)=>panel(id+'-'+i,72+i*382,188,358,422,label,body,{fill,accent,size:17,lineHeight:1.4})),notes,source);}
function callout(id,x,y,w,h,html,o={}){return [box(id+'-bg',x,y,w,h,o.fill||C.warm,o.stroke||C.coral,{radius:10}),text(id+'-text',x+16,y+11,w-32,h-22,html,{fontSize:o.size||15,fontWeight:o.weight||650,color:o.color||C.ink,valign:'middle',align:o.align||'left',lineHeight:1.35})];}
function node(id,x,y,label,o={}){const size=o.size||44;return [circle(id+'-dot',x,y,size,o.fill||C.panel,o.stroke||C.teal),text(id+'-label',x,y+size/2-10,size,20,label,{fontFamily:mono,fontSize:o.fontSize||11,fontWeight:750,align:'center',valign:'middle',color:o.color||C.ink})];}
function nativeTable(id,x,y,w,h,headers,rows,o={}){return {id,type:'table',x,y,w,h,rotation:0,opacity:1,header:true,columns:(o.columns||headers.map(()=>1)).map(width=>({w:width})),rows:[{cells:headers.map(html=>({html}))},...rows.map(row=>({cells:row.map(html=>({html}))}))],style:{headerBg:o.headerBg||C.teal,headerColor:'#FFFFFF',zebra:o.zebra||C.soft,borderColor:C.rule,borderWidth:1,cellPadX:o.padX||14,cellPadY:o.padY||10,fontSize:o.fontSize||16,color:C.ink,fontFamily:sans,radius:12}};}
function liveFallback(title,kicker,body,diagram=[]){return [box('live-fallback',72,180,1136,475,C.panel,C.rule),text('live-fallback-kicker',96,203,1088,20,kicker,{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.coral,letterSpacing:1}),text('live-fallback-title',96,232,1088,37,title,{fontFamily:serif,fontSize:27,fontWeight:700}),text('live-fallback-body',96,282,344,300,body,{fontSize:16.5,lineHeight:1.47}),...diagram,box('live-demo-mount',72,180,1136,475,'rgba(255,255,255,0)','rgba(255,255,255,0)',{opacity:0})];}

const slides=[];

slides.push(slide('overview','Chapter 2 · a reading map','Advanced State Variable Representations','States that bend. Trajectories that flow. One optimization language for both.',[
 text('cover-claim',76,196,676,108,'Optimize locally.<br><span style="color:#C2573F">Represent globally.</span>',{fontFamily:serif,fontSize:47,fontWeight:700,lineHeight:1.08,fx:{enter:'fade-up',order:0}}),
 text('cover-copy',78,317,650,62,'A visual route from constrained rotations and poses to sparse continuous-time estimation.',{fontSize:18,color:C.muted,lineHeight:1.48}),
 ...[['01','MANIFOLDS','tangent updates','tangent-space',C.soft],['02','TRAJECTORIES','local temporal support','splines',C.cool],['03','SYNTHESIS','GPs on Lie groups','gp-prior',C.warm]].flatMap(([number,title,copy,link,fill],i)=>[box('cover-card-'+i,72+i*236,423,218,100,fill),text('cover-card-title-'+i,91+i*236,440,180,25,number+' · '+title,{fontFamily:mono,fontSize:12,fontWeight:800,color:i===2?C.coral:C.teal,link}),text('cover-card-copy-'+i,91+i*236,476,180,28,copy,{fontSize:14,color:C.muted,link})]),
 text('cover-labs',76,582,700,26,'3 LIVE LABS · ROTATION ↗ · SPLINE ↗ · SPARSE GP ↗',{fontFamily:mono,fontSize:11.5,color:C.teal,link:'tangent-space'}),
 box('cover-map',808,194,400,420,C.panel,C.rule),text('cover-map-label',832,214,352,22,'THE TWO REPRESENTATION PROBLEMS',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.coral,letterSpacing:.7}),
 circle('cover-manifold',852,270,160,C.soft,C.teal,{strokeWidth:3}),line('cover-tangent',930,246,120,-56,C.coral,4),circle('cover-state',923,295,18,C.coral,C.panel,{strokeWidth:2}),text('cover-manifold-label',854,337,156,26,'MANIFOLD',{fontFamily:mono,fontSize:12,fontWeight:800,align:'center'}),
 line('cover-time-line',846,511,308,0,C.rule,3),...[[856,0],[926,1],[1018,2],[1138,3]].flatMap(([x,i])=>node('cover-time-'+i,x,489,'t'+i,{size:44,fill:i===2?C.warm:C.panel,stroke:i===2?C.coral:C.teal})),text('cover-time-label',848,558,304,25,'CONTINUOUS TIME',{fontFamily:mono,fontSize:12,fontWeight:800,align:'center'})
],'Open with the chapter’s two representation questions: how to optimize constrained states without invalidating them, and how to represent motion continuously without creating a variable per measurement. The demos are original deterministic teaching models based on Chapter 2.','SH2 · CHAPTER 2'));

slides.push(two('why-representation','0 · Motivation','Representation decides what the optimizer is allowed to change.','The numerical solver may be familiar; the state space and the time model are not.',
 'CONSTRAINED STATE',`${M(R`R^{\mathsf T}R=I,\qquad \det R=1`)}A three-dimensional rotation has nine matrix entries but only three degrees of freedom.<br><br>Adding an arbitrary matrix increment violates the constraints.<br><br><b>Need:</b> unconstrained local coordinates whose update returns a valid state.`,
 'CONTINUOUS MOTION',`${M(R`x(t),\qquad t\in\mathbb R`)}A spinning lidar, rolling-shutter camera, and IMU do not observe the robot only at a shared set of discrete pose times.<br><br>Adding one pose per sample is expensive and conceptually unnecessary.<br><br><b>Need:</b> a smooth function with local, sparse support.`,
 'Frame the chapter as a modeling problem, not a collection of notation. Rotation constraints motivate manifolds. Asynchronous and high-rate sensing motivates continuous-time trajectories.','SH2 · §2 OPENING',{rightFill:C.cool,rightAccent:C.blue}));

slides.push(three('groups','1 · Manifold-valued states','Rotations and poses are groups with fewer freedoms than entries.','Closure under composition is the structure we exploit.',[
 ['PLANAR ROTATION',`${M(R`R(\theta)=\begin{bmatrix}\cos\theta&-\sin\theta\\\sin\theta&\cos\theta\end{bmatrix}`)}${I(R`SO(2)`)} · one degree of freedom.<br><br>Composition adds angles while keeping a valid rotation.`,C.soft,C.teal],
 ['SPATIAL ROTATION',`${M(R`R\in SO(3)`)}Nine entries · three degrees of freedom.<br><br>${I(R`R^{\mathsf T}R=I`)} and ${I(R`\det R=1`)} define the embedded manifold.`,C.panel,C.blue],
 ['RIGID POSE',`${M(R`T=\begin{bmatrix}R&t\\0&1\end{bmatrix}\in SE(d)`)}Rotation and translation compose in one homogeneous transform.<br><br>In ${I(R`SE(3)`)}, the pose has six degrees of freedom.`,C.warm,C.coral]
],'Use planar rotation as the simplest group, then distinguish matrix entries from degrees of freedom. A pose combines rotation and translation. The essential property for updates is closure under matrix multiplication.','SH2 · §2.1.1'));

slides.push(slide('tangent-space','1 · Optimization on manifolds','A tangent step is local. The state stays global.','Linear algebra happens near the current estimate; retraction returns the result to the manifold.',[
 ...panel('tangent-idea',72,188,500,422,'LOCAL COORDINATES',`${M(R`T_\chi\mathcal M\ \cong\ \mathbb R^n`)}Near ${I(R`\chi\in\mathcal M`)}, the tangent space behaves like an ordinary vector space.<br><br>The optimizer solves for a small increment ${I(R`\delta`)} there—not for arbitrary entries of the constrained state.<br><br>${M(R`\chi^+=\chi\oplus\delta`)}`,{fill:C.soft,size:18}),
 box('tangent-diagram',596,188,612,422,C.panel,C.rule),text('tangent-label',620,206,564,21,'MENTAL MODEL · FLATTEN LOCALLY',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.coral}),
 circle('tangent-manifold-a',746,304,270,C.cool,C.blue,{strokeWidth:3}),circle('tangent-manifold-b',796,352,168,C.soft,C.teal,{strokeWidth:2}),circle('tangent-point',904,298,20,C.coral,C.panel,{strokeWidth:2}),
 line('tangent-plane',840,251,250,-75,C.coral,4),line('tangent-step',908,295,105,-31,C.teal,6),circle('tangent-next',1006,256,18,C.teal,C.panel,{strokeWidth:2}),
 text('tangent-m-label',660,478,150,26,I(R`\mathcal M`),{fontSize:24,align:'center'}),text('tangent-p-label',918,204,210,30,I(R`T_\chi\mathcal M`),{fontSize:21,align:'center'}),
 ...callout('tangent-watch',620,531,564,58,'NEXT · Repeat the same increment. Watch a first-order matrix step lose orthogonality while exponential-map composition remains valid.',{fill:C.warm,stroke:C.coral,size:14})
],'Introduce the tangent space as the local coordinate system used by the optimizer. Emphasize the two-stage idea: solve in a vector space, then retract. On the next slide, compare an exact exponential update with repeated first-order matrix accumulation.','SH2 · §2.1 · FIG. 2.1'));

slides.push(slide('manifold-live','Interactive lab 01','A tangent step is local. The state stays global.','Repeat a planar rotation increment and compare exact group composition with a first-order matrix shortcut.',liveFallback('Walk on the group. Do not leave it.','STATIC FALLBACK · DETERMINISTIC INITIAL STATE',`<b>Initial controls</b><br>Increment: ${I(R`12^\circ`)} · six updates.<br><br><b>Exact path</b><br>${I(R`R\leftarrow R\operatorname{Exp}(\delta)`)} preserves determinant one and orthonormal columns.<br><br><b>Shortcut path</b><br>${I(R`R\leftarrow R(I+\delta^\wedge)`)} visibly stretches the basis after repeated finite steps.<br><br><b>Observe:</b> a good local approximation is not automatically a valid global state.`,[
 box('mf-exact',476,219,315,353,C.soft,C.teal),text('mf-exact-label',500,238,267,22,'EXPONENTIAL UPDATE',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.teal}),circle('mf-exact-circle',553,295,170,'rgba(255,255,255,0)',C.rule),line('mf-exact-x',638,380,-58,-66,C.teal,5),line('mf-exact-y',638,380,66,-58,C.blue,5),...[[624,360],[610,339],[592,320],[571,306],[548,298]].flatMap(([x,y],i)=>[circle('mf-exact-step-'+i,x,y,8,C.teal,C.panel,{strokeWidth:1})]),text('mf-exact-metric',503,500,261,45,'determinant = 1.000<br>orthogonality error ≈ 0',{fontFamily:mono,fontSize:12,color:C.muted,align:'center'}),
 box('mf-euler',815,219,353,353,C.warm,C.coral),text('mf-euler-label',839,238,305,22,'FIRST-ORDER ACCUMULATION',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.coral}),circle('mf-euler-circle',906,295,170,'rgba(255,255,255,0)',C.rule),line('mf-euler-x',991,380,-92,-102,C.coral,5),line('mf-euler-y',991,380,102,-92,C.blue,5),...[[973,356],[951,329],[925,306],[895,288],[860,277]].flatMap(([x,y],i)=>[circle('mf-euler-step-'+i,x,y,8,C.coral,C.panel,{strokeWidth:1})]),text('mf-euler-metric',843,500,297,45,'columns lengthen<br>determinant drifts above one',{fontFamily:mono,fontSize:12,color:C.muted,align:'center'})
]),'Use the increment and repetition sliders. The exact branch multiplies by a true planar rotation; the comparison branch multiplies by the first-order approximation. The latter is included only to expose constraint drift—it is not presented as a recommended optimizer update. Escape returns focus to Bento; Page Up returns to the concept slide.','SH2 · §2.1.2–§2.1.3 · TEACHING MODEL','morph'));

slides.push(slide('exp-log','1 · Lie groups','Exp and Log bridge vectors, algebras, and groups.','The wedge and vee operators change representation; the exponential and logarithm change geometry.',[
 box('bridge-bg',72,190,1136,286,C.panel,C.rule),
 ...panel('bridge-vector',96,215,286,212,'VECTOR SPACE',`${M(R`\xi\in\mathbb R^n`)}Coordinates the solver can update without constraints.`,{fill:C.soft,size:16,body:{align:'center'}}),
 ...panel('bridge-algebra',497,215,286,212,'LIE ALGEBRA',`${M(R`\xi^\wedge\in\mathfrak g`)}The tangent space at the identity, represented as a matrix.`,{fill:C.cool,accent:C.blue,size:16,body:{align:'center'}}),
 ...panel('bridge-group',898,215,286,212,'LIE GROUP',`${M(R`X=\operatorname{Exp}(\xi)\in G`)}A valid rotation or pose.`,{fill:C.warm,accent:C.coral,size:16,body:{align:'center'}}),
 line('bridge-a',382,318,115,0,C.teal,4),text('bridge-a-label',392,276,95,28,I(R`(\cdot)^\wedge`),{fontSize:18,align:'center'}),
 line('bridge-b',783,318,115,0,C.coral,4),text('bridge-b-label',794,276,92,28,I(R`\exp(\cdot)`),{fontSize:18,align:'center'}),
 text('bridge-return',263,496,754,42,`${I(R`\operatorname{Log}(X)=(\log X)^\vee`)} returns from the group to vector coordinates.`,{fontSize:19,align:'center'}),
 ...callout('bridge-rule',240,552,800,54,'Notation shortcut: Exp maps a vector to the group; Log maps a group element to a vector.',{fill:C.soft,stroke:C.teal,align:'center'})
],'Walk left to right for state construction and right to left for residuals or differences. Wedge and vee are linear representation changes. Exp and Log are the geometric maps. Closed forms are normally used rather than the infinite matrix series.','SH2 · §2.1.2 · FIG. 2.2'));

slides.push(slide('optimize','1 · Lie-group optimization','Linearize → solve → retract → repeat.','The nonlinear least-squares loop is unchanged; only the coordinates and update operator differ.',[
 ...[['01','NOMINAL STATE',`${I(R`T^0\in SE(3)`)}`,C.soft,C.teal],['02','LINEARIZE',`${I(R`e(T^0\oplus\xi)\approx e_0+H\xi`)}`,C.cool,C.blue],['03','SOLVE',`${I(R`\xi^*=\arg\min\lVert b-A\xi\rVert^2`)}`,C.panel,C.amber],['04','RETRACT',`${I(R`T^0\leftarrow T^0\operatorname{Exp}(\xi^*)`)}`,C.warm,C.coral]].flatMap(([number,label,formula,fill,accent],i)=>[box('loop-card-'+i,72+i*284,212,260,155,fill,accent),text('loop-num-'+i,91+i*284,228,46,24,number,{fontFamily:mono,fontSize:11,fontWeight:800,color:accent}),text('loop-label-'+i,91+i*284,265,222,24,label,{fontFamily:mono,fontSize:11,fontWeight:800,color:accent}),text('loop-math-'+i,91+i*284,306,222,38,formula,{fontSize:16,align:'center'})]),
 ...[0,1,2].map(i=>line('loop-arrow-'+i,332+i*284,289,24,0,C.rule,4)),
 ...panel('loop-camera',72,400,724,201,'EXAMPLE · CAMERA POSE',`${M(R`z_i\approx h_i(T^0\tilde\ell_i)+H_i\xi+\eta_i`)}The chain rule differentiates the measurement with respect to a tangent perturbation. The optimizer still sees an unconstrained vector ${I(R`\xi`)}.`,{fill:C.panel,size:17}),
 ...panel('loop-invariant',820,400,388,201,'INVARIANT',`Every accepted iterate remains a valid pose because the update is group composition.<br><br><b>Retraction is the bridge between a Euclidean solver and a nonlinear state space.</b>`,{fill:C.soft,size:17})
],'Connect the chapter’s derivation to an ordinary Gauss–Newton loop. The residual is linearized with respect to a tangent perturbation. After solving, group composition applies the increment and maintains validity.','SH2 · §2.1.3 · EQS. 2.10–2.19'));

slides.push(two('uncertainty','1 · Uncertainty','Put the Gaussian in the tangent space, then map it to the group.','Ordinary addition is valid for vectors; group composition is valid for rotations and poses.',
 'VECTOR STATE',`${M(R`x=\mu+\delta,\qquad\delta\sim\mathcal N(0,\Sigma)`)}The mean and perturbation live in the same vector space.<br><br>The covariance describes local spread directly in those coordinates.`,
 'GROUP STATE',`${M(R`T=\bar T\oplus\delta=\bar T\operatorname{Exp}(\delta)`)}${M(R`\delta\sim\mathcal N(0,\Sigma)`)}The Gaussian is defined in the tangent coordinates. Mapping it through Exp guarantees ${I(R`T\in SE(d)`)}.<br><br><b>Boundary:</b> this is a local uncertainty model; broad or multimodal uncertainty needs more care.`,
 'Distinguish a Gaussian over tangent coordinates from a globally Gaussian distribution on the curved group. The construction is especially useful when uncertainty remains compact around a nominal rotation or pose.','SH2 · §2.1.4',{rightFill:C.warm,rightAccent:C.coral}));

slides.push(slide('adjoint','1 · Lie-group extras','The adjoint moves a perturbation between frames and sides.','A six-vector is not meaningful until its coordinate frame and perturbation convention are known.',[
 ...panel('adjoint-equation',72,188,548,422,'SIDE SWITCHING',`${M(R`T\operatorname{Exp}(\xi)=\operatorname{Exp}(\operatorname{Ad}(T)\xi)T`)}This identity moves a right perturbation to the left.<br><br>${M(R`\operatorname{Ad}\!\left(\begin{bmatrix}R&t\\0&1\end{bmatrix}\right)=\begin{bmatrix}R&t^\wedge R\\0&R\end{bmatrix}`)}The adjoint is a linear map on tangent coordinates.`,{fill:C.soft,size:17}),
 box('adjoint-frame',644,188,564,422,C.panel,C.rule),text('adjoint-frame-label',668,207,516,21,'SAME PHYSICAL INCREMENT · DIFFERENT COORDINATES',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.coral}),
 line('adjoint-world-x',735,490,185,0,C.blue,4),line('adjoint-world-y',735,490,0,-185,C.blue,4),text('adjoint-world',684,504,100,22,'WORLD',{fontFamily:mono,fontSize:10,color:C.blue}),
 line('adjoint-body-x',900,366,135,-67,C.teal,5),line('adjoint-body-y',900,366,67,135,C.teal,5),circle('adjoint-body',883,349,34,C.teal,C.panel,{strokeWidth:2}),text('adjoint-body-label',853,520,120,22,'BODY',{fontFamily:mono,fontSize:10,color:C.teal,align:'center'}),
 line('adjoint-local-step',907,354,88,-42,C.coral,6),line('adjoint-global-step',748,476,104,-50,C.coral,6),
 text('adjoint-local',973,289,165,36,'local coordinates',{fontSize:13,color:C.muted}),text('adjoint-global',664,404,172,36,'global coordinates',{fontSize:13,color:C.muted}),
 ...callout('adjoint-question',670,542,512,43,'Always ask: left or right perturbation—and expressed in which frame?',{fill:C.warm,stroke:C.coral,size:13,align:'center'})
],'Use the diagram to separate the physical displacement from its coordinates. The adjoint transforms the tangent vector when moving a perturbation through a pose. This is an exact identity, not a first-order approximation.','SH2 · §2.1.5.3 · EQS. 2.27–2.31'));

slides.push(three('jacobians','1 · Lie-group extras','Jacobians connect rates, products, and sensor derivatives.','They are the bookkeeping that makes local coordinates differentiable.',[
 ['KINEMATICS',`${M(R`\dot R=\omega^\wedge R`)}${M(R`\dot\theta=J(\theta)^{-1}\omega`)}The group Jacobian relates angular velocity to the rate of exponential coordinates.`,C.soft,C.teal],
 ['COMPOSITION',`${M(R`\operatorname{Exp}(\theta_1)\operatorname{Exp}(\theta_2)\approx\operatorname{Exp}\!\big(\theta_2+J(\theta_2)^{-1}\theta_1\big)`)}A small first increment can be folded into one exponential coordinate.`,C.cool,C.blue],
 ['CHAIN RULE',`${M(R`H_i=\frac{\partial h_i}{\partial\ell}\frac{\partial\ell}{\partial\xi}`)}Differentiate the sensor model with respect to the tangent perturbation.<br><br>Analytic, numerical, and automatic differentiation are all possible.`,C.warm,C.coral]
],'Do not attempt to derive every closed form on the slide. The teaching goal is to show where Lie-group Jacobians enter: rates, composition of exponentials, and the chain rule from a measurement to local pose coordinates.','SH2 · §2.1.5.4'));

slides.push(slide('continuous-time','2 · Continuous time','One trajectory function serves many clocks.','Measurements, estimation variables, and queries no longer need the same timestamps.',[
 box('time-bg',72,192,1136,237,C.panel,C.rule),line('time-axis',116,326,1044,0,C.rule,4),
 ...[[145,'0.0'],[282,'0.8'],[450,'1.7'],[635,'2.9'],[823,'4.1'],[1080,'5.0']].flatMap(([x,label],i)=>[circle('time-meas-'+i,x-8,307,16,i%2?C.coral:C.blue,C.panel,{strokeWidth:1}),text('time-meas-label-'+i,x-22,348,44,20,label,{fontFamily:mono,fontSize:9,color:C.muted,align:'center'})]),
 ...[[170,'x0'],[425,'x1'],[680,'x2'],[935,'x3']].flatMap(([x,label],i)=>[circle('time-state-'+i,x-19,281,38,C.soft,C.teal),text('time-state-label-'+i,x-19,291,38,20,label,{fontFamily:mono,fontSize:10,fontWeight:800,align:'center'})]),
 line('time-query-mark',752,264,0,126,C.amber,3),text('time-query-label',700,391,104,22,'query',{fontFamily:mono,fontSize:10,fontWeight:800,color:C.amber,align:'center'}),
 text('time-meas-name',98,218,265,24,'ASYNCHRONOUS MEASUREMENTS',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.coral}),text('time-state-name',98,252,265,24,'ESTIMATION VARIABLES',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.teal}),
 ...panel('time-use-a',72,462,358,143,'MOTION DISTORTION','Use each lidar point, radar return, or rolling-shutter row at its actual acquisition time.',{fill:C.soft,size:15}),
 ...panel('time-use-b',461,462,358,143,'HIGH RATE','Avoid creating a full pose variable for every IMU sample or pixel timestamp.',{fill:C.cool,accent:C.blue,size:15}),
 ...panel('time-use-c',850,462,358,143,'QUERY ANYWHERE','Interpolate pose—and often covariance or derivatives—at a downstream consumer’s time.',{fill:C.warm,accent:C.coral,size:15})
],'The red and blue marks are measurements at irregular times, the larger green marks are estimation variables, and the amber line is a query. Continuous time separates these three clocks. Extrapolation is possible but should be treated cautiously.','SH2 · §2.2 OPENING'));

slides.push(slide('splines','2 · Parametric trajectories','Compact support makes a smooth trajectory sparse.','At one time, only a small subset of basis functions—and therefore coefficients—can matter.',[
 ...panel('spline-equation',72,188,500,422,'PARAMETRIC FORM',`${M(R`p(t)=\sum_{k=1}^{K}\Psi_k(t)c_k`)}Known temporal basis functions ${I(R`\Psi_k`)} combine unknown coefficients ${I(R`c_k`)}.<br><br>${M(R`\dot p(t)=\sum_{k=1}^{K}\dot\Psi_k(t)c_k`)}Derivatives reuse the same coefficients.<br><br><b>Local support:</b> most basis functions are exactly zero at a given ${I(R`t`)}.`,{fill:C.soft,size:17}),
 box('spline-basis',596,188,612,422,C.panel,C.rule),text('spline-basis-label',620,206,564,22,'FOUR LOCAL BASIS FUNCTIONS · SCHEMATIC',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.coral}),
 ...[[650,0,C.blue],[750,1,C.teal],[850,2,C.coral],[950,3,C.amber]].flatMap(([x,i,color])=>[line('spline-rise-'+i,x,365,70,-128,color,3),line('spline-fall-'+i,x+70,237,70,128,color,3)]),
 line('spline-query',878,217,0,176,C.ink,2),text('spline-query-t',849,199,60,22,I(R`t_i`),{fontSize:16,align:'center'}),
 ...[[674,'c1'],[778,'c2'],[882,'c3'],[986,'c4']].flatMap(([x,label],i)=>node('spline-coeff-'+i,x,438,label,{size:42,fill:[C.cool,C.soft,C.warm,C.sun][i],stroke:[C.blue,C.teal,C.coral,C.amber][i]})),
 line('spline-factor-a',695,460,170,79,C.rule,2),line('spline-factor-b',799,460,66,79,C.rule,2),line('spline-factor-c',903,460,-38,79,C.rule,2),line('spline-factor-d',1007,460,-142,79,C.rule,2),circle('spline-factor',843,517,46,C.coral,C.panel,{strokeWidth:2}),text('spline-factor-label',843,528,46,22,I(R`z_i`),{fontSize:12,fontWeight:800,align:'center'}),
 ...callout('spline-watch',620,566,564,35,'NEXT · Move one control point; only its support interval changes.',{fill:C.warm,stroke:C.coral,size:12.5,align:'center'})
],'Explain that the basis functions are known and the coefficients are estimation variables. A measurement factor connects only to active coefficients. The next lab uses linear and cubic B-splines to make local support visible. The z label is schematic; the live lab itself has no landmark variable.','SH2 · §2.2.1 · FIG. 2.3'));

slides.push(slide('spline-live','Interactive lab 02','Compact support makes a smooth trajectory sparse.','Move one control point, choose the query time, and inspect which coefficients are active.',liveFallback('Move one control. Change one neighborhood.','STATIC FALLBACK · CUBIC BASIS AT DEFAULTS',`<b>Initial controls</b><br>Cubic basis · query ${I(R`t=0.54`)} · raise ${I(R`c_5`)} by ${I(R`0.18`)}.<br><br><b>Solid curve</b><br>Edited trajectory.<br><br><b>Muted curve</b><br>Unchanged reference.<br><br><b>Observe:</b> four of eleven basis weights are nonzero, and the moved coefficient affects only a bounded time interval.`,[
 box('sp-plot',472,220,502,350,C.soft,C.rule),
 ...[[499,405,542,440],[542,440,585,379],[585,379,629,346],[629,346,672,385],[672,385,715,293],[715,293,758,394],[758,394,801,315],[801,315,845,361],[845,361,888,322],[888,322,931,352]].flatMap(([x,y,nx,ny],i)=>[line('sp-control-'+i,x,y,nx-x,ny-y,C.rule,2)]),
 ...[[499,405],[542,440],[585,379],[629,346],[672,385],[715,293],[758,394],[801,315],[845,361],[888,322],[931,352]].flatMap(([x,y],i)=>[circle('sp-control-dot-'+i,x-7,y-7,14,i===5?C.coral:C.panel,i===5?C.coral:C.teal,{strokeWidth:2})]),
 ...[[499,414,542,408],[542,408,585,386],[585,386,629,370],[629,370,672,363],[672,363,715,352],[715,352,758,349],[758,349,801,344],[801,344,845,350],[845,350,888,354],[888,354,931,348]].flatMap(([x,y,nx,ny],i)=>[line('sp-ref-'+i,x,y,nx-x,ny-y,C.muted,2,{opacity:.65})]),
 ...[[499,414,542,408],[542,408,585,386],[585,386,629,368],[629,368,672,344],[672,344,715,326],[715,326,758,333],[758,333,801,342],[801,342,845,350],[845,350,888,354],[888,354,931,348]].flatMap(([x,y,nx,ny],i)=>[line('sp-curve-'+i,x,y,nx-x,ny-y,C.teal,5)]),
 line('sp-query',732,244,0,254,C.coral,2),circle('sp-query-dot',723,320,18,C.coral,C.panel,{strokeWidth:2}),
 box('sp-bars',996,220,172,350,C.panel,C.rule),text('sp-bars-label',1015,239,134,20,'BASIS WEIGHTS',{fontFamily:mono,fontSize:9.5,fontWeight:800,color:C.coral}),...[[0,0],[1,0],[2,0],[3,0],[4,.052],[5,.581],[6,.361],[7,.005],[8,0],[9,0],[10,0]].flatMap(([i,v])=>[text('sp-bar-label-'+i,1016,274+i*24,28,16,'c'+i,{fontFamily:mono,fontSize:9}),box('sp-bar-bg-'+i,1046,266+i*24,92,13,C.paper,C.paper,{radius:4}),box('sp-bar-'+i,1046,266+i*24,92*v,13,v?C.teal:C.rule,v?C.teal:C.rule,{radius:4})])
]),'Try linear versus cubic basis functions, move the query time, then move a control point. The model evaluates an open-uniform B-spline with Cox–de Boor basis recursion. The default curve is deterministic; the displayed query speed is a numerical derivative for teaching.','SH2 · §2.2.1 · TEACHING MODEL','morph'));

slides.push(two('kernel-trick','2 · From parametric to nonparametric','Replace explicit basis choices with a covariance kernel.','The representation moves from coefficients to correlations among states at different times.',
 'PARAMETRIC VIEW',`${M(R`p(t)=\Psi(t)c`)}Choose the family and number of basis functions.<br><br><b>Too few:</b> insufficient capacity.<br><br><b>Too many:</b> easy to overfit unless regularized.<br><br>${M(R`(\Psi^{\mathsf T}A^{\mathsf T}A\Psi+I)\,\delta c^*=\Psi^{\mathsf T}A^{\mathsf T}b`)}`,
 'KERNEL VIEW',`${M(R`K=\Psi\Psi^{\mathsf T}`)}The normal equations can be written directly in pose updates:<br>${M(R`(A^{\mathsf T}A+K^{-1})\,\delta^*=A^{\mathsf T}b`)}A kernel function ${I(R`K(t,t')`)} replaces the explicit inner product of basis functions.<br><br><b>New choice:</b> kernel family and hyperparameters.`,
 'The kernel trick does not eliminate modeling decisions; it changes them. The inverse kernel acts as a smoothing prior in the normal equations. A generic kernel may produce a dense inverse, which motivates the SDE construction next.','SH2 · §2.2.2',{rightFill:C.cool,rightAccent:C.blue,leftSize:17,rightSize:17}));

slides.push(slide('gp-prior','2 · Gaussian processes','A Markov motion prior makes the inverse kernel sparse.','Start from a stochastic differential equation; locality then appears in the precision matrix and factor graph.',[
 ...panel('gp-sde',72,188,490,422,'PHYSICS-FIRST PRIOR',`${M(R`\dot x(t)=Ax(t)+Lw(t)`)}${M(R`w(t)\sim\mathcal{GP}(0,Q\,\delta(t-t'))`)}The transition ${I(R`\Phi(t,s)=\exp(A(t-s))`)} and process noise define the covariance kernel.<br><br>A constant-velocity prior augments the state with velocity; a random walk is the simplest case.`,{fill:C.soft,size:17}),
 box('gp-graph',586,188,622,422,C.panel,C.rule),text('gp-graph-label',610,206,574,22,'MARKOV STATE → NEIGHBOR FACTORS',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.coral}),
 line('gp-chain',660,338,436,0,C.rule,4),...[[640,'x1'],[780,'x2'],[920,'x3'],[1060,'x4']].flatMap(([x,label],i)=>node('gp-node-'+i,x,316,label,{size:44,fill:i===2?C.warm:C.soft,stroke:i===2?C.coral:C.teal})),
 ...[[728,'Q1'],[868,'Q2'],[1008,'Q3']].flatMap(([x,label],i)=>[box('gp-factor-'+i,x,326,28,24,C.panel,C.amber,{radius:4}),text('gp-factor-label-'+i,x,331,28,18,label,{fontFamily:mono,fontSize:8,color:C.amber,align:'center'})]),
 text('gp-precision',625,410,544,68,M(R`K^{-1}=\Phi^{-\mathsf T}Q^{-1}\Phi^{-1}`),{fontSize:22,align:'center'}),text('gp-sparse',625,484,544,30,'block-tridiagonal for a Markov state',{fontFamily:mono,fontSize:12,fontWeight:800,color:C.teal,align:'center'}),
 ...callout('gp-watch',618,542,558,47,'NEXT · Change process variance and watch the trajectory flex while the information pattern remains banded.',{fill:C.warm,stroke:C.coral,size:13,align:'center'})
],'The SDE defines a Gaussian process and its kernel. Because the chosen state is Markovian, the inverse kernel is block-tridiagonal. Higher-order motion priors require an augmented state, such as pose and velocity.','SH2 · §2.2.3 · FIG. 2.4'));

slides.push(slide('gp-live','Interactive lab 03','A Markov motion prior makes the inverse kernel sparse.','Fit asynchronous scalar measurements, query anywhere, and trade smoothness against data fit.',liveFallback('Fit every timestamp. Keep local structure.','STATIC FALLBACK · RANDOM-WALK GP',`<b>Initial controls</b><br>Eight control states · eight asynchronous measurements · query at ${I(R`t=3.65\,\mathrm{s}`)}.<br><br><b>Model</b><br>Scalar random-walk motion factors connect neighbors; measurements interpolate between adjacent controls.<br><br><b>Observe:</b> changing process variance alters path flexibility and posterior uncertainty, but the information matrix remains tridiagonal.`,[
 box('gpf-chart',472,220,526,350,C.cool,C.rule),text('gpf-chart-label',494,239,482,20,'POSTERIOR MEAN · 95% BAND · MEASUREMENTS',{fontFamily:mono,fontSize:9.5,fontWeight:800,color:C.blue}),
 ...[[505,447],[565,405],[625,425],[685,337],[745,356],[805,287],[865,314],[945,251]].flatMap(([x,y],i)=>[line('gpf-band-'+i,x,y-22,i===7?0:60,i===7?0:([[505,447],[565,405],[625,425],[685,337],[745,356],[805,287],[865,314],[945,251]][i+1][1]-y),C.cool,28,{opacity:.85}),i===7?box('gpf-dummy',0,0,0,0,'rgba(0,0,0,0)','rgba(0,0,0,0)',{opacity:0}):line('gpf-mean-'+i,x,y,60,[[505,447],[565,405],[625,425],[685,337],[745,356],[805,287],[865,314],[945,251]][i+1][1]-y,C.teal,5)]),
 ...[[520,435],[570,390],[637,438],[696,321],[763,370],[822,275],[884,329],[951,241]].flatMap(([x,y],i)=>[box('gpf-meas-'+i,x,y,10,10,C.coral,C.coral,{radius:1,rotation:45})]),
 line('gpf-query',748,255,0,252,C.coral,2),circle('gpf-query-dot',739,342,18,C.coral,C.panel,{strokeWidth:2}),
 box('gpf-matrix-bg',1020,220,148,350,C.soft,C.rule),text('gpf-matrix-label',1035,239,118,20,'INFORMATION',{fontFamily:mono,fontSize:9.5,fontWeight:800,color:C.teal,align:'center'}),
 ...Array.from({length:8},(_,i)=>Array.from({length:8},(_,j)=>box('gpf-cell-'+i+'-'+j,1036+j*14,276+i*14,11,11,Math.abs(i-j)<=1?C.teal:C.panel,Math.abs(i-j)<=1?C.teal:C.rule,{radius:2,opacity:Math.abs(i-j)<=1?(i===j?1:.45):1}))).flat(),text('gpf-matrix-copy',1036,413,112,70,'neighbor motion<br>factors keep<br>the pattern<br>banded',{fontFamily:mono,fontSize:9.5,color:C.muted,align:'center'})
]),'Change process variance, measurement noise, and query time. The experiment performs an actual linear Gaussian solve for eight scalar control states, then inverts the information matrix for the displayed interpolation uncertainty. The synthetic measurements are deterministic and the model is intentionally one-dimensional.','SH2 · §2.2.3 · TEACHING MODEL','morph'));

slides.push(slide('cumulative','3 · Splines on Lie groups','Cumulative splines replace vector sums with group composition.','Interpolate relative motions, not raw matrix entries.',[
 ...panel('cum-vector',72,188,548,422,'VECTOR SPACE',`${M(R`p(t)=p_{k-1}+\psi_k^c(t)(p_k-p_{k-1})`)}For linear interpolation, one cumulative basis function blends the difference between two controls.<br><br>The cumulative basis starts at zero, rises locally, then remains at one.<br><br>${M(R`\psi_k^c(t)=\sum_{\ell=k}^{K}\psi_\ell(t)`)}`,{fill:C.soft,size:17}),
 ...panel('cum-group',644,188,564,422,'LIE GROUP',`${M(R`T(t)=\operatorname{Exp}\!\left(\psi_k^c(t)\operatorname{Log}(T_kT_{k-1}^{-1})\right)T_{k-1}`)}${M(R`T(t)=\left(T_kT_{k-1}^{-1}\right)^{\alpha_k(t)}T_{k-1}`)}The relative pose is mapped to the algebra, scaled, and mapped back.<br><br><b>Group multiplication replaces addition.</b>`,{fill:C.warm,accent:C.coral,size:17})
],'Present the linear case before mentioning higher-order splines. The relative transform between controls is converted to a tangent vector, scaled by the cumulative basis, then composed with the first pose. Left and right formulations are both possible.','SH2 · §2.2.4.1 · EQS. 2.53–2.62'));

slides.push(slide('gp-lie','3 · Gaussian processes on Lie groups','A pose GP is Euclidean only between neighboring controls.','Define a local tangent trajectory, apply the SDE there, then return to the global group.',[
 box('gpl-diagram',72,190,682,415,C.panel,C.rule),text('gpl-label',96,209,634,22,'LOCAL COORDINATE BETWEEN CONTROL POSES',{fontFamily:mono,fontSize:10.5,fontWeight:800,color:C.coral}),
 circle('gpl-t0',155,420,54,C.soft,C.teal),circle('gpl-t1',607,277,54,C.warm,C.coral),text('gpl-t0-label',155,438,54,20,I(R`T_k`),{fontSize:16,align:'center'}),text('gpl-t1-label',607,295,54,20,I(R`T_{k+1}`),{fontSize:16,align:'center'}),
 line('gpl-curve-a',208,423,140,-8,C.rule,5),line('gpl-curve-b',348,415,126,-52,C.teal,6),line('gpl-curve-c',474,363,133,-59,C.teal,6),circle('gpl-query-dot',452,351,22,C.coral,C.panel,{strokeWidth:2}),text('gpl-query-label',427,319,110,24,I(R`T(t)`),{fontSize:17,align:'center'}),
 text('gpl-zero',116,493,202,34,I(R`\xi_k(t_k)=0`),{fontSize:17,align:'center'}),text('gpl-end',459,205,244,54,I(R`\xi_k(t_{k+1})=\operatorname{Log}(T_{k+1}T_k^{-1})`),{fontSize:16,align:'center'}),
 ...panel('gpl-model',778,190,430,415,'LOCAL RANDOM WALK',`${M(R`\dot\xi_k(t)=w(t)`)}${M(R`\xi_k(t)=\operatorname{Log}(T(t)T_k^{-1})`)}The GP lives in ${I(R`\xi_k`)}, a vector coordinate valid in the interval.<br><br>For a random-walk prior, GP interpolation becomes the same group interpolation as the linear cumulative spline.<br><br><b>Difference:</b> the GP adds motion-prior factors that regularize the controls.`,{fill:C.soft,size:16})
],'The local variable is zero at the first control and equals the Log of the relative pose at the second. The SDE is applied to this vector-valued local variable. For the random-walk prior, the interpolation matches linear group interpolation.','SH2 · §2.2.4.2 · FIG. 2.7'));

slides.push(slide('three-clocks','3 · Continuous-time inference','Measurement, estimation, and query times can all differ.','This decoupling is the practical payoff of continuous-time state representations.',[
 ...[['MEASURE',C.coral,'every point / row / IMU sample'],['ESTIMATE',C.teal,'a smaller set of control states'],['QUERY',C.amber,'any downstream timestamp']].flatMap(([label,color,copy],row)=>[
 text('clock-label-'+row,72,214+row*113,150,26,label,{fontFamily:mono,fontSize:11,fontWeight:800,color}),line('clock-axis-'+row,240,225+row*113,916,0,C.rule,3),text('clock-copy-'+row,910,198+row*113,246,44,copy,{fontSize:13,color:C.muted,align:'right'}),
 ...Array.from({length:row===0?10:row===1?4:3},(_,i)=>{const count=row===0?10:row===1?4:3;const x=260+i*(620/(count-1));const offset=row===0?(i%3)*9:row===2?i*47:0;return circle('clock-dot-'+row+'-'+i,x+offset,216+row*113,row===1?26:14,row===1?C.soft:color,row===1?C.teal:C.panel,{strokeWidth:row===1?2:1});})
 ]),
 ...callout('clock-lidar',72,558,536,48,'Spinning lidar: interpolate one pose per point timestamp.',{fill:C.soft,stroke:C.teal,size:13}),...callout('clock-camera',632,558,576,48,'Rolling shutter: interpolate one pose per image row timestamp.',{fill:C.cool,stroke:C.blue,size:13})
],'Use the three horizontal rows to revisit the central practical point. Continuous-time estimation does not mean estimating an infinite number of variables; it means a finite representation that can be evaluated at arbitrary times.','SH2 · §2.2 · PRACTICAL CONSEQUENCES'));

slides.push(slide('compare','3 · Choosing a representation','Splines specify basis functions. GPs specify a motion prior.','Both can remain sparse, interpolate between controls, and operate on Lie groups.',[
 nativeTable('compare-table',72,190,1136,355,['QUESTION','SPLINE','GAUSSIAN PROCESS'],[
  ['What is chosen?','Basis family and control layout','SDE / kernel and hyperparameters'],
  ['Where does smoothness come from?','Basis continuity and knot placement','Probabilistic motion prior'],
  ['Why is the graph sparse?','Compact support of the basis','Markov state gives sparse precision'],
  ['How are poses handled?','Cumulative group composition','Local tangent-space GP'],
  ['How is a query evaluated?','Active basis functions','Interpolation from bracketing controls']
 ],{columns:[.95,1.35,1.35],fontSize:15,padY:9}),
 ...callout('compare-bottom',72,565,1136,45,'The choice is not “smooth versus sparse.” Both can be smooth and sparse; the real choice is how smoothness is encoded and regularized.',{fill:C.warm,stroke:C.coral,size:14,align:'center'})
],'This table is a synthesis of the chapter. Splines can also be regularized, and higher-order GP priors can produce spline-like interpolation. The distinction here is the default modeling viewpoint, not an absolute boundary.','SH2 · §2.2.1–§2.2.4'));

slides.push(slide('implementation','4 · Implementation checklist','Make the conventions explicit before trusting a result.','Most manifold bugs are not solver bugs; they are silent convention mismatches.',[
 ...[['STATE SPACE','Name the group, its degrees of freedom, and the chosen storage representation.',C.soft,C.teal],['PERTURBATION','State left or right update, coordinate frame, Exp / Log convention, and variable ordering.',C.warm,C.coral],['DERIVATIVES','Verify analytic or automatic Jacobians against finite differences in the same tangent convention.',C.cool,C.blue],['TIME MODEL','Separate measurement, control, and query times; document spline order or GP motion prior.',C.panel,C.amber],['SPARSITY','Inspect active bases or the precision pattern—not only the dense covariance.',C.soft,C.teal],['VALIDATION','Check group constraints, residual decrease, interpolation limits, and uncertainty behavior.',C.warm,C.coral]].flatMap(([label,copy,fill,accent],i)=>panel('check-'+i,72+(i%3)*382,186+Math.floor(i/3)*212,358,190,label,copy,{fill,accent,size:15.5,lineHeight:1.4})),
],'Treat this as the handoff slide for an implementation. A unit test should check that every update remains on the group, Jacobians use the declared convention, and time interpolation agrees at control boundaries.','SH2 · IMPLEMENTATION SYNTHESIS'));

slides.push(slide('equations','4 · Equation sheet','Six equations carry the chapter.','Use this as a compact reference while implementing or reviewing a continuous-time SLAM model.',[
 ...[
  ['GROUP UPDATE',M(R`T^+=T\operatorname{Exp}(\xi)`)],
  ['GROUP DIFFERENCE',M(R`T\ominus T^0=\operatorname{Log}((T^0)^{-1}T)`)],
  ['ADJOINT',M(R`T\operatorname{Exp}(\xi)=\operatorname{Exp}(\operatorname{Ad}(T)\xi)T`)],
  ['SPLINE',M(R`p(t)=\sum_k\Psi_k(t)c_k`)],
  ['SDE PRIOR',M(R`\dot x(t)=Ax(t)+Lw(t)`)],
  ['GROUP INTERPOLATION',M(R`T(t)=(T_kT_{k-1}^{-1})^{\alpha_k(t)}T_{k-1}`)]
 ].flatMap(([label,formula],i)=>panel('eq-'+i,72+(i%2)*578,184+Math.floor(i/2)*142,558,124,label,formula,{fill:i%2?C.panel:C.soft,size:18,body:{align:'center',valign:'middle'}})),
],'Read the sheet from top to bottom: update and difference on a group, move perturbations with the adjoint, define a vector-space spline, define an SDE-based GP, then interpolate between group-valued controls.','SH2 · EQUATIONS 2.24–2.25 · 2.31 · 2.36 · 2.46 · 2.74'));

slides.push(slide('summary','5 · Takeaways','Two localities make advanced states tractable.','Geometry is local in tangent coordinates; time is local through compact support or Markov structure.',[
 ...panel('summary-geometry',72,188,548,330,'LOCALITY IN GEOMETRY',`${M(R`\text{solve in }T_\chi\mathcal M\quad\longrightarrow\quad\text{retract to }\mathcal M`)}<b>Manifold state</b><br>Keep rotations and poses valid by optimizing tangent increments.<br><br><b>Uncertainty</b><br>Represent compact uncertainty in the same local coordinates.<br><br><b>Conventions</b><br>Track side, frame, and adjoint explicitly.`,{fill:C.soft,size:17}),
 ...panel('summary-time',644,188,564,330,'LOCALITY IN TIME',`${M(R`\text{query at }t\quad\longleftarrow\quad\text{nearby controls}`)}<b>Splines</b><br>Compact basis support limits active coefficients.<br><br><b>Gaussian processes</b><br>A Markov motion prior yields sparse precision.<br><br><b>Sensor fusion</b><br>Measurements, estimation states, and queries use their own clocks.`,{fill:C.cool,accent:C.blue,size:17}),
 ...callout('summary-line',72,548,1136,58,'The representation is not a wrapper around the optimizer. It is the structure that makes the optimization valid, sparse, and useful.',{fill:C.warm,stroke:C.coral,size:16,align:'center'})
],'Close by naming the two kinds of locality. Tangent coordinates give geometric locality. Compact-support bases and Markov priors give temporal locality. Together they preserve valid states and sparse inference.','SH2 · CHAPTER SYNTHESIS'));

slides.push(slide('references','Sources and scope','Source chapter and teaching-model boundary','The deck is a concise interpretation of the supplied chapter, with original browser demonstrations.',[
 ...panel('ref-main',72,188,724,422,'PRIMARY SOURCE',`<b>Timothy Barfoot, Frank Dellaert, Michael Kaess, and Jose Luis Blanco-Claraco.</b><br><br>“Advanced State Variable Representations,” Chapter 2 in <i>SLAM Handbook: From Localization and Mapping to Spatial Intelligence</i>, Cambridge University Press, 2026.<br><br><a href="${SOURCE_URL}">Official public-release repository ↗</a><br><br>Topics used here: optimization on manifolds, Lie-group uncertainty and Jacobians, splines, kernel methods, SDE-derived Gaussian processes, and continuous-time trajectories on Lie groups.`,{fill:C.soft,size:16.5}),
 ...panel('ref-scope',820,188,388,422,'WHAT IS ORIGINAL HERE',`The rotation-validity, spline-support, and sparse-GP labs are deterministic teaching models authored for this deck.<br><br>They reproduce no paper dataset and claim no timing benchmark.<br><br>The manifold lab contrasts exact composition with a deliberately crude first-order matrix accumulation.<br><br>The GP lab is scalar; the chapter’s pose-valued construction is explained statically.`,{fill:C.warm,accent:C.coral,size:15.5}),
],'Credit the chapter authors. The official public-release repository provides the chapter citation and current handbook release. Make the teaching-model boundary explicit: the demos illustrate mechanisms, not experimental results from the book.','SH2 · SOURCE AND SCOPE'));

export const deck={format:'bento/slides',version:1,docId:'advanced-state-variable-representations-bento',title:'Advanced State Variable Representations',readonly:true,meta:{author:'Bai Liping',subject:'Manifold-valued states and continuous-time trajectories for SLAM',company:'bailiping.com'},size:{width:1280,height:720},theme:{background:C.paper,color:C.ink,accent:C.teal,fontFamily:sans},slides};

const live=[
 ['tangent-space','manifold-live','manifold','Rotation retraction laboratory'],
 ['splines','spline-live','spline','Spline local-support laboratory'],
 ['gp-prior','gp-live','gp','Sparse Gaussian-process laboratory']
];
export const inlineLiveMap=live.map(([introSlide,slideId,demo,title])=>({introSlide,slide:slideId,slideIndex:slides.findIndex(slide=>slide.id===slideId),inline:true,layout:'region',bounds:{x:72,y:180,width:1136,height:475},src:`./live/?demo=${demo}&embed=region`,source:`./live/?demo=${demo}`,title,sandbox:'allow-scripts',hideSource:true,readyMessage:true,unloadWhenHidden:true}));
