import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { deck, inlineLiveMap } from './bento-deck.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const template = await readFile(resolve(here, '../kalman-filter-derivations/index.html'), 'utf8');
const safe = value => JSON.stringify(value, null, 1).replaceAll('<', '\\u003c');

if (deck.format !== 'bento/slides' || deck.size.width !== 1280 || deck.size.height !== 720) throw new Error('Invalid Bento document envelope');
const slideIds = new Set(deck.slides.map(slide => slide.id));
if (slideIds.size !== deck.slides.length) throw new Error('Duplicate slide id');
for (const [index, slide] of deck.slides.entries()) {
  if (!slide.notes) throw new Error(`Missing notes: ${slide.id}`);
  if (slide.stateOf) throw new Error(`Live teaching slides must be regular slides: ${slide.id}`);
  const elementIds = new Set();
  for (const element of slide.elements) {
    if (elementIds.has(element.id)) throw new Error(`Duplicate element ${slide.id}/${element.id}`);
    elementIds.add(element.id);
    if (element.x < -0.01 || element.y < -0.01 || element.x + element.w > 1280.01 || element.y + element.h > 720.01) throw new Error(`Out of slide: ${slide.id}/${element.id}`);
  }
  slide.elements.push({ id: 'slide-number', type: 'text', x: 940, y: 684, w: 82, h: 20, html: `${String(index + 1).padStart(2, '0')} / ${deck.slides.length}`, fontSize: 10, fontFamily: 'monospace', color: '#60747A', align: 'center' });
}

for (const entry of inlineLiveMap) {
  const liveIndex = deck.slides.findIndex(slide => slide.id === entry.slide);
  const introIndex = deck.slides.findIndex(slide => slide.id === entry.introSlide);
  if (liveIndex < 0 || introIndex !== liveIndex - 1) throw new Error(`Live slide must immediately follow its intro: ${entry.slide}`);
  if (entry.slideIndex !== liveIndex) throw new Error(`Incorrect live slide index: ${entry.slide}`);
  const marker = deck.slides[liveIndex].elements.find(element => element.id === 'live-demo-mount');
  if (!marker) throw new Error(`Missing live-demo-mount: ${entry.slide}`);
  const bounds = entry.bounds;
  if (marker.x !== bounds.x || marker.y !== bounds.y || marker.w !== bounds.width || marker.h !== bounds.height) throw new Error(`Live marker/bounds mismatch: ${entry.slide}`);
}

const authored = JSON.stringify(deck);
if (/<(sup|sub)\b/i.test(authored) || /[⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉]/.test(authored)) throw new Error('Hand-built mathematical superscript or subscript found');

const documentPattern = /(<script type="application\/bento\+json" id="bento-doc">\s*)[\s\S]*?(\s*<\/script>)/;
if (!documentPattern.test(template)) throw new Error('Bento template document not found');
let html = template.replace(documentPattern, (_, before, after) => before + safe(deck) + after);
const mapPattern = /<script type="application\/json" id="bento-inline-live-map">[\s\S]*?<\/script>/;
if (!mapPattern.test(html)) throw new Error('Bento inline-live map not found');
html = html.replace(mapPattern, `<script type="application/json" id="bento-inline-live-map">\n${safe(inlineLiveMap)}\n</script>`);

const routes = Object.fromEntries(deck.slides.map((slide, index) => [slide.id, index]));
const routeScript = `<script>(()=>{const routes=${JSON.stringify(routes)};function routeToSlide(){let route;try{route=decodeURIComponent(location.hash.replace(/^#\\/?/,''));}catch{return;}if(route&&!/^\\d+$/.test(route)&&Number.isInteger(routes[route]))history.replaceState(null,'',location.pathname+location.search+'#/'+routes[route]);}addEventListener('hashchange',routeToSlide);routeToSlide();})();</script>`;
let routeReplaced = false;
html = html.replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/g, (full, attributes, body) => {
  if (!attributes.trim() && body.includes('const routes =') && body.includes('routeToSlide')) { routeReplaced = true; return routeScript; }
  return full;
});
if (!routeReplaced) throw new Error('Template route mapper not found');

html = html.replace(/<title>[\s\S]*?<\/title>/, '<title>Advanced State Variable Representations | Bai Liping</title>');
html = html.replace(/<meta name="description"[^>]*>/, `<meta name="description" content="${deck.slides.length} interactive Bento slides on manifold-valued states, Lie-group optimization, splines, and sparse continuous-time Gaussian processes, with three live teaching labs." />`);
html = html.replace(/<link rel="canonical"[^>]*>/, '<link rel="canonical" href="https://bailiping.com/advanced-state-representations/" />');
html = html.replace(/<!-- Generated by kalman-filter-derivations[^>]*-->/, '<!-- Generated by advanced-state-representations/build.mjs. Edit bento-deck.mjs, then rebuild. -->');
html = html.replace('</head>', `<style id="asr-math-layout">
.bento-slide .math-display{height:auto!important;min-height:0;margin:.48em 0;}
.bento-slide .bento-text-inner>.math-display:first-child{margin-top:.08em;}
.bento-slide .bento-text-inner>.math-display:last-child{margin-bottom:.08em;}
</style>\n</head>`);
if (!html.includes('tex-svg-full.js') || !html.includes('mathjax-dynamic.js') || !html.includes('bento-inline-live.js')) throw new Error('Required shared runtime missing');

await writeFile(resolve(here, 'index.html'), html);
console.log(`Built ${deck.slides.length} advanced-state slides and ${inlineLiveMap.length} live labs (${html.length} characters).`);
console.log(`Slide routes: ${deck.slides.map(slide => slide.id).join(', ')}`);
