// Canonical teaching content. All diagrams are generated from lesson-model.js.
import Figures from './lesson-figures.js';
const R=String.raw;
const M=s=>`<span class="math-tex math-display">\\[${s}\\]</span>`;
const I=s=>`<span class="math-tex math-inline">\\(${s}\\)</span>`;
const P=s=>`<p>${s}</p>`;
const C={paper:'#F5F3ED',panel:'#FFFDFA',ink:'#182D33',muted:'#60747A',rule:'#D6DEDC',teal:'#16736E',soft:'#E4F0ED',coral:'#C2573F',warm:'#F7E8E1',blue:'#3F6F91',cool:'#E5EDF4'};
const sans="Inter,Arial,sans-serif",serif="Georgia,'Times New Roman',serif",mono="Consolas,monospace";
export const references={
 H:{label:'SLAM Handbook · Ch. 2',url:'https://github.com/SLAM-Handbook-contributors/slam-handbook-public-release',full:'T. Barfoot, F. Dellaert, M. Kaess, and J. L. Blanco-Claraco. Advanced State Variable Representations. SLAM Handbook, Chapter 2. Public-release citation: Cambridge University Press, 2026.'},
 L:{label:'Solà et al. · Micro Lie theory',url:'https://arxiv.org/abs/1812.01537',full:'J. Solà, J. Deray, and D. Atchuthan. A micro Lie theory for state estimation in robotics. arXiv:1812.01537, 2018.'},
 S:{label:'SciPy · BSpline definition',url:'https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.BSpline.html',full:'SciPy documentation. BSpline: Cox–de Boor recursion, knot conventions, and partition of unity.'},
 G:{label:'Barfoot et al. · RSS 2014',url:'https://www.roboticsproceedings.org/rss10/p01.html',full:'T. D. Barfoot, C. H. Tong, and S. Särkkä. Batch Continuous-Time Trajectory Estimation as Exactly Sparse Gaussian Process Regression. Robotics: Science and Systems, 2014.'},
 B:{label:'Sommer et al. · Lie B-splines',url:'https://arxiv.org/abs/1911.08860',full:'C. Sommer, V. Usenko, D. Schubert, N. Demmel, and D. Cremers. Efficient Derivative Computation for Cumulative B-Splines on Lie Groups. arXiv:1911.08860; CVPR 2020.'},
 D:{label:'Dong et al. · Lie-group GPs',url:'https://arxiv.org/abs/1705.06020',full:'J. Dong, B. Boots, and F. Dellaert. Sparse Gaussian Processes for Continuous-Time Trajectory Estimation on Matrix Lie Groups. Technical report, arXiv:1705.06020, 2017.'}
};
const slides=[],labs=[];
function text(id,x,y,w,h,html,o={}){return {id,type:'text',x,y,w,h,rotation:0,opacity:1,html,fontSize:18,fontFamily:sans,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.4,...o};}
function box(id,x,y,w,h,fill=C.panel){return {id,type:'shape',shape:'rect',x,y,w,h,rotation:0,opacity:1,fill,stroke:C.rule,strokeWidth:1,radius:12};}
function panel(id,x,y,w,h,label,body,fill=C.soft,size=18){return [box(id+'-box',x,y,w,h,fill),text(id+'-label',x+22,y+18,w-44,26,label,{fontFamily:mono,fontSize:12,fontWeight:700,color:C.teal}),text(id+'-body',x+22,y+58,w-44,h-76,body,{fontSize:size})];}
function slide(id,section,title,subtitle,content,notes,sources=['H']){const refs=sources.map(k=>references[k]);const s={id,background:C.paper,transition:'none',notes,sources,lessonTitle:title,lessonSubtitle:subtitle,elements:[text('eyebrow',72,32,1136,24,section.toUpperCase(),{fontSize:12,fontFamily:mono,color:C.coral,fontWeight:700}),text('heading',72,70,1136,53,title,{fontFamily:serif,fontSize:35,fontWeight:700,lineHeight:1.1}),text('subtitle',72,131,1136,42,subtitle,{fontSize:16,color:C.muted}),...content,box('footer-rule',72,669,1136,1,C.rule),text('footer-home',72,684,270,20,'BAI LIPING · RANDOM THOUGHTS',{fontSize:10,fontFamily:mono,color:C.muted,link:'https://bailiping.com/'}),text('footer-source',330,684,530,20,refs.map(r=>r.label).join(' · '),{fontSize:10,color:C.muted,align:'center',link:refs[0].url}),text('footer-notes',1020,684,94,20,'READ NOTES',{fontSize:10,color:C.teal,link:'./study.html#'+id}),text('footer-index',1120,684,88,20,'CONTENTS',{fontSize:10,color:C.teal,align:'right',link:'overview'})]};slides.push(s);return s;}
function pair(id,section,title,sub,a,A,b,B,notes,sources=['H'],size=18){return slide(id,section,title,sub,[...panel('left',72,190,548,452,a,A,C.soft,size),...panel('right',644,190,564,452,b,B,C.panel,size)],notes,sources);}
function cards(id,section,title,sub,items,notes,sources=['H']){return slide(id,section,title,sub,items.flatMap(([a,A],i)=>panel('card'+i,72+i*382,190,358,452,a,A,i%2?C.panel:C.soft,18)),notes,sources);}
function live(id,intro,demo,title,sub,instructions,notes,sources){const v=Figures.render(demo);const s=slide(id,'Worked laboratory · '+(labs.length+1)+' / 7',title,sub,[box('live-background',72,180,1136,475),...panel('guide',72,180,268,475,'TRY → OBSERVE → EXPLAIN',P(instructions)+P('<b>Default-state snapshot</b>')+P(v.caption),C.soft,15),{id:'model-figure',type:'image',x:352,y:190,w:844,h:380,src:'./figures/'+demo+'.svg',fit:'contain',rotation:0,opacity:1,alt:v.title},...v.metrics.flatMap(([label,value],i)=>[box('metric'+i,352+i*(844/v.metrics.length),574,844/v.metrics.length-8,67,C.paper),text('value'+i,362+i*(844/v.metrics.length),583,844/v.metrics.length-28,24,String(value),{fontSize:20,fontWeight:700,color:C.teal}),text('metric-label'+i,362+i*(844/v.metrics.length),610,844/v.metrics.length-28,27,label,{fontSize:11,lineHeight:1.2})]),{...box('live-demo-mount',72,180,1136,475),opacity:0}],notes,sources);labs.push({introSlide:intro,slide:id,demo,title});return s;}

cards('overview','A guided route through advanced state representations','Valid states. Meaningful motion. Understandable inference.','Two different modeling choices: where the state lives, and how it changes with time.',[
 ['01 · GEOMETRY',P('<b>How do we change a pose without breaking it?</b>')+P('Start with a circle. Build Exp and Log, a working optimizer, and a frame-consistent adjoint.')+P('<a href="#/tangent-space">Begin with geometry →</a>')],
 ['02 · TIME',P('<b>How do we represent motion between measurements?</b>')+P('Compare local spline bases with stochastic motion priors. Inspect smoothness and uncertainty separately.')+P('<a href="#/continuous-time">Begin with time →</a>')],
 ['03 · PRACTICE',P('<b>Can the equations explain what the demo does?</b>')+P('Seven embedded laboratories, numeric checks, worked notes, and equation sheets.')+P('<a href="./study.html">Read the full study version →</a>')]
],'This lesson expands the original overview into a sequence of small derivations. Read the geometry section first unless you already know right perturbations on SE(3). Read the time section second. The laboratory controls are embedded in the slides; no separate launch is needed. Read Notes opens a scrollable companion containing every equation, the default diagrams, and these explanations. All demonstrations are deliberately small, deterministic teaching examples, not performance benchmarks.');

pair('why-representation','0 · Motivation','Two questions that should not be mixed together.','Geometry is not a time model. A time model does not automatically preserve geometry.',
 'WHAT VALUES ARE ALLOWED?',M(R`R^{\mathsf T}R=I,\qquad\det R=1`)+P('A spatial rotation has <b>nine stored matrix entries but three degrees of freedom</b>. Arbitrary entrywise increments need not be rotations.')+P('The representation must keep the optimizer inside the valid state space.'),
 'WHAT HAPPENS BETWEEN SAMPLES?',M(R`z_i=h_i(T(t_i),\mathcal M)+\epsilon_i`)+P('A sensor measurement has its own time '+I(R`t_i`)+'. A trajectory model supplies the pose there; '+I(R`\mathcal M`)+ ' denotes the map.')+P('Its temporal assumptions determine interpolation, derivatives, and uncertainty.'),
 'A robot can use a perfectly valid SO(3) rotation at every stored timestamp and still have an inappropriate interpolation model between timestamps. Conversely, a smooth polynomial in matrix entries can leave the rotation group. We therefore separate geometric representation from temporal representation, then combine them near the end. The displayed measurement function is a generic conceptual model, not a claim that every sensor has the same residual.');

pair('notation','0 · Notation before use','Fix the convention once, then keep it everywhere.','All vectors are columns. Angles inside the equations are in radians.',
 'POSE AND LOCAL INCREMENT',M(R`p_W=R_{WB}p_B+t_{WB}`)+M(R`T=T_{WB}=\begin{bmatrix}R&t\\0&1\end{bmatrix}`)+M(R`\xi=\begin{bmatrix}\rho\\\phi\end{bmatrix}\in\mathbb R^6,\qquad T^+=T\operatorname{Exp}(\xi)`)+P('Translation comes first. A <b>right increment</b> uses body/local coordinates.'),
 'UNCERTAINTY AND TIME',P(I(R`\Sigma`)+': covariance of local state coordinates.<br>'+I(R`Q_c`)+': continuous-time process spectral density.<br>'+I(R`Q_k`)+': discrete process covariance.<br>'+I(R`R_i`)+': measurement covariance (not a rotation here).')+P(I(R`\|e\|_W^2=e^{\mathsf T}We`)+': weighted squared norm.')+P('Spline degree '+I(R`d`)+', order '+I(R`d+1`)+'. Control coefficients and knots are different objects.'),
 'The pose maps coordinates from body B into world W. Thus multiplying an increment on the right means that the increment is expressed relative to the current body frame. Multiplying on the left means world-frame coordinates, after the proper adjoint conversion. A translation-first twist is required for the particular SE(3) wedge and adjoint matrices later in the lesson. The same letter R is commonly used for rotations and measurement covariances, so each equation states which one it means. Noise spectral density and finite-interval covariance have different units.',['L','G']);

cards('groups','1 · Geometry','A group is a set of valid states with composition.','Matrix size is a storage choice; dimension is the number of independent local coordinates.',[
 ['SO(2) · ONE FREEDOM',M(R`R(\theta)=\begin{bmatrix}\cos\theta&-\sin\theta\\\sin\theta&\cos\theta\end{bmatrix}`)+P('One angle determines the entire matrix.')+P(I(R`R(a)R(b)=R(a+b)`))],
 ['SO(3) · THREE FREEDOMS',M(R`SO(3)=\{R:R^{\mathsf T}R=I,\det R=1\}`)+P('Rotation composition is generally <b>not commutative</b>.')+P('A unit quaternion stores four constrained numbers for the same three freedoms.')],
 ['SE(3) · SIX FREEDOMS',M(R`T=\begin{bmatrix}R&t\\0&1\end{bmatrix}`)+M(R`T_1T_2=\begin{bmatrix}R_1R_2&R_1t_2+t_1\\0&1\end{bmatrix}`)+P('The translation of the second motion must first be rotated.')]
],'SO means special orthogonal: orthogonality plus determinant +1 excludes reflections. SE means special Euclidean: rotations combined with translations. The identity, inverse, and product remain in the same set. SO(2) is the best entry point because its first column lies exactly on a unit circle. That drawing does not identify SO(3) with a sphere. In 3D the order of finite rotations matters.',['L']);

pair('tangent-space','1 · Geometry','A tangent must touch the state it describes.','Use SO(2) to make the geometry exact rather than suggestive.',
 'THE VALID STATES',M(R`p(\theta)=\begin{bmatrix}\cos\theta\\\sin\theta\end{bmatrix}`)+M(R`v(\theta)=\frac{dp}{d\theta}=\begin{bmatrix}-\sin\theta\\\cos\theta\end{bmatrix}`)+P('The tangent direction is perpendicular to the radius: '+I(R`p^{\mathsf T}v=0`)+'.'),
 'A VECTOR STEP IS NOT THE NEW STATE',M(R`\|p+\delta v\|^2=1+\delta^2`)+P('For a nonzero step, the straight endpoint is <b>off the circle</b>.')+M(R`p^+=p(\theta+\delta),\qquad\|p^+\|=1`)+P('The next figure draws the actual tangent through the actual current point.'),
 'Differentiate the two coordinates of p with respect to theta. Their dot product is cos(theta)(-sin(theta)) + sin(theta)cos(theta) = 0. Since both p and v have unit norm, expanding the squared norm of p + delta v gives 1 + delta squared. This proves exactly why the tangent step is only a local approximation. The circle is an exact representation of SO(2) through the first column of its rotation matrix. A generic manifold may use a retraction other than the Lie exponential.',['L']);
live('tangent-live','tangent-space','tangent','See the difference between a tangent step and a group update.','The tangent line, current point, and updated point are computed—not hand-positioned.',
 'Change the starting angle. Then increase the increment. Check which endpoint stays on the blue circle.',
 'At the default increment 0.7 rad, the linear endpoint has norm sqrt(1.49), approximately 1.221, while the exponential endpoint has norm one. At zero increment the two endpoints coincide. Changing the current angle moves the tangent line along with the point. The two operations agree to first order in the increment, but not for a finite step.',['L']);

pair('exp-log','1 · Geometry','Wedge changes representation. Exp changes the state space.','Do not treat all four maps as interchangeable.',
 'VECTOR → ALGEBRA → GROUP',M(R`\phi^\wedge=[\phi]_\times=\begin{bmatrix}0&-\phi_3&\phi_2\\\phi_3&0&-\phi_1\\-\phi_2&\phi_1&0\end{bmatrix}`)+P(I(R`[\phi]_\times a=\phi\times a`)+'. The wedge map makes a skew matrix; vee reverses this representation.')+M(R`\operatorname{Exp}(\phi)=\exp(\phi^\wedge)`),
 'GROUP → LOCAL VECTOR',M(R`\operatorname{Log}(R)=(\log R)^\vee`)+M(R`R\ominus\bar R=\operatorname{Log}(\bar R^{\mathsf T}R)`)+P('Log requires a branch. Exponential coordinates are <b>not globally unique</b>.')+P('For SO(3), the principal rotation angle is at most '+I(R`\pi`)+'. The axis is ambiguous at '+I(R`\pi`)+'.'),
 'Lowercase exp and log act on matrices. Capital Exp and Log include wedge and vee so their arguments or outputs are minimal vectors. The identity log branch works near the current estimate, not as a globally unique coordinate chart for every possible rotation. The local difference matches the right-update convention: bar R Exp(delta) = R implies delta = Log(bar R transpose R), within a consistent branch.',['L']);

pair('so3-exp','1 · Geometry','Rodrigues’ formula constructs a valid 3D rotation.','A closed form replaces an infinite matrix-exponential series.',
 'ROTATION VECTOR',M(R`\alpha=\|\phi\|,\qquad A=\phi^\wedge`)+M(R`\operatorname{Exp}(\phi)=I+\frac{\sin\alpha}{\alpha}A+\frac{1-\cos\alpha}{\alpha^2}A^2`)+P('Direction gives the rotation axis; norm gives its angle.'),
 'THE SMALL-ANGLE LIMIT MATTERS',M(R`\frac{\sin\alpha}{\alpha}\to1,\qquad\frac{1-\cos\alpha}{\alpha^2}\to\frac12`)+P('Near zero, use stable series rather than subtracting nearly equal numbers.')+P('The finite first-order shortcut '+I(R`I+A`)+' is generally not orthogonal.')+P('Exact algebraic identities still have ordinary floating-point error in a numerical implementation.'),
 'The skew matrix satisfies A cubed = -alpha squared A, which reduces the exponential series to a combination of I, A, and A squared. This yields Rodrigues’ formula. The limiting values define the formula continuously at zero. The tests check orthogonality and the SE(3) constructions at small, moderate, and near-pi angles; they do not confuse exact mathematical preservation with literally zero floating-point error.',['L']);

pair('se3-exp','1 · Geometry','An SE(3) exponential does not simply copy the translation.','Rotation and translation are coupled in a finite rigid-body increment.',
 'TRANSLATION-FIRST TWIST',M(R`\xi=\begin{bmatrix}\rho\\\phi\end{bmatrix},\quad\xi^\wedge=\begin{bmatrix}\phi^\wedge&\rho\\0&0\end{bmatrix}`)+M(R`\operatorname{Exp}(\xi)=\begin{bmatrix}\operatorname{Exp}(\phi)&J_l(\phi)\rho\\0&1\end{bmatrix}`)+P('The resulting translation is '+I(R`J_l(\phi)\rho`)+', not generally '+I(R`\rho`)+'.'),
 'THE LEFT JACOBIAN OF SO(3)',M(R`\begin{aligned}J_l(\phi)=I&+\frac{1-\cos\alpha}{\alpha^2}\phi^\wedge\\&+\frac{\alpha-\sin\alpha}{\alpha^3}(\phi^\wedge)^2\end{aligned}`)+P('Here '+I(R`\alpha=\|\phi\|`)+'. At zero, '+I(R`J_l(0)=I`)+'.')+P('The name “left Jacobian” describes this differential map. It does not force the pose update to be on the left.'),
 'Integrating a constant body twist while the body rotates produces a curved world-frame translation. The matrix exponential encodes that coupling. Pure translation, phi = 0, is the special case where the translational coordinate equals the resulting displacement. The appearance of J_l in the SE(3) closed form is compatible with our right composition T Exp(xi). Which side the update uses and which differential map occurs inside the closed form are separate concepts.',['L']);

pair('manifold-intro','1 · A falsifiable check','A plausible arrow is not enough to validate a rotation.','Check both orthogonality and determinant after repeated updates.',
 'EXACT PLANAR COMPOSITION',M(R`J=\begin{bmatrix}0&-1\\1&0\end{bmatrix},\quad R_n=\exp(n\delta J)`)+M(R`R_n^{\mathsf T}R_n=I,\qquad\det R_n=1`)+P('This is an exact group identity.'),
 'FIRST-ORDER MATRIX ACCUMULATION',M(R`\widetilde R_n=(I+\delta J)^n`)+M(R`\widetilde R_n^{\mathsf T}\widetilde R_n=(1+\delta^2)^n I`)+P('Length scales by '+I(R`(1+\delta^2)^{n/2}`)+'. The unwrapped angle is '+I(R`n\arctan\delta`)+', not '+I(R`n\delta`)+'.'),
 'One shortcut matrix has orthogonal but non-unit columns, each of length sqrt(1 + delta squared). Its determinant is 1 + delta squared. Repeating it multiplies the scale each time. Normalizing the result could remove scale in this special planar example, but it would not remove the accumulated angular bias. The next lab visualizes both effects and distinguishes approximation error from machine precision.',['L']);
live('manifold-live','manifold-intro','manifold','Repeat the update. Inspect the constraints.','The two colored coordinate frames use the same physical plot scale.',
 'Increase the number of updates. Then reduce the increment and compare determinant, orthogonality error, and angle bias.',
 'The exact and shortcut trajectories start at the identity. Both basis columns are drawn, so the diagram can reveal scale and non-orthogonality rather than only a heading. For this particular Euler shortcut the columns remain perpendicular but become too long; the Frobenius orthogonality error measures this failure of unit length. The observed behavior is derived on the previous slide.',['L']);

pair('optimize','1 · From representation to an actual estimator','Linearize the residual in the coordinates you will update.','Worked example: known corresponding body points and world measurements.',
 'RIGHT-PERTURBATION JACOBIAN',M(R`e_i(T)=Ra_i+t-z_i`)+M(R`J_i=\begin{bmatrix}R&-R[a_i]_\times\end{bmatrix}`)+P('This follows from '+I(R`T^+=T\operatorname{Exp}(\xi)`)+'.')+P('In 2D, the last column is '+I(R`RJ a_i`)+', where '+I(R`J=\left[\begin{smallmatrix}0&-1\\1&0\end{smallmatrix}\right]`)+'.'),
 'SOLVE, THEN COMPOSE',M(R`(J^{\mathsf T}WJ)\xi=-J^{\mathsf T}We`)+M(R`T^+=T\operatorname{Exp}(\beta\xi)`)+P('Stack residuals and Jacobians. '+I(R`W`)+' is the precision; '+I(R`0<\beta\le1`)+' is a line-search step.')+P('The demo uses equal weights, a tiny diagonal damping term, and backtracking. Correspondences do not change.'),
 'Expand Exp(xi) to first order inside the right update. A body point becomes R(a_i + rho + phi cross a_i) + t. Because phi cross a_i = -[a_i]_cross phi, the 3D Jacobian is [R, -R[a_i]_cross]. In 2D phi is a scalar and the angular column is R J a_i. We define residual as prediction minus measurement, so the normal-equation right-hand side has a minus sign. The numerical test perturbs the pose on the same side when checking this derivative.',['L']);
live('optimize-live','optimize','optimize','Watch a tangent-space optimizer fit a pose.','Each step recomputes the Jacobian, solves a local problem, and returns a valid pose.',
 'Press “One iteration.” Follow each numbered correspondence. Change the initial angle, then restart the solve.',
 'Four non-collinear body points are transformed by the fixed synthetic ground truth: 35 degrees rotation and translation (0.8, 0.5) meters. The initial translation is (-0.5, -0.4). Measurements are noiseless here to make the convergence mechanism easy to inspect. This is a small least-squares example with fixed associations, not a claim that arbitrary nonconvex SLAM problems converge globally. The chart shows half the squared residual norm.',['L']);

pair('uncertainty','1 · Uncertainty','The Gaussian lives in local coordinates—not in matrix entries.','A valid state and an adequate uncertainty model are separate requirements.',
 'CONCENTRATED UNCERTAINTY',M(R`T=\bar T\operatorname{Exp}(\delta_r),\qquad\delta_r\sim\mathcal N(0,\Sigma_r)`)+P('The random vector has six coordinates. Mapping it to SE(3) produces valid poses.')+P('This is not a globally unique Gaussian distribution on the group.'),
 'CHANGING THE SIDE CHANGES COVARIANCE',M(R`\delta_l=\operatorname{Ad}_{\bar T}\delta_r`)+M(R`\Sigma_l=\operatorname{Ad}_{\bar T}\Sigma_r\operatorname{Ad}_{\bar T}^{\mathsf T}`)+P('The reference pose '+I(R`\bar T`)+' is fixed in this conversion.')+P('Broad, wrapped, or multimodal orientation uncertainty needs more than a single convenient local chart.'),
 'The adjoint identity maps each right perturbation to a left perturbation at the same fixed nominal pose. Because that coordinate mapping is linear, its covariance transformation is the standard linear covariance transformation. The resulting group-valued distribution is a pushforward of the local Gaussian; its density with respect to a group volume measure is not simply an unconstrained Gaussian density in the matrix entries. A valid Exp map does not make a single Gaussian a good approximation to multiple separated orientation hypotheses.',['L']);

pair('adjoint','1 · Frames and conventions','The adjoint converts the same motion between two sides.','Simply moving an unchanged vector to the other side changes the physical update.',
 'THE EXACT IDENTITY',M(R`T\operatorname{Exp}(\xi_r)=\operatorname{Exp}(\xi_l)T`)+M(R`\xi_l=\operatorname{Ad}_T\xi_r`)+P('Right: local/body coordinates.<br>Left: global/world coordinates.')+P('The identity is exact for the paired exponential increments.'),
 'TRANSLATION-FIRST SE(3)',M(R`\operatorname{Ad}_T=\begin{bmatrix}R&[t]_\times R\\0&R\end{bmatrix}`)+M(R`\begin{aligned}\phi_l&=R\phi_r,\\\rho_l&=R\rho_r+t\times(R\phi_r).\end{aligned}`)+P('A rotation about a translated origin also affects the translational twist coordinates.'),
 'Conjugate the exponential by T: T exp(xi wedge) T inverse = exp(T xi wedge T inverse). Applying vee gives the adjoint. This derivation fixes the sign of the translation cross-product term. In 2D, using translation-first [rho_x, rho_y, omega], the adjoint is [[R, -Jt], [0, 1]]. The demonstration uses that exact planar counterpart and actual coordinate-frame endpoints rather than freehand arrows.',['L']);
live('adjoint-live','adjoint','adjoint','Move the pose, then switch the perturbation side.','The teal and amber frames overlap only after transforming the increment.',
 'Change both starting position and rotation. Compare the converted left vector with the original right vector.',
 'The demo applies a body-coordinate increment (0.7 meters, 0.2 meters, delta radians). The correct world-coordinate increment is computed by Ad(T). Both constructions yield the same homogeneous matrix up to floating-point precision. The coral comparison deliberately applies the unconverted vector on the left. All displayed frame axes are generated by transforming local basis vectors; no handedness is invented by the renderer.',['L']);

pair('jacobians','1 · Differential maps','Left and right Jacobians answer different questions.','State the side before using a symbol called J.',
 'PERTURB THE EXPONENTIAL COORDINATES',M(R`\operatorname{Exp}(\phi+d)\approx\operatorname{Exp}(J_l(\phi)d)\operatorname{Exp}(\phi)`)+M(R`\operatorname{Exp}(\phi+d)\approx\operatorname{Exp}(\phi)\operatorname{Exp}(J_r(\phi)d)`)+P('For SO(3), '+I(R`J_r(\phi)=J_l(-\phi)`)+'. Both identities are first-order in '+I(R`d`)+'.'),
 'FOLD A SMALL GROUP INCREMENT INTO Log',M(R`\operatorname{Log}(\operatorname{Exp}(d)\operatorname{Exp}(\phi))\approx\phi+J_l(\phi)^{-1}d`)+M(R`\operatorname{Log}(\operatorname{Exp}(\phi)\operatorname{Exp}(d))\approx\phi+J_r(\phi)^{-1}d`)+P('Use a consistent nonsingular local branch. The order of the factors matters.'),
 'The first pair maps an additive change in exponential coordinates into a small group increment on a chosen side. The second pair is the corresponding local inverse operation. It is incorrect to change the product order but keep an unspecified J unchanged. These are approximations in the small increment d, not exact finite rotation-vector addition rules. The tests compare the two differential identities against finite perturbations in the declared convention.',['L'],17);

pair('jacobian-rates','1 · Differential maps','Angular velocity is not generally the rotation-vector derivative.','This is the same left/right distinction in continuous time.',
 'SPATIAL AND BODY ANGULAR VELOCITY',M(R`\dot R=[\omega_l]_\times R=R[\omega_r]_\times`)+M(R`\omega_l=R\omega_r`)+P('The two angular velocities describe the same motion in different frames.'),
 'RATES OF EXPONENTIAL COORDINATES',M(R`\omega_l=J_l(\phi)\dot\phi`)+M(R`\omega_r=J_r(\phi)\dot\phi`)+P('Invert the appropriate Jacobian to obtain '+I(R`\dot\phi`)+'.')+P('Near the identity '+I(R`J_l\approx J_r\approx I`)+', which explains the tempting—but only local—shortcut.'),
 'Differentiate R(t) = Exp(phi(t)) using the previous slide over a small time dt. The induced left increment is J_l(phi) phi_dot dt, which is the spatial angular velocity times dt. The right increment gives the body angular velocity. This is important when deriving IMU residuals or placing a stochastic prior on local pose coordinates: a coordinate derivative is not automatically the physical twist.',['L']);

pair('continuous-time','2 · Why time needs a representation','One trajectory function can serve many sensor clocks.','Continuous time does not mean an infinite list of optimization variables.',
 'DISCRETE VARIABLES, CONTINUOUS QUERY',M(R`T(t)=\mathcal T(t;\vartheta)`)+P('The finite parameter collection '+I(R`\vartheta`)+' can contain spline control poses or GP support states.')+P('Every measurement queries this function at its own timestamp.'),
 'THE MEASUREMENT STILL DEFINES THE TASK',M(R`e_i=z_i-h_i(T(t_i),\mathcal M)`)+P('For rolling shutter: use each row time.<br>For spinning lidar: use each point time.<br>For radio: use the relevant acquisition time.')+P('A smooth trajectory does not by itself fix a wrong sensor model, clock offset, or data association.'),
 'Representation variables, observation times, and output-query times need not coincide. A method can exploit this separation to avoid adding a full pose variable for every high-rate measurement, but it must correctly model how those measurements depend on the support states. This lesson distinguishes an exact all-observation-time GP teaching model from approximate support-only likelihood constructions.');

cards('three-clocks','2 · Three distinct choices','Measurement time ≠ estimation time ≠ query time.','Decoupling is useful, but the interpolation model must still be justified.',[
 ['MEASURE',P('The instrument determines '+I(R`t_i`)+'.')+P('Do not silently round all observations to the nearest pose timestamp.')+P('A known or estimated clock offset is part of the sensor model.')],
 ['ESTIMATE',P('Choose knots or support times '+I(R`\tau_k`)+'.')+P('Denser support increases flexibility and often computational cost.')+P('Not every temporal GP representation stays sparse after every marginalization.')],
 ['QUERY',P('Evaluate at '+I(R`t_*`)+'.')+P('Check the mean, derivative, and covariance that the chosen model actually defines.')+P('Interpolation inside the interval is not the same as extrapolation outside it.')]
],'The three time lists answer different engineering questions. Splines often choose regular knots. SDE-derived GPs may use irregular support times. A query does not necessarily add an optimization variable: the conditional distribution can be computed from nearby support states after inference. The demo later uses all observation times in the Markov chain so that the asynchronous likelihood is exact and easy to audit.',['G']);

pair('splines','2 · Parametric trajectories','A spline is a weighted sum with a local influence pattern.','The unknowns are coefficients; the basis functions are known once the knots are fixed.',
 'VALUE AND SENSITIVITY',M(R`p(t)=\sum_{i=0}^{n-1}B_{i,d}(t)c_i`)+M(R`\frac{\partial p(t)}{\partial c_i}=B_{i,d}(t)`)+P('Changing '+I(R`c_i`)+' changes the curve only where its basis is nonzero.'),
 'SUPPORT AND SMOOTHNESS',M(R`\operatorname{supp} B_{i,d}\subseteq[u_i,u_{i+d+1}]`)+P('At most '+I(R`d+1`)+' bases are active at a time; knots can have fewer.')+P('At simple interior knots, a degree-'+I(R`d`)+' spline has '+I(R`C^{d-1}`)+' continuity. Repeated knots reduce continuity.')+P('Cubic control coefficients are not generally points the curve passes through.'),
 'Knots are the nondecreasing scalar breakpoints u_i. Control coefficients c_i may be scalar positions, vectors, or, after a different construction, group-valued controls. In an ordinary vector spline, the basis itself gives the derivative with respect to each coefficient. For a nonlinear sensor residual, multiply that derivative by the sensor Jacobian. Compact support is the origin of the local factor connectivity.',['S','H']);

pair('spline-recursion','2 · An explicit construction','Cox–de Boor builds the actual basis functions.','Triangles are appropriate for degree one, not as a substitute for cubic basis curves.',
 'FROM PIECES TO HIGHER DEGREE',M(R`B_{i,0}(t)=\mathbf 1_{[u_i,u_{i+1})}(t)`)+M(R`\begin{aligned}B_{i,d}(t)={}&\frac{t-u_i}{u_{i+d}-u_i}B_{i,d-1}(t)\\&+\frac{u_{i+d+1}-t}{u_{i+d+1}-u_{i+1}}B_{i+1,d-1}(t)\end{aligned}`)+P('A zero-denominator term contributes zero. Endpoint values use the clamped limiting convention.'),
 'DERIVATIVE AND A SIMPLE CHECK',M(R`\begin{aligned}\dot B_{i,d}(t)={}&\frac{d B_{i,d-1}(t)}{u_{i+d}-u_i}\\&-\frac{d B_{i+1,d-1}(t)}{u_{i+d+1}-u_{i+1}}\end{aligned}`)+M(R`\dot p(t)=\sum_i\dot B_{i,d}(t)c_i`)+P('On the base interval: '+I(R`B_{i,d}\ge0`)+' and '+I(R`\sum_i B_{i,d}=1`)+'.'),
 'The demonstration uses nine coefficients and an open-uniform clamped knot vector on [0, 6] seconds. Its first and last knots are repeated degree + 1 times. Zero-length intervals are handled by the zero-term rule. At the final endpoint the limiting basis places all weight on the last coefficient. At a linear-spline interior knot the derivative is not unique; the implementation reports the right derivative there and a left derivative at the final endpoint. Cubic derivatives agree across simple interior knots.',['S'],17);
live('spline-live','spline-recursion','spline','Move one coefficient. Watch its exact support.','The lower plot shows real basis functions—not a schematic with invented connections.',
 'Switch linear/cubic. Select a coefficient, move it, and slide the query across a knot. Watch the active-index list.',
 'The selected coefficient has a coral basis function and a shaded support interval on the trajectory plot. The dashed trajectory is the reference with zero displacement; the teal trajectory is the modified result. Their difference at time t is exactly the displacement times the selected basis weight. The query value and velocity are computed by the basis and its analytic derivative, not by a hand-drawn interpolant.',['S']);

pair('kernel-trick','2 · Linking basis and covariance views','A Gaussian coefficient prior induces a kernel.','The kernel trick changes the representation, not the need to make modeling assumptions.',
 'WHITENED LINEAR PROBLEM',M(R`x=\Psi c,\qquad c\sim\mathcal N(0,I)`)+M(R`b=A\Psi c+\epsilon,\qquad\epsilon\sim\mathcal N(0,I)`)+M(R`(\Psi^{\mathsf T}A^{\mathsf T}A\Psi+I)\hat c=\Psi^{\mathsf T}A^{\mathsf T}b`)+P('Both noise and coefficient priors have been whitened.'),
 'STATE-SPACE FORM',M(R`K=\Psi\Psi^{\mathsf T}`)+M(R`\hat x=KA^{\mathsf T}(I+AKA^{\mathsf T})^{-1}b`)+P('This form also works for a singular positive-semidefinite '+I(R`K`)+'.')+M(R`(A^{\mathsf T}A+K^{-1})\hat x=A^{\mathsf T}b`)+P('The last form requires '+I(R`K\succ0`)+'. A finite basis may not provide that.'),
 'Minimizing the squared whitened measurement residual plus the squared coefficient norm gives the left normal equations. The induced prior covariance of x is Psi Psi transpose. The inverse-free posterior mean follows from Gaussian conditioning and remains meaningful when the finite basis spans only a lower-dimensional state subspace. Writing K inverse without checking rank is not legitimate. A generic GP kernel is not guaranteed to have sparse precision; the SDE construction provides additional structure.',['H','G'],17);

pair('gp-prior','2 · Stochastic trajectories','A Gaussian process starts with a motion assumption.','Here the prior is a linear stochastic differential equation, not an unspecified smoothness knob.',
 'CONTINUOUS-TIME MODEL',M(R`\dot x(t)=Ax(t)+Lw(t)`)+M(R`\mathbb E[w(t)w(s)^{\mathsf T}]=Q_c\delta(t-s)`)+P('Assume a Gaussian initial state independent of zero-mean white process noise.')+P('This defines a Gaussian process for the vector state '+I(R`x(t)`)+'.'),
 'TWO DIFFERENT PRIORS',P('<b>Position random walk:</b> '+I(R`\dot p=w`)+'. Position sample paths are continuous but not differentiable.')+P('<b>Constant-velocity prior:</b> '+I(R`x=[p,v]^{\mathsf T}`)+', '+I(R`\dot p=v,\ \dot v=w`)+'. Position paths are once differentiable, not twice.')+P('Smoothness of the posterior mean is a different statement from smoothness of random sample paths.'),
 'White noise is a generalized process; the SDE notation is shorthand for an integrated stochastic model. Constant velocity refers to the drift or expected motion, not a claim that velocity is constant in every realization. A random-walk mean is piecewise linear between observation-support times, while a constant-velocity posterior position mean has cubic pieces. The sample-path regularity statements are different and should not be inferred by looking only at the mean curve.',['G']);

pair('gp-discretization','2 · From the SDE to computable factors','Integrate the noise over the actual time interval.','A spectral density is not a per-step covariance.',
 'GENERAL LINEAR TIME-INVARIANT CASE',M(R`x_{k+1}=F_kx_k+q_k,\qquad q_k\sim\mathcal N(0,Q_k)`)+M(R`F_k=e^{Ah_k},\qquad h_k=\tau_{k+1}-\tau_k`)+M(R`Q_k=\int_0^{h_k}e^{Au}LQ_cL^{\mathsf T}e^{A^{\mathsf T}u}\,du`),
 'SCALAR CONSTANT-VELOCITY EXAMPLE',M(R`F(h)=\begin{bmatrix}1&h\\0&1\end{bmatrix}`)+M(R`Q(h)=q\begin{bmatrix}h^3/3&h^2/2\\h^2/2&h\end{bmatrix}`)+P('For position random walk instead: '+I(R`F=1,\ Q=qh`)+'.')+P('In the demo, '+I(R`q`)+' has units '+I(R`\mathrm{m^2/s^3}`)+' for CV and '+I(R`\mathrm{m^2/s}`)+' for random walk.'),
 'For the constant-velocity state, A has a one in its upper-right entry and zeros elsewhere; L = [0, 1] transpose. The matrix exponential is [[1, h], [0, 1]]. Integrating the outer product [u, 1] [u, 1] transpose from zero to h gives h cubed/3, h squared/2, and h. This is an exact discretization of this linear SDE for any positive interval. The process factor depends on actual elapsed time, including irregular gaps.',['G']);

pair('gp-markov','2 · Sparsity explained','Neighbor motion factors create a block-tridiagonal precision.','The covariance usually remains dense.',
 'WRITE THE NEGATIVE LOG PRIOR',M(R`\frac12\|x_0-\mu_0\|_{P_0^{-1}}^2`)+M(R`+\frac12\sum_k\|x_{k+1}-F_kx_k\|_{Q_k^{-1}}^2`)+P('Each term touches only one state or two neighbors. Therefore the prior information matrix has only diagonal and adjacent blocks.'),
 'SAY WHICH STATE IS MARKOV',P('For the CV model, the state is '+I(R`[p,v]^{\mathsf T}`)+'. Marginalizing all velocities can destroy the sparse precision over positions alone.')+P('Local measurements preserve this banded structure. Nonlocal factors or eliminating shared variables can introduce extra couplings.')+P('Sparse precision encodes conditional independence, not zero marginal correlation.'),
 'Stack the process residuals in a block-bidiagonal operator B and stack their covariances with the initial-state covariance in a block-diagonal matrix Q. Then the prior precision is B transpose Q inverse B. This avoids overloading the symbol Phi as both a continuous state transition and a stacked matrix. The demo adds scalar position measurements at states in the chain, so their information contributions are local. Its posterior precision is therefore block tridiagonal; a general SLAM posterior need not be.',['G']);

pair('gp-interpolation','2 · Querying between support states','The conditional mean depends on the bracketing states.','For a zero-input LTI SDE, the interpolation matrices can be written explicitly.',
 'DEFINE THE INTERVAL FIRST',P(I(R`a=t-\tau_k`)+', '+I(R`h=\tau_{k+1}-\tau_k`)+', with '+I(R`0<a<h`)+'.')+M(R`\Psi=Q(a)F(h-a)^{\mathsf T}Q(h)^{-1}`)+M(R`\Lambda=F(a)-\Psi F(h)`)+M(R`\mathbb E[x(t)\mid x_k,x_{k+1}]=\Lambda x_k+\Psi x_{k+1}`),
 'THE POSTERIOR QUERY MEAN',M(R`\hat x(t)=\Lambda\hat x_k+\Psi\hat x_{k+1}`)+P('The endpoint estimates have already absorbed the observations.')+P('This formula is exact when no additional unconditioned observations lie inside this bridge interval.')+P('The demo includes every observation time as a support state, making that condition explicit.'),
 'The process-noise cross covariance between time a and the end of the interval h is Q(a) F(h-a) transpose. Gaussian conditioning gives Psi. Subtracting the part of the endpoint prediction already explained by x_k gives Lambda. A query can be evaluated without refitting the entire trajectory. However, a likelihood at an interior measurement time must not silently replace a stochastic bridge by its deterministic mean. In the exact demo every observation time is in the state grid, so query intervals contain no observations except their possible endpoints.',['G'],17);

pair('gp-uncertainty','2 · The uncertainty missing from a line segment','A random bridge has uncertainty even with fixed endpoints.','Posterior support uncertainty is only one part of a continuous-time query.',
 'CONDITIONAL BRIDGE COVARIANCE',M(R`C_b=Q(a)-\Psi Q(h)\Psi^{\mathsf T}`)+P('This remains after conditioning on exact endpoint states.')+P('For scalar position random walk:')+M(R`C_b=q\,a(h-a)/h`)+P('It is zero at an endpoint and positive in the interior.'),
 'ADD POSTERIOR ENDPOINT UNCERTAINTY',M(R`W=\begin{bmatrix}\Lambda&\Psi\end{bmatrix}`)+M(R`P(t)=C_b+W P_{k:k+1\mid z}W^{\mathsf T}`)+P('The joint endpoint covariance contains the <b>cross-covariance blocks</b>.')+P('The demo band is '+I(R`\hat p(t)\pm1.96\sqrt{P_{pp}(t)}`)+': pointwise latent-position uncertainty, not a simultaneous path band or noisy-observation interval.'),
 'Apply the law of total covariance. First average the conditional bridge covariance, which is independent of the endpoint values in this linear model. Then add the covariance of the conditional mean induced by the jointly uncertain endpoints. Omitting their cross covariance is also wrong. For a random walk with q = 1 and a = h/2 = 0.5 seconds in a one-second interval, the bridge variance is 0.25 square meters even when both endpoints are known perfectly.',['G']);

pair('gp-demo-intro','2 · A model that can be independently checked','The next lab compares two exact computations.','Sparse Markov-factor inference and dense GP regression must agree for the same prior.',
 'WHAT IS ESTIMATED?',P('Six fixed noisy observations at irregular times. The chain contains those times plus 0 and 6 seconds.')+P('Random walk: '+I(R`p(0)\sim\mathcal N(0,1)`)+'.<br>CV: '+I(R`[p(0),v(0)]^{\mathsf T}\sim\mathcal N(0,I)`)+'.')+P('The toy matrices are solved densely for transparency, not as a sparse runtime benchmark.'),
 'AN INDEPENDENT KERNEL CHECK',P('Random walk covariance:')+M(R`k(s,t)=1+q\min(s,t)`)+P('CV position covariance, with '+I(R`m=\min(s,t),\ M=\max(s,t)`)+':')+M(R`k(s,t)=1+st+q\left(\frac{m^2M}{2}-\frac{m^3}{6}\right)`)+P('A separate dense conditioning calculation verifies the mean and variance at arbitrary query times.'),
 'The 1 term in both kernels comes from initial position variance. In the CV kernel, s times t comes from independent initial velocity variance one. The integrated process covariance contributes the remaining expression. The tests compare this independently assembled kernel regression with the Markov-information solution and bridge interpolation. This demonstrates mathematical sparsity without pretending that the small JavaScript implementation uses a production sparse Cholesky solver.',['G']);
live('gp-live','gp-demo-intro','gp','Fit asynchronous data and inspect the entire query variance.','Change the prior, process noise, measurement noise, and query time.',
 'Compare random walk and CV. Move the query between observations. Toggle information/covariance and inspect all three variance readouts.',
 'The band includes support uncertainty plus the conditional bridge term. At a support time the bridge contribution vanishes, but the posterior support variance generally remains positive. The zero bridge term does not imply a perfectly known state. A larger process spectral density allows more deviation from the drift prior; larger measurement standard deviation decreases trust in observations. These knobs have different meanings. Switching motion-prior families also changes the physical units of q.',['G']);

pair('cumulative','3 · Joining geometry and time','For two poses, interpolate a relative group motion.','Choose one Log branch and one perturbation convention.',
 'VECTOR-SPACE INTERPOLATION',M(R`p(u)=p_0+u(p_1-p_0),\qquad0\le u\le1`)+P('The difference is a vector and scaling it is valid.')+P('On a group, matrix subtraction does not generally produce a valid finite motion.'),
 'CONSTANT-TWIST GROUP INTERPOLATION',M(R`\xi=\operatorname{Log}(T_0^{-1}T_1)`)+M(R`T(u)=T_0\operatorname{Exp}(u\xi)`)+P('It starts at '+I(R`T_0`)+', ends at '+I(R`T_1`)+', and remains in the group.')+P('Equivalent left form: '+I(R`\operatorname{Exp}(u\operatorname{Log}(T_1T_0^{-1}))T_0`)+', with compatible branches.'),
 'The endpoint checks follow directly from Exp(0) = I and Exp(Log(T0 inverse T1)) = T0 inverse T1. This is a constant-body-twist path when u is linear in time. The left and right expressions describe the same path under compatible logarithm choices, but raw coordinates on the two sides are different. Do not label this automatically the shortest SE(3) path: a distance or metric would first have to be specified.',['L','H']);

pair('cubic-lie','3 · Beyond two-pose interpolation','Cumulative B-splines use an ordered product of relative motions.','Higher order means more local controls—not elementwise interpolation of matrices.',
 'CUMULATIVE BASIS IDENTITY',M(R`p(t)=c_0+\sum_{i=1}^{n-1}\beta_i(t)(c_i-c_{i-1})`)+M(R`\beta_i(t)=\sum_{j=i}^{n-1}B_{j,d}(t)`)+P('This follows by telescoping and '+I(R`\sum_j B_{j,d}=1`)+'.'),
 'ONE GROUP-VALUED CONSTRUCTION',M(R`\Omega_i=\operatorname{Log}(T_{i-1}^{-1}T_i)`)+M(R`T(t)=T_0\prod_{i=1}^{n-1}\operatorname{Exp}(\beta_i(t)\Omega_i)`)+P('Multiply in increasing '+I(R`i`)+' order. In 3D, changing that order changes the path.')+P('Before the active support, completed products telescope. A local degree-'+I(R`d`)+' segment uses at most '+I(R`d+1`)+' neighboring control poses.'),
 'Expand the vector expression and collect the coefficient of each c_i to recover the ordinary spline basis. Replacing vector increments by relative group logarithms and addition by ordered group multiplication defines a cumulative Lie-group spline. It is not an equality obtained by treating noncommuting group elements as vectors. The usual compact representation telescopes factors whose cumulative weights equal one, while weights equal zero contribute identity factors. Cubic control poses generally are not interpolated by the resulting curve.',['B','H'],17);

pair('pose-intro','3 · Comparing interpolation assumptions','There are two distinct issues: validity and the chosen path.','A different valid trajectory is not automatically a mathematical error.',
 'INVALID IN GENERAL',M(R`\widetilde T(u)=(1-u)T_0+uT_1`)+P('The rotation block can shrink or become singular.')+P('Between 0° and 180° in 2D, its midpoint rotation block is the zero matrix.'),
 'TWO VALID ALTERNATIVES',P('<b>Constant twist:</b> '+I(R`T_0\operatorname{Exp}(u\xi)`)+'.')+P('<b>Split model:</b> interpolate translation linearly and rotation on SO(3).')+M(R`\begin{aligned}t(u)&=(1-u)t_0+ut_1,\\R(u)&=R_0\operatorname{Exp}(u\operatorname{Log}(R_0^{\mathsf T}R_1)).\end{aligned}`)+P('Both are valid. Their translations can follow different paths.'),
 'At a planar 180-degree endpoint rotation R1 = -I and R0 = I. The entrywise midpoint is zero, which has determinant zero and cannot be a rotation. A separate translation interpolation plus a rotation-group interpolation remains a valid rigid pose at all times; it simply imposes a different motion model from the SE(3) exponential. The same distinction applies to the SE(2) demonstration.',['L','H']);
live('pose-live','pose-intro','pose','Compare valid group motion with an invalid matrix blend.','Every coordinate frame is drawn from its actual interpolated matrix.',
 'Press “180° halfway.” Watch the coral frame collapse while the two valid frames remain full-sized. Then vary the interpolation fraction.',
 'The start pose is the identity; the end translation is (2, 1) meters. The rotation angle is adjustable. The teal origin traces the constant-twist trajectory; the blue origin follows a straight translation. The coral entrywise blend shares that translation but has an invalid rotation block in general. At fraction zero and one all methods meet their endpoints. The example uses a selected principal planar Log branch, not a globally unique interpolation through all possible rotations.',['L']);

pair('gp-lie','3 · A local construction on the pose group','Use a local vector process, then map it back to poses.','This is a useful construction—not a claim that every Lie-group GP is globally Euclidean.',
 'RIGHT-TRIVIALIZED LOCAL CHART',M(R`\xi_k(t)=\operatorname{Log}(T_k^{-1}T(t))`)+M(R`T(t)=T_k\operatorname{Exp}(\xi_k(t))`)+P('At the left endpoint '+I(R`\xi_k(\tau_k)=0`)+'. At the right endpoint it is the chosen relative-pose Log.'),
 'WHAT THE LOCAL SDE DOES AND DOES NOT SAY',P('A vector SDE can model '+I(R`\xi_k`)+' and, for higher-order priors, its derivatives.')+P('Physical body twist satisfies '+I(R`v_r=J_r(\xi_k)\dot\xi_k`)+', now using the <b>SE(3)</b> right Jacobian.')+P('Nonlinear measurement models and chart changes usually require local linearization. A local Gaussian covariance is not a global pose covariance in matrix entries.'),
 'The reference pose T_k is fixed when defining the chart inside an interval. Differentiating T_k Exp(xi_k) gives the SE(3) right-Jacobian relation between coordinate rate and body twist. The 3-by-3 SO(3) Jacobian earlier is not a substitute for the 6-by-6 SE(3) Jacobian here. A random-walk local-coordinate bridge has a linear conditional mean in xi, recovering the two-pose group interpolation under fixed endpoints, but mapped samples and uncertainty remain group-valued and nonlinear. The scalar GP lab does not claim to implement this full pose-valued estimator.',['D','L']);

pair('measurement-example','3 · A connection to radio localization','The trajectory representation enters through the sensor residual.','A simple line-of-sight range illustrates the chain rule without hiding the map model.',
 'A KNOWN ANCHOR EXAMPLE',M(R`z_i=\|p(t_i)-a\|+\epsilon_i,\quad\epsilon_i\sim\mathcal N(0,\sigma_i^2)`)+M(R`\frac{\partial h_i}{\partial p}=\frac{(p(t_i)-a)^{\mathsf T}}{\|p(t_i)-a\|}`)+P('Here '+I(R`a`)+' is a fixed anchor and '+I(R`p(t_i)\ne a`)+'.'),
 'USING A VECTOR B-SPLINE',M(R`p(t)=\sum_jB_{j,d}(t)c_j`)+M(R`\frac{\partial h_i}{\partial c_j}=B_{j,d}(t_i)\frac{(p(t_i)-a)^{\mathsf T}}{\|p(t_i)-a\|}`)+P('Only active coefficients connect to this measurement.')+P('Unknown anchors, walls, orientation, clock bias, or multipath introduce additional variables and terms; they are not silently handled by this toy range formula.'),
 'This worked example is derived directly by differentiating the Euclidean norm and applying the spline chain rule. It assumes line of sight, a known anchor, synchronized time, and a point sensor located at the position represented by p. A lever arm would make orientation enter as well. In a radio-SLAM formulation the anchor or reflecting features may be unknown map variables, and association must be modeled. Temporal representation controls which trajectory variables are involved; it does not replace those physical modeling decisions.',['H']);

cards('compare','4 · Choosing a representation','Compare the modeling assumptions—not just the smooth curves.','Splines and Gaussian processes overlap; neither name guarantees a better estimator.',[
 ['SPLINES',P('<b>You choose:</b> degree, knots, control representation.')+P('<b>Locality:</b> compact basis support.')+P('<b>Smoothness:</b> degree and knot multiplicity.')+P('<b>Uncertainty:</b> requires a probabilistic estimation model; it is not supplied by the curve alone.')],
 ['SDE-DERIVED GPs',P('<b>You choose:</b> Markov state, drift, noise, initial prior.')+P('<b>Locality:</b> sparse state precision and conditional bridges.')+P('<b>Smoothness:</b> prior order; distinguish mean and sample paths.')+P('<b>Uncertainty:</b> include bridge and support terms.')],
 ['BOTH',P('Can use finite support variables and query continuously.')+P('Can represent group-valued trajectories with appropriate constructions.')+P('Can be regularized and fitted through sensor residuals.')+P('Still depend on observability, calibration, and correct likelihoods.')]
],'The contrast is a modeling viewpoint, not a rigid separation between mathematical families. Gaussian priors on spline coefficients create covariance kernels. Some SDE priors produce spline-like posterior means. Sparse temporal support does not guarantee a globally sparse reduced SLAM system after map or velocity variables are marginalized. Decide based on the motion assumptions, needed derivatives, uncertainty treatment, and computational structure.',['G','B']);

pair('implementation','4 · What to check in code','Test the convention, the model, and the picture separately.','A numerically stable solver can still solve the wrong problem.',
 'GEOMETRY CHECKS',P('Check '+I(R`R^{\mathsf T}R\approx I`)+' and '+I(R`\det R\approx1`)+'.')+P('Check Exp/Log and pose inverse round trips on the chosen branch.')+P('Verify '+I(R`T\operatorname{Exp}(\xi)=\operatorname{Exp}(\operatorname{Ad}_T\xi)T`)+'.')+P('Compare Jacobians against finite differences using the same update side.'),
 'TIME AND VISUAL CHECKS',P('Spline: partition of unity, local support, endpoint limits, and analytic derivatives.')+P('GP: discrete-noise integration, SPD covariance, dense/sparse agreement, bridge limits.')+P('Plot equal spatial scales and compute arrows from transformed basis vectors.')+P('Keep static fallbacks and live diagrams on the same numerical implementation.'),
 'The repository tests separate model identities from user-interface behavior. The math suite uses independent finite-difference and dense-kernel comparisons where possible. Browser tests inspect generated math, control responses, slide navigation, focus, print fallbacks, and responsive layouts. Unit tests increase confidence in the modeled equations and numerical examples; they are not a formal proof of every possible nonlinear estimator or a validation of an unspecified physical sensor system.',['L','S','G']);

pair('equations','4 · Geometry equation sheet','The local geometry in one place.','All formulas use column vectors and translation-first SE(3) twists.',
 'UPDATE, DIFFERENCE, AND ADJOINT',M(R`T^+=T\operatorname{Exp}(\xi_r)`)+M(R`T\ominus\bar T=\operatorname{Log}(\bar T^{-1}T)`)+M(R`\xi_l=\operatorname{Ad}_T\xi_r`)+M(R`\operatorname{Ad}_T=\begin{bmatrix}R&[t]_\times R\\0&R\end{bmatrix}`),
 'UNCERTAINTY AND DIFFERENTIALS',M(R`\Sigma_l=\operatorname{Ad}_{\bar T}\Sigma_r\operatorname{Ad}_{\bar T}^{\mathsf T}`)+M(R`\omega_l=J_l(\phi)\dot\phi,\quad\omega_r=J_r(\phi)\dot\phi`)+M(R`J_r(\phi)=J_l(-\phi)\quad\text{on }SO(3)`)+M(R`T(u)=T_0\operatorname{Exp}(u\operatorname{Log}(T_0^{-1}T_1))`),
 'The mean pose is held fixed for the covariance-side conversion. Exp/Log formulas assume compatible branches where needed; the group exponential is not globally injective. The SO(3) angular-velocity equations use three-vectors and 3-by-3 Jacobians. Their SE(3) counterparts use six-vectors and 6-by-6 Jacobians. Keep this sheet beside an implementation rather than copying an isolated formula without its conventions.',['L'],17);

pair('equations-time','4 · Time equation sheet','The temporal model in one place.','These equations refer to a vector-valued linear Gaussian process or a vector B-spline.',
 'SPLINE AND MARKOV TRANSITION',M(R`p(t)=\sum_i B_{i,d}(t)c_i`)+M(R`\dot p(t)=\sum_i\dot B_{i,d}(t)c_i`)+M(R`x_{k+1}=F_kx_k+q_k`)+M(R`q_k\sim\mathcal N(0,Q_k)`)+P('The noise increments are independent across disjoint intervals.'),
 'CONDITIONAL BRIDGE',M(R`\Psi=Q(a)F(h-a)^{\mathsf T}Q(h)^{-1}`)+M(R`\Lambda=F(a)-\Psi F(h)`)+M(R`\hat x(t)=\Lambda\hat x_k+\Psi\hat x_{k+1}`)+M(R`C_b=Q(a)-\Psi Q(h)\Psi^{\mathsf T}`)+M(R`P(t)=C_b+[\Lambda\ \Psi]P_{k:k+1\mid z}[\Lambda\ \Psi]^{\mathsf T}`),
 'All bridge matrices are evaluated within a bracket of length h at offset a. At exact support times use the support mean and covariance, or take the limiting formula; do not invert a zero-length process covariance. The posterior interpolation statement assumes the chosen support chain and likelihood account for all intervening observations. For a nonlinear pose process these vector Gaussian formulas belong inside the declared local approximation, not directly on raw rotation-matrix entries.',['S','G'],16.5);

cards('summary','5 · Takeaways','Three distinctions make the chapter much easier to read.','Use the experiments to connect each distinction to an observable numerical consequence.',[
 ['STATE VS. COORDINATES',P('A pose belongs to a constrained group.')+P('The optimizer solves for a vector increment.')+P('Exp and composition connect them.')+P('The update side fixes the coordinate meaning.')],
 ['CURVE VS. MOTION PRIOR',P('A spline specifies basis functions.')+P('An SDE-GP specifies a stochastic dynamics model.')+P('Both can be locally supported, but their assumptions are not identical.')],
 ['MEAN VS. UNCERTAINTY',P('A smooth mean is not a smooth random sample path.')+P('Known endpoints do not eliminate bridge uncertainty.')+P('Sparse precision is not sparse covariance.')]
],'Return to the tangent experiment to remember why local coordinates are not the global state. Return to the spline experiment to see why one coefficient has only a local influence. Return to the GP experiment to see why an interpolated posterior mean is not the entire posterior distribution. The key practical payoff is a representation that is valid in geometry and explicit about its temporal assumptions.',['L','S','G']);

slide('references','Sources, assumptions, and audit trail','Primary references and the limits of the demonstrations','The full study version includes every slide’s source links and explanatory notes.',[
 ...panel('refs-left',72,190,724,452,'PRIMARY SOURCES',Object.values(references).map(r=>P(`<a href="${r.url}">${r.full}</a>`)).join(''),C.soft,15),
 ...panel('refs-right',820,190,388,452,'SCOPE OF THIS REVISION',P('All seven labs are original deterministic teaching models. No paper dataset or timing benchmark is reproduced.')+P('Spatial demos are planar where labeled. Full 3D formulas use explicit conventions.')+P('The exact scalar GP lab is not a complete Lie-group or radio-SLAM implementation.')+P('<a href="./study.html">Scrollable study notes →</a>')+P('<a href="./math-audit.md">Mathematical audit and test guide →</a>'),C.panel,16)
],'The handbook chapter supplies the overall organization. Micro Lie theory supplies explicit group and Jacobian conventions. The B-spline documentation and cumulative Lie-spline paper supply the basis and ordered-product constructions. Barfoot et al. supplies SDE-based sparse GP inference. Dong et al. supplies a local pose-group GP construction. The 2026 handbook year is the citation supplied by the public-release repository, not an independent assertion about final publication status.');

export const deck={format:'bento/slides',version:1,docId:'advanced-state-variable-representations-bento',title:'Advanced State Variable Representations',readonly:true,meta:{author:'Bai Liping',subject:'Worked geometry and continuous-time state estimation',company:'bailiping.com',revision:'2026-09-05'},size:{width:1280,height:720},theme:{background:C.paper,color:C.ink,accent:C.teal,fontFamily:sans},slides};
export const inlineLiveMap=labs.map(({introSlide,slide,demo,title})=>({introSlide,slide,slideIndex:slides.findIndex(s=>s.id===slide),inline:true,layout:'region',bounds:{x:72,y:180,width:1136,height:475},src:`./live/?demo=${demo}&embed=region`,source:`./live/?demo=${demo}`,title,sandbox:'allow-scripts',hideSource:true,readyMessage:true,unloadWhenHidden:true}));
