const C={bg:'#F6F3EB',paper:'#FFFDF8',ink:'#213D36',muted:'#64746D',line:'#D4DDD5',teal:'#137B69',soft:'#E6EEE7',gold:'#BC702D',warm:'#F3E9D9',purple:'#8063AB'};
const serif='Georgia, Times New Roman, serif',sans='Arial, Helvetica, sans-serif',mono='Consolas, monospace';
const R=String.raw,M=s=>`<span class="math-tex math-display">\\[${s}\\]</span>`,I=s=>`<span class="math-tex math-inline">\\(${s}\\)</span>`;
const T=(id,x,y,w,h,html,o={})=>({id,type:'text',x,y,w,h,html,fontFamily:sans,fontSize:21,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.38,...o});
const B=(id,x,y,w,h,fill=C.paper,o={})=>({id,type:'shape',shape:'rect',x,y,w,h,fill,stroke:C.line,strokeWidth:1,radius:13,...o});
const image=(name,x=650,y=199,w=558,h=390)=>({id:'figure-'+name,type:'image',x,y,w,h,src:'../grassmannian/figures/'+name+'.svg',fit:'contain',alt:{hero:'Two bases of the same plane',angles:'Principal angles in two coordinate slices',geodesic:'A shortest path between lines',pca:'Principal plane of a point cloud',affine:'A plane displaced from the origin',graph:'Weighted consistency matrix',tangent:'A horizontal tangent'}[name]});
const panel=(id,x,y,w,h,label,html,o={})=>[B(id+'-bg',x,y,w,h,o.fill||C.paper),T(id+'-label',x+22,y+18,w-44,24,label,{fontSize:11,fontFamily:mono,fontWeight:700,color:o.accent||C.teal,letterSpacing:1}),T(id+'-body',x+22,y+56,w-44,h-73,html,{fontSize:o.size||21})];
const slides=[];
function add(id,section,title,sub,elements,notes,source='Handbook · EAS 1998'){
 slides.push({id,background:C.bg,transition:'none',notes,elements:[T('section',72,32,1030,22,section.toUpperCase(),{fontFamily:mono,fontSize:11,fontWeight:700,color:C.gold,letterSpacing:1.5}),T('heading',72,76,1136,55,title,{fontFamily:serif,fontSize:40,fontWeight:500,lineHeight:1.07}),T('subtitle',72,139,1136,40,sub,{fontSize:17,color:C.muted}),...elements,B('footer-rule',72,666,1136,1,C.line,{radius:0}),T('home',72,682,210,20,'BAI LIPING / GEOMETRY',{fontFamily:mono,fontSize:10,color:C.muted,link:'https://bailiping.com/'}),T('source',300,682,600,20,source,{fontSize:10,color:C.muted,align:'center'}),T('contents-link',1060,682,148,20,'CONTENTS ↗',{fontFamily:mono,fontSize:10,color:C.teal,align:'right',link:'contents'})]});
}
function two(id,section,title,sub,a,b,notes,source){add(id,section,title,sub,[...panel('left',72,196,554,438,a[0],a[1],{fill:C.soft,size:a[2]||21}),...panel('right',650,196,558,438,b[0],b[1],{size:b[2]||21})],notes,source);}
function visual(id,section,title,sub,label,body,fig,notes,source){add(id,section,title,sub,[...panel('idea',72,196,554,438,label,body,{fill:C.soft}),image(fig)],notes,source);}
function eqTwo(id,section,title,sub,eq,a,b,notes,source){add(id,section,title,sub,[...panel('eq',72,193,1136,146,'THE MATHEMATICAL STATEMENT',M(eq),{fill:C.soft,size:24}).map(e=>e.id==='eq-body'?{...e,y:237,h:98}:e),...panel('left',72,357,554,277,a[0],a[1],{size:20}),...panel('right',650,357,558,277,b[0],b[1],{size:20})],notes,source);}
export const labs=[];
function live(intro,lab){
 const info={
  basis:['One plane. Many bases.','Rotate the basis, then tilt the plane. Watch which quantities change.','hero','ROTATE, THEN TILT','A quarter turn changes the basis matrix: ‖Q − QO‖F = 2. The projector difference stays zero.<br><br>Tilting the plane changes the subspace itself.','Quarter turn → same plane.'],
  angles:['Principal angles and distances','Change the two coordinate rotations; then rotate the target basis.','angles','COMPARE THE GEOMETRIES','At 30° and 60°, the geodesic distance is π√5/6 ≈ 1.171 rad; the projector distance is 1.<br><br>Rotating the basis changes neither distance.','Two independent angles in Gr(2,4).'],
  geodesic:['Follow a Grassmann geodesic','Move along the path, animate it, or flip the endpoint vector.','geodesic','FOLLOW THE SHORTEST PATH','At endpoint angle 65° and t = 0.4, the distance from the start is 26° ≈ 0.454 rad.<br><br>The line is unchanged by an endpoint sign flip. At 90°, shortest paths are not unique.','The sphere is a representative picture.'],
  pca:['Learn a plane from a point cloud','Step through gradient descent and explore a closing eigenvalue gap.','pca','OPTIMIZE THE SUBSPACE','For covariance eigenvalues (9, 4, 1), the optimal plane captures variance 13 and leaves reconstruction loss 1.<br><br>When λ₂ = λ₃, several optimal planes exist.','The spectral solution is the reference.'],
  association:['Match lines and planes','Change the scan pose, add noise, and compare the pairwise descriptors.','graph','AFFINE DATA ASSOCIATION','Three lines and three planes, plus two distractors, give 24 candidate matches.<br><br>The clean shifted-affine scene recovers 6 / 6 true matches with density 6.<br><br>This small synthetic demo solves the discrete objective exactly; the paper uses CLIPPER.','Lusk &amp; How (2022) · synthetic scene.']
 }[lab];
 const [title,sub,figure,label,body,caption]=info,slide=intro+'-live';
 add(slide,'Interactive experiment / '+String(labs.length+1).padStart(2,'0'),title,sub,[
  image(figure,72,172,628,385),
  ...panel('experiment',728,155,480,452,label,body,{fill:C.soft,size:21}),
  T('experiment-caption',88,598,605,30,caption,{fontSize:16,color:C.muted})
 ],'This is a normal sequential slide with an experiment visible as soon as the slide is active. '+body.replaceAll(/<[^>]*>/g,' ')+' Page Up and Page Down navigate from the experiment; Escape returns keyboard focus to the deck. Leaving the slide unloads it. The static illustration and result remain in print and offline views.',lab==='association'?'Lusk & How · Eqs. (2)–(5), (8)–(9)':'Handbook · EAS 1998');
 const elements=slides.at(-1).elements;
 Object.assign(elements.find(e=>e.id==='section'),{x:48,y:23,w:260,h:20});
 Object.assign(elements.find(e=>e.id==='heading'),{x:310,y:17,w:922,h:39,fontSize:31});
 Object.assign(elements.find(e=>e.id==='subtitle'),{x:48,y:64,w:1184,h:23,fontSize:15});
 labs.push({slide,slideIndex:slides.length-1,lab,title,inline:true,layout:'region',bounds:{x:48,y:101,width:1184,height:551},src:'../grassmannian/lab.html?lab='+lab+'&embed=slides',readyMessage:true,unloadWhenHidden:true,sandbox:'allow-scripts allow-same-origin allow-top-navigation-by-user-activation'});
}
add('overview','Geometry / interactive lecture','Grassmannian manifold','Visual intuition, graduate-level mathematics, and a data-association case study.',[
 T('hero',72,218,620,148,'A space<br>of <span style="color:#137B69">subspaces.</span>',{fontFamily:serif,fontSize:66,lineHeight:1.06}),T('hero-copy',76,393,541,84,'When a line, plane, or learned subspace<br>becomes a single geometric point.',{fontSize:23,color:C.muted}),image('hero',699,203,509,366),
 T('cover-count',76,520,520,25,'34 SLIDES / FIVE LIVE EXPERIMENTS',{fontFamily:mono,fontSize:12,color:C.gold}),T('cover-paper',76,563,542,53,'Includes Lusk &amp; How (2022):<br>global association of 3-D lines and planes.',{fontSize:18}),T('guide-link',760,596,425,30,'Companion guide & live labs ↗',{fontSize:17,color:C.teal,align:'right',link:'https://bailiping.com/grassmannian/'})
],'Audience: visual intuition plus graduate mathematics. Assumes linear algebra, SVD and basic optimization, not prior differential geometry. We use Gr(k,n), real subspaces unless complex is explicitly stated. Five laboratories share tested numerical code with the companion guide.');
add('contents','The route','From geometry to global matching.','Choose a chapter, or use the arrow keys to follow the story.',[
 ...[['01','The subspace is the point','definition','Bases, projectors, and quotient geometry'],['02','Measure a difference','angles','Principal angles and distance conventions'],['03','Move without leaving','tangent','Tangents, geodesics, logarithms, retractions'],['04','Learn a subspace','pca-objective','PCA as a Grassmann optimization problem'],['05','Match lines and planes','affine','The requested paper and a synthetic demo'],['06','Keep the distinctions','pitfalls','A formula sheet and primary references']].flatMap(([n,t,link,sub],i)=>{const x=72+(i%2)*578,y=195+Math.floor(i/2)*151;return[B('toc-'+n,x,y,554,131,i<2?C.soft:C.paper),T('toc-n-'+n,x+20,y+18,40,25,n,{fontFamily:mono,fontSize:15,color:C.gold}),T('toc-title-'+n,x+75,y+15,455,33,t+' →',{fontFamily:serif,fontSize:26,link}),T('toc-sub-'+n,x+75,y+65,454,44,sub,{fontSize:16,color:C.muted})];})
],'Each of the five experiments is a dedicated slide immediately after its explanation. Experiments load when their slide becomes active. Page Up and Page Down advance from within a lab; Escape returns focus to the deck. Leaving the slide releases its iframe. All slides include static illustrations and results for print and offline reading.');
visual('definition','01 / the object','A point can represent an entire plane.','Fix the dimension k. Let the subspace vary.','THE REAL GRASSMANNIAN',M(R`\mathrm{Gr}(k,n)=\{\mathcal S\subset\mathbb R^n:\dim\mathcal S=k\}`)+'A point is a <b>linear subspace</b>, not an individual vector in it.<br><br>All subspaces contain the origin.<br><br>Our notation: k first, ambient n second. We assume 0 &lt; k &lt; n.','hero','Gr(2,3) is a two-dimensional manifold whose points are planes through the origin in three-dimensional Euclidean space. Finite colored patches are drawing windows onto infinite planes. The handbook uses the reverse notation Gr(n,k).');
visual('basis','01 / invariance','Change the basis. Keep the point.','The coordinates inside a subspace are not part of its identity.','AN ENTIRE EQUIVALENCE CLASS',M(R`Q^\top Q=I_k,\qquad [Q]=\{QO:O\in O(k)\}`)+'Rotations, reflections, and column sign flips preserve the column space.<br><br>In the lab, rotate the arrows and watch the plane remain fixed.<br><br><b>Static example:</b> a 90° basis rotation gives ‖Q − QO‖F = 2; the subspace distance is 0.','hero','Q is an n-by-k orthonormal representative. The equivalence includes the whole orthogonal group, including reflections: the Grassmannian here is unoriented. At 180 degrees in k=2, QO=-Q but the same plane is represented.');live('basis','basis');
eqTwo('quotient','01 / quotient geometry','Remove the degrees of freedom of the basis.','Stiefel keeps a frame. Grassmann keeps only its span.',R`\mathrm{Gr}(k,n)=\mathrm{St}(k,n)/O(k),\qquad \dim\mathrm{Gr}(k,n)=k(n-k)`,['COUNT THE PARAMETERS',M(R`nk-\frac{k(k+1)}2-\frac{k(k-1)}2`)+'Orthonormality removes k(k+1)/2 parameters; internal rotations remove k(k−1)/2.'],['READ THE QUOTIENT','Each orthonormal frame belongs to a whole family QO.<br><br>The quotient identifies that family with one subspace. Gr(2,3) has dimension 2.'],'Stiefel dimension is nk-k(k+1)/2 for real matrices. O(k) has dimension k(k-1)/2; the quotient dimension is k(n-k). Reflections are discrete identifications and do not change this dimension count.');
eqTwo('projector','01 / a unique representation','The projector forgets the basis automatically.','Every k-dimensional subspace has exactly one orthogonal projector.',R`P=QQ^\top=(QO)(QO)^\top,\quad P^2=P=P^\top,\quad\operatorname{tr}P=k`,['WHAT P DOES',M(R`\widehat x=Px,\qquad x-Px\perp\operatorname{span}(Q)` )+'Px is the least-squares approximation of x within the subspace.'],['WHAT IT COSTS','Q stores nk entries; P stores n² entries.<br><br>P is unique, but an orthonormal basis is usually cheaper computationally.'],'The symmetric idempotent rank-k projectors are another representation of Gr(k,n). The trace equals rank because projector eigenvalues are zero or one. For a nonorthonormal full-rank B, use B(B^T B)^{-1}B^T instead of BB^T.');
two('examples','01 / small examples','Lines identify opposite directions.','A sphere picture needs an antipodal identification.', ['Gr(1,2) AND Gr(1,3)',M(R`[u]=[-u],\qquad\|u\|=1` )+'Gr(1,2): unoriented lines in a plane.<br><br>Gr(1,3) ≅ ℝP²: sphere points u and −u represent the same line.'],['Gr(2,3)','A plane through the origin is determined by its normal direction.<br><br>Normals n and −n describe the same plane.<br><br><b>Offset planes need affine geometry.</b>'],'Real projective spaces parameterize one-dimensional linear subspaces. Gr(1,2) is topologically a circle after antipodal identification. Gr(1,3) is RP2 rather than S2. Orthogonal complementation identifies Gr(k,n) and Gr(n-k,n).');
two('basis-trap','02 / the wrong difference','Matrix distance can report a change that never happened.','Two representatives may look far apart while the subspace is identical.', ['COMPARE Q AND −Q',M(R`\|Q-(-Q)\|_F=2\sqrt{k}`)+M(R`QQ^\top=(-Q)(-Q)^\top`)+'Basis distance is sensitive to signs and rotations.'],['COMPARE THE SUBSPACES',M(R`d_g([Q],[-Q])=0` )+'Use principal angles or projector distances.<br><br>Never report raw basis error as subspace error without alignment.'],'This example is exact for any real orthonormal Q. Orthogonal Procrustes can align representatives, but its distance convention still differs globally from the intrinsic geodesic distance.');
visual('angles','02 / principal angles','Find directions that align best.','The singular values of QᵀY remove both choices of basis.','SVD → ANGLES',M(R`Q^\top Y=U\operatorname{diag}(\sigma_i)V^\top`)+M(R`\theta_i=\arccos\sigma_i`)+M(R`0\leq\theta_1\leq\cdots\leq\theta_k\leq\pi/2` )+'The corresponding principal vectors are columns of QU and YV.','angles','Both bases are orthonormal. Singular values are nonnegative and sorted descending, so principal angles are sorted ascending. The first angle maximizes vector alignment; subsequent pairs add orthogonality constraints. In floating point clamp singular values to [0,1].');
visual('distances','02 / distances','Two useful distances. Two different geometries.','The normalization and angle units belong in the formula.','INTRINSIC AND PROJECTOR DISTANCE',M(R`d_g=\sqrt{\sum_i\theta_i^2}`)+M(R`d_p=\frac{\|QQ^\top-YY^\top\|_F}{\sqrt2}`)+M(R`d_p=\sqrt{\sum_i\sin^2\theta_i}`)+'Angles in <b>radians</b>. For small angles, sin θ ≈ θ; globally these distances differ.','angles','dg is the canonical Grassmann geodesic distance. dp is the normalized projector Frobenius distance, sometimes called a chordal distance; EAS distinguishes projection and chordal conventions, so the formula is explicit. Equal k is assumed.');live('distances','angles');
eqTwo('angle-example','02 / a worked example','Two planes in ℝ³ must share a direction.','The experiment uses ℝ⁴ so that both principal angles can vary.',R`Q=[e_1,e_2],\quad Y=[\cos\alpha\,e_1+\sin\alpha\,e_3,\;\cos\beta\,e_2+\sin\beta\,e_4]`,['IN FOUR DIMENSIONS',M(R`(\alpha,\beta)=(30^\circ,60^\circ)`)+M(R`d_g=\pi\sqrt5/6\approx1.171,\quad d_p=1`)],['IN THREE DIMENSIONS',M(R`\dim(S\cap T)\geq\dim S+\dim T-3=1` )+'For two planes, θ₁ = 0; only θ₂ varies.'],'For alpha,beta in [0,pi/2], the two principal angles are alpha,beta sorted ascending. Orthogonality of the two coordinate slices provides an analytic validation case. Dimensions of the ambient space must be explicit in geometric illustrations.');
visual('tangent','03 / directions of motion','A tangent points out of the current subspace.','Horizontal representatives remove motion that only changes the basis.','TANGENT IN BASIS COORDINATES',M(R`Q^\top\Delta=0`)+M(R`\Pi_Q(Z)=(I-QQ^\top)Z` )+'Internal motion QΩ, with Ωᵀ = −Ω, changes the frame alone.<br><br>A horizontal Δ changes the Grassmannian point.','tangent','The horizontal tangent lift is n-by-k and has k(n-k) degrees of freedom. General Stiefel tangents satisfy Q^T Z+Z^T Q=0; Grassmann horizontal lifts satisfy the stronger Q^T Delta=0.');
eqTwo('exponential','03 / the exponential map','Rotate the active directions with sines and cosines.','For a compact rank-r SVD Δ = UΣVᵀ, use the canonical metric.',R`Q(t)=Q+QV\big(\cos(t\Sigma)-I_r\big)V^\top+U\sin(t\Sigma)V^\top`,['WHAT THE FORMULA GUARANTEES',M(R`Q(0)=Q,\quad\dot Q(0)=\Delta`)+M(R`Q(t)^\top Q(t)=I_k` )+'Zero singular directions stay fixed.'],['LENGTH IS NOT ALWAYS DISTANCE','The speed is ‖Δ‖F.<br><br>A sufficiently long geodesic is no longer a shortest path. Cut points matter when inverting the map.'],'The compact formula with the identity correction handles rank-deficient tangents and n<2k. For horizontal Delta, Q^T U=0 for its nonzero singular directions. The horizontal metric is trace(Delta1^T Delta2); projector tangent metric has factor 1/2.');
visual('geodesic','03 / shortest paths','Follow a geodesic between unoriented lines.','A great-circle arc is a representative path, with antipodal points identified.','THE Gr(1,3) EXAMPLE',M(R`q(t)=u\cos(t\theta)+w\sin(t\theta)`)+M(R`w=\frac{v-u\cos\theta}{\sin\theta}` )+'First choose the sign of v so uᵀv ≥ 0.<br><br>For 0 ≤ t ≤ 1: distance from the start = tθ.<br><br>At θ = 0, the path is constant.','geodesic','For theta strictly below pi/2 the shortest subspace geodesic is unique. At pi/2, multiple shortest paths connect the endpoint lines; the demo chooses one. The vector sphere is a double cover of the real projective plane, not the manifold itself.');live('geodesic','geodesic');
two('logarithm','03 / inverse map & cut locus','The logarithm is local, not globally single-valued.','A principal angle of 90° marks the boundary of a unique shortest logarithm.', ['AWAY FROM THE CUT LOCUS',M(R`Z=(I-QQ^\top)Y(Q^\top Y)^{-1}`)+M(R`Z=U\Sigma V^\top`)+M(R`\operatorname{Log}_{[Q]}[Y]=U\arctan(\Sigma)V^\top` )+'This gives a horizontal tangent representative.',20],['AT THE BOUNDARY','If a principal angle is π/2, QᵀY is singular.<br><br>There are multiple minimizing logarithms. Near the boundary, this inverse-based expression is numerically fragile.<br><br>Use robust algorithms from the handbook.'], 'The displayed log formula assumes equal dimensions and all principal angles strictly less than pi/2. The returned tangent exponential reaches the target subspace, not necessarily the exact input basis. See Handbook section 5 for cut locus and stable logarithm algorithms.');
eqTwo('retraction','03 / numerical optimization','An orthonormalization can be a local step.','A retraction matches the exponential to first order; it is cheaper to compute.',R`R_Q(\Delta)=\operatorname{qf}(Q+\Delta),\qquad Q_{+}=R_Q(-\eta\operatorname{grad}f(Q))`,['PRESERVE THE CONSTRAINT','QR returns an orthonormal frame.<br><br>Column sign conventions do not change the represented subspace.'],['CHOOSE THE STEP','A tangent is local. Use a line search or a trust region to control the optimization step.<br><br>QR retraction is generally not the exact exponential.'],'For a horizontal Delta, (Q+Delta)^T(Q+Delta)=I+Delta^T Delta is positive definite, so Q+Delta retains full column rank. The demo uses twice-reorthogonalized modified Gram-Schmidt on tiny matrices and Armijo backtracking.');
eqTwo('pca-objective','04 / PCA','Learn the subspace that retains the most variance.','C is the covariance of centered data; the representation Q is orthonormal.',R`f(Q)=-\operatorname{tr}(Q^\top CQ),\qquad\operatorname{grad}f(Q)=-2(I-QQ^\top)CQ`,['WHY GRASSMANN?',M(R`f(QO)=f(Q)` )+'Only the span matters.<br><br>Reconstruction loss = tr(C) − tr(QᵀCQ).'],['WHAT IS THE OPTIMUM?','The span of the k leading eigenvectors.<br><br>The subspace is unique if λk &gt; λk+1, even when eigenvalues inside it are repeated.'],'Assume real symmetric covariance C and centered samples. The Euclidean derivative is -2CQ, then horizontal projection gives the displayed canonical gradient. The eigenspace solution follows the Rayleigh-Ritz principle. Boundary ties create nonunique optimal subspaces.');
visual('pca','04 / experiment','Watch a plane learn a point cloud.','The exact eigenspace solution supplies an independent reference.','A CONTROLLED OPTIMIZATION',M(R`\lambda(C)=(9,4,1),\quad k=2` )+'Optimum captured variance: <b>13</b>.<br>Optimum reconstruction loss: <b>1</b>.<br><br>Take one gradient step, run descent, or reduce λ₂ until the boundary gap closes.<br><br>The cloud covariance is computed from the plotted samples.','pca','This is a deterministic centered synthetic cloud of 96 Fourier-generated samples, not a Gaussian dataset or benchmark. Its covariance eigenvalues are exactly the configured values in exact arithmetic. Optimization uses the actual sample covariance. A stationary start can fail to reach the best eigenspace in general; this demonstration uses a specified nonstationary initial basis.');live('pca','pca');
two('applications','04 / beyond PCA','A useful model whenever only a span matters.','Choose the representation that preserves the information your task needs.', ['REAL SUBSPACE APPLICATIONS','<b>Subspace tracking:</b> follow a changing signal subspace.<br><br><b>Reduced models:</b> represent a low-dimensional trial space.<br><br><b>Recognition:</b> compare learned feature subspaces.'],['COMPLEX SIGNAL SUBSPACES',M(R`Q^H Q=I,\quad [Q]=\{QU:U\in U(k)\}`)+M(R`\dim_{\mathbb R}\mathrm{Gr}_{\mathbb C}(k,n)=2k(n-k)` )+'Use conjugate transpose and unitary changes of basis. The labs here are real.',20],'These are use cases of a subspace representation, not claims that every model in the named fields is Grassmannian. Complex formulas require conjugate transpose and the appropriate real part of the Hermitian tangent inner product.');
visual('affine','05 / Lusk & How · 2022','SLAM objects are often displaced lines and planes.','The supplied paper uses the affine Grassmannian.','ADD A DISPLACEMENT',M(R`\mathcal A=b+\operatorname{span}(A)`)+M(R`b_\perp=(I-AA^\top)b` )+'Line: k = 1. Plane: k = 2.<br><br>Moving b along the object does not change the affine subspace.<br><br>'+M(R`\dim\operatorname{Graff}(k,n)=(k+1)(n-k)`),'affine','Lusk and How, Global Data Association for SLAM with 3D Grassmannian Manifold Objects, arXiv:2205.08556v1. This extension is essential: directions alone do not represent object offsets. Graff(k,n) is not Gr(k,n) times an unrestricted R^n translation.','Lusk & How · §II-A · arXiv:2205.08556');
two('affine-embedding','05 / homogeneous embedding','Embed an affine object in one extra dimension.','A 3-D line becomes a 2-D linear subspace in ℝ⁴; a plane becomes a 3-D one.', ['ORTHONORMAL STIEFEL COORDINATES',M(R`Y=\begin{bmatrix}A&b_\perp/\eta\\0&1/\eta\end{bmatrix}`)+M(R`\eta=\sqrt{1+\|b_\perp\|^2}`)+M(R`\operatorname{Graff}(k,3)\hookrightarrow\mathrm{Gr}(k+1,4)` )+'Divide positions by a length scale ρ before embedding.',22],['COMPARE EMBEDDED OBJECTS','Compute singular values of Y₁ᵀY₂ and take the norm of the principal angles.<br><br>For mixed dimensions, retain min(k₁+1,k₂+1) angles.<br><br>Across dimensions, containment can give zero: this is a dissimilarity, not a separating metric.',20],'Equations (2)-(5). A has orthonormal columns, A^T b_perp=0, so the final homogeneous column is orthogonal to the others and normalized. The paper compares objects of unequal dimension using the smaller number of principal angles. Same-k metric claims should not be silently extended to their union.','Lusk & How · Eqs. (2)–(5)');
eqTwo('pair-shift','05 / the invariance step','Shift the pair before measuring its affine distance.','Raw homogeneous angles depend on the coordinate origin.',R`(b_1,b_2)\longmapsto\left(0,\frac{b_2-b_1}{\rho}\right)`,['WHY TRANSLATION CANCELS',M(R`(Rb_2+t)-(Rb_1+t)=R(b_2-b_1)` )+'Then project the shifted displacement orthogonally and form the embedding.'],['WHY THE SCALE MATTERS','ρ controls how positions compare with directions.<br><br>Large separations otherwise saturate angular distances. Use the same ρ and pair order in both scans.'],'Proposition 1 and Appendix A. Stored affine anchors must transform consistently. Do not first replace each anchor by a scan-origin closest point and then assume its difference transforms by R alone. The toy transports anchors and exposes explicit perturbations; actual feature extraction is outside its scope.','Lusk & How · Proposition 1 · §III-A');
eqTwo('consistency','05 / constructing the graph','A vertex is a match. An edge is agreement.','Candidate u = (i,j) means object Aᵢ might correspond to object Bⱼ.',R`c_{uv}=|d(A_i,A_p)-d(B_j,B_q)|,\quad M_{uv}=e^{-c_{uv}^2/(2\sigma^2)}\ \text{if }c_{uv}<\epsilon`,['CANDIDATES','Match lines to lines, and planes to planes.<br><br>But an internal pair may contain a line and a plane; its consistency informs both matches.'],['HARD EXCLUSIONS','Set Muv = 0 if c ≥ ε, or if two candidates reuse the same object.<br><br>Set Muu = 1. The matrix is symmetric.'],'Equation (8). Distances compare two objects within scan A against their proposed counterparts within scan B, not unregistered objects across scans. The unknown relative pose is absent from the pair-consistency scoring. One-to-one exclusions must be enforced explicitly.','Lusk & How · Eq. (8) · Fig. 3');
eqTwo('density','05 / selecting associations','Maximize weighted density, not just match count.','A weakly connected larger clique may score worse than a smaller strong one.',R`\max_{u\in\{0,1\}^m\setminus\{0\}}\frac{u^\top Mu}{u^\top u}\quad\text{s.t. }u_i u_j=0\ \text{when }M_{ij}=0`,['A SMALL EXAMPLE','Two vertices with weight 1 have density 2.<br><br>Add a third vertex with weights 0.1 to each: density drops to 1.8.'],['PAPER AND BROWSER','The paper uses the CLIPPER relaxation.<br><br>This small demo enumerates every feasible clique, including nonmaximal cliques, to solve the displayed discrete objective exactly.'],'Equation (9), with diagonal ones included. The three-vertex example has total matrix sum 5.4 and density 1.8. Maximizing cardinality is a distinct objective. Exhaustive enumeration is suitable only for this bounded synthetic graph and does not claim CLIPPER scalability.','Lusk & How · Eq. (9) · CLIPPER');
visual('association','05 / paper experiment','Recover the shared objects from a scrambled scene.','Six true objects. Two distractors. No initial pose supplied to matching.','CONTROLLED MIXED-OBJECT DEMO','<b>Scan A:</b> 3 lines + 3 planes.<br><b>Scan B:</b> the same objects, reordered and transformed, plus 2 distractors.<br><br><b>24 candidate matches.</b><br>With no noise, the 6 true matches form a unit-weight clique: density 6.<br><br>Change pose, noise, ρ, and ε. Compare shifted, raw, and direction-only scores.','graph','The candidate graph is constructed only from object geometry and type. Ground-truth identities evaluate the solution but are not supplied to scoring or optimization. The diagram and static numbers are generated by the same tested model as the lab. The no-noise density 6 attains the upper bound imposed by six source objects and weights at most one.','Lusk & How · synthetic Eq. (8)–(9) experiment');live('association','association');
two('paper-scope','05 / interpreting the result','Association is one stage of the paper’s pipeline.','A synthetic recovery result is not a loop-closure benchmark.', ['IMPLEMENTED IN THIS DEMO','Affine embedding; shift and scale.<br><br>Pairwise consistency and exclusions.<br><br>Exact weighted clique selection on 24 candidates.<br><br>Ground-truth recovery shown only for evaluation.',20],['THE PAPER GOES FURTHER','Extract lines and planes from lidar.<br><br>Use CLIPPER for association.<br><br>Estimate rotation and translation from matched objects, then evaluate loop closures on KITTI.<br><br>These stages are not run in the browser.',20],'The paper uses rho=40m, epsilon=.2, sigma=.02 for KITTI. Demo defaults are rho=3m, epsilon=.16rad, sigma=.05rad. Noise perturbs synthetic anchors and directions. Eq. (10) is a downstream matched line/plane registration problem. There is no claim to reproduce benchmark performance, extract features, or certify geometric observability from the selected count.','Lusk & How · §III-C–IV');
two('pitfalls','06 / distinctions to keep','Five distinctions keep the geometry honest.','Every one is visible somewhere in the experiments.', ['GEOMETRY','<b>Basis ≠ subspace.</b> Use equivalence classes.<br><br><b>Sphere ≠ Grassmannian.</b> Identify antipodes for real lines.<br><br><b>Linear ≠ affine.</b> Offsets need additional coordinates.'],['COMPUTATION','<b>Path length ≠ shortest distance</b> after a cut point.<br><br><b>Count ≠ weighted density</b> in the association objective.<br><br>Also state radians, projector normalization, and real versus complex conventions.'],'These distinctions prevent frequent visualization and implementation errors. For the association paper, also distinguish same-type candidate edges from mixed-type within-scan comparisons and a dissimilarity across dimensions from a metric on a single fixed-k Grassmannian.');
two('formula-sheet','06 / keep this page','A compact computational reference.','Real orthonormal bases; equal subspace dimensions unless stated otherwise.', ['REPRESENT · COMPARE',M(R`[Q]=\{QO:O\in O(k)\},\quad P=QQ^\top`)+M(R`\theta_i=\arccos\sigma_i(Q^\top Y)`)+M(R`d_g=\|\theta\|_2,\qquad d_p=\|\sin\theta\|_2`)+M(R`\dim\mathrm{Gr}(k,n)=k(n-k)`),22],['MOVE · OPTIMIZE',M(R`Q^\top\Delta=0,\quad\Pi_Q(Z)=(I-P)Z`)+M(R`g(\Delta_1,\Delta_2)=\operatorname{tr}(\Delta_1^\top\Delta_2)`)+M(R`\operatorname{grad}f=(I-P)\nabla f`)+M(R`Q_+=\operatorname{qf}(Q-\eta\operatorname{grad}f)`),21],'The gradient expression assumes a smooth right-orthogonally invariant objective and the canonical horizontal Frobenius metric. Units of angles in distance calculations are radians. For affine association, additionally shift corresponding anchors before homogeneous embedding and keep the scale fixed across scans.');
add('references','Primary sources / further reading','Follow the formulas back to their sources.','The guide includes implementation details, numerical checks, and all five labs.',[
 ...[['01','A Grassmann Manifold Handbook','Bendokat, Zimmermann & Absil · quotient geometry, exp/log, cut locus','https://arxiv.org/abs/2011.13699'],['02','The Geometry of Algorithms with Orthogonality Constraints','Edelman, Arias & Smith (1998) · §2.5 geometry; §4.5 distances','https://arxiv.org/abs/physics/9806030'],['03','Global Data Association for SLAM with 3D Grassmannian Manifold Objects','Lusk & How (2022) · the supplied paper; Eqs. (2)–(9), Proposition 1','https://arxiv.org/pdf/2205.08556']].flatMap(([n,title,sub,link],i)=>{const y=190+i*124;return[B('ref-'+n,72,y,1136,106,i===2?C.soft:C.paper),T('ref-no-'+n,93,y+23,40,30,n,{fontFamily:mono,fontSize:16,color:C.gold}),T('ref-title-'+n,147,y+18,1030,32,title+' ↗',{fontSize:21,fontFamily:serif,link}),T('ref-sub-'+n,148,y+61,1010,24,sub,{fontSize:14,color:C.muted})];}),
 T('guide',72,585,510,30,'Companion guide & all experiments ↗',{fontSize:18,color:C.teal,link:'https://bailiping.com/grassmannian/'}),T('clipper',636,585,270,30,'Authors’ CLIPPER code ↗',{fontSize:17,color:C.teal,link:'https://github.com/mit-acl/clipper'}),T('pdf',951,585,257,30,'Printable PDF ↗',{fontSize:17,color:C.teal,align:'right',link:'https://bailiping.com/grassmannian-slides/grassmannian.pdf'})
],'Primary sources were reviewed against the displayed mathematical conventions. Handbook notation Gr(n,k) reverses this deck’s argument order. Original illustrations and original browser implementations are educational companions; no figures or benchmark results from the papers are reproduced here.','Geometry · computation · reproducibility');
for(const [i,s]of slides.entries())s.elements.push(T('page',943,682,82,20,String(i+1).padStart(2,'0')+' / '+slides.length,{fontFamily:mono,fontSize:10,color:C.muted,align:'center'}));
slides[0].elements.find(e=>e.id==='cover-count').html=slides.length+' SLIDES / FIVE LIVE EXPERIMENTS';
export const deck={format:'bento/slides',version:1,docId:'grassmannian-manifold',title:'Grassmannian Manifold',readonly:true,size:{width:1280,height:720},theme:{background:C.bg,color:C.ink,accent:C.teal,fontFamily:sans},meta:{author:'Bai Liping',subject:'Grassmannian geometry and affine data association'},slides};
