import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
import {deck,inlineLiveMap} from './bento-deck.mjs';

const here=dirname(fileURLToPath(import.meta.url));
const template=await readFile(resolve(here,'../kalman-filter-derivations/index.html'),'utf8');
const safe=value=>JSON.stringify(value,null,1).replaceAll('<','\\u003c');

if(deck.format!=='bento/slides'||deck.size.width!==1280||deck.size.height!==720)throw new Error('Invalid Bento document envelope');
const slideIds=new Set(deck.slides.map(s=>s.id));
if(slideIds.size!==deck.slides.length)throw new Error('Duplicate slide id');
for(const [i,s] of deck.slides.entries()){
  if(!s.notes)throw new Error('Missing notes: '+s.id);
  const ids=new Set();
  for(const e of s.elements){
    if(ids.has(e.id))throw new Error('Duplicate element '+s.id+'/'+e.id);
    ids.add(e.id);
    if(e.x<0||e.y<0||e.x+e.w>1281||e.y+e.h>721)throw new Error('Out of slide: '+s.id+'/'+e.id);
    if(e.link&&!/^https?:/.test(e.link)&&!slideIds.has(e.link))throw new Error('Broken slide link '+s.id+'/'+e.id+' → '+e.link);
  }
  // The shared extension appendix carries its own page counter.
  if(s.id!=='s-extensions')s.elements.push({id:'slide-number',type:'text',x:940,y:684,w:82,h:20,html:`${String(i+1).padStart(2,'0')} / ${deck.slides.length}`,fontSize:10,fontFamily:'monospace',color:'#66756E',align:'center'});
}
for(const entry of inlineLiveMap){
  const index=deck.slides.findIndex(s=>s.id===entry.slide);
  const intro=deck.slides.findIndex(s=>s.id===entry.introSlide);
  if(index<0||intro!==index-1)throw new Error('Live slide must immediately follow its intro: '+entry.slide);
  if(entry.slideIndex!==index)throw new Error('Incorrect live slide index: '+entry.slide);
  const marker=deck.slides[index].elements.find(e=>e.id==='live-demo-mount');
  if(!marker)throw new Error('Missing live-demo-mount: '+entry.slide);
  const b=entry.bounds;
  if(marker.x!==b.x||marker.y!==b.y||marker.w!==b.width||marker.h!==b.height)throw new Error('Live marker/bounds mismatch: '+entry.slide);
}

const pattern=/(<script type="application\/bento\+json" id="bento-doc">\s*)[\s\S]*?(\s*<\/script>)/;
if(!pattern.test(template))throw new Error('Bento template document not found');
let html=template.replace(pattern,(_,a,b)=>a+safe(deck)+b);
const mapPattern=/<script type="application\/json" id="bento-inline-live-map">[\s\S]*?<\/script>/;
if(!mapPattern.test(html))throw new Error('Bento inline-live map not found');
html=html.replace(mapPattern,()=>'<script type="application/json" id="bento-inline-live-map">\n'+safe(inlineLiveMap)+'\n</script>');

const routes=Object.fromEntries(deck.slides.map((s,i)=>[s.id,i]));
const routeScript=`<script>(()=>{const routes=${JSON.stringify(routes)};function routeToSlide(){let r;try{r=decodeURIComponent(location.hash.replace(/^#\\/?/,''));}catch{return;}if(r&&!/^\\d+$/.test(r)&&Number.isInteger(routes[r]))history.replaceState(null,'',location.pathname+location.search+'#/'+routes[r]);}addEventListener('hashchange',routeToSlide);routeToSlide();})();</script>`;
let routeReplaced=false;
html=html.replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/g,(full,attrs,body)=>{
  if(!attrs.trim()&&body.includes('const routes =')&&body.includes('routeToSlide')){routeReplaced=true;return routeScript;}
  return full;
});
if(!routeReplaced)throw new Error('Template route mapper not found');

html=html.replace(/<title>[\s\S]*?<\/title>/,'<title>See how samplers think | Bai Liping</title>');
html=html.replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${deck.slides.length} Bento slides on Monte Carlo sampling with ${inlineLiveMap.length} live labs: Gibbs, Metropolis–Hastings, HMC, slice, rejection, importance sampling and a particle filter checked against an exact Kalman filter." />`);
html=html.replace(/<link rel="canonical"[^>]*>/,'<link rel="canonical" href="https://bailiping.com/sampling-playground/" />');
html=html.replace(/<!-- Generated by kalman-filter-derivations[^>]*-->/,'<!-- Generated by sampling-playground/build-bento.mjs. Edit bento-deck.mjs or model.js, then rebuild. -->');
html=html.replace(/<link[^>]+href="visual\.css[^"]*"[^>]*>/,'');
html=html.replace('</head>',`<style id="sampling-layout">
.bento-slide .bento-text-inner{text-rendering:optimizeLegibility;}
.bento-slide a:focus-visible{outline:3px solid #496E87;outline-offset:4px;}
.bento-slide .math-display{height:auto!important;min-height:0;margin:.45em 0;}
.bento-slide .bento-text-inner>.math-display:first-child{margin-top:.05em;}
.bento-slide .bento-text-inner>.math-display:last-child{margin-bottom:.05em;}
</style>\n</head>`);
if(!html.includes('tex-svg-full.js')||!html.includes('mathjax-dynamic.js')||!html.includes('bento-inline-live.js'))throw new Error('Required shared runtime missing');

html=html.replace('</body>','<script src="print.js"></script></body>');
const staticSlides=deck.slides.map((s,i)=>`<article class="static-page"><span>${i+1} / ${deck.slides.length}</span>${s.elements.filter(e=>e.type==='text'&&!e.id.startsWith('chrome')&&e.id!=='slide-number').map(e=>e.id==='heading'?`<h1>${e.html}</h1>`:`<div>${e.html}</div>`).join('')}${s.elements.filter(e=>e.id==='fallback').map(e=>`<img alt="${e.alt}" src="${e.src}">`).join('')}</article>`).join('');
html=html.replace('<body>','<body><noscript><style>.static-page{padding:30px;max-width:1100px;margin:20px auto;background:#fff;color:#203129;font:18px/1.5 system-ui}.static-page img{width:100%}.static-page>div{margin:12px 0}</style>'+staticSlides+'</noscript>');
html=html.replace(/[ \t]+$/gm,'');
await writeFile(resolve(here,'index.html'),html);
console.log(`Built ${deck.slides.length} sampling slides and ${inlineLiveMap.length} live laboratories (${html.length} characters).`);
console.log('Slide routes: '+deck.slides.map(s=>s.id).join(', '));
