// Canonical slide content. Presentation layout matches the site's Random Thoughts decks.
import {models,chartSVG} from './model.mjs';
const R=String.raw, P=s=>`<p>${s}</p>`, esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const M=s=>`<span class="math-tex math-display">\\[${esc(s)}\\]</span>`;
const I=s=>`<span class="math-tex math-inline">\\(${esc(s)}\\)</span>`;
const C={paper:'#F5F3ED',panel:'#FFFDFA',ink:'#182D33',muted:'#60747A',rule:'#D6DEDC',teal:'#16736E',soft:'#E4F0ED',coral:'#C2573F',warm:'#F7E8E1'};
const sans='Inter,Arial,sans-serif',serif="Georgia,'Times New Roman',serif",mono='Consolas,monospace';
export const paper='https://arxiv.org/abs/2506.00838';
const slides=[],labs=[];
function text(id,x,y,w,h,html,o={}){return {id,type:'text',x,y,w,h,rotation:0,opacity:1,html,fontSize:18,fontFamily:sans,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.4,...o};}
function box(id,x,y,w,h,fill=C.panel){return {id,type:'shape',shape:'rect',x,y,w,h,rotation:0,opacity:1,fill,stroke:C.rule,strokeWidth:1,radius:12};}
function panel(id,x,y,w,h,label,body,fill=C.soft,size=18){return [box(id+'-box',x,y,w,h,fill),text(id+'-label',x+22,y+18,w-44,27,label,{fontFamily:mono,fontSize:12,fontWeight:700,color:C.teal}),text(id+'-body',x+22,y+61,w-44,h-79,body,{fontSize:size})];}
function slide(id,section,title,subtitle,elements,notes,source='Worked explanation · based on §§5–6'){const s={id,background:C.paper,transition:'none',notes,lessonTitle:title,lessonSubtitle:subtitle,sourceLabel:source,elements:[text('eyebrow',72,32,1136,24,section.toUpperCase(),{fontFamily:mono,fontSize:12,fontWeight:700,color:C.coral}),text('heading',72,70,1136,53,title,{fontFamily:serif,fontSize:35,fontWeight:700,lineHeight:1.1}),text('subtitle',72,131,1136,42,subtitle,{fontSize:16,color:C.muted}),...elements,box('footer-rule',72,669,1136,1,C.rule),text('footer-home',72,684,270,20,'BAI LIPING · RANDOM THOUGHTS',{fontFamily:mono,fontSize:10,color:C.muted,link:'https://bailiping.com/'}),text('footer-source',345,684,560,20,source,{fontSize:10,color:C.muted,link:paper,align:'center'}),text('footer-notes',1020,684,94,20,'READ NOTES',{fontSize:10,color:C.teal,link:'./study.html#'+id}),text('footer-index',1120,684,88,20,'CONTENTS',{fontSize:10,color:C.teal,align:'right',link:'overview'})]};slides.push(s);return s;}
function pair(id,section,title,sub,a,A,b,B,notes,source,size=18){return slide(id,section,title,sub,[...panel('left',72,190,548,452,a,A,C.soft,size),...panel('right',644,190,564,452,b,B,C.panel,size)],notes,source);}
function cards(id,section,title,sub,items,notes,source){return slide(id,section,title,sub,items.flatMap(([a,A],i)=>panel('card'+i,72+i*382,190,358,452,a,A,i===1?C.panel:C.soft,18)),notes,source);}
function live(id,intro,demo,title,sub,instructions,notes){const result=models[demo]();slide(id,'Interactive laboratory · '+(labs.length+1)+' / 4',title,sub,[...panel('guide',72,180,268,475,'TRY → OBSERVE → EXPLAIN',P(instructions)+P('<b>Computed default snapshot</b>')+P('Use the controls in presentation mode. Print and study notes preserve this calculated view.'),C.soft,15),box('chart-bg',352,180,856,475),{id:'model-figure',type:'image',x:363,y:195,w:830,h:335,rotation:0,opacity:1,src:'./figures/'+demo+'.svg',fit:'contain',alt:title},text('legend',375,535,808,28,result.curves.map(c=>c.name).join(' · '),{fontSize:12,color:C.muted}),...result.metrics.flatMap(([a,b],i)=>[box('metric'+i,363+i*278,576,265,68,C.paper),text('metric-value'+i,375+i*278,583,240,27,b,{fontSize:21,fontWeight:700,color:C.teal}),text('metric-label'+i,375+i*278,615,240,22,a,{fontSize:11})]),{...box('live-demo-mount',72,180,1136,475),opacity:0}],notes,'Original numerical example · finite-grid approximation');labs.push({slide:id,introSlide:intro,demo,title});}
const hero=models.reconstruction({order:4});
slide('overview','Paper walkthrough · arXiv:2506.00838','Beyond the Gaussian belief.','Max Entropy Moment Kalman Filter for Polynomial Systems with Arbitrary Noise',[
 ...panel('hero',72,190,548,262,'MEM-KF · THE CORE IDEA',P('<b>Propagate moments.</b><br>Reconstruct a distribution.<br>Update its polynomial energy.')+P('A paper walkthrough with four working numerical laboratories.'),C.soft,24),
 box('hero-chart-bg',644,190,564,262),{id:'hero-chart',type:'image',x:654,y:200,w:544,h:238,rotation:0,opacity:1,src:'./figures/reconstruction.svg',fit:'contain',alt:'A bimodal density and its fourth-order maximum-entropy reconstruction'},
 ...[['01 · REPRESENT','Moment constraints → maximum entropy','max-entropy'],['02 · COMPUTE','Prediction → likelihood → posterior','polynomial-lift'],['03 · EXPERIMENT','Four browser-local numerical labs','reconstruction-live']].flatMap(([a,b,link],i)=>[...panel('route'+i,72+i*382,474,358,168,a,P(b),i===1?C.panel:C.soft,18),text('route-link'+i,94+i*382,603,305,26,'EXPLORE →',{fontFamily:mono,fontSize:12,color:C.teal,link})])
],'This is a teaching companion, not the authors’ implementation or a reproduction of their robotics experiments. Read the first half to understand the probability representation, then follow one prediction and one update before trying the complete scalar filter. Green curves are the richer representation; coral curves are a target or reference, except in the sensor lab where coral denotes a Gaussian sensor approximation. Every lab identifies its finite integration interval and displays numerical diagnostics. Source: Sangli Teng, Harry Zhang, David Jin, Ashkan Jasour, Ram Vasudevan, Maani Ghaffari, and Luca Carlone, arXiv:2506.00838v1, June 1, 2025.','Teng et al. · arXiv:2506.00838v1 · 2025');

pair('why-moments','1 · Motivation','The mean can sit where almost nothing is likely.','A simple counterexample: two narrow, equally weighted modes.',
 'WHAT TWO MOMENTS REMEMBER',M(R`X\sim\tfrac12\mathcal N(-a,s^2)+\tfrac12\mathcal N(a,s^2)`)+M(R`\mathbb E[X]=0,\quad \mathbb E[X^2]=a^2+s^2`)+P('A moment-matched Gaussian puts its mode at zero. The mixture may have a deep valley there.'),
 'WHAT A FOURTH MOMENT ADDS',M(R`\mathbb E[X^4]=a^4+6a^2s^2+3s^4`)+M(R`\mathbb E[G^4]=3(a^2+s^2)^2`)+P('The difference is '+I(R`2a^4`)+'. The first two moments do not encode the missing shape.'),
 'Derive the fourth moment by writing each mixture component as plus or minus a plus s times a standard normal variable. Odd terms vanish by symmetry. A centered Gaussian with the same variance has fourth moment three times the variance squared, giving a difference of 2a^4. This original example explains why more moments can distinguish distributions that a mean-and-covariance description cannot. It does not assert that every fourth-order maximum-entropy fit recovers an arbitrary mixture exactly.','Original worked mixture example');

cards('paper-map','1 · Reading the paper','Three operations, three different questions.','Keep representation, inference, and point estimation separate.',[
 ['REPRESENT',P('Use an exponential of a polynomial to encode a moment-constrained maximum-entropy belief.')+P('<b>Question:</b> which density matches these moments?')],
 ['FILTER',P('Predict moments through polynomial dynamics. Incorporate measurements by adding likelihood energy.')+P('<b>Question:</b> what is the posterior distribution?')],
 ['EXTRACT',P('Optimize the posterior polynomial energy. Moment-SDP relaxations can provide bounds and certificates.')+P('<b>Question:</b> where is a posterior mode?')]
],'The paper’s MED coefficients, predicted moments, and MAP point are distinct objects. Optimizing the coefficients is a convex parameter-estimation problem. Searching for a mode is generally a nonconvex polynomial problem, handled through convex relaxations. A correct implementation must not confuse the moment sequence representing a probability density with the relaxation moments used to optimize its energy.','Paper roadmap · §§5–6');

pair('notation','1 · Set up the problem','Fix the state, support, and noise model first.','The teaching derivations use additive, state-independent noise.',
 'POLYNOMIAL SYSTEM',M(R`x_{k+1}=f(x_k,u_k,w_k)`)+M(R`y_k=g(x_k)+v_k`)+P('The functions '+I(R`f`)+ ' and '+I(R`g`)+ ' are polynomial. Noise is independent of the current state and fresh across time.'),
 'BELIEF AND MOMENTS',M(R`m_{\alpha,k}=\mathbb E[x_k^\alpha],\qquad m_{0,k}=1`)+M(R`p_\lambda(x)=Z(\lambda)^{-1}e^{-\lambda^\top\phi(x)}`)+P('Here '+I(R`\phi`)+ ' excludes the constant term. '+I(R`Z`)+ ' carries normalization. The support and base measure are part of the model.'),
 'For several variables, alpha is a multi-index and x to alpha is the product of coordinate powers. The paper permits a more general polynomial residual h(y,x)=v and polynomial equality-constrained states. This deck begins with additive measurement noise because its likelihood has an unambiguous unit Jacobian. Every expectation requires that the relevant moment exists. In the labs the integration measure is approximated with trapezoidal weights, not with an unweighted array of density heights.','Notation · paper §4; normalized convention');

pair('moment-problem','2 · Representation','A finite moment vector is not a unique distribution.','Maximum entropy chooses a representative; it does not invent extra observations.',
 'THE CONSTRAINTS',M(R`\int_Kp(x)\,dx=1,\quad p(x)\geq0`)+M(R`\int_K\phi_j(x)p(x)\,dx=m_j`)+P('Many densities can satisfy the same finite list. Feasibility is a separate question from fitting.'),
 'THE SELECTION RULE',M(R`p^*=\arg\max_p\left[-\int_Kp(x)\log p(x)\,dx\right]`)+P('Choose the least additional structure allowed by the constraints and the chosen reference measure.')+P('More moments reduce the feasible family, but increase numerical burden.'),
 'Entropy is not invariant to an arbitrary change of coordinates unless the reference measure is transformed consistently. Consequently the support and coordinates cannot be left implicit. On a finite grid, an interior feasible moment target has a well-behaved maximum-entropy solution. On unbounded continuous domains, existence, integrability, and limiting arguments need additional conditions. The paper’s asymptotic claim concerns moment-determinate distributions, not every conceivable heavy-tailed law.','Worked interpretation · paper §5.1');

pair('max-entropy','2 · Representation','The constraints become a polynomial energy.','A Lagrange multiplier for each moment gives an exponential family.',
 'STATIONARITY IN THE DENSITY',M(R`-\log p(x)-1-\lambda_0-\lambda^\top\phi(x)=0`)+M(R`p_\lambda(x)=\frac{e^{-\lambda^\top\phi(x)}}{Z(\lambda)}`)+P('For monomial features, the negative log density is a polynomial plus a constant.'),
 'ORDER TWO AND ORDER FOUR',M(R`p_2(x)\propto e^{-\lambda_1x-\lambda_2x^2}`)+M(R`p_4(x)\propto e^{-\lambda_1x-\cdots-\lambda_4x^4}`)+P('On '+I(R`\mathbb R`)+', a normalizable quadratic energy is Gaussian. A quartic energy can have two wells.'),
 'Vary the entropy Lagrangian with respect to p and solve the pointwise stationarity equation. Absorb the constant multiplier into the partition function. On the real line, a positive quadratic coefficient is needed for the quadratic family to integrate. A positive quartic leading term gives integrable tails even when the quadratic term is negative. On a bounded interval, the corresponding order-two family is generally a truncated exponential-quadratic density, not literally the unrestricted Gaussian.','Derivation · paper §5.2, Eq. (3)');

pair('convex-dual','2 · Representation','A convex solve makes the moments agree.','Eliminate the constant multiplier and optimize the log partition function.',
 'NORMALIZED DUAL',M(R`F(\lambda)=\log Z(\lambda)+\lambda^\top m`)+M(R`\nabla F=m-\mathbb E_{p_\lambda}[\phi]`)+P('At the optimum, the gradient is zero: requested and reconstructed moments agree.'),
 'WHY IT IS CONVEX',M(R`\nabla^2F=\operatorname{Cov}_{p_\lambda}[\phi]\succeq0`)+P('The Hessian is a covariance matrix. Redundant features may make it singular.')+P('The paper keeps the constant coefficient; its equivalent dual has an unnormalized moment-matrix Hessian.'),
 'The paper writes an integral of the unnormalized exponential plus the multiplier-moment inner product. Minimizing over its constant coefficient yields this normalized log-partition dual, up to an additive constant. Differentiating log Z once gives minus the feature expectation, and differentiating again yields feature covariance. The browser solver uses theta=-lambda and scaled Legendre features, so its gradient is E[phi]-m. This is the same convex problem in another polynomial basis, not a different belief family.','Derived normalized dual · paper Eqs. (4)–(5)');

pair('convex-not-unimodal','2 · A crucial distinction','Convex in coefficients does not mean unimodal in state.','The optimizer variable and the random variable are different.',
 'A TWO-WELL ENERGY',M(R`E(x)=(x^2-a^2)^2`)+M(R`p(x)\propto e^{-E(x)}`)+P('For '+I(R`a>0`)+', the density has modes at '+I(R`x=\pm a`)+'. Its negative log density is not a convex function of '+I(R`x`)+'.'),
 'TWO DIFFERENT OPTIMIZATIONS',P('<b>Fit the distribution:</b> vary the coefficient vector while matching moments.')+P('<b>Find a mode:</b> hold coefficients fixed and vary the state.')+P('The first problem is convex. The second can have several globally optimal answers.'),
 'Differentiating E gives 4x(x^2-a^2), so the stationary points are zero and plus/minus a. At zero the second derivative is negative when a is positive; at plus/minus a it is positive. Thus the state energy has two minima while the maximum-entropy coefficient-fitting dual remains convex. No contradiction is involved. This distinction prevents the misleading claim that the entire posterior is log-concave merely because its coefficients were obtained by a convex solver.','Original quartic example');

pair('reconstruction-guide','3 · Laboratory 1 · setup','How much shape is hiding in higher moments?','Reconstruct a two-component mixture from only its moment constraints.',
 'CHANGE THE INFORMATION',M(R`p_{\rm target}=\pi\mathcal N(-a,0.48^2)+(1-\pi)\mathcal N(a,0.48^2)`)+P('Move the modes apart. Compare '+I(R`r=2,4,6,8`)+'. Change the mixture weight to reveal asymmetry.'),
 'READ THE DIAGNOSTICS',P('<b>Moment residual:</b> maximum mismatch in scaled Legendre features.')+P('<b>KL divergence:</b> shape discrepancy on this grid, not a filtering error guarantee.')+P('<b>Numerics:</b> 401 points on [−5, 5], trapezoidal weights, damped Newton and line search.'),
 'The target mixture is renormalized on the lab interval before its moments are measured. The solver fits a genuine finite-quadrature maximum-entropy model by optimizing log-sum-exp, not a hand-designed curve. It uses all polynomial features through the selected order, including odd features. Increasing the order enlarges the exponential family and, for an accurately solved feasible problem with the same target and support, cannot increase the optimal forward KL divergence. This does not imply monotonic point-estimation accuracy.','Original lab · MED principle in paper §5');
live('reconstruction-live','reconstruction-guide','reconstruction','Fit the same density with more information.','The green curve is optimized in your browser—not selected from a gallery.', 'Start at r = 2. Increase to 4, then 8. Move the separation and weight sliders. Does a small moment residual imply a small shape error?', 'The default is a symmetric mixture with separation 1.5 and component standard deviation 0.48. Target and model are compared on a fixed quadrature grid. A low residual certifies only approximate satisfaction of the selected grid moments. It is not a statement about unmeasured moments, tails outside the interval, or global filtering error.');

pair('polynomial-lift','4 · Prediction','Powers of a polynomial are still polynomials.','Prediction can be written as algebra on moments.',
 'LIFT THE DYNAMICS',M(R`\phi_r(f(x,u,w))=A(u,w)\phi_s(x)`)+M(R`m^-_{k+1}=\mathbb E_w[A(u_k,w)]m_k`)+P('State–noise independence lets mixed expectations factor.'),
 'PAY ATTENTION TO THE ORDER',M(R`s\leq r\,\deg_x f`)+P('A quadratic transition may need state moments through '+I(R`2r`)+ ' to predict through '+I(R`r`)+'.')+P('Obtain those higher moments from the current fitted belief. Truncating them without a closure rule changes the algorithm.'),
 'The lifted relation is exact algebra when all required moments exist and are supplied accurately. Exact propagation relative to the current fitted belief is not the same as exact propagation of the unknown true posterior. Reconstruction introduces a finite-order approximation, and numerical integration may introduce another one. A finite vector of stored moments alone need not close under nonlinear dynamics; the fitted density supplies the higher moments requested by the next step.','Worked interpretation · paper §6.3, Eqs. (8)–(9)');

pair('prediction-guide','4 · Laboratory 2 · setup','Work one nonlinear prediction all the way through.','Use a quadratic state transition and independent uniform process noise.',
 'THE MODEL',M(R`X^+=aX+b(X^2-1)+W,\quad a=0.7`)+M(R`W\sim U[-0.4,0.4]`)+M(R`\mathbb E[X^+]=a m_1+b(m_2-1)`)+P('The noise has zero mean and variance '+I(R`0.4^2/3`)+'.'),
 'THE SECOND MOMENT',M(R`\mathbb E[(X^+)^2]=a^2m_2+2ab(m_3-m_1)`)+M(R`\quad+b^2(m_4-2m_2+1)+0.4^2/3`)+P('Higher output moments use the same expansion. No linearization and no Monte Carlo are required.'),
 'Expand the square of aX+b(X^2-1)+W. Independence and E[W]=0 remove its cross terms. The fourth input moment already appears in the second output moment. The implementation generalizes the expansion by multiplying polynomial coefficient arrays and applying the binomial theorem for independent additive noise. It uses input moments through 2r even when b=0, where that bound is conservative. The coral reference separately evaluates the pushforward density using the uniform-noise kernel.','Original worked polynomial example');
live('prediction-live','prediction-guide','prediction','Propagate first. Reconstruct second.','Exact polynomial moment algebra; approximate finite-order density reconstruction.', 'Increase the quadratic coefficient b. Compare r = 2 with r = 6. Notice that matching moments does not make the entire pushforward exact.', 'The input is a truncated, slightly asymmetric two-component mixture on [-2.5,2.5]. The uniform noise support and slider range keep the exact pushforward inside [-3,4]. The reference uses deterministic quadrature over the input state and the exact uniform kernel; its edges have small grid artifacts. The green fit uses independently propagated raw moments, transformed into the solver’s Legendre basis.');

pair('update-coefficients','5 · Measurement update','Bayes multiplication becomes energy addition.','Once the measurement is fixed, its residual is a polynomial in the state.',
 'SUBSTITUTE THE RESIDUAL',M(R`p_v(v)\propto e^{-\mu^\top\psi(v)}`)+M(R`L_y(x)=p_v(y-g(x))\propto e^{-\nu(y)^\top\phi(x)}`)+P('Expand the composed polynomial in a common basis.'),
 'ADD, THEN NORMALIZE',M(R`p^+(x)\propto p^-(x)L_y(x)`)+M(R`\lambda^+=\lambda^-+\nu(y)`)+P('Pad missing degrees with zeros. Recompute the normalizer and the moments needed for the next prediction.'),
 'These formulas describe a posterior density, not just a MAP estimate. Multiplying exponentials adds their energies. Constants independent of x affect the normalizer but not the location of a mode. If the sensor energy has degree r_v and g has degree d, the resulting state energy may have degree r_v times d; this need not equal the prediction reconstruction order. The complete scalar lab has a quartic posterior likelihood even when prediction is reconstructed using only order two.','Worked derivation · paper §6.4, Eqs. (10)–(12)');

pair('likelihood-caveat','5 · Model carefully','A residual density is not automatically a likelihood.','The simple substitution is safe for the additive model used in these demos.',
 'ADDITIVE OBSERVATION',M(R`y=g(x)+v`)+M(R`p(y\mid x)=p_v(y-g(x))`)+P('For fixed x, the transformation from y to v has unit Jacobian.'),
 'GENERAL RESIDUAL MODEL',M(R`v=h(y,x)`)+M(R`p(y\mid x)=p_v(h(y,x))\left|\det\frac{\partial h}{\partial y}\right|`)+P('This local formula needs an appropriate invertible transformation. An x-dependent Jacobian cannot be dropped.'),
 'This is a modeling qualification, not a claim that all residual equations in robotics are invalid. For equal-dimensional invertible changes of observation coordinates, the usual change-of-variables determinant is required. Noninvertible maps and dimension-changing constraints require an explicit observation measure and more care. In the paper’s planar localization rearrangement, multiplication by a proper rotation has determinant one. The additive sensor examples in this deck deliberately avoid this ambiguity.','Original modeling check · relates to paper Eq. (11)');

pair('update-guide','5 · Laboratory 3 · setup','Let a sensor keep its two plausible explanations.','Compare a quartic-noise likelihood with its moment-matched Gaussian approximation.',
 'NON-GAUSSIAN SENSOR',M(R`p_v(v)\propto\exp\left[-\frac{(v^2-a^2)^2}{2s^2}\right]`)+M(R`y_i=x+v_i,\quad s=0.35`)+P('One observation can favor both '+I(R`x\approx y_i-a`)+ ' and '+I(R`x\approx y_i+a`)+'.'),
 'ACCUMULATE EVIDENCE',M(R`E_N(x)=\frac{x^2}{2(1.8)^2}+\sum_{i=1}^N\frac{((y_i-x)^2-a^2)^2}{2s^2}`)+P('The green posterior is computed from this energy. The coral baseline replaces the sensor distribution—not the state likelihood—with a Gaussian.'),
 'The symbol s here sets the quartic energy scale; it is not the standard deviation of v. The lab calculates the sensor variance by quadrature before constructing the Gaussian baseline. Observations are a deliberately fixed sequence around alternating modes for a static state x=0.6; they are not claimed to be random draws from the sensor density. Both methods receive exactly the same observations and prior. A grid argmax is displayed only as an approximate mode, never as an SDP-certified estimate.','Original quartic sensor example');
live('update-live','update-guide','update','One reading, two explanations. More readings, less ambiguity.','Move through a fixed observation sequence and compare posterior shapes.', 'Begin with one observation. Add the second. Compare the posterior mean with the highest peak, then change the sensor mode separation.', 'The normalizer is recomputed after each batch of observations. The gray curve is the original prior, green is the quartic sensor posterior, and coral is the Gaussian sensor approximation posterior. Blue marks the known synthetic truth. The same truth is not supplied to either inference calculation. The integration interval is [-4,4] with 501 points.');

cards('filter-loop','6 · Put the pieces together','The filter alternates two representations.','Moments are convenient for prediction; energy coefficients are convenient for correction.',[
 ['01 · PREDICT',P('Integrate the current belief for the moments required by the transition.')+P('Apply polynomial moment algebra.')+P('Fit a new maximum-entropy prediction at order r.')],
 ['02 · CORRECT',P('Compose the sensor energy with the observed residual.')+P('Add it to the prior energy.')+P('Normalize; retain the resulting belief for the next step.')],
 ['03 · REPORT',P('Keep the full belief when ambiguity matters.')+P('Compute a mean for squared-error loss, or extract a mode for MAP.')+P('Label numerical approximations and any optimization certificate separately.')]
],'The update does not require a Kalman gain. The analogy with a Kalman filter is the recursive predict–correct structure, not a promise that nonlinear filtering is a finite closed-form recursion. The current exponential-polynomial density can be integrated to obtain more moments than were originally constrained at prediction. Those extra moments come from the chosen maximum-entropy representative, and therefore include a closure assumption.','Algorithmic reading · paper Algorithm 1');

pair('filter-guide','6 · Laboratory 4 · setup','Can the filter preserve an unresolved sign?','A squared observation sees magnitude but does not directly reveal the sign of x.',
 'A COMPLETE SCALAR SYSTEM',M(R`x_{k+1}=0.92x_k+u+w_k`)+M(R`y_k=x_k^2+v_k`)+P(I(R`w_k\sim\mathcal N(0,0.14^2)`)+', '+I(R`v_k\sim\mathcal N(0,0.23^2)`)+'. The prior is centered and broad.'),
 'WHAT TO COMPARE',P('With u = 0, symmetry should remain. With u = 0.18, known motion can help distinguish signs.')+P('Compare prediction orders 2, 4, and 6 on the same seeded sequence.')+P('The coral reference performs direct grid Bayes prediction. It is numerical—not ground-truth continuous Bayes.'),
 'The synthetic trajectory begins at +1.2, but the estimator receives only the broad zero-mean prior. A seeded generator produces the process and measurement noise. With zero control and an even initial belief, every transition and likelihood preserves reflection symmetry, so no correct filter should claim to know the sign. A nonzero known control changes this identifiability. At every step the MEM path integrates its posterior moments, propagates through the affine transition, reconstructs a maximum-entropy prediction, then multiplies by the quartic likelihood induced by y-x^2.','Original end-to-end MEM-KF teaching model');
live('filter-live','filter-guide','filter','Follow a full predict–correct cycle.','Both algorithms see the same measurements; neither is given the truth.', 'Step forward with zero control. Change prediction order without changing the data. Then turn on known drift. Does an apparently precise mean conceal two peaks?', 'This is a genuine scalar implementation of the predict–reconstruct–correct architecture, but not the authors’ SE(2) solver. The comparison uses 321 points on [-4,4]. It reports L1 discrepancy between quadrature masses, the last prediction’s moment-fit residual, and the largest raw mass truncation discrepancy in the grid reference. Order denotes prediction reconstruction order, not the degree of the post-measurement energy.');

pair('mean-map','7 · Estimation','A belief, a mean, and a mode answer different questions.','A single number cannot faithfully summarize every multimodal posterior.',
 'SQUARED-ERROR DECISION',M(R`\hat x_{\rm mean}=\mathbb E[x\mid y]`)+P('The posterior mean minimizes expected squared error.')+P('For a symmetric two-mode belief it is zero, even when zero has little density.'),
 'DENSITY-MAXIMIZING DECISION',M(R`\hat x_{\rm MAP}\in\arg\max_{x\in K}p(x\mid y)`)+M(R`=\arg\min_{x\in K}E(x)`)+P('A MAP estimate can select one of several equal peaks. That selection does not remove the uncertainty.'),
 'Expand E[(x-a)^2 | y] into posterior variance plus (E[x|y]-a)^2 to obtain the mean’s squared-error optimality. MAP is tied to density relative to the chosen coordinates and measure. In the symmetric filter lab there may be equally plausible positive and negative modes; the grid argmax may return the first by indexing convention. That is not evidence for the negative sign. The paper’s point-extraction step specifically targets a posterior mode.','Decision-theoretic interpretation · paper §6.5');

pair('certification','7 · Optimization guarantees','A convex relaxation is not automatically an exact MAP solve.','The polynomial energy can be nonconvex even though its SDP relaxation is convex.',
 'BOUND THE POLYNOMIAL MINIMUM',M(R`\min_{x\in K}E(x)`)+P('A moment-SDP relaxation gives a lower bound on this minimum.')+P('A feasible extracted state gives an upper bound. A small gap is meaningful evidence.'),
 'STATE THE CERTIFICATE',P('An appropriate rank/extraction condition can certify global optimality.')+P('Without tightness, report the bound and gap rather than declaring an exact mode.')+P('<b>These browser labs use a grid argmax and do not solve an SDP.</b>'),
 'The paper discusses a rank-one solution as a sufficient extraction certificate. More general moment hierarchies use flatness conditions to extract finite collections of minimizers; a problem with multiple global minima need not have a unique rank-one moment solution. A certificate concerns optimization of the represented posterior energy. It does not certify that a finite-order reconstructed posterior equals the true filtering distribution, nor that a MAP point is minimum-MSE.','Paper §6.5 and Appendix A · guarantee boundary');

pair('kalman-special-case','8 · Connect to familiar filters','The Gaussian case is a quadratic-energy calculation.','Linear dynamics + linear observations + Gaussian beliefs close at order two.',
 'INFORMATION-FORM CORRECTION',M(R`E^-(x)=\tfrac12(x-m^-)^\top(P^-)^{-1}(x-m^-)`)+M(R`E_y(x)=\tfrac12(y-Hx)^\top R^{-1}(y-Hx)`)+P('Adding these energies keeps the result quadratic.'),
 'COLLECT THE COEFFICIENTS',M(R`(P^+)^{-1}=(P^-)^{-1}+H^\top R^{-1}H`)+M(R`m^+=P^+[(P^-)^{-1}m^-+H^\top R^{-1}y]`)+P('This is the familiar Kalman correction in information form.'),
 'Expand both quadratic forms and collect the coefficients of x transpose x and x. Constants independent of x are absorbed into the normalizer. This derivation assumes positive-definite covariance matrices and Euclidean coordinates. The familiar exact Kalman closure relies on Gaussian initialization and Gaussian noise as well as linear models; a Gaussian approximation to genuinely non-Gaussian noise does not become exact just because the model is linear.','Original quadratic derivation · paper Remark 3');

pair('association','8 · Why robotics cares','Unknown landmark identity creates a mixture.','Do not collapse a correspondence ambiguity before representing it.',
 'REARRANGE A PLANAR OBSERVATION',M(R`y=R^\top(L_i+v-p)`)+M(R`Ry+p=L_i+v`)+P('Unknown landmark identity i produces a multimodal effective sensor variable.'),
 'ENCODE THE AMBIGUITY IN MOMENTS',M(R`p(v_L)=\sum_i\pi_i\,\mathcal N(v_L;L_i,\Sigma)`)+P('Moment constraints describe the effective noise without committing to one landmark.')+P('The rotation still obeys '+I(R`c^2+s^2=1`)+'. A planar pose is not an unconstrained vector.'),
 'This slide connects the scalar multimodal sensor intuition to the paper’s SE(2) example. The paper uses equal landmark probabilities in its maximum-entropy association model and also evaluates a mismatched association frequency scenario. A moment representation does not magically infer arbitrary unknown association probabilities; the assumed probabilities and noise moments remain modeling inputs. The browser labs do not implement this constrained multidimensional localization experiment.','Paper §7.3, Eqs. (17)–(18)');

cards('paper-results','8 · Evidence and interpretation','What the paper tests—and what the demos do not claim.','Separate reported experiments from this independent teaching implementation.',[
 ['DENSITY RECONSTRUCTION',P('Increasing moment order recovers more of the shapes in the paper’s numerical examples.')+P('<b>Read:</b> Figure 2 and Appendix H.')],
 ['ACCUMULATED OBSERVATIONS',P('Higher-order sensor models preserve multiple modes. Small-sample point errors need not improve monotonically.')+P('<b>Read:</b> Figure 3 and Table 1.')],
 ['ROBOT LOCALIZATION',P('The paper compares MEM-KF with Gaussian-filter baselines and a particle filter in landmark-association experiments.')+P('<b>Read:</b> §7.3 and Appendix H.3.')]
],'No performance numbers in these labs are presented as reproductions of the authors’ results. The model dimensions, sensor distributions, quadrature, optimizers, and synthetic sequences differ. The paper’s own small-sample discussion warns that multimodality can make a point estimate’s empirical error worse even when the represented distribution is richer. A useful reading question is whether the result concerns density approximation, MAP objective value, estimation error, or runtime: these are different axes.','Reported scope · paper §7, Table 1, Appendix H');

cards('limits','9 · Read the guarantees precisely','“Arbitrary noise” still has mathematical requirements.','Finite-order practical filtering is an approximation, not a universal exact Bayes filter.',[
 ['MOMENTS & EXISTENCE',P('Required moments must exist and be feasible.')+P('Moment determinacy and existence of the relevant MED matter in asymptotic claims.')+P('A Cauchy noise law has no finite variance.')],
 ['DIMENSION & NUMERICS',M(R`\#\{x^\alpha:|\alpha|\leq r\}=\binom{n+r}{r}`)+P('Degree and dimension increase both coefficient count and integration cost.')+P('Scaling, quadrature, and conditioning remain central.')],
 ['THREE ERROR SOURCES',P('<b>Model error:</b> incorrect dynamics, moments, or associations.')+P('<b>Representation error:</b> finite-order MED closure.')+P('<b>Numerical error:</b> integration, fitting, and optimization relaxation.')]
],'The word arbitrary signals departure from a Gaussian-only noise assumption, not the removal of existence and integrability conditions. Higher-order moments grow quickly and may be unstable when estimated from limited data. Increasing r can improve expressiveness while making estimation and numerical conditioning harder. Polynomial state constraints require a suitable measure and consistency relations among moments. Numerical quadrature replaces a difficult symbolic marginalization; it does not eliminate integration from the method.','Critical reading · paper §§5–6 and conclusion');

pair('implementation','9 · Reproducibility','Know exactly what the browser is solving.','All four labs are deterministic, local, and inspectable.',
 'IMPLEMENTED HERE',P('Finite trapezoidal quadrature with explicit support.')+P('Legendre-basis log-partition fitting, covariance Hessian, damped Newton, and line search.')+P('Exact polynomial expansion relative to supplied moments; normalized likelihood updates; a grid-Bayes comparison.'),
 'NOT IMPLEMENTED HERE',P('Adaptive multidimensional integration, manifold integration, or the authors’ SE(2) experiment.')+P('Semidefinite programming or a global MAP certificate.')+P('The displayed residual uses scaled feature moments. A small residual alone says nothing about tail truncation.'),
 'The model source is model.mjs and the tests are test.mjs. The build generates a static SVG for each lab from exactly the same functions used by the interactive controls. This makes printed slides honest computed snapshots instead of decorative illustrations. The filter reference reports raw prediction mass loss on the finite interval; the other labs use fixed normalized intervals explicitly stated in their controls. Browser tests check the native Bento document, the four iframe integrations, keyboard navigation, plot changes, MathJax rendering, and narrow-screen laboratory layout.','Original implementation and test contract');

slide('references','10 · Keep exploring','Read the source. Inspect the model. Keep the belief.','A paper companion with worked explanations, not an alternative statement of the paper.',[
 ...panel('reference',72,190,738,452,'PRIMARY PAPER',P('<b>Max Entropy Moment Kalman Filter for Polynomial Systems with Arbitrary Noise</b>')+P('Sangli Teng · Harry Zhang · David Jin · Ashkan Jasour · Ram Vasudevan · Maani Ghaffari · Luca Carlone')+P('arXiv:2506.00838v1 · June 1, 2025')+P('§5: maximum entropy<br>§6: filtering and MAP extraction<br>§7 + Appendix H: numerical experiments'),C.panel,20),
 ...panel('next',834,190,374,452,'COMPANION MATERIAL','',C.soft),
 ...[['Open the paper →',paper],['Read the study notes →','./study.html'],['Open all live laboratories →','./live.html'],['Inspect model source →','./model.mjs'],['Back to Random Thoughts →','https://bailiping.com/']].map(([label,link],i)=>text('reference-link'+i,856,270+i*61,330,44,label,{fontSize:17,color:C.teal,link}))
],'Reference checked against arXiv version 1. The slides’ scalar examples, numerical code, and explanatory derivations are original teaching material built around the paper’s ideas. No author-provided code is embedded. The actual Bento runtime and site-shared live-slide adapter are retained from the existing Random Thoughts presentation format, with their original license notices.','Primary reference · arXiv:2506.00838v1');

for(const [i,s] of slides.entries()){s.elements.unshift({...box('progress-bg',0,0,1280,4,C.rule),strokeWidth:0,radius:0},{...box('progress-fill',0,0,1280*(i+1)/slides.length,4,C.teal),strokeWidth:0,radius:0});s.elements.push(text('slide-number',920,684,85,20,`${String(i+1).padStart(2,'0')} / ${slides.length}`,{fontFamily:mono,fontSize:10,color:C.muted,align:'center'}));}
export const deck={format:'bento/slides',version:1,docId:'mem-kf-bento',title:'Beyond the Gaussian Belief · MEM-KF',readonly:true,meta:{author:'Bai Liping',subject:'Paper walkthrough: maximum-entropy moment filtering, polynomial prediction, non-Gaussian updates, and four live labs',company:'bailiping.com'},size:{width:1280,height:720},theme:{background:C.paper,color:C.ink,accent:C.teal,fontFamily:sans},slides};
export const inlineLiveMap=labs.map(e=>({...e,slideIndex:slides.findIndex(s=>s.id===e.slide),src:'./live.html?embed=1&demo='+e.demo,source:'./model.mjs',inline:true,layout:'region',bounds:{x:72,y:180,width:1136,height:475},readyMessage:true,hideSource:true,unloadWhenHidden:false}));
