'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'mem-kf-qa');fs.mkdirSync(out,{recursive:true});
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),doc=JSON.parse(html.match(/<script type="application\/bento\+json" id="bento-doc">([\s\S]*?)<\/script>/)[1]),maps=JSON.parse(html.match(/<script type="application\/json" id="bento-inline-live-map">([\s\S]*?)<\/script>/)[1]);
const errors=[],warnings=[],checks=[];
const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403);return res.end();}try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');const mime={'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2','.json':'application/json','.md':'text/plain'}[path.extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':mime});fs.createReadStream(file).pipe(res);}catch{res.writeHead(404);res.end('Not found');}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/mem-kf/`,browser=await chromium.launch({headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1280,height:720},reducedMotion:'reduce'});if(process.env.MATHJAX_BUNDLE)await context.route('**/tex-svg-full.js',r=>r.fulfill({path:process.env.MATHJAX_BUNDLE,contentType:'text/javascript'}));const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});
async function active(id){await page.waitForSelector(`section.present .bento-slide[data-slide-id="${id}"]`,{timeout:30000});return page.locator(`section.present .bento-slide[data-slide-id="${id}"]`).last();}
async function go(i){await page.goto('about:blank');await page.goto(base+'#/'+i,{waitUntil:'domcontentloaded'});await page.waitForSelector('.bento-slide',{state:'attached',timeout:30000});if(!await page.locator('section.present .bento-slide').count()){const b=page.getByRole('button',{name:/present/i}).first();if(await b.count())await b.click();}const r=await active(doc.slides[i].id);await page.waitForFunction(()=>typeof window.MathJax?.tex2svgPromise==='function',null,{timeout:30000});await page.waitForTimeout(450);await page.waitForFunction(()=>[...document.querySelectorAll('section.present .math-tex')].every(n=>n.querySelector('mjx-container')),null,{timeout:30000});return r;}
try{
 for(let i=0;i<doc.slides.length;i++){const s=doc.slides[i],r=await go(i);assert.equal(await r.locator('[data-mml-node="merror"],mjx-merror').count(),0,'MathJax error '+s.id);const bad=await r.evaluate(el=>[...el.querySelectorAll('.bento-text-inner')].flatMap(n=>{const box=n.closest('.bento-el-text').getBoundingClientRect(),range=document.createRange();range.selectNodeContents(n);const content=range.getBoundingClientRect();return content.bottom>box.bottom+4||content.right>box.right+4?[{text:n.textContent.slice(0,140),box:{x:box.x,y:box.y,w:box.width,h:box.height},content:{x:content.x,y:content.y,w:content.width,h:content.height}}]:[];}));if(bad.length)warnings.push({slide:s.id,overflow:bad});await page.screenshot({path:path.join(out,String(i+1).padStart(2,'0')+'-'+s.id+'.png')});checks.push('slide '+s.id);}
 for(const m of maps){const r=await go(m.slideIndex),iframe=r.locator('iframe');await iframe.waitFor();const frame=await(await iframe.elementHandle()).contentFrame();await frame.waitForFunction(()=>window.memDemo);assert.equal(await frame.evaluate(()=>window.memDemo.name),m.demo);const input=frame.locator('input[type="range"]').first();await input.focus();const before=await input.inputValue(),url=page.url();await input.press('ArrowRight');await page.waitForTimeout(180);assert.equal(page.url(),url,'range stole navigation');assert.notEqual(await input.inputValue(),before);await input.press('Escape');await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>document.activeElement?.classList.contains('reveal')),'Escape focus');await frame.locator('#next-slide').click();await active(doc.slides[m.slideIndex+1].id);checks.push('embedded navigation '+m.demo);await go(m.slideIndex);await page.emulateMedia({media:'print'});const stage=page.locator(`.bento-slide[data-slide-id="${m.slide}"] .companion-demo-stage`).last();assert.equal(await stage.evaluate(e=>getComputedStyle(e).display),'none');assert.ok(await page.locator(`.bento-slide[data-slide-id="${m.slide}"] img`).count());await page.emulateMedia({media:'screen'});checks.push('print snapshot '+m.demo);}
 for(const m of maps){await page.setViewportSize({width:1136,height:475});await page.goto(base+'live.html?embed=1&demo='+m.demo);await page.waitForFunction(()=>window.memDemo);const original=await page.evaluate(()=>window.memDemo.values);for(const input of await page.locator('input[type="range"],select').all()){const cfg=await input.evaluate(e=>({key:e.name,values:e.type==='range'?[e.min,e.max]:[...e.options].map(o=>o.value)}));for(const value of cfg.values){await input.evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},value);await page.waitForFunction(({key,value})=>String(window.memDemo.values[key])===value,{key:cfg.key,value});assert.ok(!/NaN|Infinity|undefined/.test(await page.locator('#plot').innerHTML()));assert.ok(await page.locator('#error').isHidden());}}await page.locator('#reset').click();assert.deepEqual(await page.evaluate(()=>window.memDemo.values),original);const size=await page.evaluate(()=>({h:document.documentElement.scrollHeight,w:document.documentElement.scrollWidth}));if(size.h>479||size.w>1140)warnings.push({demo:m.demo,embeddedOverflow:size});await page.screenshot({path:path.join(out,'lab-'+m.demo+'.png'),fullPage:true});checks.push('all controls '+m.demo);await page.setViewportSize({width:390,height:844});await page.goto(base+'live.html?demo='+m.demo);await page.waitForFunction(()=>window.memDemo);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'mobile overflow '+m.demo);await page.screenshot({path:path.join(out,'mobile-'+m.demo+'.png'),fullPage:true});checks.push('mobile '+m.demo);}
 await page.setViewportSize({width:1100,height:850});await page.goto(base+'study.html');await page.waitForFunction(()=>typeof window.MathJax?.tex2svgPromise==='function');await page.waitForFunction(()=>[...document.querySelectorAll('.math-tex')].every(n=>n.querySelector('mjx-container')),null,{timeout:60000});assert.equal(await page.locator('[data-mml-node="merror"]').count(),0);assert.equal(await page.locator('main>section').count(),28);await page.screenshot({path:path.join(out,'study.png')});checks.push('study notes and equations');
 assert.deepEqual(errors,[],'browser errors');fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({slides:28,labs:4,checks,errors,warnings},null,2));console.log(JSON.stringify({slides:28,labs:4,checks:checks.length,errors,warnings},null,2));if(warnings.length)throw Error('Layout warnings require correction');
}catch(e){fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,errors,warnings,failure:String(e),url:page.url()},null,2));fs.writeFileSync(path.join(out,'failure-dom.html'),await page.content());await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
