// Original, deterministic teaching models for arXiv:2506.00838.
// Masses live on a finite trapezoidal quadrature grid. No SDP is implemented.
export const sum = a => a.reduce((s,x)=>s+x,0);
export function grid(lo=-5,hi=5,n=401){const dx=(hi-lo)/(n-1);return {lo,hi,dx,x:Array.from({length:n},(_,i)=>lo+i*dx),w:Array.from({length:n},(_,i)=>dx*(i===0||i===n-1?.5:1))};}
export function distribution(g,logDensity){const z=g.x.map((x,i)=>logDensity(x)+Math.log(g.w[i]));const m=Math.max(...z);const a=z.map(x=>Math.exp(x-m)),s=sum(a);if(!(s>0))throw Error('Distribution is not normalizable on the grid');return a.map(x=>x/s);}
export function moments(g,p,r){return Array.from({length:r+1},(_,j)=>sum(p.map((v,i)=>v*g.x[i]**j)));}
export function gaussianMoment(j,mu=0,sigma=1){const m=[1,mu];for(let k=2;k<=j;k++)m[k]=mu*m[k-1]+(k-1)*sigma*sigma*m[k-2];return m[j];}
export function choose(n,k){let a=1;for(let j=1;j<=k;j++)a=a*(n-j+1)/j;return a;}
export function polynomialProduct(a,b){const c=Array(a.length+b.length-1).fill(0);a.forEach((v,i)=>b.forEach((w,j)=>c[i+j]+=v*w));return c;}
export function propagate(m,coeff,noise,r){let power=[1];const fp=[1];for(let j=1;j<=r;j++){power=polynomialProduct(power,coeff);if(power.length>m.length)throw Error('Insufficient input moments');fp[j]=sum(power.map((v,k)=>v*m[k]));}return Array.from({length:r+1},(_,j)=>sum(Array.from({length:j+1},(_,k)=>choose(j,k)*fp[k]*noise[j-k])));}
function legendre(g,r){const c=(g.hi+g.lo)/2,h=(g.hi-g.lo)/2;const polys=[[1],[-c/h,1/h]];for(let j=2;j<=r;j++){const a=polynomialProduct(polys[j-1],[-c/h,1/h]).map(v=>v*(2*j-1)/j);polys[j-2].forEach((v,k)=>a[k]-=(j-1)/j*v);polys.push(a);}const features=g.x.map(x=>{const t=(x-c)/h,p=[1,t];for(let j=2;j<=r;j++)p[j]=((2*j-1)*t*p[j-1]-(j-1)*p[j-2])/j;return p.slice(1,r+1);});return {polys:polys.slice(1,r+1),features};}
function solve(A,b){const n=b.length,a=A.map((row,i)=>[...row,b[i]]);for(let k=0;k<n;k++){let q=k;for(let i=k+1;i<n;i++)if(Math.abs(a[i][k])>Math.abs(a[q][k]))q=i;[a[k],a[q]]=[a[q],a[k]];if(Math.abs(a[k][k])<1e-18)throw Error('Singular Newton system');for(let i=k+1;i<n;i++){const f=a[i][k]/a[k][k];for(let j=k;j<=n;j++)a[i][j]-=f*a[k][j];}}const x=Array(n).fill(0);for(let i=n-1;i>=0;i--)x[i]=(a[i][n]-sum(a[i].slice(i+1,n).map((v,k)=>v*x[i+1+k])))/a[i][i];return x;}
export function fitMED(g,m,r,{tol=2e-8,maxIter=100}={}){
 if(!Number.isInteger(r)||r<1||m.length<=r)throw Error('Invalid moment order');
 const {polys,features}=legendre(g,r),target=polys.map(a=>sum(a.map((v,k)=>v*m[k])));let theta=Array(r).fill(0),iterations=0;
 function evaluate(t,hessian=false){const log=features.map((f,i)=>sum(f.map((v,j)=>v*t[j]))+Math.log(g.w[i])),z=Math.max(...log),a=log.map(v=>Math.exp(v-z)),s=sum(a),p=a.map(v=>v/s),mean=Array(r).fill(0);for(let i=0;i<p.length;i++)for(let j=0;j<r;j++)mean[j]+=p[i]*features[i][j];const grad=mean.map((v,j)=>v-target[j]),obj=z+Math.log(s)-sum(t.map((v,j)=>v*target[j]));let H;if(hessian){H=Array.from({length:r},()=>Array(r).fill(0));for(let i=0;i<p.length;i++)for(let j=0;j<r;j++)for(let k=0;k<=j;k++)H[j][k]+=p[i]*(features[i][j]-mean[j])*(features[i][k]-mean[k]);for(let j=0;j<r;j++){for(let k=0;k<j;k++)H[k][j]=H[j][k];H[j][j]+=1e-11;}}return {p,grad,obj,H};}
 for(;iterations<maxIter;iterations++){const q=evaluate(theta,true);if(Math.max(...q.grad.map(Math.abs))<tol)break;const d=solve(q.H,q.grad),gd=sum(q.grad.map((v,j)=>v*d[j]));let step=1,accepted=false;for(let k=0;k<35;k++){const trial=theta.map((v,j)=>v-step*d[j]),e=evaluate(trial);if(e.obj<=q.obj-1e-4*step*gd+1e-14){theta=trial;accepted=true;break;}step*=.5;}if(!accepted)break;}
 const q=evaluate(theta),residual=Math.max(...q.grad.map(Math.abs));return {p:q.p,theta,residual,iterations,converged:residual<tol*5,order:r};
}
export function l1(p,q){return sum(p.map((v,i)=>Math.abs(v-q[i])));}
export function kl(p,q){return sum(p.map((v,i)=>v>0?v*Math.log(v/Math.max(q[i],1e-300)):0));}
export function stats(g,p){const m=moments(g,p,2),i=p.indexOf(Math.max(...p));return {mean:m[1],variance:Math.max(0,m[2]-m[1]**2),map:g.x[i],edge:p[0]+p.at(-1)};}
export function reconstruction({order=4,separation=1.5,weight=.5}={}){const g=grid(-5,5),s=.48;const p=distribution(g,x=>Math.log(weight*Math.exp(-.5*((x+separation)/s)**2)+(1-weight)*Math.exp(-.5*((x-separation)/s)**2)+1e-300));const fit=fitMED(g,moments(g,p,order),order);return {g,reference:p,fit,curves:[{name:'Target mixture',p,color:'#C2573F'},{name:`Max entropy, r=${order}`,p:fit.p,color:'#16736E'}],metrics:[['Moment residual',fit.residual.toExponential(1)],['KL(target ∥ MED)',kl(p,fit.p).toFixed(4)],['Newton iterations',String(fit.iterations)]]};}
export function prediction({order=4,nonlinearity=.25}={}){const input=grid(-2.5,2.5,301),p=distribution(input,x=>Math.log(.45*Math.exp(-.5*((x+1)/.35)**2)+.55*Math.exp(-.5*((x-1)/.4)**2)+1e-300)),noise=Array.from({length:2*order+1},(_,j)=>j%2?0:.4**j/(j+1)),coeff=[-nonlinearity,.7,nonlinearity],m=propagate(moments(input,p,2*order),coeff,noise,order),g=grid(-3,4,501),fit=fitMED(g,m,order),ref=g.x.map(y=>sum(p.map((v,i)=>Math.abs(y-(coeff[0]+coeff[1]*input.x[i]+coeff[2]*input.x[i]**2))<=.4?v/.8:0))*g.dx);const norm=sum(ref),reference=ref.map(v=>v/norm);return {g,fit,reference,predictedMoments:m,input,curves:[{name:'Quadrature pushforward',p:reference,color:'#C2573F'},{name:`Reconstructed MED, r=${order}`,p:fit.p,color:'#16736E'}],metrics:[['Predicted mean',m[1].toFixed(4)],['Input order required',String(2*order)],['Moment residual',fit.residual.toExponential(1)]]};}
export function update({count=1,separation=1}={}){const g=grid(-4,4,501),a=separation,s=.35,truth=.6,offsets=[.08,-.09,.04,.12,-.06,.03,-.08,.01],observations=offsets.map((v,i)=>truth+(i%2?-a:a)+v),prior=distribution(g,x=>-.5*(x/1.8)**2),noiseGrid=grid(-4,4,801),noise=distribution(noiseGrid,v=>-((v*v-a*a)**2)/(2*s*s)),variance=moments(noiseGrid,noise,2)[2],energy=x=>.5*(x/1.8)**2+sum(observations.slice(0,count).map(y=>(((y-x)**2-a*a)**2)/(2*s*s))),p=distribution(g,x=>-energy(x)),gaussian=distribution(g,x=>-.5*(x/1.8)**2-sum(observations.slice(0,count).map(y=>(y-x)**2/(2*variance))));return {g,reference:p,observations,truth,energy,curves:[{name:'Prior',p:prior,color:'#60747A'},{name:'Quartic MED sensor',p,color:'#16736E'},{name:'Gaussian sensor approximation',p:gaussian,color:'#C2573F'}],metrics:[['Observations used',String(count)],['Posterior mean',stats(g,p).mean.toFixed(3)],['Grid MAP (not certified)',stats(g,p).map.toFixed(3)]]};}
function rng(seed){let a=seed|0;return ()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
export function sequence(control=0,steps=10){const random=rng(23),normal=()=>Math.sqrt(-2*Math.log(Math.max(random(),1e-12)))*Math.cos(2*Math.PI*random());const out=[];let x=1.2;for(let k=0;k<steps;k++){x=.92*x+control+.14*normal();out.push({x,y:x*x+.23*normal()});}return out;}
export function filter({order=4,step=3,control=0}={}){const g=grid(-4,4,321),data=sequence(control),initial=distribution(g,x=>-.5*(x/1.2)**2);let p=initial,ref=initial,fit={p,residual:0,iterations:0,converged:true};const history=[];let lost=0;for(let k=0;k<step;k++){const m=propagate(moments(g,p,order),[control,.92],Array.from({length:order+1},(_,j)=>gaussianMoment(j,0,.14)),order);fit=fitMED(g,m,order);const pred=g.x.map((x,i)=>sum(ref.map((v,j)=>v*Math.exp(-.5*((x-.92*g.x[j]-control)/.14)**2)/(.14*Math.sqrt(2*Math.PI))))*g.w[i]);lost=Math.max(lost,Math.abs(1-sum(pred)));const y=data[k].y,logL=x=>-.5*((y-x*x)/.23)**2;p=distribution(g,(x)=>Math.log(Math.max(fit.p[Math.round((x-g.lo)/g.dx)]/g.w[Math.round((x-g.lo)/g.dx)],1e-300))+logL(x));ref=distribution(g,(x)=>Math.log(Math.max(pred[Math.round((x-g.lo)/g.dx)]/g.w[Math.round((x-g.lo)/g.dx)],1e-300))+logL(x));history.push({time:k+1,...stats(g,p),truth:data[k].x,residual:fit.residual,error:l1(p,ref)});}
 return {g,fit,reference:ref,p,history,data,truth:step?data[step-1].x:1.2,lost,curves:[{name:'Grid Bayes reference',p:ref,color:'#C2573F'},{name:`MEM-KF, prediction r=${order}`,p,color:'#16736E'}],metrics:[['Time step',String(step)],['L1 vs grid Bayes',l1(p,ref).toFixed(4)],['Prediction fit residual',fit.residual.toExponential(1)]]};}
export const defaults={reconstruction:{order:4,separation:1.5,weight:.5},prediction:{order:4,nonlinearity:.25},update:{count:1,separation:1},filter:{order:4,step:3,control:0}};
export const models={reconstruction,prediction,update,filter};
export function chartSVG(result,{width=820,height=310,title='Probability density'}={}){const {g,curves}=result,L=56,R=20,T=42,B=48,W=width-L-R,H=height-T-B,max=Math.max(...curves.flatMap(c=>c.p.map((v,i)=>v/g.w[i])))*1.12;const X=x=>L+(x-g.lo)/(g.hi-g.lo)*W,Y=y=>T+H-y/max*H;const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;');let s=`<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${esc(title)}" viewBox="0 0 ${width} ${height}"><rect width="100%" height="100%" rx="10" fill="#FFFDFA"/><g font-family="Arial,sans-serif" font-size="12" fill="#60747A"><text x="${L}" y="21" font-weight="700">${esc(title)}</text>`;for(let i=0;i<=4;i++){const y=max*i/4;s+=`<path d="M${L},${Y(y)}H${width-R}" stroke="#D6DEDC"/><text x="${L-8}" y="${Y(y)+4}" text-anchor="end">${y.toFixed(1)}</text>`;}for(let i=0;i<=6;i++){const x=g.lo+(g.hi-g.lo)*i/6;s+=`<text x="${X(x)}" y="${height-B+22}" text-anchor="middle">${x.toFixed(1)}</text>`;}s+=`<text x="${width-R}" y="${height-8}" text-anchor="end">state x</text></g>`;curves.forEach((c,j)=>{const d=c.p.map((v,i)=>`${i?'L':'M'}${X(g.x[i]).toFixed(2)},${Y(v/g.w[i]).toFixed(2)}`).join('');s+=`<path d="${d}" fill="none" stroke="${c.color}" stroke-width="${j===curves.length-1?2.7:2}" ${j===0?'stroke-dasharray="6 3"':''}/>`;});if(Number.isFinite(result.truth))s+=`<path d="M${X(result.truth)},${T}V${height-B}" stroke="#3F6F91" stroke-width="1.5" stroke-dasharray="3 4"/><text x="${X(result.truth)+5}" y="${T+13}" font-family="Arial" font-size="12" fill="#3F6F91">truth</text>`;return s+'</svg>';}
