import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as M from './model.mjs';
import {deck,inlineLiveMap} from './bento-deck.mjs';
const close=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} != ${b}`);
function valid(q){for(const c of q.curves){assert.ok(c.p.every(v=>Number.isFinite(v)&&v>=0));close(M.sum(c.p),1,1e-10);}if(q.fit)assert.ok(q.fit.converged,`Residual ${q.fit.residual}`);assert.ok(!/NaN|Infinity|undefined/.test(M.chartSVG(q)));}
test('28 regular native Bento slides, notes, unique identifiers, four paired labs',()=>{assert.equal(deck.format,'bento/slides');assert.equal(deck.slides.length,28);assert.equal(inlineLiveMap.length,4);assert.equal(new Set(deck.slides.map(s=>s.id)).size,28);for(const s of deck.slides){assert.ok(s.notes.length>100);assert.ok(!s.stateOf);assert.equal(new Set(s.elements.map(e=>e.id)).size,s.elements.length);for(const e of s.elements){assert.ok(e.x>=0&&e.y>=0&&e.x+e.w<=1280.01&&e.y+e.h<=720.01,s.id+'/'+e.id);}}for(const m of inlineLiveMap){assert.equal(deck.slides[m.slideIndex].id,m.slide);assert.equal(deck.slides[m.slideIndex-1].id,m.introSlide);}});
test('Gaussian moments and independent polynomial propagation agree with direct enumeration',()=>{close(M.gaussianMoment(4,0,2),48);const order=4,states=[-1,2],weights=[.3,.7],m=Array.from({length:2*order+1},(_,j)=>M.sum(states.map((x,i)=>weights[i]*x**j))),noise=Array.from({length:order+1},(_,j)=>j%2?0:.3**j),coeff=[-.2,.7,.25],p=M.propagate(m,coeff,noise,order);for(let j=0;j<=order;j++){const direct=M.sum(states.flatMap((x,i)=>[-.3,.3].map(w=>weights[i]/2*(coeff[0]+coeff[1]*x+coeff[2]*x*x+w)**j)));close(p[j],direct,1e-11);}assert.throws(()=>M.propagate([1,0,1],coeff,noise,4),/Insufficient/);});
test('Order-two maximum entropy recovers a Gaussian on a wide grid',()=>{const g=M.grid(-7,7,801),p=M.distribution(g,x=>-.5*((x-.3)/.9)**2),fit=M.fitMED(g,M.moments(g,p,2),2);assert.ok(fit.converged);assert.ok(M.l1(p,fit.p)<1e-6);});
test('Reconstruction stays normalized and converges over all control extremes',()=>{for(const order of [2,4,6,8])for(const separation of [0,1.5,2.2])for(const weight of [.15,.5,.85])valid(M.reconstruction({order,separation,weight}));});
test('Higher-order maximum entropy reduces forward KL on the fixed target',()=>{let previous=Infinity;for(const order of [2,4,6,8]){const q=M.reconstruction({order}),d=M.kl(q.reference,q.fit.p);assert.ok(d<=previous+1e-7);previous=d;}assert.ok(previous<.02);});
test('Prediction remains feasible over polynomial and order controls',()=>{for(const order of [2,4,6,8])for(const nonlinearity of [0,.25,.4]){const q=M.prediction({order,nonlinearity});valid(q);const actual=M.moments(q.g,q.fit.p,order);for(let j=0;j<=order;j++)close(actual[j],q.predictedMoments[j],2e-4);}});
test('Quartic posterior equals an independently multiplied likelihood',()=>{for(const count of [1,2,8])for(const separation of [.5,1,1.4]){const q=M.update({count,separation});valid(q);const independent=M.distribution(q.g,x=>-.5*(x/1.8)**2+M.sum(q.observations.slice(0,count).map(y=>-(((y-x)**2-separation**2)**2)/(2*.35**2))));assert.ok(M.l1(q.reference,independent)<1e-12);}});
test('Complete filter is deterministic, normalized and symmetric without drift',()=>{assert.deepEqual(M.sequence(),M.sequence());for(const order of [2,4,6]){const q=M.filter({order,step:10});valid(q);assert.ok(M.l1(q.p,[...q.p].reverse())<1e-6);assert.ok(Math.abs(M.stats(q.g,q.p).mean)<1e-6);assert.ok(q.lost<1e-4);valid(M.filter({order,step:10,control:.18}));}});
test('Higher prediction order is closer to grid Bayes in this specific seeded regression',()=>{const a=M.filter({order:2,step:10}),b=M.filter({order:4,step:10});assert.ok(M.l1(b.p,b.reference)<M.l1(a.p,a.reference));});
test('Quadrature-refinement check for the default reconstruction',()=>{const a=M.reconstruction();const g=M.grid(-5,5,801),p=M.distribution(g,x=>Math.log(.5*Math.exp(-.5*((x+1.5)/.48)**2)+.5*Math.exp(-.5*((x-1.5)/.48)**2))),b=M.fitMED(g,M.moments(g,p,4),4);close(M.kl(a.reference,a.fit.p),M.kl(p,b.p),1e-4);});
test('Generated document contains the canonical content and homepage card',async()=>{const html=await readFile(new URL('./index.html',import.meta.url),'utf8'),doc=JSON.parse(html.match(/<script type="application\/bento\+json" id="bento-doc">([\s\S]*?)<\/script>/)[1]);assert.deepEqual(doc,deck);assert.ok(html.includes('bento-inline-live.js'));assert.ok(html.includes('https://bailiping.com/mem-kf/'));const home=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.equal((home.match(/href="\/mem-kf\/"/g)||[]).length,1);assert.ok(home.indexOf('href="/mem-kf/"')>home.indexOf('id="group-random-thoughts"'));});
