// Bento source for One Graph, Many Hypotheses. No build dependencies.
const C={paper:'#F7F5EF',panel:'#FFFEFB',ink:'#203129',muted:'#66756E',rule:'#D8DED7',green:'#2F6B4F',soft:'#E7F0EA',rust:'#A94F2A',warm:'#F5E8DF',blue:'#496E87',cool:'#E7EEF3',amber:'#986B22'};
const serif="Georgia, 'Times New Roman', serif",sans="Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",mono="'SFMono-Regular', Consolas, monospace";
const R=String.raw;
const M=s=>`<span class="math-tex math-display">\\[${s}\\]</span>`;
const I=s=>`<span class="math-tex math-inline">\\(${s}\\)</span>`;
function text(id,x,y,w,h,html,o={}){return {id,type:'text',x,y,w,h,rotation:0,opacity:1,html,fontSize:18,fontFamily:sans,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.4,...o};}
function box(id,x,y,w,h,fill=C.panel,stroke=C.rule,o={}){return {id,type:'shape',shape:'rect',x,y,w,h,fill,stroke,strokeWidth:1,radius:14,rotation:0,opacity:1,...o};}
function line(id,x,y,dx,dy,color=C.rule,width=2,o={}){const length=Math.hypot(dx,dy);return {id,type:'shape',shape:'line',x:x+dx/2-length/2,y:y+dy/2-width/2,w:length,h:width,fill:color,stroke:'none',strokeWidth:0,radius:0,rotation:Math.atan2(dy,dx)*180/Math.PI,opacity:1,...o};}
function circle(id,x,y,size,fill=C.panel,stroke=C.green,o={}){return {id,type:'shape',shape:'ellipse',x,y,w:size,h:size,fill,stroke,strokeWidth:2,rotation:0,opacity:1,...o};}
function panel(id,x,y,w,h,label,html,o={}){return [box(id+'-bg',x,y,w,h,o.fill||C.panel,o.stroke||C.rule),text(id+'-label',x+22,y+17,w-44,23,label,{fontFamily:mono,fontSize:11,fontWeight:800,color:o.accent||C.green,letterSpacing:.8}),text(id+'-body',x+22,y+57,w-44,h-73,html,{fontSize:o.size||19,lineHeight:1.45,...(o.body||{})})];}
function chrome(source){return [box('chrome-rule',72,669,1136,1,C.rule,C.rule,{radius:0}),text('chrome-home',72,684,278,20,'BAI LIPING · ESTIMATION NOTES',{fontFamily:mono,fontSize:10,color:C.muted,link:'https://bailiping.com/'}),text('chrome-source',350,684,580,21,source||'iSAM · iSAM2 · MH-iSAM2',{fontFamily:mono,fontSize:10,color:C.muted,align:'center'}),text('chrome-index',1032,684,176,20,'CONTENTS ↗',{fontFamily:mono,fontSize:10,color:C.green,align:'right',link:'overview'})];}
function slide(id,section,title,sub,elements,notes,source='[K11] Kaess et al. · [M19] Hsiao & Kaess',transition='none'){return {id,background:C.paper,transition,notes,elements:[text('eyebrow',72,35,1110,23,section.toUpperCase(),{fontFamily:mono,fontSize:11,fontWeight:800,color:C.rust,letterSpacing:1.3}),text('heading',72,70,1136,58,title,{fontFamily:serif,fontSize:38,fontWeight:700,lineHeight:1.05}),text('subtitle',72,129,1136,44,sub,{fontSize:16,color:C.muted,lineHeight:1.35}),...elements,...chrome(source)]};}
function two(id,section,title,sub,leftLabel,left,rightLabel,right,notes,source,o={}){return slide(id,section,title,sub,[...panel(id+'-left',72,188,548,422,leftLabel,left,{fill:o.leftFill||C.soft,size:o.leftSize||19,accent:o.leftAccent||C.green,body:o.leftBody}),...panel(id+'-right',644,188,564,422,rightLabel,right,{fill:o.rightFill||C.panel,size:o.rightSize||19,accent:o.rightAccent||C.rust,body:o.rightBody})],notes,source,o.transition||'none');}
function three(id,section,title,sub,cards,notes,source){return slide(id,section,title,sub,cards.flatMap(([label,body,fill,accent],i)=>panel(id+'-'+i,72+i*382,188,358,422,label,body,{fill,accent,size:17})),notes,source);}
function sheet(id,title,sub,items,notes,source){return slide(id,'Equation sheet',title,sub,items.flatMap(([label,body],i)=>panel(id+'-'+i,72+(i%2)*578,184+Math.floor(i/2)*231,558,211,label,body,{size:21,body:{valign:'middle',align:'center'},fill:i%2?C.panel:C.soft})),notes,source);}
function node(id,x,y,label,o={}){return [circle(id+'-dot',x,y,o.size||42,o.fill||C.panel,o.stroke||C.green),text(id+'-label',x,y+(o.size||42)/2-10,o.size||42,20,label,{fontFamily:mono,fontSize:o.fontSize||12,fontWeight:750,align:'center',valign:'middle',color:o.color||C.ink})];}
function nativeTable(id,x,y,w,h,headers,rows,o={}){return {id,type:'table',x,y,w,h,rotation:0,opacity:1,header:true,columns:(o.columns||headers.map(()=>1)).map(w=>({w})),rows:[{cells:headers.map(html=>({html}))},...rows.map(row=>({cells:row.map(html=>({html}))}))],style:{headerBg:o.headerBg||C.green,headerColor:'#FFFFFF',zebra:o.zebra||C.soft,borderColor:C.rule,borderWidth:1,cellPadX:o.padX||13,cellPadY:o.padY||10,fontSize:o.fontSize||16,color:C.ink,fontFamily:sans,radius:12}};}
function callout(id,x,y,w,h,html,o={}){return [box(id+'-bg',x,y,w,h,o.fill||C.warm,o.stroke||C.rust,{radius:10}),text(id+'-text',x+16,y+12,w-32,h-24,html,{fontSize:o.size||15,fontWeight:o.weight||650,color:o.color||C.ink,valign:'middle',align:o.align||'left',lineHeight:1.35})];}
function liveFallback(id,title,kicker,body,diagram=[]){return [box(id+'-fallback',72,180,1136,475,C.panel,C.rule),text(id+'-fallback-kicker',96,205,1088,20,kicker,{fontFamily:mono,fontSize:11,fontWeight:800,color:C.rust,letterSpacing:1}),text(id+'-fallback-title',96,237,1088,40,title,{fontFamily:serif,fontSize:28,fontWeight:700}),text(id+'-fallback-body',96,287,380,300,body,{fontSize:17,lineHeight:1.5}),...diagram,box('live-demo-mount',72,180,1136,475,'rgba(255,255,255,0)','rgba(255,255,255,0)',{opacity:0})];}

const slides=[];

slides.push(slide('overview','A reading map','One Graph, Many Hypotheses','iSAM → iSAM2 → MH-iSAM2: reuse computation through time, then share it across alternatives.',[
 text('cover-title',77,194,684,112,'Reuse the work.<br><span style="color:#A94F2A">Keep the alternatives.</span>',{fontFamily:serif,fontSize:46,fontWeight:700,lineHeight:1.08,fx:{enter:'fade-up',order:0}}),
 text('cover-copy',78,313,650,63,'From a sparse least-squares system to a Bayes tree, then to several plausible maps.',{fontSize:18,color:C.muted,lineHeight:1.5}),
 ...[['01','iSAM','incremental QR','problem',C.soft],['02','iSAM2','Bayes-tree locality','bayes-tree',C.cool],['03','MH-iSAM2','discrete ambiguity','ambiguity',C.warm]].flatMap(([n,t,d,link,fill],i)=>[box('cover-card-'+i,72+i*236,408,218,106,fill),text('cover-card-title-'+i,91+i*236,424,180,29,n+' · '+t,{fontFamily:serif,fontSize:21,fontWeight:700,link}),text('cover-card-copy-'+i,91+i*236,465,180,31,d,{fontFamily:mono,fontSize:11,color:C.muted,link})]),
 box('cover-map-bg',808,194,400,422,C.panel,C.rule),
 text('cover-map-label',830,211,356,23,'ONE ESTIMATE → MANY',{fontFamily:mono,fontSize:11,fontWeight:800,color:C.green,letterSpacing:.8}),
 text('cover-map-formula',840,302,336,118,M(R`\delta^*=\arg\min_\delta\lVert A\delta-b\rVert^2`),{fontSize:22,align:'center',valign:'middle'}),
 text('cover-map-factor',840,484,336,32,'<b>factorization</b> → Bayes tree',{fontSize:20,align:'center'}),
 text('cover-map-modes',840,544,336,32,'<b>mode history</b> → Hypo-tree',{fontSize:20,align:'center'}),
 text('cover-labs',76,593,690,29,'3 LIVE LABS · QR ↗  ·  TREE ↗  ·  BRANCHING ↗',{fontFamily:mono,fontSize:12,color:C.green,link:'isam'})
],'Use the chapter cards to jump. The deck follows Kaess et al. (2011) for iSAM2 and Hsiao & Kaess (2019) for MH-iSAM2. The three browser experiments are deterministic teaching models, not reproductions of paper datasets.','[K11] iSAM2 · [M19] MH-iSAM2'));

slides.push(two('problem','01 · iSAM foundations','The graph is the problem. iSAM is a solver.','Smoothing retains the trajectory instead of estimating only the newest pose.',
 'WHAT IS ESTIMATED?',`${M(R`\Theta=\{x_0,\ldots,x_T,\ell_1,\ldots,\ell_L\}`)}Poses, landmarks, calibration terms, and any other modeled variables.<br><br>A pose graph is the special case without explicit landmarks.<br><br>A prior or another gauge constraint fixes the global reference frame.`,
 'DIVISION OF LABOR',`<b>Front-end</b><br>Measurements, candidate associations, and initial values.<br><br><b>Factor graph</b><br>Variables, residual models, and uncertainty.<br><br><b>Optimizer</b><br>A state estimate consistent with those supplied constraints.<br><br><span style="color:#2F6B4F"><b>iSAM incrementally solves the sparse smoothing problem; it does not replace the SLAM formulation.</b></span>`,
 'For fixed associations, the back-end optimizes the supplied graph. Odometry is one possible factor, not the definition of GraphSLAM. A prior or another gauge constraint is needed to remove unobservable reference-frame freedom.','[K11] §I, §III, Fig. 2'));

slides.push(two('objective','01 · iSAM foundations','A product of factors becomes a sum of squared errors.','Independent Gaussian measurement errors lead to covariance-weighted residuals.',
 'PROBABILITY',`${M(R`p(\Theta\mid Z)\propto\prod_k f_k(\Theta_k)`)}${M(R`f_k(\Theta_k)\propto\exp\!\left[-\tfrac12\lVert h_k(\Theta_k)-z_k\rVert_{\Sigma_k}^{2}\right]`)}Each factor touches only a small subset of variables. A prior is another factor.`,
 'OPTIMIZATION',`${M(R`\hat\Theta=\arg\min_\Theta\tfrac12\sum_k\lVert e_k(\Theta_k)\rVert_{\Sigma_k}^{2}`)}${M(R`e_k=h_k(\Theta_k)-z_k,\quad\lVert e\rVert_\Sigma^2=e^{\mathsf T}\Sigma^{-1}e`)}Sparse dependence is what the solver exploits.<br><br><b>Gaussian measurement noise does not make a nonlinear posterior globally Gaussian.</b>`,
 'The MAP notation includes a prior as a factor. MH-iSAM2 is presented as multi-hypothesis maximum-likelihood estimation; it does not derive normalized Bayesian probabilities over hypotheses.','[K11] §III, Eqs. (1)–(3) · [M19] §III-A',{rightSize:18}));

slides.push(two('linearize','01 · iSAM foundations','Linearize locally. Solve sparsely. Retract.','The same linear subproblem sits underneath batch SAM, iSAM, and iSAM2.',
 'LOCAL COORDINATES',`${M(R`e_k(\bar\Theta\oplus\delta)\approx e_k(\bar\Theta)+J_k\delta_k`)}${M(R`A_k=\Sigma_k^{-1/2}J_k,\qquad b_k=-\Sigma_k^{-1/2}e_k(\bar\Theta)`)}Stack the whitened blocks into sparse ${I('A')} and ${I('b')}. The retraction ${I(R`\oplus`)} applies a tangent-space increment.`,
 'TRIANGULARIZE → SOLVE',`${M(R`\delta^*=\arg\min_\delta\lVert A\delta-b\rVert^2`)}${M(R`Q^{\mathsf T}[A\;b]=\begin{bmatrix}R&d\\0&r_\perp\end{bmatrix},\qquad R\delta^*=d`)}${M(R`\hat\Theta=\bar\Theta\oplus\delta^*`)}QR avoids explicitly forming normal equations. The nonlinear problem generally needs repeated local solves.`,
 'The residual sign convention is h minus z, so b is minus the whitened residual. Sigma to the minus one half denotes any whitening matrix W with W-transpose W equal to Sigma inverse.','[K11] §III, Eq. (4), Alg. 1',{rightSize:18}));

slides.push(two('isam','01 · iSAM foundations','iSAM appends new rows instead of starting over.','Keep the square-root information factor and restore triangular form with Givens rotations.',
 'THE INCREMENTAL UPDATE',`${M(R`\begin{bmatrix}R_t&d_t\\A_{\mathrm{new}}&b_{\mathrm{new}}\end{bmatrix}\xrightarrow{\mathrm{Givens}}\begin{bmatrix}R_{t+1}&d_{t+1}\\0&r_\perp\end{bmatrix}`)}<b>Append.</b> New variables add columns; new measurements add rows.<br><br><b>Rotate.</b> Eliminate entries below the diagonal.<br><br><b>Solve.</b> Recover the trajectory by back-substitution.`,
 'NEXT · LAB 1',`<b>What to observe</b><br><br>1. Odometry alone can have zero residual and still drift.<br><br>2. A loop closure changes old poses, not only the newest one.<br><br>3. Incremental Givens updates and a fresh batch factorization agree to numerical precision.<br><br><span style="color:#A94F2A"><b>The lab is linear and translation-only:</b> it isolates reuse of ${I('R')}, not manifold relinearization.</span>`,
 'New columns are zero-padded in old rows. Original iSAM periodically reorders and relinearizes. iSAM2 removes scheduled full batch steps, though a difficult update can still touch most of the graph.','[K11] §II, §IV · [I08] original iSAM',{rightFill:C.warm,rightAccent:C.rust}));

slides.push(slide('qr-demo','Interactive lab 01','A loop closure changes old poses.','Add eight odometry factors, then close the loop. Incremental QR is checked against a fresh batch solve.',liveFallback('qr','Incremental square-root update','STATIC FALLBACK · THE LIVE LAB APPEARS HERE',`<b>Sequence</b><br>1 pose → 8 odometry additions → 1 loop closure.<br><br><b>Computed</b><br>Givens-updated ${I('R')}, optimized trajectory, whitened residual, and batch/incremental difference.<br><br><b>Print result</b><br>The closure corrects the entire drifted path while retaining the same linear least-squares solution as batch QR.`,[
 box('qr-chart',518,220,650,355,C.soft,C.rule),text('qr-chart-label',542,240,600,22,'TRAJECTORY SCHEMATIC',{fontFamily:mono,fontSize:11,fontWeight:800,color:C.green}),
 line('qr-grid-a',566,291,0,218,C.rule,1),line('qr-grid-b',566,509,470,0,C.rule,1),line('qr-truth-1',574,500,0,-170,C.muted,3),line('qr-truth-2',574,330,285,0,C.muted,3),line('qr-truth-3',859,330,0,170,C.muted,3),line('qr-truth-4',859,500,-285,0,C.muted,3),
 line('qr-drift-1',574,500,23,-154,C.rust,3),line('qr-drift-2',597,346,292,24,C.rust,3),line('qr-drift-3',889,370,15,155,C.rust,3),
 line('qr-fit-1',574,500,5,-166,C.green,4),line('qr-fit-2',579,334,283,4,C.green,4),line('qr-fit-3',862,338,3,164,C.green,4),line('qr-fit-4',865,502,-291,-2,C.green,4),
 ...node('qr-p0',554,480,'p0',{size:40,fill:C.panel}),...node('qr-p8',844,482,'p8',{size:40,fill:C.warm,stroke:C.rust}),text('qr-legend',554,543,584,22,'grey: truth   ·   rust: odometry   ·   green: optimized',{fontFamily:mono,fontSize:11,color:C.muted})
]),'The browser maintains R and two transformed right-hand sides, one per coordinate. Each factor applies Givens rotations to one whitened row. A separate full factorization verifies the estimate. The synthetic drift is deterministic.','[K11] Eq. (4), §IV · original teaching model'));

slides.push(slide('bayes-tree','02 · iSAM2','A Bayes tree organizes the triangular system.','Each clique stores a conditional density for its frontal variables, given its separator variables.',[
 ...panel('bt-math',72,188,518,422,'CONDITIONALS ↔ BLOCKS OF R',`${M(R`p(\delta\mid Z,\bar\Theta)=\prod_C p(\delta_{F_C}\mid\delta_{S_C})`)}${M(R`R_{FF}\delta_F+R_{FS}\delta_S=d_F`)}<b>Frontals ${I('F_C')}</b> are eliminated in this clique.<br><br><b>Separators ${I('S_C')}</b> connect it to its parent.<br><br>At the root, the separator is empty.`,{fill:C.soft,size:18}),
 box('bt-diagram',614,188,594,422,C.panel,C.rule),text('bt-label',638,205,546,22,'ILLUSTRATIVE VALID CLIQUE TREE',{fontFamily:mono,fontSize:11,fontWeight:800,color:C.rust}),
 line('bt-e1',900,270,-170,90,C.rule,2),line('bt-e2',900,270,170,90,C.rule,2),line('bt-e3',730,382,0,100,C.rule,2),
 box('bt-root',798,238,204,64,C.soft,C.green),text('bt-root-t',818,258,164,28,`${I(R`F=\{x_3,x_4\},\;S=\varnothing`)}`,{fontSize:15,align:'center'}),
 box('bt-c1',638,349,184,64,C.cool,C.blue),text('bt-c1-t',643,369,174,28,`${I(R`F=\{x_1\},\;S=\{x_3\}`)}`,{fontSize:14,align:'center'}),
 box('bt-c2',978,349,184,64,C.warm,C.rust),text('bt-c2-t',983,369,174,28,`${I(R`F=\{x_2\},\;S=\{x_3,x_4\}`)}`,{fontSize:14,align:'center'}),
 box('bt-c3',638,468,184,64,C.panel,C.green),text('bt-c3-t',643,488,174,28,`${I(R`F=\{x_0\},\;S=\{x_1\}`)}`,{fontSize:14,align:'center'}),
 ...callout('bt-call',646,549,508,43,'Ordering controls clique structure—and the work each update awakens.',{fill:C.soft,stroke:C.green,size:13})
],'A child separator is contained in its parent clique. A variable is frontal in exactly one clique. This tree is not the robot path; it encodes conditional dependence in the current linearized Gaussian system.','[K11] §IV, Fig. 3'));

slides.push(two('isam2-update','02 · iSAM2 update','Remove the affected top. Keep the orphan subtrees.','New factors and stale linearization points contribute to the same incremental update.',
 'UPWARD · REBUILD',`<b>01 · Mark</b><br>Find touched variables and relevant cliques.<br><br><b>02 · Detach</b><br>Remove those cliques and their ancestors.<br><br><b>03 · Cache</b><br>Preserve orphan subtrees and marginal factors.<br><br><b>04 · Re-eliminate</b><br>Relinearize as required and reorder the affected variables.`,
 'DOWNWARD · OBSERVE IN LAB 2',`${M(R`\delta_F=R_{FF}^{-1}(d_F-R_{FS}\delta_S)`)}<b>05 · Reattach</b> unchanged orphan subtrees.<br><br><b>06 · Back-substitute</b> updated separator values.<br><br><b>What to observe next</b><br>Change ordering, then compare a new odometry edge with short and long loops. The touched pose can move from a leaf toward the root.<br><br><span style="color:#A94F2A"><b>Reuse does not freeze a subtree:</b> its estimate may still change through its separator.</span>`,
 'The inverse is teaching shorthand for a triangular solve. A numerical state update can propagate below the re-eliminated top. Local refactorization does not imply that only local states move.','[K11] Algs. 2–4, §IV-B–C',{rightFill:C.warm,rightSize:17}));

slides.push(slide('tree-demo','Interactive lab 02','Which part of the Bayes tree changes?','Compare elimination orders and update endpoints. The highlighted cliques are computed symbolically.',liveFallback('tree','Ordering changes the work.','STATIC FALLBACK · THE LIVE LAB APPEARS HERE',`<b>Controls</b><br>Choose an ordering and an event: append, short or long loop, or relinearization.<br><br><b>Computed</b><br>Fill-in, cliques, affected ancestors, and reusable orphan subtrees.<br><br>The pre-update tree is shown; a newly appended variable has no clique yet.`,[
 box('tree-chart',516,218,650,360,C.soft,C.rule),text('tree-chart-label',540,238,600,22,'SYMBOLIC PRE-UPDATE TREE',{fontFamily:mono,fontSize:11,fontWeight:800,color:C.green}),
 line('tree-e1',839,286,-190,88,C.rust,3),line('tree-e2',839,286,190,88,C.rule,2),line('tree-e3',649,394,0,90,C.green,2),
 box('tree-root',759,260,160,58,C.warm,C.rust),text('tree-root-t',775,279,128,24,'rebuild · root',{fontFamily:mono,fontSize:13,fontWeight:700,align:'center'}),
 box('tree-left',569,368,160,58,C.warm,C.rust),text('tree-left-t',585,387,128,24,'rebuild',{fontFamily:mono,fontSize:13,fontWeight:700,align:'center'}),
 box('tree-right',949,368,160,58,C.panel,C.green),text('tree-right-t',965,387,128,24,'reusable',{fontFamily:mono,fontSize:13,fontWeight:700,align:'center'}),
 box('tree-orphan',569,472,160,58,C.panel,C.green),text('tree-orphan-t',585,491,128,24,'orphan subtree',{fontFamily:mono,fontSize:13,fontWeight:700,align:'center'}),
 text('tree-stats',764,470,337,72,'affected cliques   2 / 4<br>reusable cliques   2<br>fill-in blocks      computed',{fontFamily:mono,fontSize:15,lineHeight:1.65})
]),'There are nine existing scalar variable blocks and a connected anchored graph. The matrix shows block sparsity, not numerical values. Alternative orders are explicit teaching choices, not an implementation of CCOLAMD.','[K11] Alg. 3, §IV-A · original symbolic example'));

slides.push(two('thresholds','02 · iSAM2','Two thresholds. Two different questions.','Relinearization changes the local model; partial back-substitution changes how far an update propagates.',
 'RELINEARIZATION',`${M(R`\lVert\delta_j\rVert>\beta_j\quad\Longrightarrow\quad\bar\theta_j\leftarrow\bar\theta_j\oplus\delta_j`)}<b>Is the linearization point too old?</b><br><br>Compare the current estimate with its own linearization point. Recompute affected nonlinear factor linearizations when needed.<br><br>Test the accumulated increment, not only the newest small change.`,
 'PARTIAL STATE UPDATE',`${M(R`\lVert\delta_j^{\mathrm{new}}-\delta_j^{\mathrm{old}}\rVert>\alpha_j`)}<b>Will the next subtree change enough?</b><br><br>Continue downward when separator updates differ enough. Otherwise retain the prior increments in an unreached subtree.<br><br>The ${I(R`\alpha_j`)} test concerns a <b>change</b> in ${I(R`\delta_j`)}, not its absolute size.`,
 'The source uses alpha for partial back-substitution and beta for relinearization. Different physical units need appropriate scaling. Larger thresholds trade accuracy for work; they are not convergence certificates.','[K11] §IV-B–C, Algs. 4–5'));

slides.push(sheet('isam2-sheet','iSAM2 on one page','Same smoothing objective. A different schedule for the linear algebra.',[
 ['NONLINEAR OBJECTIVE',M(R`\hat\Theta=\arg\min_\Theta\sum_k\lVert e_k(\Theta_k)\rVert_{\Sigma_k}^{2}`)],
 ['LINEAR SUBPROBLEM',M(R`\delta^*=\arg\min_\delta\lVert A\delta-b\rVert^2`)],
 ['CLIQUE SOLVE',M(R`\delta_{F_C}=R_{FF,C}^{-1}(d_C-R_{FS,C}\delta_{S_C})`)],
 ['RETRACTION',M(R`\hat\Theta=\bar\Theta\oplus\delta^*`)]
],'The inverse notation means solve a triangular system. The update recipe is: add factors, mark endpoints and stale linearization points, rebuild the affected top with cached orphan marginals, reattach, then propagate increments as required.','[K11] Eq. (4), Algs. 2–5'));

slides.push(two('ambiguity','03 · MH-iSAM2','A precise answer to the wrong graph is still wrong.','A single optimizer cannot preserve alternatives that the front-end has already discarded.',
 'CONTINUOUS UNCERTAINTY',`${M(R`\theta\approx\mathcal N(\mu,\Sigma)`)}One locally Gaussian estimate describes spread around one solution.<br><br>Making the covariance broader does not explicitly encode two different associations or a loop closure that may be false.<br><br><b>One mode, local uncertainty.</b>`,
 'DISCRETE AMBIGUITY',`${M(R`h\in\{h_1,h_2,\ldots\}`)}Different measurement values, different associations, or a factor that may be absent create distinct graph explanations.<br><br>MH-iSAM2 keeps several discrete choices long enough for later measurements to distinguish them.<br><br><b>Several hypothesis-conditioned optimized states.</b>`,
 'The output is a collection of optimized states conditioned on retained hypotheses. It is not a set of posterior samples and not a complete calibrated multimodal posterior density.','[M19] §I, §III-A–C',{rightFill:C.warm,rightAccent:C.rust}));

slides.push(three('modes','03 · Ambiguity models','Three multi-mode factors','An input mode changes a measurement, an association, or whether a factor exists.',[
 ['TYPE 1 · MULTI-MEASUREMENT',`${M(R`z_r\in\{z_{r(1)},\ldots,z_{r(m)}\}`)}<b>Same variables, different candidate measurements.</b><br><br>Example: two conflicting visual-odometry estimates for the same pose pair.<br><br>${I('x_i')} ⇉ ${I('x_j')}`,C.soft,C.green],
 ['TYPE 2 · MULTI-ASSOCIATION',`${M(R`a_r\in\{\ell_1,\ldots,\ell_m\}`)}<b>Same observation, different variables to connect.</b><br><br>Example: one feature may correspond to either of two landmarks.<br><br>${I('x')} → ${I(R`\ell_1`)} or ${I(R`\ell_2`)}`,C.cool,C.blue],
 ['TYPE 3 · BOOLEAN',`${M(R`b_r\in\{0,1\}`)}<b>Factor on or off.</b><br><br>A loop-closure proposal may be correct or an outlier.<br><br>Dropping a factor changes residual dimension, so raw error alone is not a fair pruning rule.`,C.warm,C.rust]
],'Modes are inputs; hypotheses are output combinations. A Boolean alternative can be combined with the other types to express that none of the candidates is valid.','[M19] §III-C, Fig. 2'));

slides.push(two('mh-objective','03 · The objective','One mixture optimum is not a set of hypothesis optima.','MH-MLE conditions on one discrete choice for every ambiguous measurement.',
 'MIXTURE MODEL',`${M(R`P_M(z_r\mid\Theta_r)=\sum_{i=1}^{m_r}w_{r(i)}P(z_{r(i)}\mid\Theta_r)`)}${M(R`\hat\Theta=\arg\max_\Theta\prod_sP(z_s\mid\Theta_s)\prod_rP_M(z_r\mid\Theta_r)`)}Optimizing the summed mixture returns one maximizer. It does not preserve the state optimum for every mode combination.`,
 'MULTI-HYPOTHESIS MLE',`${M(R`\hat\Theta_{[h]}=\arg\max_\Theta\left[\prod_sP(z_s\mid\Theta_s)\right]\left[\prod_rw_{r(h_r)}P(z_{r(h_r)}\mid\Theta_r)\right]`)}${M(R`\hat\Theta_M=\{\hat\Theta_{[h]}:h\text{ retained}\}`)}Each ${I('h')} selects one mode per multi-mode factor. The Hypo-tree and MH Bayes tree avoid duplicating all work independently.`,
 'For fixed h, positive theta-independent mode weights do not move its optimizer. Across hypotheses, weights and Gaussian normalization terms should not be confused with residual-only rankings.','[M19] §III-A, Eqs. (2)–(5)',{leftSize:17,rightSize:17}));

slides.push(slide('hypo-tree','03 · Hypothesis bookkeeping','The Hypo-tree records the discrete history.','One new multi-mode factor adds a layer; each surviving node branches into its candidate modes.',[
 ...panel('hypo-copy',72,188,484,422,'GLOBAL AND LOCAL HYPOTHESES',`${M(R`n_t=\prod_{r=1}^{t}m_r`)}A root-to-leaf path is an entire choice sequence.<br><br><b>Global hypothesis:</b> one active leaf.<br><br><b>Local hypothesis:</b> the alternatives a particular variable or inference component currently needs.<br><br>${M(R`\theta_p^{\{r\}}\longleftrightarrow L_r`)}The Bayes tree organizes conditional dependence. The Hypo-tree organizes mode correspondence.`,{fill:C.soft,size:17}),
 box('hypo-diagram',580,188,628,422,C.panel,C.rule),text('hypo-label',604,205,580,22,'TWO BINARY FACTORS → FOUR PREFIXES',{fontFamily:mono,fontSize:11,fontWeight:800,color:C.rust}),
 line('h-e1',646,294,178,-66,C.rule,2),line('h-e2',646,294,178,66,C.rule,2),line('h-e3',824,228,185,-35,C.rule,2),line('h-e4',824,228,185,35,C.rule,2),line('h-e5',824,360,185,-35,C.rule,2),line('h-e6',824,360,185,35,C.rule,2),
 ...node('h-root',622,270,'∅',{size:48,fill:C.soft}),...node('h-p',800,204,'+',{size:48,fill:C.soft}),...node('h-m',800,336,'−',{size:48,fill:C.warm,stroke:C.rust}),
 ...node('h-pp',985,169,'++',{size:50,fill:C.panel}),...node('h-pm',985,239,'+−',{size:50,fill:C.panel}),...node('h-mp',985,301,'−+',{size:50,fill:C.panel}),...node('h-mm',985,371,'−−',{size:50,fill:C.panel}),
 text('h-layers',624,452,490,28,`${I('L_0')}                    ${I('L_1')}                       ${I('L_2')}`,{fontFamily:mono,fontSize:15,color:C.muted,align:'center'}),
 ...callout('h-call',615,505,558,66,'Ancestor and descendant lookups let several later leaves reuse one earlier local value.',{fill:C.warm,stroke:C.rust,size:15,align:'center'})
],'The root layer contains one initial hypothesis. Each multi-mode factor creates a chronological layer. Pruning removes active branches, but later factors do not require restructuring earlier Hypo-layers.','[M19] §IV-A–C, Fig. 3'));

slides.push(two('local-sharing','03 · Local hypotheses','Share an early prefix—until later evidence reaches it.','A closing constraint can make an old variable depend on a more recent ambiguity.',
 'BEFORE A CLOSING CONSTRAINT',`Four global leaves may require only two local values for an earlier variable:<br><br><b>++ and +−</b> share the “+” prefix.<br><br><b>−+ and −−</b> share the “−” prefix.${M(R`\theta_p^{\{1\}}:\quad 2\text{ local hypotheses}`)}Sharing follows factor-graph dependencies; it does not mean every old pose is shared.`,
 'AFTER INFORMATION PROPAGATES BACK',`${M(R`\theta_p^{\{1\}}\longrightarrow\theta_p^{\{2\}}`)}${M(R`2\text{ local hypotheses}\longrightarrow\text{up to }4`)}The newer mode can now change the earlier pose estimate, so its local alternatives expand.<br><br><b>Update the variable-to-layer association; do not rebuild the Hypo-tree.</b><br><br>Numerically similar compatible updates may later merge.`,
 'This sharing is the key distinction from one full optimizer per global leaf. Similar values merge only when their Hypo-tree correspondence is compatible; coincident coordinates do not make whole joint hypotheses identical.','[M19] §IV-A–C, Figs. 3–4; §VII-D',{rightFill:C.warm}));

slides.push(two('mh-inference','03 · MH Bayes tree','Each clique eliminates compatible local hypotheses.','The Hypo-tree tells the Bayes tree which modes and messages belong together.',
 'COLLECT → MATCH → ELIMINATE',`${M(R`\phi_C^{[h]}(F,S)=\gamma_C^{[h]}(F\mid S)\,\omega_C^{[h]}(S)`)}<b>Collect</b> factors and child marginal messages.<br><br><b>Match</b> compatible histories by ancestry.<br><br><b>Eliminate</b> frontals; pass a marginal upward.<br><br>A child marginal may serve several compatible parent hypotheses.`,
 'BLOCK ALGEBRA',`${M(R`\Phi=\begin{bmatrix}H_{FF}&H_{FS}\\H_{SF}&H_{SS}\end{bmatrix},\qquad g=\begin{bmatrix}g_F\\g_S\end{bmatrix}`)}${M(R`H_{\mathrm{marg}}=H_{SS}-H_{SF}H_{FF}^{-1}H_{FS}`)}${M(R`g_{\mathrm{marg}}=g_S-H_{SF}H_{FF}^{-1}g_F`)}Keep the scalar constant when tracking residual error.`,
 'The Schur equations are a pedagogical expansion of the described partial factorization. Implementations use triangular solves. All hypotheses share one variable order constructed from union connectivity.','[M19] §V-A–D',{leftSize:17,rightSize:17}));

slides.push(two('mh-backsub','03 · Returning to states','Back-substitution can expand local hypotheses.','A clique conditional and its separator increments may live at different Hypo-layers.',
 'MATCH FIRST, SOLVE SECOND',`${M(R`\delta_F^{[h]}=(R_{FF}^{[a_C(h)]})^{-1}\!\left(d_F^{[a_C(h)]}-R_{FS}^{[a_C(h)]}\delta_S^{[h]}\right)`)}The ancestor map ${I(R`a_C(h)`)} selects the compatible local conditional.<br><br>One conditional may serve several descendant separator hypotheses.<br><br><b>Never take a Cartesian product of unrelated local alternatives:</b> that mixes incompatible histories.`,
 'THEN RETRACT',`<b>1 · Solve</b> compatible conditional / separator pairs.<br><br><b>2 · Merge</b> numerically similar increments with valid correspondence.<br><br><b>3 · Expand</b> a state to a later layer if more alternatives are needed.<br><br><b>4 · Retract</b> each increment onto its matching linearization point.${M(R`\theta_{p,[h]}\leftarrow\bar\theta_{p,[a_p(h)]}\oplus\delta_{p,[h]}`)}`,
 'The conditional and state ancestor maps can target different layers. M19 notes that local merging is not guaranteed to remove every numerical redundancy after nonlinear convergence.','[M19] §IV-C, §V-E, Fig. 5(b)',{leftSize:17,rightSize:17,rightFill:C.warm}));

slides.push(three('pruning','03 · Controlling growth','Pruning is part of the algorithm.','Three criteria control the active set; the next lab shows what happens when the cap is too small.',[
 ['01 · STATISTICAL GATE',`${M(R`e_h^2>\chi^2_{d_h,0.95}`)}${M(R`d_h=\dim(\text{factors})-\dim(\text{variables})`)}Reject inconsistent fits using a chi-square threshold.<br><br>The paper approximates nonlinear error with the linearized residual.`,C.warm,C.rust],
 ['02 · DESIRED COUNT',`${M(R`n_{R1}>n_{\mathrm{desire}}`)}When too many alternatives survive, prefer more constrained fits before applying the hard capacity.<br><br>Boolean “off” modes can lower both residual and degrees of freedom.`,C.panel,C.amber],
 ['03 · HARD LIMIT · WATCH NEXT',`${M(R`n_{R2}>n_{\mathrm{limit}}`)}Remove lower-consistency alternatives until the cap is met.<br><br><b>In Lab 3:</b> use cap 4 to delay commitment, then reset with cap 1. The needed branch can disappear before evidence arrives—and cannot resurrect itself.`,C.soft,C.green]
],'Residual chi-square interpretation assumes an appropriate Gaussian model, sufficient rank, and a suitable local approximation. The lab uses equal branch dimensions, so residual ordering is sufficient there.','[M19] §VI-A–B, Fig. 6; §VII-D'));

slides.push(slide('mh-demo','Interactive lab 03','Keep the right branch until evidence arrives.','Two ambiguous displacements create four trajectories. Later constraints separate them.',liveFallback('mh','Delay commitment.','STATIC FALLBACK · THE LIVE LAB APPEARS HERE',`<b>Default stream</b><br>1 → 2 → 4 → 2 → 1 retained hypotheses.<br><br><b>Evidence</b><br>An endpoint constraint leaves two opposite-sign paths. A later midpoint constraint selects the supported one.<br><br><b>Failure mode</b><br>A cap of one breaks an early tie arbitrarily. The selected branch can later fail the gate, leaving an empty set. Deleted branches are not restored.`,[
 box('mh-chart',518,218,648,360,C.soft,C.rule),text('mh-chart-label',542,238,600,22,'HYPOTHESIS PREFIX TREE',{fontFamily:mono,fontSize:11,fontWeight:800,color:C.rust}),
 line('mh-e1',610,360,185,-86,C.rule,2),line('mh-e2',610,360,185,86,C.rule,2),line('mh-e3',795,274,190,-42,C.rule,2),line('mh-e4',795,274,190,42,C.rule,2),line('mh-e5',795,446,190,-42,C.rule,2),line('mh-e6',795,446,190,42,C.rule,2),
 ...node('mh-root',586,336,'∅',{size:48,fill:C.panel}),...node('mh-plus',771,250,'+',{size:48,fill:C.soft}),...node('mh-minus',771,422,'−',{size:48,fill:C.panel}),
 ...node('mh-pp',961,208,'++',{size:48,fill:C.panel,stroke:C.muted}),...node('mh-pm',961,292,'+−',{size:48,fill:C.soft,stroke:C.green}),...node('mh-mp',961,380,'−+',{size:48,fill:C.panel,stroke:C.blue}),...node('mh-mm',961,464,'−−',{size:48,fill:C.panel,stroke:C.muted}),
 text('mh-seq',557,533,560,27,'survivors · 1 → 2 → 4 → 2 → 1',{fontFamily:mono,fontSize:15,fontWeight:750,color:C.green,align:'center'})
]),'The synthetic supported branch is plus/minus. With cap 4 and default noise, all four survive before evidence, the endpoint leaves plus/minus and minus/plus, and the midpoint leaves plus/minus. Scores are not posterior probabilities.','[M19] §III–VI · original linear branch-and-prune example'));

slides.push(two('demo-model','03 · Lab equation sheet','What the multi-hypothesis lab actually computes','A small linear problem makes delayed evidence and irreversible pruning inspectable.',
 'SYNTHETIC MEASUREMENTS',`${M(R`p_0=(0,0),\quad z_{01}=(1,0),\quad z_{23}=(1,0)`)}${M(R`z_{12}^{(a)}=(1,1.2a),\quad z_{34}^{(b)}=(1,1.2b)`)}${M(R`a,b\in\{+1,-1\}`)}Later: ${I(R`p_4-p_0\approx(4,0)`)}; then ${I(R`p_2-p_0\approx(2,1.2)`)}.`,
 'ONE EXACT LINEAR SOLVE PER BRANCH',`${M(R`\hat p^{[a,b]}=\arg\min_{p_1,\ldots,p_4}\sum_{(i,j)}\frac{\lVert p_j-p_i-z_{ij}^{[a,b]}\rVert^2}{\sigma_{ij}^2}`)}${M(R`d_h=2N_{\mathrm{vector\ factors}}-2N_{\mathrm{free\ poses}}`)}Anchor ${I('p_0')} exactly. Initial displacement scale is 0.16; later-measurement scale is interactive. Equal dimensions and covariances make residual ordering sufficient here.`,
 'All values are original teaching choices, not measurements reported by M19. Before redundant constraints arrive, residual degrees of freedom are zero and the chi-square gate is not applied.','[M19] Eqs. (4)–(5), §VI · pedagogical model',{leftSize:17,rightSize:16}));

slides.push(slide('comparison','04 · Synthesis','What changes—and what stays the same?','GraphSLAM defines the estimation problem; these methods differ in how they maintain its solutions.',[
 nativeTable('comparison-table',72,184,1136,384,['Question','iSAM','iSAM2','MH-iSAM2'],[
  ['Continuous objective','Sparse nonlinear smoothing','Same problem class','One conditional problem per retained mode combination'],
  ['Representation','Square-root matrix','Bayes tree','MH Bayes tree + Hypo-tree'],
  ['Reuse','Incremental QR','Unaffected cliques and cached marginals','Temporal reuse + compatible local hypotheses'],
  ['Ordering / relinearization','Periodic batch steps','Selective / incremental','Extended across retained hypotheses; common ordering'],
  ['Output','One optimized state','One optimized state','Several hypothesis-conditioned optimized states']
 ],{columns:[1.05,1,1.25,1.7],fontSize:14,padY:8}),
 ...callout('comparison-call',72,585,1136,58,'Two kinds of reuse: iSAM2 reuses computation across time; MH-iSAM2 additionally shares computation across compatible hypotheses.',{fill:C.warm,stroke:C.rust,size:17,align:'center'})
],'“One optimized state” describes the fixed-graph use in these papers, not a claim that no wrapper could run multiple iSAM2 instances. MH-iSAM2 differs by tracking local hypotheses and sharing inference.','[K11] §II–IV · [M19] §III–VI'));

slides.push(three('limits','04 · Limits that matter','Incremental does not mean constant cost or certainty.','The graph, active hypotheses, and nonlinear approximation all matter.',[
 ['COMPUTATION',`Local updates can become global. Long loop closures or extensive relinearization may touch much of the Bayes tree.${M(R`n_t=\prod_r m_r`)}Pruning bounds the active set, not the unpruned combinatorial space.`,C.soft,C.green],
 ['OPTIMIZATION',`A linear least-squares solve can be exact to numerical precision.<br><br>A nonlinear per-hypothesis solve still depends on initialization, iterations, and linearization.<br><br><b>No claim of finding every global nonlinear optimum.</b>`,C.cool,C.blue],
 ['AMBIGUITY',`A tight cap can remove the correct branch before later evidence arrives.<br><br>Wrong but statistically plausible constraints may survive.<br><br><b>Discrete alternatives are the scope; a full continuous multimodal posterior is not the output.</b>`,C.warm,C.rust]
],'K11 gives constant-cost behavior only in restricted exploration settings, not universally. M19 reports empirical speed with bounded hypotheses and identifies adaptive limits and continuous ambiguity as future work.','[K11] §IV-D · [M19] §VII-B–D'));

slides.push(slide('references','Sources & navigation','Read the two papers alongside the experiments.','Slide footers identify the relevant sections; teaching models remain explicitly separate.',[
 ...[
  ['[K11] Kaess et al. · ICRA 2011','iSAM2: Incremental Smoothing and Mapping with Fluid Relinearization and Incremental Variable Reordering. Objective; Bayes-tree update; ordering; state update; relinearization.','https://www.cs.cmu.edu/~kaess/pub/Kaess11icra.html',C.soft],
  ['[M19] Hsiao & Kaess · ICRA 2019','MH-iSAM2: Multi-hypothesis iSAM using Bayes Tree and Hypo-tree. Ambiguity models; Hypo-tree; inference; pruning; limitations.','https://www.cs.cmu.edu/~kaess/pub/Hsiao19icra.html',C.warm],
  ['[I08] Kaess, Ranganathan & Dellaert · T-RO 2008','iSAM: Incremental Smoothing and Mapping. The original incremental sparse-QR method and periodic batch reordering / relinearization.','https://www.cs.cmu.edu/~kaess/pub/Kaess08tro.html',C.cool]
 ].flatMap(([title,desc,link,fill],i)=>[box('ref-'+i,72,181+i*128,1136,108,fill),text('ref-title-'+i,94,196+i*128,1092,27,title,{fontFamily:serif,fontSize:20,fontWeight:700,link}),text('ref-desc-'+i,94,232+i*128,1092,48,desc,{fontSize:14,color:C.muted,lineHeight:1.45,link})]),
 text('refs-labs',82,581,1116,37,'LABS · incremental QR ↗   ·   Bayes-tree locality ↗   ·   delayed disambiguation ↗',{fontFamily:mono,fontSize:13,color:C.green,align:'center',link:'isam'})
],'The deck uses the 2011 conference version of iSAM2 and the 2019 MH-iSAM2 paper. Source PDFs are not republished. The three live experiments are original, deterministic, browser-local teaching code.','PRIMARY REFERENCES'));

export const deck={format:'bento/slides',version:1,docId:'isam-mh-isam-bento',title:'One Graph, Many Hypotheses: iSAM, iSAM2 & MH-iSAM2',readonly:true,meta:{author:'Bai Liping',subject:'Incremental smoothing, Bayes trees, discrete ambiguity, and MH-iSAM2',company:'bailiping.com'},size:{width:1280,height:720},theme:{background:C.paper,color:C.ink,accent:C.green,fontFamily:sans},slides};
export const inlineLiveMap=[
 ['qr-demo','qr','isam','Incremental QR and loop closure'],
 ['tree-demo','tree','isam2-update','Bayes-tree update locality'],
 ['mh-demo','mh','pruning','Delayed disambiguation and pruning']
].map(([id,demo,intro,title])=>({introSlide:intro,slide:id,slideIndex:slides.findIndex(s=>s.id===id),inline:true,layout:'region',bounds:{x:72,y:180,width:1136,height:475},src:'./live/?demo='+demo+'&embed=region',source:'./live/?demo='+demo,title,sandbox:'allow-scripts',hideSource:true,readyMessage:true,unloadWhenHidden:true}));
