import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
import {deck,inlineLiveMap} from './bento-deck.mjs';
import {applyTeachingRevisions} from './teaching-revisions.mjs';

applyTeachingRevisions(deck,inlineLiveMap);
const here=dirname(fileURLToPath(import.meta.url));
const template=await readFile(resolve(here,'../kalman-filter-derivations/index.html'),'utf8');
const safe=value=>JSON.stringify(value,null,1).replaceAll('<','\\u003c');

if(deck.format!=='bento/slides'||deck.size.width!==1280||deck.size.height!==720)throw new Error('Invalid Bento document envelope');
const slideIds=new Set(deck.slides.map(s=>s.id));
if(slideIds.size!==deck.slides.length)throw new Error('Duplicate slide id');
for(const [i,s] of deck.slides.entries()){
  if(!s.notes)throw new Error('Missing notes: '+s.id);
  const ids=new Set();
  for(const e of s.elements){
    if(ids.has(e.id))throw new Error('Duplicate element '+s.id+'/'+e.id);
    ids.add(e.id);
    if(e.x<0||e.y<0||e.x+e.w>1281||e.y+e.h>721)throw new Error('Out of slide: '+s.id+'/'+e.id);
  }
  s.elements.push({id:'slide-number',type:'text',x:940,y:684,w:82,h:20,html:`${String(i+1).padStart(2,'0')} / ${deck.slides.length}`,fontSize:10,fontFamily:'monospace',color:'#66756E',align:'center'});
}
for(const entry of inlineLiveMap){
  const index=deck.slides.findIndex(s=>s.id===entry.slide);
  const intro=deck.slides.findIndex(s=>s.id===entry.introSlide);
  if(index<0||intro!==index-1)throw new Error('Live slide must immediately follow its intro: '+entry.slide);
  if(entry.slideIndex!==index)throw new Error('Incorrect live slide index: '+entry.slide);
  const marker=deck.slides[index].elements.find(e=>e.id==='live-demo-mount');
  if(!marker)throw new Error('Missing live-demo-mount: '+entry.slide);
  const b=entry.bounds;
  if(marker.x!==b.x||marker.y!==b.y||marker.w!==b.width||marker.h!==b.height)throw new Error('Live marker/bounds mismatch: '+entry.slide);
}

const pattern=/(<script type="application\/bento\+json" id="bento-doc">\s*)[\s\S]*?(\s*<\/script>)/;
if(!pattern.test(template))throw new Error('Bento template document not found');
let html=template.replace(pattern,(_,a,b)=>a+safe(deck)+b);
const mapPattern=/<script type="application\/json" id="bento-inline-live-map">[\s\S]*?<\/script>/;
if(!mapPattern.test(html))throw new Error('Bento inline-live map not found');
html=html.replace(mapPattern,()=>'<script type="application/json" id="bento-inline-live-map">\n'+safe(inlineLiveMap)+'\n</script>');

const routes=Object.fromEntries(deck.slides.map((s,i)=>[s.id,i]));
const routeScript=`<script>(()=>{const routes=${JSON.stringify(routes)};function routeToSlide(){let r;try{r=decodeURIComponent(location.hash.replace(/^#\\/?/,''));}catch{return;}if(r&&!/^\\d+$/.test(r)&&Number.isInteger(routes[r]))history.replaceState(null,'',location.pathname+location.search+'#/'+routes[r]);}addEventListener('hashchange',routeToSlide);routeToSlide();})();</script>`;
let routeReplaced=false;
html=html.replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/g,(full,attrs,body)=>{
  if(!attrs.trim()&&body.includes('const routes =')&&body.includes('routeToSlide')){routeReplaced=true;return routeScript;}
  return full;
});
if(!routeReplaced)throw new Error('Template route mapper not found');

html=html.replace(/<title>[\s\S]*?<\/title>/,'<title>One Graph, Many Hypotheses: iSAM, iSAM2 &amp; MH-iSAM2 | Bai Liping</title>');
html=html.replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${deck.slides.length} interactive Bento slides on iSAM, iSAM2, and MH-iSAM2, with four live labs: incremental QR, separator-summary reuse, Bayes-tree locality, and hypothesis pruning." />`);
html=html.replace(/<link rel="canonical"[^>]*>/,'<link rel="canonical" href="https://bailiping.com/isam-mh-isam/" />');
html=html.replace(/<!-- Generated by kalman-filter-derivations[^>]*-->/,'<!-- Generated by isam-mh-isam/build-bento.mjs. Edit bento-deck.mjs and teaching-revisions.mjs, then rebuild. -->');
// Natural-height display spans keep grouped equations inside their native panels.
html=html.replace('</head>',`<style id="isam-math-layout">
.bento-slide .math-display{height:auto!important;min-height:0;margin:.55em 0;}
.bento-slide .bento-text-inner>.math-display:first-child{margin-top:.1em;}
.bento-slide .bento-text-inner>.math-display:last-child{margin-bottom:.1em;}
</style>\n</head>`);
if(!html.includes('tex-svg-full.js')||!html.includes('mathjax-dynamic.js')||!html.includes('bento-inline-live.js'))throw new Error('Required shared runtime missing');

await writeFile(resolve(here,'index.html'),html);
console.log(`Built ${deck.slides.length} iSAM slides and ${inlineLiveMap.length} live laboratories (${html.length} characters).`);
console.log('Slide routes: '+deck.slides.map(s=>s.id).join(', '));
