// Editable public teaching deck. Runtime is shared with the existing radio deck.
const C={bg:'#F4F6F8',ink:'#16222E',muted:'#51606E',line:'#D7DEE5',blue:'#1874B8',teal:'#0A6B5E',orange:'#D76809',paper:'#FFFFFF',cool:'#E8F2FA',mint:'#E3F2EF',warm:'#FCEBDA'};
const serif="Georgia, 'Times New Roman', serif",sans='Arial, Helvetica, sans-serif',mono='Menlo, Consolas, monospace';
const R=String.raw;
const M=s=>`<span class="math-tex math-display">\\[${s}\\]</span>`;
const I=s=>`<span class="math-tex math-inline">\\(${s}\\)</span>`;
const PAPER='https://arxiv.org/html/2607.04847v2';
export const references={
 paper:{short:'Shen et al. · arXiv:2607.04847v2',title:'Amplitude-Independent Robust Snapshot 6-D Radio SLAM via a Unified Angle-Delay Formulation',url:PAPER},
 pdf:{short:'Paper PDF',title:'Paper PDF, version 2',url:'https://arxiv.org/pdf/2607.04847v2'},
 background:{short:'Radio measurements → radio map',title:'Radio Measurements → Radio Map',url:'https://bailiping.com/mpc-detection-to-bounce-count-slides/'},
 crb:{short:'Measurement precision and CRB',title:'Cramér–Rao Bounds for Radio Measurements',url:'https://bailiping.com/radio-cramer-rao-slides/'}
};
const cite=(label,anchor='')=>({label,url:PAPER+(anchor?'#'+anchor:'')});
const ext=(key)=>({label:references[key].short,url:references[key].url});
function txt(id,x,y,w,h,html,o={}){return{id,type:'text',x,y,w,h,rotation:0,opacity:1,html,fontFamily:sans,fontSize:22,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.32,...o};}
function box(id,x,y,w,h,fill=C.paper,stroke=C.line){return{id,type:'shape',shape:'rect',x,y,w,h,fill,stroke,strokeWidth:1,radius:10,rotation:0,opacity:1};}
function panel(id,x,y,w,h,label,body,{fill=C.paper,size=22,accent=C.blue}={}){return[box(id+'-box',x,y,w,h,fill),txt(id+'-label',x+22,y+18,w-44,25,label,{fontFamily:mono,fontSize:12,fontWeight:700,color:accent}),txt(id+'-body',x+22,y+58,w-44,h-76,body,{fontSize:size})];}
const slides=[],liveMap=[];
function add(id,section,title,subtitle,elements,notes,sources=[cite('Paper')]){slides.push({id,background:C.bg,transition:'none',notes:notes+'\n\nSources:\n'+sources.map(s=>s.label+' — '+s.url).join('\n'),elements:[
 txt('extensions-shortcut',1018,7,166,17,'EXTENSIONS ↗',{fontSize:10,fontFamily:mono,color:C.blue,align:'right',link:'extensions'}),
 txt('section',96,28,780,22,section.toUpperCase(),{fontSize:12,fontFamily:mono,color:C.orange,fontWeight:700,letterSpacing:1}),
 txt('home',930,28,254,22,'RADIO SLAM · SNAPSHOT',{fontSize:11,fontFamily:mono,color:C.muted,align:'right',link:'https://bailiping.com/'}),
 box('rule',96,66,1088,1,C.line,C.line),txt('heading',96,86,1088,52,title,{fontFamily:serif,fontSize:37,fontWeight:700,lineHeight:1.1}),
 txt('subtitle',96,142,1088,34,subtitle,{fontSize:18,color:C.muted}),...elements,
 txt('sources',96,677,915,22,sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${s.label}</a>`).join(' · '),{fontSize:11,color:C.muted}),
 txt('contents',1040,677,144,20,'CONTENTS ↗',{fontSize:11,fontFamily:mono,color:C.blue,align:'right',link:'overview'})]});}
function two(id,section,title,subtitle,ll,lb,rl,rb,notes,sources,size=[22,22]){add(id,section,title,subtitle,[...panel('left',96,191,532,450,ll,lb,{fill:C.cool,size:size[0]}),...panel('right',652,191,532,450,rl,rb,{fill:C.paper,size:size[1],accent:C.teal})],notes,sources);}
function live(id,intro,title,subtitle,lab,body,notes,sources){add(id,'Interactive experiment',title,subtitle,[...panel('print-fallback',72,180,1136,475,'INTERACTIVE LAB',body,{size:24,fill:C.cool}),{...box('live-demo-mount',72,180,1136,475,'transparent','transparent'),opacity:0}],notes,sources);liveMap.push({slide:id,introSlide:intro,inline:true,layout:'region',bounds:{x:72,y:180,width:1136,height:475},src:`./live/?lab=${lab}&embed=1`,source:`./live/?lab=${lab}`,title,sandbox:'allow-scripts allow-same-origin allow-top-navigation-by-user-activation',hideSource:true,readyMessage:true,unloadWhenHidden:true});}

add('overview','Snapshot radio SLAM','Estimate the first pose and clock','A step-by-step reading of the unified angle–delay method.',[
 txt('hero',96,200,1088,109,'One channel snapshot.<br><span style="color:#0A6B5E">Unknown pose. Unknown clock. Unknown map.</span>',{fontFamily:serif,fontSize:39,fontWeight:700,lineHeight:1.15}),
 ...panel('citation',96,334,1088,141,'THE PAPER',`<b>${references.paper.title}</b><br>Shengqiang Shen, Aoyun Hao, Weihao Geng, Lei Yang, Shiyin Li and Henk Wymeersch · arXiv:2607.04847v2`,{size:20}),
 ...[['01','Path geometry','geometry-intro',C.cool],['02','Linear solve','linear-intro',C.mint],['03','Orientation search','orientation-intro',C.warm],['04','Robust refinement','consensus',C.cool]].flatMap(([n,t,link,fill],i)=>[box('tile-'+i,96+278*i,499,254,111,fill),txt('nav-'+i,116+278*i,516,214,81,n+'<br><b>'+t+'</b>',{fontSize:21,link})])
],'This public educational deck explains the method in arXiv:2607.04847v2. The paper uses estimated path delays and angles to initialize a known-BS, unknown-UE radio SLAM problem. It does not assume an initial UE state. The early linear solve is conditional on an orientation candidate. The browser laboratories expose geometry, the conditional linear system and orientation optimization. They are deliberately smaller than the full exhaustive-subset plus IRLS/QAIC estimator. All prose and teaching examples here are explanatory rather than copied paper text.',[cite('Paper · abstract'),ext('background')]);

two('observations','01 · define the unknowns','What arrives at the snapshot estimator?','Channel estimation has already extracted the resolvable path parameters.',
 'OBSERVED FOR EACH PATH',M(R`\mathbf z_i=[\rho_i,\phi_{a,i},\phi_{e,i},\theta_{a,i},\theta_{e,i}]^\top`)+M(R`\rho_i=c\tilde\tau_i`)+ 'AoD: angles in the <b>BS frame</b>.<br>AoA: angles in the <b>UE frame</b>.<br><br>Planar mode keeps range and the two azimuths.',
 'KNOWN AND UNKNOWN','<b>Known:</b> BS position and orientation.<br><br><b>Unknown:</b> UE position, UE orientation, one clock bias, path identities and single-bounce scatterers.<br><br>'+M(R`\mathbf x=\{\mathbf p_{\rm UE},b_{\rm UE},\mathbf R_{\rm UE}\}`),
 'The input is a set of noisy channel-parameter estimates. The estimator discussed here does not operate directly on raw IQ samples. The paper assumes known BS position and orientation, which anchors the global coordinate frame. In 3D, pose means three position coordinates and three rotation degrees of freedom, with an additional clock bias. The observation vector contains one range-like delay and two angular pairs. Path magnitudes are deliberately not used by the proposed estimator. Noise covariance is part of the simulator, but calibrated per-path covariance is not an estimator input.',[cite('Section II-A · Eqs. (1)–(3)','S2.SS1')],[21,22]);

two('clock','01 · the clock is shared','Every path includes the same receiver clock','A clock error shifts apparent path lengths together.',
 'DISTANCE UNITS MAKE THE SIGN CLEAR',M(R`B=cb_{\rm UE},\qquad\rho_i=d_i+B`)+M(R`d_i=\rho_i-B`)+ 'Here B is the clock bias in metres.<br><br>'+M(R`1\ \mathrm{ns}\ \longleftrightarrow\ 0.299792458\ \mathrm m`),
 'WHAT GEOMETRY MUST SEPARATE','For LoS, '+I(R`d_i=\|\mathbf p_{\rm UE}-\mathbf p_{\rm BS}\|`)+'.<br><br>For one bounce, '+I(R`d_i=\|\mathbf p_i-\mathbf p_{\rm BS}\|+\|\mathbf p_i-\mathbf p_{\rm UE}\|`)+'.<br><br>All accepted paths must agree on <b>one</b> B and <b>one</b> UE pose.',
 'B is a teaching and implementation notation for c times the clock bias. The original paper keeps b in seconds and stacks minus c b in its linear unknown vector. This deck will show that exact sign convention before relating it to the positive-B convention used by the browser. A positive receiver timing offset adds to every measured delay. The geometry, not an independent per-path clock correction, must separate propagation lengths from that common offset. The simulator can set a true clock to generate data, but that truth is never given to an unknown-state estimator.',[cite('Eqs. (2), (3), (8)','S2.E2'),cite('Linear convention · Eq. (14)','S3.E14')]);

two('directions','02 · put angles in one frame','AoD and AoA become global unit vectors','The UE orientation is unknown, so the global AoA is not yet known.',
 'ONE LOCAL BEARING',M(R`\mathbf q(a,e)=\begin{bmatrix}\cos e\cos a\\\cos e\sin a\\\sin e\end{bmatrix}`)+M(R`\mathbf u_i=\mathbf R_{\rm BS}\mathbf q(\phi_{a,i},\phi_{e,i})`),
 'ROTATE THE RECEIVER BEARING',M(R`\mathbf v_i(\mathbf R)=\mathbf R\,\mathbf q(\theta_{a,i},\theta_{e,i})`)+ 'Both vectors point <b>toward</b> the interaction point.<br><br>LoS: u points BS → UE.<br>LoS: v points UE → BS.<br><br>'+M(R`\mathbf v_i=-\mathbf u_i\quad\text{at LoS truth}`),
 'Rotation matrices map a local coordinate vector into global coordinates. AoA is the look direction from the UE to the preceding interaction or the BS, rather than the direction of wave propagation into the UE. Confusing these signs reverses the geometric relation. The BS direction is immediately known from its known orientation, whereas the UE direction depends on the candidate orientation. The planar mode uses zero elevation and yaw rotations, which is a special case of the same vector construction.',[cite('Eqs. (5), (6), (20), (21)','S3.E20')]);

two('geometry-intro','02 · inspect the propagation','A single-bounce path forms one triangle','The first lab shows the measured rays, physical segment lengths and common clock.',
 'THE TWO RAYS',M(R`\mathbf p_i=\mathbf p_{\rm BS}+a_i\mathbf u_i`)+M(R`\mathbf p_i=\mathbf p_{\rm UE}+s_i\mathbf v_i`)+M(R`\mathbf t=a_i\mathbf u_i-s_i\mathbf v_i`)+ 'Here '+I(R`a_i,s_i\ge0`)+', and '+I(R`\mathbf t=\mathbf p_{\rm UE}-\mathbf p_{\rm BS}`)+'.',
 'WHAT TO TRY','<b>Change the clock:</b> apparent ranges move together while the physical paths remain fixed.<br><br><b>Rotate the candidate UE:</b> its global AoA rays move.<br><br><b>Compare LoS and one bounce:</b> the same clock enters both.',
 'The ray equations are a direct derivation from the physical model. For a single bounce, a is the BS-to-scatterer length and s is the UE-to-scatterer length, with total propagation distance d=a+s. This is the point-scatterer model. It does not enforce a known wall or a specular reflection law. The next lab includes the true layout for explanation. Such truth is display and evaluation information, not an input to the conditional solver. The browser is a deterministic numerical teaching tool rather than a rendering of a published experimental scene.',[cite('Single-bounce measurement model · Eq. (3)','S2.E3'),cite('Geometry · Eqs. (8)–(11)','S3.E8')],[22,22]);

live('geometry-live','geometry-intro','Inspect one channel snapshot','Move between the geometry, matrix and orientation views without changing the measurement model.','geometry',
 'Explore the BS, UE and single-bounce landmarks in 3D.<br><br>Inspect how AoD, AoA, physical length and the common clock combine into each measurement.<br><br>Truth is shown for explanation and error evaluation. The estimator receives measured angles and delays plus the known BS pose.',
 'The embedded laboratory is a teaching experiment. It generates angle-delay observations from the stated geometry and exposes the measurement conventions. An explicit truth view is distinct from an estimator input. The static text provides a meaningful print fallback when the iframe is unavailable. Open the standalone laboratory for more room.',[cite('Section II-A · physical measurements','S2.SS1')]);

two('eliminate','03 · remove the scatterer variables','Eliminate the unknown interaction point','The coarse equation retains the UE state and measured directions.',
 'START WITH THE PATH TRIANGLE',M(R`\mathbf t=a_i\mathbf u_i-s_i\mathbf v_i`)+M(R`d_i=a_i+s_i`)+ 'Construct '+I(R`\mathbf M_i`)+ ' so that'+M(R`\mathbf M_i\mathbf u_i=\mathbf v_i-\mathbf u_i`)+M(R`\mathbf M_i\mathbf v_i=\mathbf u_i-\mathbf v_i`),
 'THE TWO LENGTHS DISAPPEAR',M(R`\mathbf M_i=\mathbf v_i\mathbf u_i^\top+\mathbf u_i\mathbf v_i^\top`)+M(R`\hspace{15mm}-(1+\mathbf u_i^\top\mathbf v_i)\mathbf I`)+M(R`\boxed{\mathbf M_i\mathbf t=d_i(\mathbf v_i-\mathbf u_i)}`)+ 'No '+I(R`\mathbf p_i`)+', '+I(R`a_i`)+ ' or '+I(R`s_i`)+ ' remains in this coarse equation.',
 'This slide gives a short algebraic explanation equivalent to the paper’s auxiliary-segment derivation. Multiplying t=a u-s v by M yields a(v-u)-s(u-v)=(a+s)(v-u). The stated M follows Eq. (10). This elimination reduces the coarse unknowns, but it does not mean that scatterer uncertainty has vanished or that every algebraic solution is physically possible. The lengths and scatterer positions can be recovered later. The equality also holds at the LoS limit v=-u, where the induced constraint becomes more degenerate.',[cite('Eq. (9) · eliminated constraint','S3.E9'),cite('Eq. (10) · matrix definition','S3.E10')],[21,21]);

two('unified-residual','03 · one equation for two inlier types','The residual uses pose and clock only','LoS and single-bounce paths enter the same coarse objective.',
 'A PATH RESIDUAL',M(R`\mathbf w_i=\mathbf v_i-\mathbf u_i`)+M(R`\mathbf r_i(\mathbf x)=\mathbf M_i\mathbf t-(\rho_i-B)\mathbf w_i`)+M(R`J(\mathbf x)=\sum_{i\in\mathcal I}\|\mathbf r_i(\mathbf x)\|_2^2`),
 'WHAT HAS BEEN GAINED','No initial map is needed.<br><br>No amplitude-based LoS label is needed before coarse estimation.<br><br>The unknown UE rotation still changes both '+I(R`\mathbf M_i`)+ ' and '+I(R`\mathbf w_i`)+'.<br><br><b>The complete problem remains nonlinear.</b>',
 'The residual is a vector in metres, since M and w are dimensionless and both t and corrected path length are distances. The paper minimizes the sum of squared residual norms at the coarse stage. A residual near zero is geometric consistency with the eliminated model, not an automatic proof of a positive-length physical path or correct path identity. The later consensus and feasibility checks handle outliers and inadmissible candidates. A fixed orientation creates a linear least-squares subproblem, but an unknown orientation still requires search or nonlinear optimization.',[cite('Eqs. (11)–(13)','S3.E11')],[22,22]);

two('conditional-linear','04 · conditional linear algebra','Fix the orientation, then solve position and clock','“Closed form” applies to this conditional subproblem.',
 'THE ORIGINAL PAPER’S SIGN',M(R`\mathbf y=\begin{bmatrix}\mathbf t\\-B\end{bmatrix}`)+M(R`\mathbf A_i=[\,\mathbf M_i\quad-\mathbf w_i\,]`)+M(R`\mathbf b_i=\rho_i\mathbf w_i`)+M(R`\mathbf A_i\mathbf y=\mathbf b_i`),
 'THE EQUIVALENT DEMO CONVENTION',M(R`\mathbf q=\begin{bmatrix}\mathbf t\\B\end{bmatrix}`)+M(R`\mathbf A_i^+=[\,\mathbf M_i\quad\mathbf w_i\,]`)+M(R`\mathbf A_i^+\mathbf q=\mathbf b_i`)+ 'Both recover the same physical B.<br>Only the last column and coordinate change sign.',
 'The original paper’s unknown vector is [pUE-pBS; -c bUE], and the final column of each A_i is -(v-u). The browser uses a positive distance-clock coordinate B, so its final column is +(v-u). Both identities follow directly by moving the B w term to the left-hand side. Using the paper’s matrix with the demo’s positive clock coordinate would introduce a sign error. The letter b_i denotes the right-hand-side block and should not be confused with the receiver clock bUE.',[cite('Eqs. (14), (17), (18)','S3.E14')],[23,22]);

two('stacking','04 · combine the paths','Stack every path into one linear system','The shared unknown is the same displacement and clock for all rows.',
 'GENERAL 3D',M(R`\mathbf A=\begin{bmatrix}\mathbf A_1\\\vdots\\\mathbf A_N\end{bmatrix}\in\mathbb R^{3N\times4}`)+M(R`\mathbf b=\begin{bmatrix}\mathbf b_1\\\vdots\\\mathbf b_N\end{bmatrix}`)+M(R`\hat{\mathbf y}=\mathbf A^\dagger\mathbf b`),
 'PLANAR MODE',M(R`\mathbf A_{\rm 2D}=\begin{bmatrix}\mathbf A\\0\quad0\quad1\quad0\end{bmatrix}`)+M(R`\mathbf b_{\rm 2D}=\begin{bmatrix}\mathbf b\\0\end{bmatrix}`)+ 'The added row imposes '+I(R`t_z=0`)+'.<br><br>Then '+I(R`\hat{\mathbf p}_{\rm UE}=\mathbf p_{\rm BS}+\hat{\mathbf t}`)+'.',
 'Each path contributes a three-row block, but its rows need not represent three independent constraints. The 3D matrix has four columns for the three displacement coordinates and one signed distance-clock coordinate. The planar construction retains the 3D embedding and adds a row fixing vertical displacement to zero. It is equivalent to eliminating the fixed vertical coordinate algebraically. The pseudoinverse produces a least-squares solution for noisy data and a minimum-norm solution if the matrix is rank deficient. Rank must therefore be inspected rather than inferred from the number of rows.',[cite('Planar stacking · Eqs. (15)–(18)','S3.E15'),cite('3D stacking · Eqs. (23), (24)','S3.E23')],[22,22]);

two('svd','04 · what the pseudoinverse computes','SVD reveals the observable directions','Small singular values make the conditional estimate sensitive to noise.',
 'FACTOR AND SOLVE',M(R`\mathbf A=\mathbf U\boldsymbol\Sigma\mathbf V^\top`)+M(R`\hat{\mathbf y}=\sum_{j:\sigma_j>\epsilon}\mathbf v_j\,\frac{\mathbf u_j^\top\mathbf b}{\sigma_j}`)+ 'Project the measurements onto each supported direction, divide by its singular value, then reconstruct.',
 'RANK AND CONDITIONING',M(R`\operatorname{rank}(\mathbf A)=\#\{j:\sigma_j>\epsilon\}`)+ 'A zero singular value leaves a conditional ambiguity.<br><br>A very small value amplifies perturbations.<br><br>A returned pseudoinverse vector is <b>not evidence of identifiability</b>.',
 'This is the numerical linear-algebra expansion of the paper’s pseudoinverse update, not a new objective. The threshold epsilon is a numerical rank tolerance whose scale must be stated in an implementation. SVD avoids explicitly forming an inverse of A transpose A, which would square the condition number. A rank-deficient pseudoinverse selects a minimum-norm representative, not a uniquely determined physical state. These statements concern the fixed-orientation matrix. They do not establish local rank of the full pose-and-clock residual or exclude another orientation solution.',[cite('Pseudoinverse update · Eq. (18)','S3.E18'),cite('Full-state rank analysis · Section IV','S4')],[23,22]);

two('linear-intro','04 · inspect the actual matrix','A numerical solve from the live scene','This example explicitly conditions on the correct orientation and zero noise.',
 'SEVEN PATHS, FOUR LINEAR UNKNOWNS','BS position: '+I(R`[0,0,2]^\top`)+ ' m.<br>Six single-bounce paths plus LoS.<br><br>First LoS row of '+I(R`\mathbf A^+`)+':'+M(R`[-1.3272,\,-0.8848,\,-0.3318,\,-1.6292]`)+ 'Its right-hand side is −16.8843 m.<br><br>Full-system singular values:<br><b>4.7786, 4.3055, 3.4830, 1.0324.</b>',
 'RECOVER DISPLACEMENT AND CLOCK',M(R`\hat{\mathbf q}=[6,\,4,\,1.5,\,2.99792458]^\top`)+M(R`\hat{\mathbf p}_{\rm UE}=[6,\,4,\,3.5]^\top\ \mathrm m`)+M(R`\hat b=10\ \mathrm{ns}`)+ 'Next, change the candidate orientation.<br><br>A and b change, so the conditional estimate and residual change too.',
 'The numbers come from the same numerical engine used by the live laboratory, with BS [0,0,2], UE [6,4,3.5], distance-clock B=2.99792458 and six single-bounce paths plus LoS. The supplied true rotation is Rz(30 degrees) Ry(12 degrees) Rx(-8 degrees). This is explicitly a conditional check, not an unknown-orientation initializer. The first LoS observation has apparent range 10.36338451 m, and its first matrix row times q equals -16.88429715 m before rounding. The full 21-by-4 matrix has singular values 4.7785703804, 4.3054520190, 3.4830149740 and 1.0324425753. The matrix inspector exposes every computed row. Altering the candidate orientation changes both A and the right-hand side because both depend on the rotated AoA.',[cite('Conditional position/clock solution · Eqs. (14)–(18)','S3.E14')],[20,21]);

live('linear-live','linear-intro','Inspect the matrix and its SVD','The matrix entries are calculated from the current measured rays.','linear',
 'Inspect each path block, the stacked right-hand side, the singular values and the recovered displacement and clock.<br><br>Use a known-orientation conditional check, then change the candidate orientation.<br><br>The browser uses the positive distance-clock coordinate B = cb. Its last matrix column is +w.',
 'This lab is a transparent conditional least-squares calculation. Its true-orientation check verifies a single stage. Unknown pose estimation still needs the orientation search. The displayed singular values diagnose the supported directions of the conditional matrix only. The complete robust paper algorithm also enumerates path subsets and performs physical refinement with model selection, neither of which should be inferred from this matrix-only view.',[cite('Eqs. (14)–(18), (23), (24)','S3.E18')]);

two('profile-orientation','05 · the nonlinear variable','Evaluate an orientation after solving its linear part','The orientation objective is a profiled least-squares residual.',
 'ONE CANDIDATE ORIENTATION',M(R`\hat{\mathbf y}(\mathbf R)=\mathbf A(\mathbf R)^\dagger\mathbf b(\mathbf R)`)+M(R`F(\mathbf R)=\|\mathbf A(\mathbf R)\hat{\mathbf y}(\mathbf R)-\mathbf b(\mathbf R)\|^2`)+ 'Every trial rotation gets its own best position and clock.',
 'PLANAR YAW SEARCH',M(R`\hat\alpha=\arg\min_{\alpha\in\mathcal A}F(\mathbf R_z(\alpha))`)+ 'The paper evaluates a 1° heading grid in its planar experiments.<br><br>Inspect the whole curve. A low local minimum does not establish a unique physical solution.',
 'Profiling means eliminating position and clock by their exact conditional least-squares solution before comparing orientations. This is a lower-dimensional nonlinear problem. In planar mode, the paper samples the heading circle at one-degree resolution. In full 3D, a yaw-only curve is a slice of SO(3), not an exhaustive rotation search. The residual also has nonphysical and ambiguous algebraic configurations, which is why feasibility and rank checks remain necessary. The browser’s local refinement is an educational optimization experiment and should be read with its stated initialization.',[cite('Planar profile search · Eq. (19)','S3.E19'),cite('3D objective · Eq. (22)','S3.E22')],[21,22]);

add('rotation-step','05 · solve the rotation increment','The actual Gauss–Newton rotation step','Linearize the coarse residual while holding the current position and clock fixed.',[
 ...panel('rotation-jacobian-core',96,191,1088,163,'THE ANALYTIC JACOBIAN CORE',M(R`\mathbf G_i=(\mathbf u_i^\top\mathbf t-d_i)\mathbf I+\mathbf u_i\mathbf t^\top-\mathbf t\mathbf u_i^\top`)+ 'The corrected length is '+I(R`d_i=\rho_i-B`)+', and '+I(R`[\mathbf v_i]_\times\mathbf a=\mathbf v_i\times\mathbf a`)+'.',{size:23,fill:C.cool}),
 ...panel('rotation-increment',96,376,532,265,'STACK PATHS, THEN SOLVE',M(R`\mathbf J_{R,i}=-\mathbf G_i[\mathbf v_i]_\times`)+M(R`\delta\boldsymbol\omega=-\mathbf J_R^\dagger\mathbf r`)+ 'The minus sign reduces the current coarse residual '+I(R`\mathbf r`)+'.',{size:23}),
 ...panel('rotation-alternation',652,376,532,265,'ROTATE, THEN RESOLVE',M(R`\mathbf R^+=\operatorname{Exp}([\delta\boldsymbol\omega]_\times)\mathbf R`)+ 'At the new rotation, resolve position and clock with the conditional linear solve.<br><br>Repeat the alternating updates.',{size:22,fill:C.mint,accent:C.teal})
],'Equations (25)–(27) use a left perturbation R_new=Exp([delta omega]_cross)R. Stack each 3-by-3 J_R,i block and each three-vector residual before solving delta omega=-J_R dagger r. The Jacobian on this slide differentiates the coarse residual r=M t-d(v-u) with respect to a rotation perturbation while holding t and d fixed. It is not a total derivative of the profiled objective through t_hat(R) and B_hat(R). After updating orientation, the paper resolves the linear position-and-clock block and repeats. The minus sign follows from minimizing r+J_R delta. This is distinct from the later physical refinement convention e=z-h with J=dh/dTheta, where the increment has the positive weighted-pseudoinverse form. Step control and convergence thresholds are numerical implementation choices.',[cite('Left update · Eq. (25)','S3.E25'),cite('Gauss–Newton step · Eq. (26)','S3.E26'),cite('Analytic rotation Jacobian · Eq. (27)','S3.E27')]);

two('orientation-intro','05 · full 3D orientation','Twist, swing, then update on SO(3)','The paper uses an upright prior to initialize the nonlinear search.',
 'THE PAPER’S TWO-STAGE SEED',M(R`\mathbf R_{\rm tw}(\psi)=\mathbf R_z(\psi)`)+M(R`\mathbf R_{\rm sw}(\chi,\beta)=\operatorname{Exp}(\beta[\mathbf a(\chi)]_\times)`)+M(R`\mathbf a(\chi)=[-\sin\chi,\cos\chi,0]^\top`)+ 'Search yaw first, then bounded tilt around the selected yaw seed.',
 'A LOCAL ROTATION UPDATE',M(R`\mathbf R^{+}=\operatorname{Exp}([\delta\boldsymbol\omega]_\times)\mathbf R`)+ 'Recompute position and clock as orientation changes.<br><br><b>Next lab:</b> inspect a yaw sweep and local SO(3) refinement.<br><br>It does not execute all of Algorithm 1.',
 'The paper selects a twist from its yaw grid and then traverses swing-axis and swing-magnitude candidates around that one twist seed. Its experimental spacings are 6 degrees for twist, 12 for swing axis, 10 for swing magnitude and a 90-degree maximum swing. The subsequent left-multiplicative exponential update preserves a valid rotation matrix. A single selected twist can miss another orientation basin, and local Gauss–Newton refinement is not globally convergent. The browser lab demonstrates a yaw slice and local SO(3) mechanics. It is not the complete paper twist-swing plus exhaustive-subset plus IRLS/QAIC implementation.',[cite('Eqs. (25)–(30)','S3.E25'),cite('Search-grid settings · Section V-A','S5.SS1')],[20,22]);

live('orientation-live','orientation-intro','Explore the orientation objective','A conditional linear solve runs inside every evaluated orientation.','orientation',
 'Inspect how a yaw sweep changes the residual and the estimated position and clock.<br><br>Run local SO(3) refinement from an explicit candidate orientation and compare convergence from different starts.<br><br>This lab teaches the orientation subproblem. It does not run the paper’s complete robust subset search or final IRLS/QAIC selection.',
 'Orientation optimization is the nonlinear part of the coarse state estimate. The local starting rotation is displayed and controlled explicitly, and any true-orientation reference is a labeled conditional experiment. The algorithm receives generated observations and the known BS pose. This UI does not claim to implement all of Algorithm 1 or Section III-C. Numerical convergence, geometric feasibility, global optimality and correctness of the selected path model are separate properties.',[cite('Orientation profiling and update · Eqs. (19), (25)–(30)','S3.E25')]);

two('rank','06 · how many paths?','Four paths is a formulation-specific minimum','Row count, conditional matrix rank and full-state rank are different checks.',
 'THE PAPER’S COARSE FORMULATION','A single-bounce path contributes at most <b>two</b> local full-state constraint directions in 3D.<br><br>The 3D state has <b>seven</b> local coordinates: 3 position, 3 rotation, 1 clock.<br><br>The paper uses '+I(R`N_{\min}=4`)+'.',
 'THE QUALIFICATIONS','Four paths do not guarantee a well-conditioned or unique solution.<br><br>In planar mode, this formulation also requires four paths generically.<br><br>A different physical-model solver with a known LoS identity can require fewer paths.',
 'Section IV analyzes the rank of this particular eliminated residual. The matrix M has rank two for a generic single-bounce path and rank one at LoS. The clock column does not increase the translation-plus-clock block rank for one path. In the full residual, a single-bounce path has at most two independent first-order constraints in 3D, leading to a minimum of four paths for seven local state coordinates. In planar mode the full per-path residual has at most one independent local constraint at a true inlier, leading to four for four unknowns. These are formulation-specific necessary implications, not universal minimum measurement counts for all radio positioning methods. At LoS truth the coarse orientation derivative vanishes, unlike the full physical angle model.',[cite('Section IV · Theorem 1 and minimal sets','S4'),cite('Planar analysis · Section IV-B','S4.SS2')],[22,22]);

two('consensus','06 · robust initialization','Try four-path hypotheses, then test every path','Algorithm 1 searches all minimum-size subsets.',
 'HYPOTHESIS GENERATION',M(R`\mathfrak J=\{\mathcal J\subseteq\mathcal I:\ |\mathcal J|=4\}`)+ 'For each subset:<br><br><b>1.</b> Estimate orientation, position and clock.<br><b>2.</b> Reject infeasible subset geometry.<br><b>3.</b> Evaluate the hypothesis on all paths.',
 'TRUNCATED CONSENSUS SCORE',M(R`C_{\mathcal J}=\sum_{k\in\mathcal I}\min(\|\mathbf r_k\|^2,T_\epsilon^2)`)+M(R`\widehat{\mathcal I}_{\mathcal J}=\{k:\|\mathbf r_k\|<T_\epsilon\}`)+ 'A gross outlier contributes a capped cost.<br><br>For 11 paths, '+I(R`\binom{11}{4}=330`)+ ' subsets are tested.',
 'The published procedure is exhaustive minimum-subset consensus with an MSAC-style truncated squared residual objective. It is not necessary to call it randomized RANSAC, since every minimum-size subset is enumerated in Algorithm 1. The winning hypothesis minimizes the truncated cost, and its thresholded residuals define the coarse inlier set. In the experiments T_epsilon is one metre because the vector residual has distance units. A random subset cap is an implementation approximation that must be disclosed. The browser labs do not perform this robust outer search.',[cite('Algorithm 1 · Section III-B','S3.SS2'),cite('Threshold and path counts · Section V-A','S5.SS1')],[22,21]);

two('feasibility','06 · algebra is not enough','Check that the rays describe a physical path','Small eliminated residuals can admit invalid geometric branches.',
 'THE PAPER’S DIRECTION TESTS',M(R`\Delta_1=\bar{\mathbf t}\times\mathbf v_i,\quad\Delta_2=\bar{\mathbf t}\times\mathbf u_i`)+ 'LoS candidate: both cross products are small.<br><br>Single bounce: the cross products align, and'+M(R`\bar{\mathbf t}^{\top}\mathbf v_i<\bar{\mathbf t}^{\top}\mathbf u_i`),
 'WHY THE TEST IS NEEDED','The eliminated equality encodes an algebraic relationship.<br><br>Physical propagation also has direction and ordering.<br><br>Parallel rays, nearly collinear scatterers and a wrong orientation basin can make a candidate unstable or infeasible.',
 'The paper checks each minimal-set candidate against either a collinearity-consistent LoS interpretation or a coplanar, same-side, correctly ordered single-bounce interpretation. The normalized cross-product dot product must exceed a positive coplanarity threshold for a single bounce, with the additional projection ordering shown on the slide. The document does not provide all numerical feasibility constants, so a replication has to identify those choices explicitly. One can also inspect reconstructed ray distances, but an extra rejection rule should be labeled as an implementation addition rather than attributed to Algorithm 1 without explanation.',[cite('Section III-A3 · feasibility checks','S3.SS1.SSS3')],[21,22]);

two('physical-refinement','07 · return to the measurement model','Now introduce the scatterers and candidate LoS labels','The coarse state initializes a separate physical-model refinement.',
 'RECOVER AN INITIAL SCATTERER',M(R`\begin{bmatrix}a_i\\s_i\end{bmatrix}=[\,\mathbf u_i\quad-\mathbf v_i\,]^\dagger\mathbf t`)+M(R`\mathbf p_i^{(0)}=\mathbf p_{\rm BS}+\tfrac12(a_i\mathbf u_i+s_i\mathbf v_i+\mathbf t)`)+ 'This is the midpoint of the two closest ray points.',
 'FIT M + 1 CANDIDATE MODELS','With M accepted paths:<br><br><b>One model:</b> every path is single-bounce.<br><br><b>M other models:</b> one selected path is LoS and the others are single-bounce.<br><br>Each model refines UE pose, clock and its own scatterer variables.',
 'The coarse formulation had no explicit scatterer variables. Section III-C first uses its UE state to initialize those points. In a noisy scene, the two bearing rays can be skew. Their least-squares closest points are averaged in Eq. (35). A candidate declared LoS has no associated scattering point. Every other retained path contributes a 2D or 3D scatterer. Models with no LoS and with each possible single LoS are optimized separately. This differs from preclassifying the strongest or earliest path as LoS and never revisiting the decision.',[cite('Candidate model variables · Eq. (31)','S3.E31'),cite('Scatterer initialization · Eq. (35)','S3.E35')],[21,22]);

two('irls','07 · local physical refinement','Balance residual sensitivities with IRLS','The weights depend on the current Jacobian rows.',
 'FREEZE ONE ITERATION’S WEIGHTS',M(R`\mathbf e_\ell=\mathbf z-\mathbf h(\boldsymbol\Theta_\ell)`)+M(R`\mathbf J_\ell=\nabla_{\boldsymbol\Theta}\mathbf h(\boldsymbol\Theta_\ell)`)+M(R`W_{jj}=\|\mathbf J_{j,:}\|_2^{-1}`)+ 'A numerical implementation needs a floor for near-zero row norms.',
 'SOLVE THE WEIGHTED STEP',M(R`\delta_\ell=(\mathbf W_\ell^{1/2}\mathbf J_\ell)^\dagger\mathbf W_\ell^{1/2}\mathbf e_\ell`)+ 'Add Euclidean increments.<br>Update rotation through the exponential map.<br><br>Recompute weights at the next iteration.<br><br>This is row equilibration, not fixed covariance weighting.',
 'The square root of W premultiplies both the Jacobian and residual in the least-squares step. Using W directly there would square the intended weight. Because W_jj is the inverse row norm, the actual row multiplier is the inverse square root of that norm. The weights are recomputed at each linearization and then held fixed for the local solve. The paper distinguishes this row-equilibrated IRLS method from minimization of a calibrated Gaussian likelihood. Numerical row floors, line-search choices, stopping rules and the units used for state coordinates affect an implementation and must be documented. Local rotation increments use a left exponential update.',[cite('Section III-C · Eqs. (32), (33)','S3.E32')],[22,21]);

two('qaic','07 · choose a path interpretation','QAIC compares the refined candidate models','Fit quality and model dimension determine the selected LoS hypothesis.',
 'THE PAPER’S COMPARISON SCORE',M(R`\widetilde E_m=\|\mathbf W_m^{1/2}\mathbf e_m\|_2^2`)+M(R`\mathrm{QAIC}_m=2d_\Theta^{(m)}+\frac{n}{\hat c}\ln\!\left(\frac{\widetilde E_m}{n}\right)`)+M(R`n=k_dM,\quad k_d=3\ \text{or}\ 5`),
 'INTERPRET THE TWO TERMS','<b>Residual term:</b> how well the candidate explains the observations.<br><br><b>Dimension term:</b> a LoS path needs no scatterer, so its model has fewer parameters.<br><br>Experiments use '+I(R`\hat c=\exp(\gamma)`)+'.<br><b>This scale is a tuning choice.</b>',
 'All M+1 candidate models are refined before selecting the smallest QAIC score. The terminal weighted residual is a quasi-deviance, not an exact negative log-likelihood, because its weights come from Jacobian row equilibration. The dimension count uses genuine degrees of freedom: 4 planar UE coordinates or 7 spatial UE coordinates, plus 2 or 3 per modeled single-bounce scatterer. It does not count nine rotation-matrix entries as nine free parameters. The paper sets the residual scale to exp(gamma) at the simulated noise level, not to the constant Euler number. Logarithms at zero residual require an explicit numerical safeguard.',[cite('Final score · Eq. (33)','S3.E33'),cite('QAIC · Eq. (34)','S3.E34'),cite('Scale choice · Section V-A','S5.SS1')],[21,21]);

two('limits','08 · scope and limitations','What this method does with double-bounce paths','In this paper, multi-bounce paths are outliers to reject.',
 'THE MODELED INLIERS','LoS: one straight segment.<br><br>Single bounce: two segments meeting at one unknown point.<br><br>Double bounce generally needs two interaction points and three segment lengths. It does not satisfy this single-scatterer model.',
 'WHAT TO CHECK IN A REPLICATION','Retain failed trials and report them.<br><br>Inspect rank, conditioning and physical feasibility.<br><br>State orientation initialization and numerical choices.<br><br>Local convergence and a low residual do not guarantee the correct global solution.',
 'This is a different paper from the Tampere–Chalmers work that explicitly exploits selected double-bounce paths. arXiv:2607.04847v2 robustly rejects paths inconsistent with LoS or one-bounce geometry. Its Appendix B synthetic multi-bounce outliers use random angles and skew-normal delays rather than ray-traced double-bounce scenes. No claim is made that its residual classifies every physical path’s bounce count correctly. A replication should expose missing seeds, unspecified feasibility thresholds and numerical conventions, and should report unconditional performance rather than dropping failed solves. The three embedded labs teach selected stages and do not constitute the entire algorithm.',[cite('Model scope · Section II-A','S2.SS1'),cite('Synthetic outliers · Appendix B','A2'),cite('Full algorithm · Sections III-B/C','S3.SS2')],[22,22]);

add('extensions','09 · continue exploring','Extensions and source material','Use the full-size labs to inspect the numerical steps.',[
 ...panel('full-labs',96,191,1088,137,'INTERACTIVE EXPERIMENTS','<a href="https://bailiping.com/snapshot-radio-slam/live/"><b>Open the complete snapshot estimation laboratory ↗</b></a><br>Geometry, the conditional matrix/SVD solve and orientation refinement.',{fill:C.mint,size:23,accent:C.teal}),
 ...panel('paper-links',96,351,532,288,'THE PAPER',`<a href="${references.pdf.url}" target="_blank" rel="noopener"><b>Read or download the paper PDF ↗</b></a><br><br><a href="${PAPER}" target="_blank" rel="noopener">Read the searchable HTML ↗</a><br><br>Shen et al., arXiv:2607.04847v2.<br>Equations and algorithm links appear on each slide.`,{size:21}),
 ...panel('next-links',652,351,532,288,'RELATED RADIO LESSONS',`<a href="${references.background.url}"><b>Radio measurements → radio map ↗</b></a><br><br><a href="${references.crb.url}"><b>Radio measurement CRB ↗</b></a><br><br>Possible next steps: repeated snapshots, wall features, calibrated uncertainties and explicit multi-bounce geometry.`,{size:21})
],'The standalone laboratories use the same public implementation as the embedded views. The original paper remains the authority for the published method and claims. This deck separates the exact eliminated equations from implementation choices and from the intentionally narrower browser demonstrations. Sequential SLAM requires adding time, data association and possibly a motion model. Modeling walls instead of independent scattering points changes the map state. Exploiting double-bounce measurements requires another physical model and its observability assumptions. Links stay within the public site except for the original arXiv paper.',[ext('pdf'),ext('background'),ext('crb')]);

for(let i=0;i<slides.length;i++)slides[i].elements.push(txt('slide-number',978,655,206,18,`${String(i+1).padStart(2,'0')} / ${slides.length}`,{fontSize:11,fontFamily:mono,color:C.muted,align:'right'}));
for(const entry of liveMap){slides.find(s=>s.id===entry.slide).elements.push(txt('open-lab',758,657,248,18,'OPEN FULL-SIZE LAB ↗',{fontSize:11,fontFamily:mono,color:C.blue,link:'https://bailiping.com/snapshot-radio-slam/'+entry.source.replace(/^\.\//,'')}));entry.slideIndex=slides.findIndex(s=>s.id===entry.slide);}
export const deck={format:'bento/slides',version:1,docId:'snapshot-radio-slam',title:'Snapshot Radio SLAM: Initial Pose and Clock',readonly:true,meta:{author:'Bai Liping',subject:'Unified angle-delay snapshot radio SLAM, conditional least squares, SVD and orientation estimation',company:'bailiping.com',source:'https://bailiping.com/snapshot-radio-slam/'},size:{width:1280,height:720},theme:{background:C.bg,color:C.ink,accent:C.blue,fontFamily:serif},slides};
export const inlineLiveMap=liveMap;
