// Shared geometry with the site's Bento decks; radar content is authored below.
import {fallback} from './fallback.mjs';
import {refs} from './references.mjs';
const C={paper:'#F7F5EF',panel:'#FFFEFB',ink:'#203129',muted:'#66756E',rule:'#D8DED7',green:'#2F6B4F',soft:'#E7F0EA',rust:'#A94F2A',warm:'#F5E8DF',blue:'#496E87',cool:'#E7EEF3',amber:'#986B22'};
const serif="Georgia, 'Times New Roman', serif",sans="Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",mono="'SFMono-Regular', Consolas, monospace";
const R=String.raw;
const M=s=>`<span class="math-tex math-display">\\[${s}\\]</span>`;
const I=s=>`<span class="math-tex math-inline">\\(${s}\\)</span>`;
function text(id,x,y,w,h,html,o={}){return {id,type:'text',x,y,w,h,rotation:0,opacity:1,html,fontSize:18,fontFamily:sans,fontWeight:400,color:C.ink,align:'left',valign:'top',lineHeight:1.4,...o};}
function box(id,x,y,w,h,fill=C.panel,stroke=C.rule,o={}){return {id,type:'shape',shape:'rect',x,y,w,h,fill,stroke,strokeWidth:1,radius:14,rotation:0,opacity:1,...o};}
function line(id,x,y,dx,dy,color=C.rule,width=2,o={}){const length=Math.hypot(dx,dy);return {id,type:'shape',shape:'line',x:x+dx/2-length/2,y:y+dy/2-width/2,w:length,h:width,fill:color,stroke:'none',strokeWidth:0,radius:0,rotation:Math.atan2(dy,dx)*180/Math.PI,opacity:1,...o};}
function circle(id,x,y,size,fill=C.panel,stroke=C.green,o={}){return {id,type:'shape',shape:'ellipse',x,y,w:size,h:size,fill,stroke,strokeWidth:2,rotation:0,opacity:1,...o};}
function panel(id,x,y,w,h,label,html,o={}){return [box(id+'-bg',x,y,w,h,o.fill||C.panel,o.stroke||C.rule),text(id+'-label',x+22,y+17,w-44,23,label,{fontFamily:mono,fontSize:11,fontWeight:800,color:o.accent||C.green,letterSpacing:.8}),text(id+'-body',x+22,y+57,w-44,h-73,html,{fontSize:o.size||19,lineHeight:1.45,...(o.body||{})})];}
function chrome(source){return [box('chrome-rule',72,669,1136,1,C.rule,C.rule,{radius:0}),text('chrome-home',72,684,278,20,'BAI LIPING · ESTIMATION NOTES',{fontFamily:mono,fontSize:10,color:C.muted,link:'https://bailiping.com/'}),text('chrome-source',350,684,580,21,source||'RADAR SLAM · SYNTHETIC TEACHING MODELS',{fontFamily:mono,fontSize:10,color:C.muted,align:'center'}),text('chrome-index',1032,684,176,20,'CONTENTS ↗',{fontFamily:mono,fontSize:10,color:C.green,align:'right',link:'overview'})];}
function slide(id,section,title,sub,elements,notes,source='Radar SLAM · see references',transition='none'){return {id,background:C.paper,transition,notes,elements:[text('eyebrow',72,35,1110,23,section.toUpperCase(),{fontFamily:mono,fontSize:11,fontWeight:800,color:C.rust,letterSpacing:1.3}),text('heading',72,70,1136,58,title,{fontFamily:serif,fontSize:38,fontWeight:700,lineHeight:1.05}),text('subtitle',72,129,1136,44,sub,{fontSize:16,color:C.muted,lineHeight:1.35}),...elements,...chrome(source)]};}
function two(id,section,title,sub,leftLabel,left,rightLabel,right,notes,source,o={}){return slide(id,section,title,sub,[...panel(id+'-left',72,188,548,422,leftLabel,left,{fill:o.leftFill||C.soft,size:o.leftSize||19,accent:o.leftAccent||C.green,body:o.leftBody}),...panel(id+'-right',644,188,564,422,rightLabel,right,{fill:o.rightFill||C.panel,size:o.rightSize||19,accent:o.rightAccent||C.rust,body:o.rightBody})],notes,source,o.transition||'none');}
function three(id,section,title,sub,cards,notes,source){return slide(id,section,title,sub,cards.flatMap(([label,body,fill,accent],i)=>panel(id+'-'+i,72+i*382,188,358,422,label,body,{fill,accent,size:17})),notes,source);}
function sheet(id,title,sub,items,notes,source){return slide(id,'Equation sheet',title,sub,items.flatMap(([label,body],i)=>panel(id+'-'+i,72+(i%2)*578,184+Math.floor(i/2)*231,558,211,label,body,{size:21,body:{valign:'middle',align:'center'},fill:i%2?C.panel:C.soft})),notes,source);}
function node(id,x,y,label,o={}){return [circle(id+'-dot',x,y,o.size||42,o.fill||C.panel,o.stroke||C.green),text(id+'-label',x,y+(o.size||42)/2-10,o.size||42,20,label,{fontFamily:mono,fontSize:o.fontSize||12,fontWeight:750,align:'center',valign:'middle',color:o.color||C.ink})];}
function nativeTable(id,x,y,w,h,headers,rows,o={}){return {id,type:'table',x,y,w,h,rotation:0,opacity:1,header:true,columns:(o.columns||headers.map(()=>1)).map(w=>({w})),rows:[{cells:headers.map(html=>({html}))},...rows.map(row=>({cells:row.map(html=>({html}))}))],style:{headerBg:o.headerBg||C.green,headerColor:'#FFFFFF',zebra:o.zebra||C.soft,borderColor:C.rule,borderWidth:1,cellPadX:o.padX||13,cellPadY:o.padY||10,fontSize:o.fontSize||16,color:C.ink,fontFamily:sans,radius:12}};}
function callout(id,x,y,w,h,html,o={}){return [box(id+'-bg',x,y,w,h,o.fill||C.warm,o.stroke||C.rust,{radius:10}),text(id+'-text',x+16,y+12,w-32,h-24,html,{fontSize:o.size||15,fontWeight:o.weight||650,color:o.color||C.ink,valign:'middle',align:o.align||'left',lineHeight:1.35})];}
function liveFallback(id,title,kicker,body,diagram=[]){return [box(id+'-fallback',72,180,1136,475,C.panel,C.rule),text(id+'-fallback-kicker',96,205,1088,20,kicker,{fontFamily:mono,fontSize:11,fontWeight:800,color:C.rust,letterSpacing:1}),text(id+'-fallback-title',96,237,1088,40,title,{fontFamily:serif,fontSize:28,fontWeight:700}),text(id+'-fallback-body',96,287,380,300,body,{fontSize:17,lineHeight:1.5}),...diagram,box('live-demo-mount',72,180,1136,475,'rgba(255,255,255,0)','rgba(255,255,255,0)',{opacity:0})];}

const slides=[];
const bounds={x:72,y:180,width:1136,height:475};
const liveIds=['whole-run','range','cfar','frames','velocity','icp','optimize'];
const source=(...keys)=>keys.map(k=>`<a href="${refs[k][1]}" target="_blank" rel="noopener">${k}</a>`).join(' · ');
const add=(id,section,title,sub,items,notes,keys=[])=>slides.push(slide(id,section,title,sub,items,notes,source(...keys)));
function four(id,section,title,sub,cards,notes,keys=[]){add(id,section,title,sub,cards.flatMap(([label,body],i)=>panel(id+'-'+i,72+(i%2)*578,186+Math.floor(i/2)*228,558,210,label,body,{fill:i===0?C.soft:C.panel,size:17})),notes,keys);}
function pair(id,section,title,sub,formula,explanation,watch,notes,keys){
 add(id,section,title,sub,[...panel('concept',72,186,676,447,'THE MODEL',`${M(formula)}<br>${explanation}`,{size:22,fill:C.soft}),...panel('watch',772,186,436,447,'WHAT TO WATCH NEXT',watch,{size:20,fill:C.panel,accent:C.rust})],notes,keys);
 const image=fallback(id);
 add(id+'-live',section+' · experiment',title,sub,[{id:'fallback',type:'image',...{x:72,y:180,w:1136,h:475},src:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(image),fit:'contain'},box('live-demo-mount',72,180,1136,475,'rgba(255,255,255,0)','rgba(255,255,255,0)',{opacity:0})],notes+' The next/previous page keys work inside the lab. Escape returns focus to the presentation.',keys);
}
add('overview','Radar SLAM / a field guide','Radar SLAM, one scan at a time.','From an echo to a moving sensor, a persistent map, and a verified revisit.',[
 text('hero',72,204,680,116,'Where did I move?<br><span style="color:#2F6B4F">What stayed still?</span>',{fontFamily:serif,fontSize:48,fontWeight:700,lineHeight:1.1}),
 text('cover-copy',74,343,650,80,'A sequence of seven experiments makes the transformations—and their failure modes—visible.',{fontSize:22,color:C.muted}),
 ...[['01','Measure','range'],['02','Estimate motion','velocity'],['03','Correct the map','optimize']].flatMap(([n,t,link],i)=>[box('cover-card-'+i,72+i*227,452,210,104,i===1?C.cool:C.soft),text('cover-card-'+i+'-label',90+i*227,470,176,68,n+'<br><b>'+t+'</b>',{fontSize:18,link})]),
 box('cover-route',790,188,418,435,C.panel,C.rule),
 ...[['01','Watch the whole run','whole-run'],['02','Range & detection','range'],['03','Coordinates & uncertainty','frames'],['04','Doppler & registration','velocity'],['05','Loop closure & optimization','optimize'],['06','Methods & references','references']].map(([n,t,link],i)=>text('route-'+n,816,220+i*59,363,38,`<span style="color:#A94F2A">${n}</span> &nbsp; ${t} →`,{fontSize:18,link})),
 text('cover-boundary',74,585,680,48,'33 SLIDES · 7 LIVE LABS · DETERMINISTIC 2D MODELS',{fontSize:12,fontFamily:mono,color:C.green})
],'A 2D teaching pipeline starts at synthetic detections. FMCW, CFAR and Doppler labs are separate controlled experiments, not a complete raw-I/Q-to-SLAM implementation. Advance normally to load each experiment automatically.',['TI','RADAR']);
pair('whole-run','01 · the complete process','Watch the map grow.','Scrub the sequence, then compare normal matching with a declared heading bias.',R`T_k=T_{k-1}Z_{k-1,k}`,`Each scan arrives in its own radar frame.<br><br>ICP estimates the relative transform. Composing those transforms places the scans in one world frame.`, `<b>1 · Play or step</b><br>Watch local detections become a global map.<br><br><b>2 · Toggle heading bias</b><br>Small persistent errors accumulate.<br><br><b>3 · Jump to the revisit</b><br>Look for misaligned structure.`, '49 simulated scans, 95 reflectors, range/bearing noise, missed returns and three clutter points per scan. Idealized 360-degree planar field of view. No landmark identities enter ICP. Default heading bias is 0.35 degrees per frame after matching; truth is comparison only. Accepted pairs below 0.45 m are retained; the first scan bootstraps the map.',['RADAR','CFEAR']);
four('unknowns','02 · define the problem','The sensor does not output its pose.','Keep observations, estimated variables, and simulator truth separate.',[
 ['OBSERVATIONS',`${M(R`Z_k=\{z_{k1},\ldots,z_{kn}\}`)}Range, angle, radial velocity and strength, where available.`],
 ['ESTIMATES',`${M(R`T_k=(R_k,p_k),\qquad \mathcal M`)}The trajectory and a persistent map; often the associations too.`],
 ['COORDINATE CONVENTION',`${M(R`\hat m=R_kq+p_k`)}A pose maps radar-frame points into world coordinates.`],
 ['COMPARISON ONLY','The true trajectory and reflector locations are available to the simulator. <b>The estimator never receives them.</b>']
],'Positive radial velocity denotes increasing range; angles use counterclockwise azimuth. Joint inference may include associations as latent variables. Registration followed by a pose graph is one architecture, not the definition of all SLAM.',['RADAR','RAVE']);
four('sensor-contract','02 · define the problem','First ask: which radar data?','The sensor determines the front end. Consistent geometry remains the objective.',[
 ['FMCW ARRAY','Fast time, slow time and array phase can yield range, radial velocity and angles. A “4D” detection commonly has 3D position plus radial velocity.'],
 ['SCANNING RADAR','A rotating beam produces a range–azimuth intensity image. Do not assume every image includes per-return Doppler or elevation.'],
 ['THIS WALKTHROUGH','FMCW concepts in the signal labs; simplified planar detections in the SLAM run. The labs do not emulate a particular product.'],
 ['ODOMETRY → SLAM','Odometry accumulates successive motion. Here, verified revisit constraints provide global consistency and correct drift.']
],'CFEAR uses oriented surface geometry from scanning radar. Doppler ego-velocity requires suitable Doppler measurements. Sensor capabilities should not be silently combined.',['TI','CFEAR','RAVE']);
add('signal-cube','03 · form measurements','One echo, three kinds of phase variation.','Complex baseband samples are the starting point.',[
 ...[['FAST TIME','ADC samples within a chirp','beat frequency → range'],['SLOW TIME','Chirps across a coherent interval','phase progression → Doppler'],['APERTURE','Receive / virtual-array channels','spatial phase → angle']].flatMap(([a,b,c],i)=>panel('axis-'+i,72+i*382,185,358,192,a,`<b>${b}</b><br><br>${c}`,{size:19,fill:i===1?C.cool:C.soft})),
 ...panel('cube-math',72,402,1136,230,'SIMPLIFIED SEPARABLE ECHO',M(R`s[n,\ell,a]\approx\sum_j A_j\exp\!\left\{i2\pi\left(f_{b,j}nT_s+f_{D,j}\ell T_r+\frac{d_a\cdot u_j}{\lambda}\right)\right\}+w`)+`Constant motion over the coherent interval; calibrated channels; negligible range–Doppler coupling.`,{size:22})
],'The sign depends on mixing and channel conventions. Chirp slope S gives beat frequency approximately 2Sr/c. Real systems handle leakage, sidelobes, calibration and, for TDM-MIMO, inter-transmitter motion phase.',['TI','CHIRP']);
pair('range','03 · range processing','Resolve two reflectors in range.','Try the merged and separated presets, then change bandwidth without moving the reflectors.',R`r\approx\frac{cf_b}{2S},\qquad\Delta r\approx\frac{c}{2B}`,`More bandwidth provides a finer nominal range scale.<br><br>A Hann window reduces sidelobes but broadens the main lobe.`, `<b>Hold separation fixed.</b><br>Increase the bandwidth and watch two peaks emerge.<br><br><b>Compare the window.</b><br>Peak width and sidelobes change together.<br><br>The curve is an actual DFT of synthetic complex samples.`, '256 samples span a 50-microsecond sweep. Reflectors at 6 m and 6 m plus selected separation. No Doppler or angle processing in this lab. Nominal unwindowed resolution is distinct from isolated-target estimation accuracy.',['TI','CHIRP']);
four('doppler-angle','03 · form measurements','Range is only the first coordinate.','Look across chirps for motion and across antennas for direction.',[
 ['RADIAL VELOCITY',`${M(R`\Delta\phi\approx\frac{4\pi\dot r T_r}{\lambda},\quad\dot r=\frac{\lambda f_D}{2}`)}Only the relative motion along the line of sight.`],
 ['ARRAY DIRECTION',`${M(R`\Delta\phi_{\rm array}=\frac{2\pi d\sin\theta}{\lambda}`)}Illustrative broadside uniform linear array convention.`],
 ['IDEAL SLOW-TIME LIMITS',`${M(R`|\dot r|<\frac{\lambda}{4T_r},\quad\Delta\dot r\approx\frac{\lambda}{2T_{\rm coh}}`)}Uniform single-transmitter sampling; other waveforms change the limits.`],
 ['STILL AN OBSERVATION','A return at 8 m, 20 degrees and −3 m/s does not identify a wall or give the robot pose. Repeated observations must agree.']
],'TDM-MIMO changes effective sampling and ambiguity. Array calibration and aperture determine which angles are observable.',['TI','CHIRP']);
pair('cfar','03 · detection','Which peaks count as detections?','Inspect one cell’s guard and training windows; then introduce a clutter edge.',R`\tau_k=\alpha\,\overline P_{\rm train},\quad\alpha=N(P_{\rm FA}^{-1/N}-1)`,`CA-CFAR estimates the local background from neighboring cells.<br><br>Guard cells keep the tested peak out of its own background estimate.`, `<b>1 · Inspect a cell</b><br>The highlighted windows explain its threshold.<br><br><b>2 · Tighten the design rate</b><br>Fewer cells pass the test.<br><br><b>3 · Add the clutter edge</b><br>A homogeneous-noise assumption fails.`, '16 training cells, two guard cells on each side. Formula assumes independent exponential powers and homogeneous background. Partial windows at the boundaries are not tested. The design false-alarm probability is not the observed rate in one synthetic slice.',['CFAR']);
pair('frames','04 · coordinates','A point changes coordinates, not location.','Change the assumed pose and watch the same local return move in the map.',R`q=\begin{bmatrix}r\cos\theta\\r\sin\theta\end{bmatrix},\qquad\hat m=R(\psi)q+p`,`The measurement stays fixed in the radar frame.<br><br>The pose determines its placement in world coordinates. A wrong pose makes a wrong map.`, `<b>Translate.</b><br>Every placed point shifts equally.<br><br><b>Rotate.</b><br>The point and uncertainty ellipse turn around the sensor.<br><br>The ellipse shows measurement uncertainty only.`, 'Return at 6 m and 30 degrees. Range standard deviation 0.15 m, bearing standard deviation 3 degrees. First-order two-standard-deviation contour, not a 95 percent joint region. Pose uncertainty is not included.',['RADAR','CERES']);
four('measurement-noise','04 · uncertainty','Angular error grows sideways with range.','An apparently precise range can still give a wide lateral uncertainty.',[
 ['POLAR → CARTESIAN',`${M(R`\Sigma_q\approx J\Sigma_{r\theta}J^{\mathsf T}`)}${I(R`J=\begin{bmatrix}\cos\theta&-r\sin\theta\\\sin\theta&r\cos\theta\end{bmatrix}`)}`],
 ['A USEFUL SCALE',`${M(R`r=20\,\mathrm m,\quad\sigma_\theta=1^\circ`)}${M(R`r\sigma_\theta\approx0.35\,\mathrm m`)}Angles must be in radians in the multiplication.`],
 ['ADD POSE UNCERTAINTY',`${M(R`\Sigma_m\approx R\Sigma_qR^{\mathsf T}+J_T\Sigma_TJ_T^{\mathsf T}`)}This sum assumes independent point and pose errors.`],
 ['MATCHING CONSEQUENCE','Euclidean nearest neighbors are a teaching baseline. Radar uncertainty, multipath and changing scattering centers often need richer models.']
],'The covariance expressions are first-order approximations. SLAM induces correlations; ignoring them can cause overconfidence. The frames lab intentionally isolates measurement uncertainty.',['TI','CERES']);
pair('velocity','05 · ego-velocity','Static objects reveal the radar’s velocity.','Compare robust and ordinary fits to exactly the same Doppler observations.',R`\dot r_j=-u_j^{\mathsf T}v_R+\epsilon_j`, `A moving radar sees nonzero Doppler from stationary objects.<br><br>All static returns share one velocity-dependent pattern. Moving returns violate that pattern.`, `<b>Outliers.</b><br>Increase moving returns and compare the two fits.<br><br><b>Geometry.</b><br>Narrow the bearing span. Even a robust fit cannot recover missing information.<br><br>Truth is only a reference.`, 'True lateral velocity is 1 m/s. RANSAC uses two-return hypotheses and a 0.28 m/s gate, then refits by least squares. Measured bearings are treated as exact. Moving/static labels never enter the estimator.',['RAVE','EFEAR']);
four('observability','05 · motion information','What can this scan actually constrain?','Many measurements can still provide very little independent information.',[
 ['BEARING DIVERSITY',`${M(R`U=[u_1,\ldots,u_n]^{\mathsf T},\quad\mathcal I\propto U^{\mathsf T}U`)}Near-forward rays constrain forward velocity much better than lateral velocity.`],
 ['DOPPLER ≠ FULL POSE','Instantaneous static-return Doppler constrains phase-center translation. It does not supply absolute position or a full orientation.'],
 ['REGISTRATION GEOMETRY','Parallel walls can weakly constrain along-corridor motion. Repeated geometry can support several associations. Convergence alone is insufficient.'],
 ['GAUGE ≠ OBSERVABILITY','Fixing the first pose chooses world coordinates. It does not create missing scene geometry or reliable matches.']
],'A lever arm makes phase-center velocity differ from body-origin velocity during rotation. In 3D, vertical velocity needs independent elevation information.',['RAVE','CERES']);
four('deskew','05 · acquisition time','Put the returns at a common time.','A scan takes time to acquire; motion can distort it before registration.',[
 ['DESKEW',`${M(R`q_{\rm ref}=T(t_{\rm ref})^{-1}T(t_j)q(t_j)`)}Use estimated motion to express every return at one time.`],
 ['PREDICT','IMU, wheel odometry, Doppler velocity or the previous relative transform can supply an initial guess.'],
 ['INITIALIZATION ≠ PRIOR','A starting guess changes where the local solver begins. A motion prior must appear explicitly as a probabilistic factor or residual.'],
 ['PROCESSING ORDER','Calibrate → timestamp → predict → deskew → filter → register.<br><br>The toy run assumes instantaneous scans; it does not deskew.']
],'Some real systems iterate motion estimation and filtering. Time and extrinsic calibration are essential.',['RADAR','EFEAR']);
four('registration','05 · scan registration','Match geometry. Estimate the transformation.','Correspondences and poses depend on one another.',[
 ['TRANSFORM CONVENTION',`${M(R`Z_{k-1,k}\approx T_{k-1}^{-1}T_k`)}Current scan points map into the previous frame. Compose on the right.`],
 ['POINT-TO-POINT',`${M(R`\min_{R,t,A}\sum_j\rho\!\left(\lVert Rq_j+t-q_{A(j)}\rVert^2\right)`)}ICP alternates association and a rigid transformation update.`],
 ['POINT-TO-LINE',`${M(R`e_j=n_{A(j)}^{\mathsf T}(Rq_j+t-\mu_{A(j)})`)}Oriented surface points model local structure, as in CFEAR.`],
 ['ACCEPTANCE','Check overlap, residuals, conditioning and plausibility. A solver returning a transform is not a reason to accept it.']
],'The labs use gated, robustly weighted point-to-point ICP. They do not reproduce CFEAR. Nearest-neighbor matches may be many-to-one; no known reflector IDs are used.',['CFEAR','RADAR']);
pair('icp','05 · scan registration','Open up one ICP iteration.','Alternate the two stages, or animate the solve. Watch the residual history alongside the geometry.',R`A\leftarrow\operatorname{NN}(Rq+t),\qquad (R,t)\leftarrow\operatorname{fit}(A)`,`First freeze tentative correspondences.<br><br>Then solve their weighted rigid alignment and compose the correction. Recompute matches at the new pose.`, `<b>Start nearby.</b><br>Watch the scan settle onto the reference.<br><br><b>Start poorly.</b><br>A local solver may reach the wrong alignment.<br><br><b>Tighten the gate.</b><br>A low error from few pairs can mislead.`, 'Fixed pairs are aligned by weighted centroids and an optimal planar rotation. Each correction is left-composed. Robust weights are updated between associations. RMSE uses current gated pairs, so changing the gate changes the statistic.',['CFEAR']);
four('submaps','06 · build a map','Place the new scan. Keep useful history.','A map can retain local observations and their poses.',[
 ['SCAN-TO-SCAN','Match the previous scan. Simple, but weak overlap and measurement errors accumulate into drift. This is the toy front end.'],
 ['SCAN-TO-SUBMAP','Match several recent keyframes or local surface geometry. History provides more context but may include stale or dynamic returns.'],
 ['KEYFRAMES','Retain scans after useful translation, rotation, elapsed time or overlap changes. Store local points, timestamps and ownership.'],
 ['PERSISTENCE','Bright returns need not be permanent landmarks. Viewpoint, dynamics and multipath change what is observed.']
],'Possible map representations include points, surfels, occupancy, intensity and explicit surfaces. Choose a representation consistent with the observation model. A dense-looking map is not an accuracy metric.',['CFEAR','RADAR']);
add('graph','07 · enforce consistency','Turn relative motion into a graph.','Poses are vertices; uncertain relative measurements are edges.',[
 ...panel('graph-left',72,186,650,445,'CHAIN + REVISIT',`${M(R`T_0\xrightarrow{Z_{01}}T_1\longrightarrow\cdots\longrightarrow T_K`)}<br>A chain can be satisfied exactly by composition—and still drift.<br><br>A verified revisit adds competing evidence between distant times.`,{size:22,fill:C.soft}),
 ...panel('graph-right',746,186,462,445,'WHERE IS THE MAP?',`In a pose graph, local scans attach to poses and move with them.<br><br>A landmark graph may optimize poses and map features together.<br><br><b>The graph defines the problem.</b> The optimizer solves its chosen objective.`,{size:21})
],'The toy uses a damped dense least-squares backend, not an incremental Bayes-tree solver. A loop edge is a measurement, not a hard constraint to the true trajectory.',['RADAR','CERES']);
add('graph-noise','07 · weighted residuals','Noise determines how much an edge matters.','The lab uses a coordinate residual with wrapped heading.',[
 ...panel('residual',72,184,1136,197,'RELATIVE-POSE DISCREPANCY',M(R`r_{ij}=\begin{bmatrix}R_i^{\mathsf T}(p_j-p_i)-z_{ij,t}\\\operatorname{wrap}(\psi_j-\psi_i-z_{ij,\psi})\end{bmatrix}`),{size:26,fill:C.soft}),
 ...panel('objective',72,405,650,228,'WHITEN → MINIMIZE',M(R`\min_{T:\,T_0\;\mathrm{fixed}}\frac12\sum_{(i,j)}\lVert\Sigma_{ij}^{-1/2}r_{ij}\rVert^2`)+'Smaller covariance gives an edge more influence.',{size:22}),
 ...panel('robust',746,405,462,228,'ROBUSTNESS HAS LIMITS','A robust loss reduces large normalized residuals. It cannot certify an association or repair missing information.',{size:21,fill:C.warm})
],'Independent Gaussian edges produce the unrobustified likelihood objective. This coordinate residual is not an exact SE(2) logarithm. Translation and angle units differ. Analytic Jacobians, damping and a non-increasing-cost step check are implemented. Edge noise settings are illustrative, not calibrated scan-matching covariances.',['CERES']);
four('loop','07 · verify revisits','A familiar place is a hypothesis.','Retrieve a candidate, then test its geometric consistency.',[
 ['1 · RETRIEVE','Use place descriptors or structural similarity to propose an old keyframe. Proximity of drifted estimates is not enough.'],
 ['2 · VERIFY','Register scans or submaps. Check overlap, ambiguity, residual quality and agreement with other information.'],
 ['SUPPLIED IN THIS LAB','The candidate is frame 0 ↔ 48. Its transform comes from scan registration, initialized at identity. Place retrieval is not implemented.'],
 ['FALSE CONSTRAINTS','An incorrect, confident edge can deform the entire map. Robust loss is useful protection, not a substitute for verification.']
],'The next experiment deliberately injects a wrong loop. Inspect trajectory error as well as objective reduction.',['TBV','RADAR']);
pair('optimize','07 · pose-graph optimization','Let a loop correct the whole trajectory.','Try a valid loop, a false loop, and robust loss. Compare geometry as well as the objective.',R`(J^{\mathsf T}WJ+\lambda D)\delta=-J^{\mathsf T}Wr`,`The same scan-derived odometry run supplies the chain.<br><br>A loop residual changes all free poses. Stored local scans are re-placed after every accepted update.`, `<b>Step the solver.</b><br>Watch cost and position error separately.<br><br><b>Show the map.</b><br>Historical scans move with corrected poses.<br><br><b>Inject a false loop.</b><br>Lower cost can still mean a worse map.`, 'First pose fixed. Odometry noise: 0.12 m per translation axis and 1.8 degrees in heading. Loop heading noise: 1.2 degrees. False loop is (4 m, −3 m, 24 degrees). Huber threshold 3 acts on normalized loop residual norm. It may downweight correct loops with large drift. Truth is evaluation only. Compare costs only within an unchanged objective.',['CERES','TBV']);
four('rebuild','08 · finish the update','Correcting poses must also correct the map.','Keep the observations in local coordinates so they can be placed again.',[
 ['BEFORE',`${M(R`\hat m_{kj,\rm old}=T_{k,\rm old}q_{kj}`)}Drift duplicates or smears repeated observations.`],
 ['AFTER',`${M(R`\hat m_{kj,\rm new}=T_{k,\rm new}q_{kj}`)}Move every retained scan with its corrected pose.`],
 ['TRY IT','Enable the scan map in the preceding lab before optimizing. Point placement is recomputed at every accepted solver step.'],
 ['PRESERVE OWNERSHIP','A flattened cloud in an old world frame loses the information needed to correct individual scans cleanly. Fused maps may need reintegration.']
],'The toy re-places original local points rather than attracting map points to truth. Submap transformations are another practical option.',['RADAR']);
add('recipe','08 · the algorithm','Every stage has an input and an output.','Run global correction when useful; keep the local estimation cycle moving.',[
 ...panel('recipe-local',72,186,548,444,'EACH ACQUISITION','<b>01</b> Form available measurements.<br><br><b>02</b> Calibrate, timestamp and deskew.<br><br><b>03</b> Predict, select and register.<br><br><b>04</b> Inspect the match quality.<br><br><b>05</b> Update pose and local map.',{size:23,fill:C.soft}),
 ...panel('recipe-global',644,186,564,444,'WHEN A KEYFRAME IS USEFUL','<b>06</b> Retain local scan and pose.<br><br><b>07</b> Add the relative-motion edge.<br><br><b>08</b> Retrieve and verify revisits.<br><br><b>09</b> Optimize accepted constraints.<br><br><b>10</b> Re-place the map.',{size:23})
],'A representative architecture, not a definition of every radar-SLAM system. Production systems also need failure recovery, synchronization, calibrated uncertainty and resource management.',['RADAR','CFEAR','TBV']);
four('three-d','09 · beyond the toy','What changes in 3D?','The same geometric principle needs richer states and enough spatial information.',[
 ['SPATIAL RETURN',`${M(R`q=r\begin{bmatrix}\cos\phi\cos\theta\\\cos\phi\sin\theta\\\sin\phi\end{bmatrix}`)}Azimuth and elevation follow device conventions.`],
 ['SPATIAL POSE',`${M(R`T_k\in\mathrm{SE}(3),\quad\hat m=R_kq+p_k`)}Three translation and three orientation degrees of freedom.`],
 ['EXTRINSICS',`${M(R`T_{WR}=T_{WB}T_{BR}`)}${I(R`v_R^B=v_B^B+\omega^B\times p_{BR}^B`)}<br>Rotate phase-center velocity into radar coordinates for Doppler.`],
 ['OBSERVABILITY','Poor elevation geometry can weaken vertical motion or orientation estimates. IMU fusion can help; calibration errors can mimic motion.']
],'Inertial states may also include velocity and biases. The 2D demos do not implement a 3D SLAM system.',['RAVE','EFEAR']);
add('failure-modes','09 · experiments to revisit','Try to break the estimator.','Change one cause and observe the corresponding failure.',[
 ...[['range','RANGE','Reduce bandwidth','Watch neighboring reflectors merge.'],['velocity','DOPPLER','Narrow the bearing span','Watch lateral information disappear.'],['icp','REGISTRATION','Start with the wrong heading','Watch a local solution become misleading.'],['optimize','LOOP CLOSURE','Trust a false constraint','Watch cost improve while geometry worsens.']].flatMap(([link,label,title,body],i)=>[...panel('failure-'+i,72+(i%2)*578,186+Math.floor(i/2)*228,558,210,label,`<b>${title}</b><br><br>${body}`,{size:21,fill:i%2?C.warm:C.soft}),text('failure-link-'+i,95+(i%2)*578,349+Math.floor(i/2)*228,485,25,'REVISIT THE CONCEPT →',{fontSize:11,color:C.green,fontFamily:mono,link})])
],'Chapter links lead to the explanation immediately before each live experiment. Robustness to outliers and observability are different questions.',['CFEAR','RAVE','TBV']);
four('radar-vs-radio','09 · connect the concepts','Radar SLAM is not automatically radio SLAM.','Share the inference tools; keep the correct propagation model.',[
 ['MONOSTATIC SINGLE REFLECTION',`${M(R`c\tau=2\lVert m-p_R\rVert`)}Colocated transmitter and receiver; range is half the traveled path.`],
 ['BISTATIC SINGLE REFLECTION',`${M(R`c\tau=\lVert m-p_{TX}\rVert+\lVert m-p_{RX}\rVert`)}Separated transmitter and receiver; account for clock offsets.`],
 ['MULTIPATH','A conventional front end may reject it. A multipath-aware model can instead infer surfaces or virtual anchors, with appropriate associations.'],
 ['SHARED BACKEND PRINCIPLE','Define states, predict the actual observations, quantify uncertainty, and infer consistent geometry.']
],'Geometric single-reflection path relations only. Higher-order paths, diffuse scattering, unresolved paths and clock errors need more modeling. No bistatic or virtual-anchor SLAM is implemented here.',['TI']);
add('references','Reference desk','Read the methods. Know the simplifications.','Primary sources for the concepts; the browser labs are independent teaching implementations.',[
 ...Object.entries(refs).map(([k,r],i)=>text('ref-'+k,72+(i%2)*578,186+Math.floor(i/2)*70,548,58,`<b>${k}</b> · ${r[0]} ↗`,{fontSize:17,link:r[1]})),
 ...panel('scope',72,550,1136,104,'SCOPE','Implemented: DFT, CFAR, coordinate transforms, RANSAC, ICP, pose composition and graph optimization. No real sensor driver, deskewing, automatic place retrieval or benchmark reproduction.',{size:14})
],'All simulations use fixed seeds except the explicitly requested new CFAR noise realization. The Bento shell is embedded. A pinned MathJax 3.2.2 bundle typesets equations. Live controls are independent of the math renderer. '+Object.values(refs).map(r=>r[2]).join('\n'),[]);
export const deck={format:'bento/slides',version:1,docId:'radar-slam-bento',title:'Radar SLAM, one scan at a time',readonly:true,meta:{author:'Bai Liping',subject:'Radar SLAM with seven interactive experiments',company:'bailiping.com'},size:{width:1280,height:720},theme:{background:C.paper,color:C.ink,accent:C.green,fontFamily:sans},slides};
export const inlineLiveMap=liveIds.map(id=>({introSlide:id,slide:id+'-live',slideIndex:slides.findIndex(s=>s.id===id+'-live'),inline:true,layout:'region',bounds,src:`./live/?demo=${id}&embed=region`,source:`./live/?demo=${id}`,title:slides.find(s=>s.id===id).elements.find(e=>e.id==='heading').html,sandbox:'allow-scripts'+(id==='optimize'?' allow-downloads':''),hideSource:true,readyMessage:true,unloadWhenHidden:false}));
