// Generated by mpc-detection-to-bounce-count-slides/build.mjs.

/* incidence-single-model.js */
(function (root) {
  'use strict';
  const add = (a, b) => a.map((v, i) => v + b[i]);
  const sub = (a, b) => a.map((v, i) => v - b[i]);
  const mul = (v, s) => v.map(x => x * s);
  const dot = (a, b) => a[0] * b[0] + a[1] * b[1];
  const cross = (a, b) => a[0] * b[1] - a[1] * b[0];
  const norm = v => Math.hypot(...v);
  const direction = degrees => [Math.cos(degrees * Math.PI / 180), Math.sin(degrees * Math.PI / 180)];
  const bearing = v => Math.atan2(v[1], v[0]) * 180 / Math.PI;
  const scene = {
    bs: [0, 0], ue: [6, -10], wallPoint: [19, 13],
    wallTangent: [Math.sin(Math.PI / 10), -Math.cos(Math.PI / 10)]
  };

  // Synthetic measurements only. The estimator below never receives a wall.
  // Minimize the two physical segment lengths along the reference wall.
  function referenceMeasurements(bs, ue, wallPoint, wallTangent) {
    const tangent = mul(wallTangent, 1 / norm(wallTangent));
    const normal = [-tangent[1], tangent[0]];
    const db = dot(sub(bs, wallPoint), normal), du = dot(sub(ue, wallPoint), normal);
    if (db * du <= 0) throw new RangeError('Both endpoints must be on the same side of the reflecting wall.');
    const footB = sub(bs, mul(normal, db)), footU = sub(ue, mul(normal, du));
    const point = mul(add(mul(footB, Math.abs(du)), mul(footU, Math.abs(db))), 1 / (Math.abs(db) + Math.abs(du)));
    return { point, aod: bearing(sub(point, bs)), aoa: bearing(sub(point, ue)), length: norm(sub(point, bs)) + norm(sub(point, ue)) };
  }

  // Both bearings point OUTWARD from their endpoint toward the scatterer.
  // BS + t * departure = UE + s * arrival, with t > 0 and s > 0.
  function intersectRays(bs, ue, aod, aoa) {
    if (![...bs, ...ue, aod, aoa].every(Number.isFinite)) return { status: 'invalid' };
    const departure = direction(aod), arrival = direction(aoa), delta = sub(ue, bs);
    const determinant = cross(departure, arrival);
    const base = { departure, arrival };
    if (Math.abs(determinant) < 1e-8) {
      const collinear = Math.abs(cross(delta, departure)) < 1e-8 * Math.max(1, norm(delta));
      return { ...base, status: collinear ? 'collinear' : 'parallel' };
    }
    const bsDistance = cross(delta, arrival) / determinant;
    const ueDistance = cross(delta, departure) / determinant;
    if (bsDistance <= 1e-8 || ueDistance <= 1e-8) return { ...base, status: 'behind', bsDistance, ueDistance };
    const point = add(bs, mul(departure, bsDistance));
    const normalSum = add(departure, arrival);
    const normal = mul(normalSum, 1 / norm(normalSum));
    return {
      ...base, status: 'ok', point, bsDistance, ueDistance,
      length: bsDistance + ueDistance, wallNormal: normal, wallTangent: [-normal[1], normal[0]],
      crossingAngle: Math.asin(Math.min(1, Math.abs(determinant))) * 180 / Math.PI
    };
  }

  function construction(bs, ue, aod, aoa, measuredLength) {
    const result = intersectRays(bs, ue, aod, aoa);
    return { ...result, measuredLength, residual: result.status === 'ok' ? measuredLength - result.length : null };
  }

  const api = { scene, direction, referenceMeasurements, intersectRays, construction };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.IncidenceSingleModel = api;
})(globalThis);

;

/* incidence-single-render.js */
(function (root) {
  'use strict';
  const WIDTH = 760, HEIGHT = 400;
  const colors = { bs: '#1874b8', ue: '#0e8f7e', ink: '#16222e', muted: '#51606e', reference: '#a2adb7' };
  const label = (x, y, text, color = colors.muted, size = 13, anchor = 'start') =>
    `<text x="${x}" y="${y}" fill="${color}" font-family="Arial,Helvetica,sans-serif" font-size="${size}" text-anchor="${anchor}">${text}</text>`;
  const line = (a, b, color, width = 2, dash = '') =>
    `<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${color}" stroke-width="${width}" ${dash ? `stroke-dasharray="${dash}"` : ''}/>`;
  function arrow(a, b, color) {
    const angle = Math.atan2(b[1] - a[1], b[0] - a[0]);
    const end = offset => [b[0] - 9 * Math.cos(angle + offset), b[1] - 9 * Math.sin(angle + offset)];
    return line(a, b, color, 2.4) + `<path d="M${end(-0.4)} L${b} L${end(0.4)}" fill="none" stroke="${color}" stroke-width="2.4"/>`;
  }
  function render({ bs, ue, result, reference, showReference = false }) {
    const valid = result.status === 'ok';
    const points = [bs, ue, ...(valid ? [result.point] : []), ...(showReference && reference ? [reference.point] : [])];
    let minX = Math.min(...points.map(p => p[0])), maxX = Math.max(...points.map(p => p[0]));
    let minY = Math.min(...points.map(p => p[1])), maxY = Math.max(...points.map(p => p[1]));
    const spanX = Math.max(28, maxX - minX + 10), spanY = Math.max(18, maxY - minY + 8);
    const scale = Math.min(540 / spanX, 255 / spanY);
    const camera = { scale, x: 320 - (minX + maxX) / 2 * scale, y: 195 + (minY + maxY) / 2 * scale };
    const project = p => [camera.x + scale * p[0], camera.y - scale * p[1]];
    const B = project(bs), U = project(ue), P = valid ? project(result.point) : null;
    const rayLimit = (p, d, maximum) => Math.max(0, Math.min(maximum,
      d[0] > 0 ? (738 - p[0]) / d[0] : d[0] < 0 ? (22 - p[0]) / d[0] : Infinity,
      d[1] > 0 ? (342 - p[1]) / d[1] : d[1] < 0 ? (60 - p[1]) / d[1] : Infinity));
    const wallEnds = (p, t, maximum) => {
      const d = [t[0], -t[1]], back = [-d[0], -d[1]];
      const a = rayLimit(p, back, maximum), b = rayLimit(p, d, maximum);
      return [[p[0] - d[0] * a, p[1] - d[1] * a], [p[0] + d[0] * b, p[1] + d[1] * b], a, b];
    };
    let markup = '<rect width="760" height="400" fill="#fff"/>';
    markup += line([22, 23], [48, 23], colors.bs, 3) + label(56, 27, 'BS AoD ray', colors.bs, 12);
    markup += line([181, 23], [207, 23], colors.ue, 3) + label(215, 27, 'UE AoA ray', colors.ue, 12);
    if (valid) markup += line([341, 23], [367, 23], colors.ink, 4) + label(375, 27, 'inferred wall', colors.ink, 12);
    if (showReference && reference) {
      const center = project(reference.point), t = reference.tangent;
      const [a, b] = wallEnds(center, t, 116);
      markup += line(a, b, colors.reference, 7, '5 5');
      markup += label(Math.max(110, a[0] - 12), Math.max(58, a[1] - 9), 'reference only', colors.reference, 11, 'end');
    }
    if (valid) {
      const t = result.wallTangent, n = result.wallNormal;
      const [a, b, back, forward] = wallEnds(P, t, 96);
      markup += line(a, b, colors.ink, 4);
      for (let v = -back + 8; v <= forward - 8; v += 18) {
        const q = [P[0] + v * t[0], P[1] - v * t[1]];
        markup += line(q, [q[0] + 7 * (n[0] + t[0]), q[1] - 7 * (n[1] + t[1])], colors.reference, 1.3);
      }
    }
    for (const [origin, d, distance, color, name, sign] of [
      [B, result.departure, result.bsDistance, colors.bs, 'AoD', -1],
      [U, result.arrival, result.ueDistance, colors.ue, 'AoA', 1]
    ]) {
      if (!d) continue;
      const length = valid ? distance * scale : 230;
      const drawnLength = rayLimit(origin, [d[0], -d[1]], length + 40);
      const end = [origin[0] + d[0] * drawnLength, origin[1] - d[1] * drawnLength];
      markup += arrow(origin, end, color);
      const mid = [origin[0] + d[0] * Math.min(length, drawnLength) * .43, origin[1] - d[1] * Math.min(length, drawnLength) * .43];
      markup += label(mid[0], mid[1] + sign * 17, name, color, 14, 'middle');
    }
    markup += `<rect x="${B[0] - 6}" y="${B[1] - 6}" width="12" height="12" fill="${colors.ink}"/>`;
    markup += label(B[0] - 14, B[1] + 22, 'BS', colors.ink, 14);
    markup += `<circle cx="${U[0]}" cy="${U[1]}" r="8" fill="#2ca02c" stroke="#fff" stroke-width="2"/><circle cx="${U[0]}" cy="${U[1]}" r="14" fill="none" stroke="#2ca02c" stroke-dasharray="3 3"/>`;
    markup += label(U[0] - 12, U[1] + 30, 'UE · drag', '#1d7a1d', 13);
    if (valid) {
      markup += `<circle cx="${P[0]}" cy="${P[1]}" r="8" fill="${colors.ue}" stroke="#fff" stroke-width="2"/>`;
      markup += label(P[0] + 22, P[1] - 34, 'P · incidence point', colors.ue, 15);
    } else {
      markup += label(380, 345, result.status === 'behind' ? 'The forward rays do not meet.' : 'No unique forward-ray intersection.', '#b45607', 16, 'middle');
    }
    markup += label(22, 381, valid ? 'Angles locate P. The wall orientation follows from the reflection law.' : 'A single bounce requires a unique intersection in front of both endpoints.', colors.muted, 12);
    return { markup, camera, svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${HEIGHT}" role="img" aria-label="Incidence point at the intersection of the BS departure ray and UE arrival ray">${markup}</svg>` };
  }
  const api = { render };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.IncidenceSingleDrawing = api;
})(globalThis);

;

/* incidence-single.js */
(() => {
  'use strict';
  if (new URLSearchParams(location.search).get('construction') !== 'incidence-points') return;
  const model = window.IncidenceSingleModel, drawing = window.IncidenceSingleDrawing;
  const { bs, ue: initialUE, wallPoint, wallTangent } = model.scene;
  const panel = document.getElementById('usingle');
  panel.classList.add('incidence-single');
  panel.querySelector('h3').innerHTML = '<span class="no">3.1</span>Single bounce: intersect the AoD and AoA rays';
  document.querySelector('#unknown-tab-single small').textContent = 'ray intersection';
  const demo = document.getElementById('usingle-demo');
  demo.innerHTML = `<div class="body split">
    <svg id="incidence-scene" viewBox="0 0 760 400" role="img" tabindex="0" aria-keyshortcuts="ArrowLeft ArrowRight ArrowUp ArrowDown" aria-label="Single-bounce incidence point from BS AoD and UE AoA rays. Drag the UE or use arrow keys to move it."></svg>
    <div class="rail">
      <h4>Angle measurements · world frame</h4>
      <div class="ctl">
        <label for="incidence-aod"><span>BS departure angle (AoD)</span><output id="incidence-aod-value"></output></label>
        <input id="incidence-aod" type="range" min="-35" max="35" step="0.1" value="0">
        <label for="incidence-aoa"><span>UE arrival angle (AoA)</span><output id="incidence-aoa-value"></output></label>
        <input id="incidence-aoa" type="range" min="-35" max="35" step="0.1" value="0">
        <label for="incidence-length"><span>Measured path length · check only</span><output id="incidence-length-value"></output></label>
        <input id="incidence-length" class="meas" type="range" min="-3" max="3" step="0.05" value="0">
      </div>
      <button class="reset" id="incidence-reset">Reset measurements</button>
      <label class="ck"><input id="incidence-reference" type="checkbox"> Show reference wall</label>
      <div class="incidence-result" aria-live="polite" aria-atomic="true">
        <strong id="incidence-status"></strong>
        <div id="incidence-position"></div>
        <div id="incidence-length-check"></div>
      </div>
      <div class="hint">Drag the UE to sample fresh measurements. Delay checks the path length; it does not move the point.</div>
    </div>
  </div><div class="figcap"><b>Read it.</b> Project the BS ray along AoD and the UE ray toward the arrival direction. Their forward intersection is the incidence point. Under a specular single-bounce hypothesis, the two directions also determine the wall normal. The wall map is not an input; the optional reference wall only illustrates the synthetic scene.</div>`;
  const $ = name => document.getElementById(`incidence-${name}`);
  const state = { ue: [...initialUE], aod: 0, aoa: 0, length: 0, reference: false };
  let camera;
  const format = value => Math.abs(value) < .005 ? '0.00' : Math.abs(value) >= 10000 ? value.toExponential(2) : value.toFixed(2);
  const angle = value => (((value + 180) % 360 + 360) % 360 - 180).toFixed(1) + '°';
  const reasons = {
    parallel: 'Parallel rays do not determine an incidence point.',
    collinear: 'Collinear rays do not determine a unique incidence point.',
    behind: 'The lines meet behind a ray origin; reject the single-bounce candidate.',
    invalid: 'Choose finite angle measurements.'
  };
  function render() {
    const reference = model.referenceMeasurements(bs, state.ue, wallPoint, wallTangent);
    const aod = reference.aod + state.aod, aoa = reference.aoa + state.aoa, length = reference.length + state.length;
    const result = model.construction(bs, state.ue, aod, aoa, length);
    const frame = drawing.render({ bs, ue: state.ue, result, reference: { point: reference.point, tangent: wallTangent }, showReference: state.reference });
    camera = frame.camera;
    $('scene').innerHTML = frame.markup;
    for (const [key, value, text] of [['aod', state.aod, angle(aod)], ['aoa', state.aoa, angle(aoa)], ['length', state.length, format(length) + ' m']]) {
      $(key).value = value;
      $(key).setAttribute('aria-valuetext', text);
      $(`${key}-value`).textContent = text;
    }
    const valid = result.status === 'ok';
    $('status').textContent = valid ? 'Forward-ray intersection' : 'No incidence point';
    $('position').textContent = valid ? `P: x ${format(result.point[0])} m · y ${format(result.point[1])} m` : reasons[result.status];
    $('length-check').textContent = valid ? `Length from rays: ${format(result.length)} m. Residual: ${format(result.residual)} m.` : 'Delay cannot resolve this bearing geometry.';
    if (valid && result.crossingAngle < 2) $('length-check').textContent += ' Nearly parallel: sensitive to angle errors.';
    else if (valid && Math.abs(result.residual) > .15) $('length-check').textContent += ' Delay mismatch.';
    $('status').parentElement.classList.toggle('is-warning', !valid || Math.abs(result.residual) > .15 || result.crossingAngle < 2);
  }
  for (const key of ['aod', 'aoa', 'length']) $(key).addEventListener('input', event => { state[key] = Number(event.target.value); render(); });
  $('reference').addEventListener('change', event => { state.reference = event.target.checked; render(); });
  const resetMeasurements = () => { state.aod = 0; state.aoa = 0; state.length = 0; };
  $('reset').addEventListener('click', () => { resetMeasurements(); render(); });
  const clampUE = p => [Math.max(-4, Math.min(10, p[0])), Math.max(-15, Math.min(-3, p[1]))];
  function localPoint(event) {
    const point = $('scene').createSVGPoint();
    point.x = event.clientX; point.y = event.clientY;
    return point.matrixTransform($('scene').getScreenCTM().inverse());
  }
  let dragging = false;
  $('scene').addEventListener('pointerdown', event => {
    const p = localPoint(event), u = [camera.x + camera.scale * state.ue[0], camera.y - camera.scale * state.ue[1]];
    if (Math.hypot(p.x - u[0], p.y - u[1]) > 24) return;
    dragging = true; $('scene').setPointerCapture(event.pointerId); $('scene').focus(); event.preventDefault();
  });
  $('scene').addEventListener('pointermove', event => {
    if (!dragging) return;
    const p = localPoint(event);
    state.ue = clampUE([(p.x - camera.x) / camera.scale, (camera.y - p.y) / camera.scale]);
    resetMeasurements(); render();
  });
  for (const event of ['pointerup', 'pointercancel', 'lostpointercapture']) $('scene').addEventListener(event, () => { dragging = false; });
  $('scene').addEventListener('keydown', event => {
    const delta = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, 1], ArrowDown: [0, -1] }[event.key];
    if (!delta) return;
    state.ue = clampUE(state.ue.map((v, i) => v + delta[i] * (event.shiftKey ? 1 : .25)));
    resetMeasurements(); render(); event.preventDefault();
  });
  render();
})();

;

/* incidence-corner-model.js */
(function (root) {
  'use strict';
  const single = typeof module === 'object' && module.exports ? require('./incidence-single-model.js') : root.IncidenceSingleModel;
  const add = (a, b) => a.map((v, i) => v + b[i]);
  const sub = (a, b) => a.map((v, i) => v - b[i]);
  const mul = (v, s) => v.map(x => x * s);
  const dot = (a, b) => a[0] * b[0] + a[1] * b[1];
  const norm = v => Math.hypot(...v);
  const unit = v => mul(v, 1 / norm(v));
  const bearing = v => Math.atan2(v[1], v[0]) * 180 / Math.PI;
  const reflect = (direction, normal) => sub(direction, mul(normal, 2 * dot(direction, normal)));
  const scene = {
    bs: [0, 0], ue: [16, -17],
    wallA: { point: [0, 7.5], tangent: [1, 0] },
    wallB: { point: [24, 7.5], tangent: [Math.sin(Math.PI / 9), -Math.cos(Math.PI / 9)] }
  };

  function hitWall(origin, direction, point, normal) {
    const denominator = dot(direction, normal);
    if (Math.abs(denominator) < 1e-8) return { status: 'parallel-wall' };
    const distance = dot(sub(point, origin), normal) / denominator;
    if (distance <= 1e-8) return { status: 'behind-wall' };
    return { status: 'ok', point: add(origin, mul(direction, distance)), distance };
  }

  // Synthetic observations only. The reconstruction below receives no reference map.
  function referenceMeasurements(bs, ue, wallA = scene.wallA, wallB = scene.wallB) {
    const normalB = unit([-wallB.tangent[1], wallB.tangent[0]]);
    const reflectedUE = sub(ue, mul(normalB, 2 * dot(sub(ue, wallB.point), normalB)));
    const first = single.referenceMeasurements(bs, ue, wallA.point, wallA.tangent);
    const unfolded = single.referenceMeasurements(bs, reflectedUE, wallA.point, wallA.tangent);
    const p1 = unfolded.point, departure = unit(sub(p1, bs));
    const normalA = unit([-wallA.tangent[1], wallA.tangent[0]]);
    const hit = hitWall(p1, reflect(departure, normalA), wallB.point, normalB);
    if (hit.status !== 'ok') throw new RangeError('The synthetic route must hit wall B after wall A.');
    const p2 = hit.point;
    return {
      single: first,
      double: { aod: bearing(sub(p1, bs)), aoa: bearing(sub(p2, ue)), length: norm(sub(p1, bs)) + norm(sub(p2, p1)) + norm(sub(ue, p2)) },
      points: { single: first.point, p1, p2 }
    };
  }

  // Path 1 is associated with a single reflection on path 2's FIRST wall.
  // Bearings are outward, in the known global BS/UE orientation frame.
  function construction(bs, ue, firstMeasurement, secondMeasurement) {
    const first = single.construction(bs, ue, firstMeasurement.aod, firstMeasurement.aoa, firstMeasurement.length);
    const base = { single: first };
    if (first.status !== 'ok') return { ...base, status: 'first-wall-unresolved' };
    const wallA = { point: first.point, normal: first.wallNormal, tangent: first.wallTangent };
    const a = { ...base, wallA };
    if (![secondMeasurement.aod, secondMeasurement.aoa].every(Number.isFinite)) return { ...a, status: 'invalid' };
    const departure = single.direction(secondMeasurement.aod), arrival = single.direction(secondMeasurement.aoa);
    const hit = hitWall(bs, departure, wallA.point, wallA.normal);
    const b = { ...a, departure, arrival };
    if (hit.status !== 'ok') return { ...b, status: hit.status };
    const reflected = reflect(departure, wallA.normal), p1 = hit.point;
    const second = single.intersectRays(p1, ue, bearing(reflected), secondMeasurement.aoa);
    const c = { ...b, p1, reflected, firstDistance: hit.distance, second };
    if (second.status !== 'ok') return { ...c, status: `second-${second.status}` };
    const length = hit.distance + second.length;
    return {
      ...c, status: 'ok', p2: second.point,
      wallB: { point: second.point, normal: second.wallNormal, tangent: second.wallTangent },
      middleDistance: second.bsDistance, lastDistance: second.ueDistance,
      length, measuredLength: secondMeasurement.length, residual: secondMeasurement.length - length,
      crossingAngle: second.crossingAngle
    };
  }

  const api = { scene, referenceMeasurements, construction };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.IncidenceCornerModel = api;
})(globalThis);

;

/* incidence-corner-render.js */
(function (root) {
  'use strict';
  const C = { bs: '#1874b8', ue: '#0e8f7e', ink: '#16222e', muted: '#51606e', faint: '#a2adb7', point: '#e8720c' };
  const label = (p, text, color = C.muted, size = 13, anchor = 'start') =>
    `<text x="${p[0]}" y="${p[1]}" fill="${color}" font-family="Arial,Helvetica,sans-serif" font-size="${size}" text-anchor="${anchor}">${text}</text>`;
  const line = (a, b, color, width = 2, dash = '') =>
    `<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${color}" stroke-width="${width}" ${dash ? `stroke-dasharray="${dash}"` : ''}/>`;
  const point = (p, color, radius = 6) => `<circle cx="${p[0]}" cy="${p[1]}" r="${radius}" fill="${color}" stroke="#fff" stroke-width="2"/>`;
  function arrow(a, b, color, dash = '') {
    const angle = Math.atan2(b[1] - a[1], b[0] - a[0]);
    const tip = offset => [b[0] - 8 * Math.cos(angle + offset), b[1] - 8 * Math.sin(angle + offset)];
    return line(a, b, color, 2.5, dash) + `<path d="M${tip(-.4)} L${b} L${tip(.4)}" fill="none" stroke="${color}" stroke-width="2.5"/>`;
  }
  function render({ bs, ue, result, step = 3, reference, showReference = false }) {
    const points = [bs, ue, result.single.point, result.p1, result.p2].filter(Boolean);
    if (showReference && reference) points.push(reference.points.single, reference.points.p1, reference.points.p2);
    const minX = Math.min(...points.map(p => p[0])), maxX = Math.max(...points.map(p => p[0]));
    const minY = Math.min(...points.map(p => p[1])), maxY = Math.max(...points.map(p => p[1]));
    const scale = Math.min(560 / Math.max(32, maxX - minX + 10), 225 / Math.max(26, maxY - minY + 4));
    const camera = { scale, x: 350 - (minX + maxX) * .5 * scale, y: 175 + (minY + maxY) * .5 * scale };
    const project = p => [camera.x + p[0] * scale, camera.y - p[1] * scale];
    const B = project(bs), U = project(ue);
    const limit = (p, d, maximum = 1200) => Math.max(0, Math.min(maximum,
      d[0] > 0 ? (738 - p[0]) / d[0] : d[0] < 0 ? (22 - p[0]) / d[0] : Infinity,
      d[1] > 0 ? (302 - p[1]) / d[1] : d[1] < 0 ? (64 - p[1]) / d[1] : Infinity));
    function ray(origin, direction, length, color, dash = '') {
      if (!direction) return '';
      const d = [direction[0], -direction[1]], distance = limit(origin, d, length);
      return arrow(origin, [origin[0] + d[0] * distance, origin[1] + d[1] * distance], color, dash);
    }
    function wall(w, length, color = C.ink, dash = '') {
      const p = project(w.point), d = [w.tangent[0], -w.tangent[1]];
      const back = limit(p, [-d[0], -d[1]], length), forward = limit(p, d, length);
      return line([p[0] - d[0] * back, p[1] - d[1] * back], [p[0] + d[0] * forward, p[1] + d[1] * forward], color, dash ? 6 : 3.5, dash);
    }
    let markup = '<rect width="760" height="340" fill="#fff"/>';
    markup += line([22, 23], [46, 23], C.bs, 3) + label([54, 27], 'BS AoD / reflected ray', C.bs, 12);
    markup += line([243, 23], [267, 23], C.ue, 3) + label([275, 27], 'UE AoA ray', C.ue, 12);
    markup += line([399, 23], [423, 23], C.ink, 3.5) + label([431, 27], 'inferred wall', C.ink, 12);
    if (showReference && reference) {
      markup += wall({ point: reference.points.single, tangent: reference.wallA.tangent }, 225, C.faint, '5 6');
      markup += wall({ point: reference.points.p2, tangent: reference.wallB.tangent }, 95, C.faint, '5 6');
      markup += label([738, 47], 'dashed gray: reference only', C.muted, 11, 'end');
    }
    if (result.wallA) markup += wall(result.wallA, 290);
    if (step === 3 && result.wallB) markup += wall(result.wallB, 94);
    const first = result.single;
    markup += `<g opacity="${step === 1 ? 1 : .33}">`;
    markup += ray(B, first.departure, first.status === 'ok' ? first.bsDistance * scale + 23 : 220, C.bs, step > 1 ? '5 5' : '');
    markup += ray(U, first.arrival, first.status === 'ok' ? first.ueDistance * scale + 23 : 220, C.ue, step > 1 ? '5 5' : '');
    markup += '</g>';
    if (first.point) {
      const S = project(first.point);
      markup += point(S, step === 1 ? C.ue : C.muted);
      markup += label([S[0] - 12, S[1] - 18], 'S · single bounce', step === 1 ? C.ue : C.muted, 13, 'end');
      markup += label([S[0] - 60, S[1] + 21], 'wall A', C.ink, 13);
    }
    if (step >= 2) {
      markup += ray(B, result.departure, result.p1 ? result.firstDistance * scale : 245, C.bs);
      if (result.p1) {
        const P1 = project(result.p1);
        markup += ray(P1, result.reflected, result.p2 ? result.middleDistance * scale + 35 : 250, C.bs);
        markup += point(P1, C.bs, 7);
        markup += label([P1[0] + 8, P1[1] - 18], 'P1 · first hit', C.bs, 13);
        const length = result.p2 ? result.middleDistance * scale : 160;
        markup += label([P1[0] + result.reflected[0] * length * .4, P1[1] - result.reflected[1] * length * .4 + 27], 'reflected AoD', C.bs, 12, 'middle');
      }
    }
    if (step === 3) {
      markup += ray(U, result.arrival, result.p2 ? result.lastDistance * scale + 32 : 245, C.ue);
      if (result.p2) {
        const P2 = project(result.p2);
        markup += point(P2, C.point, 8);
        markup += label([P2[0] + 19, P2[1] - 17], 'P2 · second hit', C.point, 14);
        markup += label([P2[0] + 34, P2[1] + 35], 'wall B', C.ink, 13);
      }
    }
    markup += `<rect x="${B[0] - 6}" y="${B[1] - 6}" width="12" height="12" fill="${C.ink}"/>`;
    markup += label([B[0] - 22, B[1] + 24], 'BS', C.ink, 14);
    markup += point(U, '#2ca02c', 8) + `<circle cx="${U[0]}" cy="${U[1]}" r="14" fill="none" stroke="#2ca02c" stroke-dasharray="3 3"/>`;
    markup += label([U[0], U[1] + 28], 'UE · drag', '#1d7a1d', 13, 'middle');
    if (step === 1 && first.status !== 'ok' || step >= 2 && !result.p1 || step === 3 && !result.p2) {
      markup += label([380, 326], 'No forward construction for these bearings.', '#89520e', 13, 'middle');
    } else {
      markup += label([22, 326], step === 1 ? 'One single-bounce MPC fixes a point and the orientation of wall A.' : 'S and P1 share wall A; they belong to different measured paths.', C.muted, 12);
    }
    return { markup, camera, svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 340" role="img" aria-label="Two-bounce incidence points constructed from a single-bounce wall and two measured rays">${markup}</svg>` };
  }
  const api = { render };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.IncidenceCornerDrawing = api;
})(globalThis);

;

/* incidence-corner.js */
(() => {
  'use strict';
  if (new URLSearchParams(location.search).get('construction') !== 'incidence-points') return;
  document.documentElement.classList.add('incidence-points-construction');
  const model = window.IncidenceCornerModel, drawing = window.IncidenceCornerDrawing;
  const { bs, ue: initialUE, wallA, wallB } = model.scene;
  const panel = document.getElementById('udouble');
  panel.classList.add('incidence-corner');
  panel.querySelector('h3').innerHTML = '<span class="no">3.2</span>Double bounce: infer wall A, then intersect the reflected ray';
  document.querySelector('#unknown-tab-double small').textContent = 'reflect → intersect';
  document.getElementById('udouble-demo').innerHTML = `<div class="body split">
    <div class="corner-stage">
      <svg id="corner-scene" viewBox="0 0 760 340" role="img" tabindex="0" aria-keyshortcuts="ArrowLeft ArrowRight ArrowUp ArrowDown" aria-label="Corner with two bounces. Infer the first wall from a single-bounce path, then reflect and intersect measured rays. Drag the UE or use arrow keys to move it."></svg>
      <div class="corner-steps" role="group" aria-label="Construction steps">
        <button type="button" data-corner-step="1" aria-pressed="true">1 · Infer wall A</button>
        <button type="button" data-corner-step="2" aria-pressed="false">2 · Reflect on A</button>
        <button type="button" data-corner-step="3" aria-pressed="false">3 · Locate P2</button>
      </div>
      <p id="corner-caption" aria-live="polite"></p>
    </div>
    <div class="rail">
      <div class="corner-measurements" role="group" aria-label="Measurement to edit">
        <button type="button" data-corner-measurement="single" aria-pressed="true">Single bounce</button>
        <button type="button" data-corner-measurement="double" aria-pressed="false">Double bounce</button>
      </div>
      <div class="ctl">
        <label for="corner-aod"><span>BS departure angle (AoD)</span><output id="corner-aod-value"></output></label>
        <input id="corner-aod" type="range" min="-35" max="35" step="0.1" value="0">
        <label for="corner-aoa"><span>UE arrival angle (AoA)</span><output id="corner-aoa-value"></output></label>
        <input id="corner-aoa" type="range" min="-35" max="35" step="0.1" value="0">
        <label for="corner-length"><span>Measured length · check only</span><output id="corner-length-value"></output></label>
        <input id="corner-length" class="meas" type="range" min="-3" max="3" step="0.05" value="0">
      </div>
      <button type="button" class="reset" id="corner-reset">Reset both measurements</button>
      <label class="ck"><input type="checkbox" id="corner-reference"> Show reference walls</label>
      <div class="corner-result" aria-live="polite" aria-atomic="true">
        <strong id="corner-status"></strong>
        <div id="corner-position"></div>
        <div id="corner-check"></div>
      </div>
      <div class="hint">The single path identifies the first wall of the double path. Drag UE for fresh data. Delays check lengths only.</div>
    </div>
  </div><div class="figcap"><b>Read it.</b> Intersect the single-bounce AoD and AoA rays at S; the reflection law gives wall A through S. The double-bounce AoD ray hits this inferred wall at P1. Reflect that ray on A and intersect it with the double-bounce UE AoA ray to obtain P2 on wall B. S and P1 generally differ. Both paths must be associated with the same first wall; reference walls are only synthetic ground truth, never estimator inputs.</div>`;
  const $ = name => document.getElementById(`corner-${name}`);
  const zero = () => ({ aod: 0, aoa: 0, length: 0 });
  const state = { ue: [...initialUE], single: zero(), double: zero(), step: 1, measurement: 'single', reference: false };
  const format = value => Math.abs(value) < .005 ? '0.00' : Math.abs(value) >= 10000 ? value.toExponential(2) : value.toFixed(2);
  const angle = value => (((value + 180) % 360 + 360) % 360 - 180).toFixed(1) + '°';
  const coords = p => `(${format(p[0])}, ${format(p[1])}) m`;
  const captions = [
    'Single bounce: the AoD and AoA rays meet at S. Their directions determine the wall normal, fixing wall A.',
    'Double bounce: project the BS AoD ray to wall A at P1, then reflect it using the inferred wall normal.',
    'Project the UE AoA ray. Its forward intersection with the reflected ray is P2 on the second wall.'
  ];
  const reasons = {
    'first-wall-unresolved': 'The single-bounce rays do not determine wall A.',
    'parallel-wall': 'The double-bounce AoD ray is parallel to wall A.',
    'behind-wall': 'The double-bounce AoD ray points away from wall A.',
    'second-parallel': 'The reflected AoD and UE AoA rays are parallel.',
    'second-collinear': 'The reflected and arrival rays have no unique intersection.',
    'second-behind': 'The second intersection is behind a ray origin.',
    invalid: 'Choose finite angle measurements.'
  };
  let camera;
  function render() {
    const reference = model.referenceMeasurements(bs, state.ue);
    const measurements = {};
    for (const path of ['single', 'double']) measurements[path] = Object.fromEntries(['aod', 'aoa', 'length'].map(key => [key, reference[path][key] + state[path][key]]));
    const result = model.construction(bs, state.ue, measurements.single, measurements.double);
    const frame = drawing.render({ bs, ue: state.ue, result, step: state.step, reference: { ...reference, wallA, wallB }, showReference: state.reference });
    camera = frame.camera;
    $('scene').innerHTML = frame.markup;
    $('caption').textContent = captions[state.step - 1];
    for (const button of panel.querySelectorAll('[data-corner-step]')) button.setAttribute('aria-pressed', String(Number(button.dataset.cornerStep) === state.step));
    for (const button of panel.querySelectorAll('[data-corner-measurement]')) button.setAttribute('aria-pressed', String(button.dataset.cornerMeasurement === state.measurement));
    for (const key of ['aod', 'aoa', 'length']) {
      const value = measurements[state.measurement][key];
      const text = key === 'length' ? `${format(value)} m` : angle(value);
      $(key).value = state[state.measurement][key];
      $(key).setAttribute('aria-valuetext', `${state.measurement} bounce: ${text}`);
      $(`${key}-value`).textContent = text;
    }
    const firstValid = result.single.status === 'ok';
    const visibleValid = state.step === 1 ? firstValid : state.step === 2 ? !!result.p1 : result.status === 'ok';
    $('status').textContent = visibleValid ? ['Wall A inferred', 'Departure ray reflected', 'Second incidence point located'][state.step - 1] : 'No forward construction';
    $('position').textContent = visibleValid ? state.step === 1 ? `S: ${coords(result.single.point)}` : state.step === 2 ? `P1: ${coords(result.p1)}` : `P2: ${coords(result.p2)}` : reasons[result.status];
    const checks = [];
    if (firstValid) checks.push(`Single residual: ${format(result.single.residual)} m`);
    if (state.step === 3 && result.status === 'ok') checks.push(`Double residual: ${format(result.residual)} m`);
    const mismatch = firstValid && Math.abs(result.single.residual) > .15 || state.step === 3 && result.status === 'ok' && Math.abs(result.residual) > .15;
    const sensitive = firstValid && result.single.crossingAngle < 2 || state.step === 3 && result.status === 'ok' && result.crossingAngle < 2;
    if (mismatch) checks.push('Delay mismatch.');
    if (sensitive) checks.push('Nearly parallel rays: angle sensitive.');
    $('check').textContent = checks.join(' · ');
    $('status').parentElement.classList.toggle('is-warning', !visibleValid || mismatch || sensitive);
  }
  for (const key of ['aod', 'aoa', 'length']) $(key).addEventListener('input', event => { state[state.measurement][key] = Number(event.target.value); render(); });
  for (const button of panel.querySelectorAll('[data-corner-step]')) button.addEventListener('click', () => {
    state.step = Number(button.dataset.cornerStep); state.measurement = state.step === 1 ? 'single' : 'double'; render();
  });
  for (const button of panel.querySelectorAll('[data-corner-measurement]')) button.addEventListener('click', () => { state.measurement = button.dataset.cornerMeasurement; render(); });
  const resetMeasurements = () => { state.single = zero(); state.double = zero(); };
  $('reset').addEventListener('click', () => { resetMeasurements(); render(); });
  $('reference').addEventListener('change', event => { state.reference = event.target.checked; render(); });
  const clampUE = p => [Math.max(14, Math.min(21, p[0])), Math.max(-21, Math.min(-13, p[1]))];
  function localPoint(event) {
    const point = $('scene').createSVGPoint(); point.x = event.clientX; point.y = event.clientY;
    return point.matrixTransform($('scene').getScreenCTM().inverse());
  }
  let dragging = false;
  $('scene').addEventListener('pointerdown', event => {
    const p = localPoint(event), u = [camera.x + camera.scale * state.ue[0], camera.y - camera.scale * state.ue[1]];
    if (Math.hypot(p.x - u[0], p.y - u[1]) > 24) return;
    dragging = true; $('scene').setPointerCapture(event.pointerId); $('scene').focus(); event.preventDefault();
  });
  $('scene').addEventListener('pointermove', event => {
    if (!dragging) return;
    const p = localPoint(event);
    state.ue = clampUE([(p.x - camera.x) / camera.scale, (camera.y - p.y) / camera.scale]);
    resetMeasurements(); render();
  });
  for (const event of ['pointerup', 'pointercancel', 'lostpointercapture']) $('scene').addEventListener(event, () => { dragging = false; });
  $('scene').addEventListener('keydown', event => {
    const delta = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, 1], ArrowDown: [0, -1] }[event.key];
    if (!delta) return;
    state.ue = clampUE(state.ue.map((v, i) => v + delta[i] * (event.shiftKey ? 1 : .25)));
    resetMeasurements(); render(); event.preventDefault();
  });
  render();
})();

;

/* incidence-paths-model.js */
(function (root) {
  'use strict';
  const single = typeof module === 'object' && module.exports ? require('./incidence-single-model.js') : root.IncidenceSingleModel;
  const add = (a, b) => a.map((v, i) => v + b[i]);
  const sub = (a, b) => a.map((v, i) => v - b[i]);
  const mul = (v, s) => v.map(x => x * s);
  const dot = (a, b) => a[0] * b[0] + a[1] * b[1];
  const norm = v => Math.hypot(...v);
  const unit = v => mul(v, 1 / norm(v));
  const bearing = v => Math.atan2(v[1], v[0]) * 180 / Math.PI;
  const reflect = (v, n) => sub(v, mul(n, 2 * dot(v, n)));
  const wall = (point, tangent) => ({ point, tangent: unit(tangent), normal: unit([-tangent[1], tangent[0]]) });
  const wallAngle = (a, b) => Math.acos(Math.min(1, Math.abs(dot(a.normal, b.normal)))) * 180 / Math.PI;
  const scenes = {
    corner3: {
      bs: [0, 0], ue: [16, -17], bounds: [14, 21, -21, -13],
      walls: [wall([0, 7.5], [1, 0]), wall([24, 7.5], [Math.sin(Math.PI / 9), -Math.cos(Math.PI / 9)]), wall([-3, -28.5], [Math.cos(8 * Math.PI / 180), Math.sin(8 * Math.PI / 180)])],
      routes: [[0], [0, 1], [0, 1, 2]]
    },
    corridor2: {
      bs: [0, 0], ue: [10, 25], bounds: [1, 15, 8, 28],
      walls: [wall([17, 0], [0, 1]), wall([-5, 0], [0, 1])], routes: [[0], [0, 1]]
    },
    corridor3: {
      bs: [0, 0], ue: [10, 25], bounds: [1, 15, 8, 28],
      walls: [wall([17, 0], [0, 1]), wall([-5, 0], [0, 1])], routes: [[0], [0, 1], [0, 1, 0]]
    }
  };

  function hitWall(origin, direction, w) {
    const denominator = dot(direction, w.normal);
    if (Math.abs(denominator) < 1e-8) return { status: 'parallel-wall' };
    const distance = dot(sub(w.point, origin), w.normal) / denominator;
    if (distance <= 1e-8) return { status: 'behind-wall' };
    return { status: 'ok', point: add(origin, mul(direction, distance)), distance };
  }

  // Test-scene observation generator only. No reference walls enter reconstruct().
  // Unfold the receiver to generate a physical departure bearing, then ray-trace
  // every ordered reflection and check that the last forward leg reaches the UE.
  function referencePath(bs, ue, orderedWalls) {
    let target = [...ue];
    for (const w of [...orderedWalls].reverse()) target = sub(target, mul(w.normal, 2 * dot(sub(target, w.point), w.normal)));
    const departure = unit(sub(target, bs));
    let origin = bs, direction = departure, length = 0;
    const hits = [];
    for (const w of orderedWalls) {
      const hit = hitWall(origin, direction, w);
      if (hit.status !== 'ok') return { status: hit.status };
      hits.push(hit.point); length += hit.distance;
      origin = hit.point; direction = reflect(direction, w.normal);
    }
    const last = sub(ue, origin), distance = norm(last);
    if (distance < 1e-8 || dot(last, direction) <= 0 || norm(sub(unit(last), direction)) > 1e-7) return { status: 'invalid-route' };
    return { status: 'ok', aod: bearing(departure), aoa: bearing(sub(origin, ue)), length: length + distance, hits };
  }
  function referenceMeasurements(scene, ue = scene.ue) {
    return scene.routes.map(route => referencePath(scene.bs, ue, route.map(i => scene.walls[i])));
  }

  // Reflect the measured AoD at already inferred walls. The last hit is the
  // forward intersection with measured AoA, never a point read from a map.
  function advance(bs, ue, measurement, knownWalls) {
    if (![...bs, ...ue, measurement.aod, measurement.aoa].every(Number.isFinite)) return { status: 'invalid', hits: [], directions: [] };
    const departure = single.direction(measurement.aod), arrival = single.direction(measurement.aoa);
    let origin = bs, direction = departure, spent = 0;
    const hits = [], directions = [departure];
    const base = { departure, arrival, hits, directions, measuredLength: measurement.length };
    for (let i = 0; i < knownWalls.length; i++) {
      const hit = hitWall(origin, direction, knownWalls[i]);
      if (hit.status !== 'ok') return { ...base, status: hit.status, failedWall: i };
      hits.push(hit.point); spent += hit.distance; origin = hit.point;
      direction = reflect(direction, knownWalls[i].normal); directions.push(direction);
    }
    const last = single.intersectRays(origin, ue, bearing(direction), measurement.aoa);
    if (last.status !== 'ok') return { ...base, status: last.status };
    hits.push(last.point);
    const length = spent + last.length;
    return { ...base, status: 'ok', length, residual: measurement.length - length,
      lastWall: { point: last.point, normal: last.wallNormal, tangent: last.wallTangent },
      crossingAngle: last.crossingAngle, lastDistance: last.ueDistance };
  }

  function reconstruct(bs, ue, measurements, { corridor = false, repeated = false } = {}) {
    const paths = [], walls = [];
    for (let i = 0; i < measurements.length; i++) {
      const path = advance(bs, ue, measurements[i], walls.slice(0, i));
      paths.push(path);
      if (path.status !== 'ok') return { status: 'unresolved', failedPath: i, paths, walls };
      if (i < 2 || !repeated) walls.push(path.lastWall);
    }
    const result = { status: 'ok', paths, walls, consistent: true };
    if (corridor && walls.length >= 2) {
      result.parallelError = wallAngle(walls[0], walls[1]);
      result.consistent = result.parallelError <= 2;
    }
    if (repeated && paths.length === 3) {
      const last = paths[2], point = last.hits[2];
      const distance = Math.abs(dot(sub(point, walls[0].point), walls[0].normal));
      const orientation = wallAngle(last.lastWall, walls[0]);
      result.closure = { distance, orientation, expected: hitWall(last.hits[1], last.directions[2], walls[0]) };
      result.consistent = result.consistent && distance <= .15 && orientation <= 2 && result.closure.expected.status === 'ok';
    }
    return result;
  }

  const ambiguityScene = {
    bs: [0, 0], ues: [[15, -14], [20.5, -20.5]], pivot: [24, 7.5],
    walls: scenes.corner3.walls.slice(0, 2), rotationBounds: [-18, 12]
  };
  function ambiguityMeasurements(scene = ambiguityScene) {
    return scene.ues.map(ue => referencePath(scene.bs, ue, scene.walls));
  }
  function ambiguity(bs, ues, measurements, candidateWallA, singleMeasurement = null) {
    let firstWall = candidateWallA, singlePath = null;
    if (singleMeasurement) {
      singlePath = advance(bs, ues[0], singleMeasurement, []);
      if (singlePath.status !== 'ok') return { status: 'unresolved', singlePath, paths: [] };
      firstWall = singlePath.lastWall;
    }
    const paths = ues.map((ue, i) => advance(bs, ue, measurements[i], [firstWall]));
    if (paths.some(p => p.status !== 'ok')) return { status: 'unresolved', wallA: firstWall, singlePath, paths };
    const wallB = paths[0].lastWall;
    const sharedError = Math.abs(dot(sub(paths[1].hits[1], wallB.point), wallB.normal));
    return { status: 'ok', wallA: firstWall, wallB, paths, singlePath, sharedError,
      sharedAngle: wallAngle(wallB, paths[1].lastWall), maxResidual: Math.max(...paths.map(p => Math.abs(p.residual))) };
  }
  const api = { scenes, wall, referencePath, referenceMeasurements, advance, reconstruct, ambiguityScene, ambiguityMeasurements, ambiguity };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.IncidencePathsModel = api;
})(globalThis);

;

/* incidence-paths-render.js */
(function (root) {
  'use strict';
  const C = { bs: '#1874b8', ue: '#0e8f7e', ink: '#16222e', muted: '#51606e', faint: '#a2adb7', point: '#e8720c' };
  const distance = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1]);
  const label = (p, text, color = C.muted, size = 13, anchor = 'start') =>
    `<text x="${p[0]}" y="${p[1]}" fill="${color}" font-family="Arial,Helvetica,sans-serif" font-size="${size}" text-anchor="${anchor}" stroke="#fff" stroke-width="3" paint-order="stroke">${text}</text>`;
  const line = (a, b, color, width = 2, dash = '') =>
    `<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${color}" stroke-width="${width}" ${dash ? `stroke-dasharray="${dash}"` : ''}/>`;
  const dot = (p, color, radius = 6) => `<circle cx="${p[0]}" cy="${p[1]}" r="${radius}" fill="${color}" stroke="#fff" stroke-width="2"/>`;
  function arrow(a, b, color, dash = '') {
    const angle = Math.atan2(b[1] - a[1], b[0] - a[0]);
    const tip = offset => [b[0] - 8 * Math.cos(angle + offset), b[1] - 8 * Math.sin(angle + offset)];
    return line(a, b, color, 2.5, dash) + `<path d="M${tip(-.4)} L${b} L${tip(.4)}" fill="none" stroke="${color}" stroke-width="2.5"/>`;
  }
  function frame(points) {
    const minX = Math.min(...points.map(p => p[0])), maxX = Math.max(...points.map(p => p[0]));
    const minY = Math.min(...points.map(p => p[1])), maxY = Math.max(...points.map(p => p[1]));
    const scale = Math.min(560 / Math.max(32, maxX - minX + 10), 225 / Math.max(26, maxY - minY + 5));
    const camera = { scale, x: 350 - (minX + maxX) * .5 * scale, y: 175 + (minY + maxY) * .5 * scale };
    const project = p => [camera.x + p[0] * scale, camera.y - p[1] * scale];
    const limit = (p, d, maximum = 1000) => Math.max(0, Math.min(maximum,
      d[0] > 0 ? (738 - p[0]) / d[0] : d[0] < 0 ? (22 - p[0]) / d[0] : Infinity,
      d[1] > 0 ? (301 - p[1]) / d[1] : d[1] < 0 ? (59 - p[1]) / d[1] : Infinity));
    function ray(origin, direction, length, color, dash = '') {
      if (!direction) return '';
      const p = project(origin), d = [direction[0], -direction[1]], t = limit(p, d, length);
      return arrow(p, [p[0] + d[0] * t, p[1] + d[1] * t], color, dash);
    }
    function wall(w, color = C.ink, dash = '', extent = 270) {
      const p = project(w.point), d = [w.tangent[0], -w.tangent[1]];
      const back = limit(p, [-d[0], -d[1]], extent), forward = limit(p, d, extent);
      return line([p[0] - d[0] * back, p[1] - d[1] * back], [p[0] + d[0] * forward, p[1] + d[1] * forward], color, dash ? 6 : 3.5, dash);
    }
    function endpoints(bs, ues, draggable = true) {
      const B = project(bs);
      let out = `<rect x="${B[0] - 6}" y="${B[1] - 6}" width="12" height="12" fill="${C.ink}"/>` + label([B[0] - 13, B[1] + 24], 'BS', C.ink, 14, 'end');
      ues.forEach((ue, i) => {
        const U = project(ue);
        out += dot(U, '#2ca02c', 8);
        if (draggable) out += `<circle cx="${U[0]}" cy="${U[1]}" r="14" fill="none" stroke="#2ca02c" stroke-dasharray="3 3"/>`;
        out += label([U[0] - 12, U[1] + (ues.length === 1 ? 25 : 19)], ues.length === 1 ? 'UE · drag' : `UE ${i ? 'b' : 'a'}`, '#1d7a1d', 13, 'end');
      });
      return out;
    }
    const legend = '<rect width="760" height="340" fill="#fff"/>' + line([22, 23], [46, 23], C.bs, 3) + label([54, 27], 'BS AoD / reflected ray', C.bs, 12)
      + line([244, 23], [268, 23], C.ue, 3) + label([276, 27], 'UE AoA ray', C.ue, 12)
      + line([399, 23], [423, 23], C.ink, 3.5) + label([431, 27], 'wall from rays', C.ink, 12);
    return { camera, project, ray, wall, endpoints, legend };
  }
  function finish(markup, camera, description) {
    return { markup, camera, svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 340" role="img" aria-label="${description}">${markup}</svg>` };
  }

  function render({ bs, ue, result, view, names = ['A', 'B', 'C'], maxOrder = 3, reference, showReference = false }) {
    const points = [bs, ue, ...result.paths.flatMap(p => p.hits)];
    if (showReference && reference) points.push(...reference.measurements.flatMap(p => p.hits || []));
    const f = frame(points), { project, ray, wall, camera } = f;
    let markup = f.legend;
    if (showReference && reference) {
      reference.walls.forEach(w => { markup += wall(w, C.faint, '5 6'); });
      markup += label([738, 47], 'dashed gray: reference only', C.muted, 11, 'end');
    }
    result.walls.slice(0, view.walls).forEach((w, i) => {
      markup += wall(w);
      const p = project(w.point), vertical = Math.abs(w.tangent[1]) > .75;
      markup += label(vertical ? [p[0] + (i === 1 ? -20 : 20), 68] : [Math.max(75, p[0] - 95), p[1] + 20], `wall ${names[i]}`, C.ink, 13, vertical && i === 1 ? 'end' : 'start');
    });
    // Shorter paths locate the walls, but their hits are not the next path's hits.
    result.paths.slice(0, view.path).forEach((p, index) => {
      if (p.status !== 'ok') return;
      const nodes = [bs, ...p.hits, ue];
      markup += '<g opacity=".23">';
      nodes.slice(1).forEach((q, i) => { markup += line(project(nodes[i]), project(q), C.muted, 1.4, '4 5'); });
      markup += '</g>';
      const q = project(p.hits.at(-1));
      markup += dot(q, C.faint, 4) + label([q[0] + 12, q[1] + 5], index === 0 ? 'S' : 'Q2', C.muted, 11);
    });
    const path = result.paths[view.path];
    if (path) {
      const visibleHits = path.hits.slice(0, view.hits);
      const origins = [bs, ...visibleHits];
      const limit = Math.min(path.directions.length, view.hits + (view.arrival ? 0 : 1));
      for (let i = 0; i < limit; i++) {
        if (!origins[i]) break;
        const target = path.hits[i], length = target ? distance(origins[i], target) * camera.scale : 235;
        const isLast = i === limit - 1;
        markup += ray(origins[i], path.directions[i], length + (isLast ? 24 : 0), C.bs);
      }
      if (view.arrival) markup += ray(ue, path.arrival, path.status === 'ok' ? path.lastDistance * camera.scale + 25 : 230, C.ue);
      visibleHits.forEach((p, i) => {
        const q = project(p), last = i === view.path && view.arrival;
        const w = result.walls[i] || result.walls[0], vertical = w && Math.abs(w.tangent[1]) > .75;
        const left = vertical && i === 1;
        const name = view.path === 0 ? 'S' : view.path === 1 && maxOrder === 3 ? `Q${i + 1}` : `P${i + 1}`;
        const offset = vertical ? [left ? -14 : 14, -10] : [9, q[1] > 230 ? 23 : -17];
        markup += dot(q, last ? C.point : C.bs, 7) + label([q[0] + offset[0], q[1] + offset[1]], `${name}${last ? ' · intersection' : ''}`, last ? C.point : C.bs, last ? 14 : 13, left ? 'end' : 'start');
      });
      if (view.arrival && result.closure && !result.consistent && result.closure.expected.status === 'ok' && view.path === 2) {
        markup += line(project(path.hits[2]), project(result.closure.expected.point), '#b45607', 2, '4 4');
      }
    }
    markup += f.endpoints(bs, [ue]);
    markup += label([22, 326], path && (path.status === 'ok' || path.hits.length >= view.hits) ? 'Each measured path has its own incidence points on the shared walls.' : 'This construction stops when a required forward ray does not meet.', C.muted, 12);
    return finish(markup, camera, 'Incidence points reconstructed by reflecting measured rays at walls inferred from shorter paths');
  }

  function renderAmbiguity({ bs, ues, result, baseline, step = 3, showReference = false, fitPoints }) {
    const f = frame([bs, ...ues, ...(fitPoints || [...result.paths.flatMap(p => p.hits), ...baseline.paths.flatMap(p => p.hits)])]);
    const { project, wall, ray, camera } = f;
    let markup = f.legend;
    if (showReference) {
      markup += wall(baseline.wallA, C.faint, '5 6') + wall(baseline.wallB, C.faint, '5 6');
      markup += label([738, 47], 'dashed gray: original walls', C.muted, 11, 'end');
    }
    if (step >= 2 && result.wallA) {
      markup += wall(result.wallA);
      const a = project(result.paths[0]?.hits[0] || result.wallA.point);
      markup += label([a[0] - 150, a[1] + 18], result.singlePath ? 'wall A · fixed by single path' : 'candidate wall A', C.ink, 12);
      if (result.wallB) {
        markup += wall(result.wallB, C.ink, '', 96);
        const b = project(result.wallB.point);
        markup += label([b[0] + 25, b[1] + 55], 'wall B · from rays', C.ink, 12);
      }
    }
    result.paths.slice(0, step === 2 ? 1 : 2).forEach((p, index) => {
      const dash = index ? '6 5' : '';
      markup += `<g opacity="${index ? .6 : 1}">`;
      if (step === 1) {
        markup += ray(bs, p.departure, 220, C.bs, dash) + ray(ues[index], p.arrival, 220, C.ue, dash);
      } else {
        const origins = [bs, p.hits[0]];
        for (let i = 0; i < Math.min(2, p.directions.length); i++) {
          if (origins[i]) markup += ray(origins[i], p.directions[i], p.hits[i] ? distance(origins[i], p.hits[i]) * camera.scale + (i ? 24 : 0) : 220, C.bs, dash);
        }
        markup += ray(ues[index], p.arrival, p.status === 'ok' ? p.lastDistance * camera.scale + 22 : 220, C.ue, dash);
        p.hits.forEach((p, i) => {
          const q = project(p);
          markup += dot(q, i ? C.point : C.bs, index ? 5 : 7);
          if (!index) markup += label([q[0] + 13, q[1] - 15], `P${i + 1}`, i ? C.point : C.bs, 14);
        });
      }
      markup += '</g>';
    });
    if (result.singlePath && step >= 2) {
      const p = result.singlePath, S = p.hits[0];
      markup += '<g opacity=".35">' + ray(bs, p.departure, distance(bs, S) * camera.scale, C.muted, '4 5') + ray(ues[0], p.arrival, distance(ues[0], S) * camera.scale, C.muted, '4 5') + '</g>';
      const q = project(S); markup += dot(q, C.muted, 5) + label([q[0] - 12, q[1] - 16], 'S · single path', C.muted, 12, 'end');
    }
    markup += f.endpoints(bs, ues, false);
    markup += label([22, 326], step === 1 ? 'Known poses and fixed endpoint rays do not specify the first reflecting wall.' : 'Solid: UE a. Dashed: UE b. Each pose observes its own double-bounce MPC.', C.muted, 12);
    return finish(markup, camera, 'Two known UE poses share an ambiguity family of incidence points until a single-bounce measurement fixes the first wall');
  }
  const api = { render, renderAmbiguity };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.IncidencePathsDrawing = api;
})(globalThis);

;

/* incidence-paths.js */
(() => {
  'use strict';
  if (new URLSearchParams(location.search).get('construction') !== 'incidence-points') return;
  const model = window.IncidencePathsModel, drawing = window.IncidencePathsDrawing;
  const format = v => Math.abs(v) < .005 ? '0.00' : Math.abs(v) >= 10000 ? v.toExponential(2) : v.toFixed(2);
  const angle = v => (((v + 180) % 360 + 360) % 360 - 180).toFixed(1) + '°';
  const coords = p => `(${format(p[0])}, ${format(p[1])}) m`;
  const view = (path, hits, arrival, walls) => ({ path, hits, arrival, walls });
  const configs = [
    { key: 'corner3', panel: 'utriple', tab: 'triple', number: '3.3', title: 'Corner ×3: infer two walls, then locate the third incidence point', detail: 'two reflections → P3', names: ['A', 'B', 'C'],
      steps: ['1 · Infer A', '2 · Infer B', '3 · Hit A', '4 · Reflect B', '5 · Locate P3'],
      views: [view(0, 1, true, 1), view(1, 2, true, 2), view(2, 1, false, 2), view(2, 2, false, 2), view(2, 3, true, 3)],
      captions: [
        'Single bounce: intersect its BS AoD and UE AoA rays at S. The reflection law fixes wall A.',
        'Double bounce: reflect its AoD ray on A. Its intersection with the UE AoA ray fixes a point and wall B.',
        'Triple bounce: start with this path’s own AoD. It hits inferred wall A at P1; reflect the ray there.',
        'The reflected ray hits inferred wall B at P2. Reflect it again using the normal of B.',
        'Intersect the twice-reflected ray with the triple-bounce UE AoA ray. This gives P3 and wall C.'
      ], hint: 'The single and double paths infer the same first two walls used by the triple path. Drag UE for fresh data.' },
    { key: 'corridor2', panel: 'ucorridor', tab: 'corridor', number: '3.4', title: 'Corridor ×2: infer the first wall, reflect, then intersect', detail: 'infer R → locate L', names: ['R', 'L'], corridor: true,
      steps: ['1 · Infer R', '2 · Reflect on R', '3 · Locate P2'],
      views: [view(0, 1, true, 1), view(1, 1, false, 1), view(1, 2, true, 2)],
      captions: [
        'The single-bounce AoD and AoA rays meet at S and determine the first corridor wall R.',
        'The double-bounce AoD ray hits inferred R at P1. Reflect it toward the opposite side of the corridor.',
        'Intersect the reflected ray with the UE AoA ray to locate P2 and wall L. Check that R and L are parallel.'
      ], hint: 'Infer R from the associated single path. Reflect before intersecting: the original endpoint rays are parallel.' },
    { key: 'corridor3', panel: 'ucorridor3', tab: 'corridor3', number: '3.5', title: 'Corridor ×3: reconstruct R → L → the same R', detail: 'return to the same R', names: ['R', 'L'], corridor: true, repeated: true,
      steps: ['1 · Infer R', '2 · Infer L', '3 · Hit R', '4 · Reflect L', '5 · Return R'],
      views: [view(0, 1, true, 1), view(1, 2, true, 2), view(2, 1, false, 2), view(2, 2, false, 2), view(2, 3, true, 2)],
      captions: [
        'Use the single-bounce measurement to locate S and infer the first wall R.',
        'Use the double-bounce measurement and inferred R to locate the second wall L. Check their parallelism.',
        'Project the triple-bounce BS AoD ray to R at P1, then reflect it toward L.',
        'The ray reaches L at P2. Reflect it on L; the next hit must return to the original wall R.',
        'Intersect with the triple-bounce UE AoA ray at P3. Verify both incidence on the original R and its reflection law.'
      ], hint: 'R and L come from the shorter paths. A third wall cannot replace the original R.' }
  ];
  const reasons = {
    invalid: 'Invalid angle measurement.', 'parallel-wall': 'The departure ray is parallel to the next inferred wall.',
    'behind-wall': 'The departure ray points away from the next inferred wall.',
    parallel: 'The final reflected and arrival rays are parallel.', collinear: 'The final rays overlap; the last hit is not unique.',
    behind: 'The final intersection is behind a ray origin.'
  };
  function initPath(config) {
    const scene = model.scenes[config.key], panel = document.getElementById(config.panel), total = scene.routes.length;
    panel.classList.add('incidence-paths');
    panel.querySelector('h3').innerHTML = `<span class="no">${config.number}</span>${config.title}`;
    document.querySelector(`#unknown-tab-${config.tab} small`).textContent = config.detail;
    const prefix = `ip-${config.key}`, $ = key => document.getElementById(`${prefix}-${key}`);
    panel.querySelector('.fig').innerHTML = `<div class="body split">
      <div class="ip-stage">
        <svg id="${prefix}-scene" viewBox="0 0 760 340" role="img" tabindex="0" aria-keyshortcuts="ArrowLeft ArrowRight ArrowUp ArrowDown" aria-label="${config.title}. Drag the UE or use arrow keys to move it."></svg>
        <div class="ip-steps" role="group" aria-label="Construction steps">${config.steps.map((label, i) => `<button type="button" data-ip-step="${i}" aria-pressed="${i === 0}">${label}</button>`).join('')}</div>
        <p id="${prefix}-caption" aria-live="polite"></p>
      </div>
      <div class="rail">
        <div class="ip-measurements" role="group" aria-label="Measurement to edit">${['Single', 'Double', 'Triple'].slice(0, total).map((label, i) => `<button type="button" data-ip-measurement="${i}" aria-pressed="${i === 0}">${label} bounce</button>`).join('')}</div>
        <div class="ctl">
          <label for="${prefix}-aod"><span>BS departure angle (AoD)</span><output id="${prefix}-aod-value"></output></label>
          <input id="${prefix}-aod" type="range" min="-35" max="35" step="0.1" value="0">
          <label for="${prefix}-aoa"><span>UE arrival angle (AoA)</span><output id="${prefix}-aoa-value"></output></label>
          <input id="${prefix}-aoa" type="range" min="-35" max="35" step="0.1" value="0">
          <label for="${prefix}-length"><span>Measured length · check only</span><output id="${prefix}-length-value"></output></label>
          <input id="${prefix}-length" class="meas" type="range" min="-3" max="3" step="0.05" value="0">
        </div>
        <button class="reset" type="button" id="${prefix}-reset">Reset all measurements</button>
        <label class="ck"><input type="checkbox" id="${prefix}-reference"> Show reference walls</label>
        <div class="ip-result" aria-live="polite" aria-atomic="true"><strong id="${prefix}-status"></strong><div id="${prefix}-position"></div><div id="${prefix}-check"></div></div>
        <div class="hint">${config.hint} Delays check lengths only.</div>
      </div>
    </div><div class="figcap"><b>Read it.</b> ${config.captions.join(' ')} Each associated path has its own incidence points. Reference walls only generate the synthetic observations; they are not reconstruction inputs.</div>`;
    const zero = () => scene.routes.map(() => ({ aod: 0, aoa: 0, length: 0 }));
    const state = { ue: [...scene.ue], offsets: zero(), step: 0, measurement: 0, reference: false };
    let camera;
    function render() {
      const reference = model.referenceMeasurements(scene, state.ue);
      const measurements = reference.map((m, i) => Object.fromEntries(['aod', 'aoa', 'length'].map(k => [k, m[k] + state.offsets[i][k]])));
      const result = model.reconstruct(scene.bs, state.ue, measurements, config);
      const view = config.views[state.step], current = result.paths[view.path];
      const frame = drawing.render({ bs: scene.bs, ue: state.ue, result, view, names: config.names, maxOrder: total, reference: { walls: scene.walls, measurements: reference }, showReference: state.reference });
      camera = frame.camera; $('scene').innerHTML = frame.markup; $('caption').textContent = config.captions[state.step];
      for (const button of panel.querySelectorAll('[data-ip-step]')) button.setAttribute('aria-pressed', String(Number(button.dataset.ipStep) === state.step));
      for (const button of panel.querySelectorAll('[data-ip-measurement]')) button.setAttribute('aria-pressed', String(Number(button.dataset.ipMeasurement) === state.measurement));
      for (const key of ['aod', 'aoa', 'length']) {
        const value = measurements[state.measurement][key], text = key === 'length' ? `${format(value)} m` : angle(value);
        $(key).value = state.offsets[state.measurement][key]; $(key).setAttribute('aria-valuetext', `${['Single', 'Double', 'Triple'][state.measurement]} bounce: ${text}`); $(`${key}-value`).textContent = text;
      }
      const valid = current && (view.arrival ? current.status === 'ok' : current.hits.length >= view.hits);
      const final = state.step === config.steps.length - 1;
      const mismatch = result.paths.slice(0, view.path + 1).some(p => p.status === 'ok' && Math.abs(p.residual) > .15);
      const sensitive = result.paths.slice(0, view.path + 1).some(p => p.crossingAngle < 2);
      const corridorMismatch = config.corridor && view.walls >= 2 && result.parallelError > 2;
      const repeatedMismatch = final && result.closure && (result.closure.distance > .15 || result.closure.orientation > 2);
      let status = view.path === 0 ? `Wall ${config.names[0]} inferred` : !view.arrival ? `Ray reflected at ${config.names[view.hits - 1]}` : `Wall ${config.names[view.path] || 'R'} located`;
      if (final && config.repeated) status = repeatedMismatch ? 'Return to R rejected' : 'Third hit matches original R';
      if (corridorMismatch) status = 'Parallel-wall condition fails';
      $('status').textContent = valid ? status : 'No forward construction';
      $('position').textContent = valid ? `${view.path === 0 ? 'S' : view.path === 1 && total === 3 ? `Q${view.hits}` : `P${view.hits}`}: ${coords(current.hits[view.hits - 1])}` : `Path ${(result.failedPath ?? view.path) + 1}: ${reasons[result.paths.at(-1)?.status] || 'A shorter path must first determine its wall.'}`;
      const residuals = result.paths.slice(0, view.path + 1).filter(p => p.status === 'ok').map(p => format(p.residual));
      const checks = residuals.length ? [`Length residual${residuals.length > 1 ? 's' : ''} (m): ${residuals.join(' / ')}`] : [];
      if (view.walls >= 2 && result.parallelError !== undefined) checks.push(`Parallel error: ${format(result.parallelError)}°`);
      if (final && result.closure) checks.push(`R gap: ${format(result.closure.distance)} m · normal: ${format(result.closure.orientation)}°`);
      if (mismatch) checks.push('Delay mismatch.'); if (sensitive) checks.push('Nearly parallel rays: angle sensitive.');
      $('check').textContent = checks.join(' · ');
      $('status').parentElement.classList.toggle('is-warning', Boolean(!valid || mismatch || sensitive || corridorMismatch || repeatedMismatch));
    }
    for (const key of ['aod', 'aoa', 'length']) $(key).addEventListener('input', e => { state.offsets[state.measurement][key] = Number(e.target.value); render(); });
    for (const button of panel.querySelectorAll('[data-ip-step]')) button.addEventListener('click', () => { state.step = Number(button.dataset.ipStep); state.measurement = config.views[state.step].path; render(); });
    for (const button of panel.querySelectorAll('[data-ip-measurement]')) button.addEventListener('click', () => { state.measurement = Number(button.dataset.ipMeasurement); render(); });
    $('reset').addEventListener('click', () => { state.offsets = zero(); render(); });
    $('reference').addEventListener('change', e => { state.reference = e.target.checked; render(); });
    const clamp = p => [Math.max(scene.bounds[0], Math.min(scene.bounds[1], p[0])), Math.max(scene.bounds[2], Math.min(scene.bounds[3], p[1]))];
    function localPoint(event) { const p = $('scene').createSVGPoint(); p.x = event.clientX; p.y = event.clientY; return p.matrixTransform($('scene').getScreenCTM().inverse()); }
    let dragging = false;
    $('scene').addEventListener('pointerdown', e => {
      const p = localPoint(e), u = [camera.x + camera.scale * state.ue[0], camera.y - camera.scale * state.ue[1]];
      if (Math.hypot(p.x - u[0], p.y - u[1]) > 24) return;
      dragging = true; $('scene').setPointerCapture(e.pointerId); $('scene').focus(); e.preventDefault();
    });
    $('scene').addEventListener('pointermove', e => {
      if (!dragging) return; const p = localPoint(e);
      state.ue = clamp([(p.x - camera.x) / camera.scale, (camera.y - p.y) / camera.scale]); state.offsets = zero(); render();
    });
    for (const event of ['pointerup', 'pointercancel', 'lostpointercapture']) $('scene').addEventListener(event, () => { dragging = false; });
    $('scene').addEventListener('keydown', e => {
      const delta = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, 1], ArrowDown: [0, -1] }[e.key]; if (!delta) return;
      state.ue = clamp(state.ue.map((v, i) => v + delta[i] * (e.shiftKey ? 1 : .25))); state.offsets = zero(); render(); e.preventDefault();
    });
    render();
  }
  configs.forEach(initPath);

  function initAmbiguity() {
    const scene = model.ambiguityScene, panel = document.getElementById('uestimate');
    panel.classList.add('incidence-paths');
    panel.querySelector('h3').innerHTML = '<span class="no">3.6</span>Ambiguity: fixed rays, moving incidence points';
    panel.querySelector('.lede').textContent = 'Two double-bounce MPCs at known UE poses can fit a family of wall pairs. Rotate the candidate first wall, reflect each measured departure ray, and intersect with its arrival ray. The resulting incidence points move while both measured lengths remain unchanged.';
    panel.querySelector('.accuracy').textContent = 'An associated single-bounce measurement locates a point and the normal of wall A. Once A is fixed, each double-bounce measurement determines its two incidence points.';
    document.querySelector('#unknown-tab-estimate small').textContent = 'fixed rays, moving hits';
    const $ = key => document.getElementById(`ip-ambiguity-${key}`);
    panel.querySelector('.fig').innerHTML = `<div class="body split"><div class="ip-stage">
      <svg id="ip-ambiguity-scene" viewBox="0 0 760 340" role="img" aria-label="Fixed measured rays at two known UE poses fit moving incidence points and a family of two-wall maps."></svg>
      <div class="ip-steps" role="group" aria-label="Ambiguity construction steps">
        <button type="button" data-ambiguity-step="1" aria-pressed="false">1 · Measured rays</button>
        <button type="button" data-ambiguity-step="2" aria-pressed="false">2 · Reflect / intersect</button>
        <button type="button" data-ambiguity-step="3" aria-pressed="true">3 · Two-pose check</button>
      </div><p id="ip-ambiguity-caption" aria-live="polite"></p></div>
      <div class="rail">
        <div class="ctl"><label for="ip-ambiguity-rotation"><span>Candidate wall A rotation</span><output id="ip-ambiguity-rotation-value"></output></label>
          <input id="ip-ambiguity-rotation" type="range" min="-18" max="12" step="0.2" value="0"></div>
        <label class="ck"><input type="checkbox" id="ip-ambiguity-prefix"> Add single-bounce measurement</label>
        <label class="ck"><input type="checkbox" id="ip-ambiguity-reference"> Show original walls</label>
        <button class="reset" type="button" id="ip-ambiguity-reset">Reset family</button>
        <div class="ip-fixed-data"><strong>Fixed double-bounce measurements</strong><div id="ip-ambiguity-data"></div></div>
        <div class="ip-result" aria-live="polite" aria-atomic="true"><strong id="ip-ambiguity-status"></strong><div id="ip-ambiguity-check"></div></div>
      </div></div><div class="figcap"><b>Read it.</b> Each double-bounce path starts with its measured BS AoD, reflects on the candidate first wall, and intersects its UE AoA ray. A common-rotation family of wall pairs preserves both poses’ geometric measurements. Add the associated single-bounce measurement to determine wall A from its own two rays and remove this family. No wall map is supplied to that reconstruction.</div>`;
    const measurements = model.ambiguityMeasurements(scene);
    const single = model.referencePath(scene.bs, scene.ues[0], [scene.walls[0]]);
    const baseline = model.ambiguity(scene.bs, scene.ues, measurements, scene.walls[0]);
    const candidate = degrees => model.wall(scene.pivot, [Math.cos(degrees * Math.PI / 180), Math.sin(degrees * Math.PI / 180)]);
    const fitPoints = [];
    for (let a = -18; a <= 12; a += 1) fitPoints.push(...model.ambiguity(scene.bs, scene.ues, measurements, candidate(a)).paths.flatMap(p => p.hits));
    const state = { rotation: 0, prefix: false, reference: false, step: 3 };
    const captions = [
      'Each pose provides a double-bounce AoD, AoA and length. The endpoint rays alone do not identify the first wall.',
      'Choose a candidate wall A. Reflect the BS AoD there and intersect with UE a’s AoA to locate P2 and wall B.',
      'Both known UE poses fit the same rotating wall pair. The points move while the measured rays and lengths stay fixed.'
    ];
    function render() {
      const result = model.ambiguity(scene.bs, scene.ues, measurements, candidate(state.rotation), state.prefix ? single : null);
      const frame = drawing.renderAmbiguity({ bs: scene.bs, ues: scene.ues, result, baseline, step: state.step, fitPoints, showReference: state.reference });
      $('scene').innerHTML = frame.markup;
      $('rotation').disabled = state.prefix; $('rotation').value = state.rotation;
      $('rotation').setAttribute('aria-valuetext', state.prefix ? 'Fixed by the single-bounce measurement' : angle(state.rotation));
      $('rotation-value').textContent = state.prefix ? 'fixed by single path' : angle(state.rotation);
      $('caption').textContent = state.prefix ? 'The single path fixes S and wall A. Reflecting each double-bounce AoD on that wall now determines both paths’ incidence points.' : captions[state.step - 1];
      for (const b of panel.querySelectorAll('[data-ambiguity-step]')) b.setAttribute('aria-pressed', String(Number(b.dataset.ambiguityStep) === state.step));
      $('data').innerHTML = '<table><thead><tr><th>Pose</th><th>AoD</th><th>AoA</th><th>Length</th></tr></thead><tbody>' + measurements.map((m, i) => `<tr><td>UE ${i ? 'b' : 'a'}</td><td>${angle(m.aod)}</td><td>${angle(m.aoa)}</td><td>${format(m.length)} m</td></tr>`).join('') + '</tbody></table>';
      const motion = result.status === 'ok' ? Math.max(...result.paths.flatMap((p, j) => p.hits.map((q, i) => Math.hypot(q[0] - baseline.paths[j].hits[i][0], q[1] - baseline.paths[j].hits[i][1])))) : NaN;
      $('status').textContent = result.status !== 'ok' ? 'No forward construction' : state.prefix ? 'Wall A fixed by single path' : 'Two poses still admit a wall family';
      $('check').textContent = result.status !== 'ok' ? 'The candidate does not fit both forward paths.' : `Largest length residual: ${format(result.maxResidual)} m. Point motion: ${format(motion)} m. Both poses share wall B.`;
      $('status').parentElement.classList.toggle('is-warning', result.status !== 'ok' || !state.prefix);
    }
    $('rotation').addEventListener('input', e => { state.rotation = Number(e.target.value); render(); });
    $('prefix').addEventListener('change', e => { state.prefix = e.target.checked; state.step = 3; render(); });
    $('reference').addEventListener('change', e => { state.reference = e.target.checked; render(); });
    $('reset').addEventListener('click', () => { state.rotation = 0; state.prefix = false; $('prefix').checked = false; render(); });
    for (const b of panel.querySelectorAll('[data-ambiguity-step]')) b.addEventListener('click', () => { state.step = Number(b.dataset.ambiguityStep); render(); });
    render();
  }
  initAmbiguity();
})();
